
ALTER TABLE public.posts
  ADD COLUMN status text NOT NULL DEFAULT 'pending',
  ADD COLUMN pinned boolean NOT NULL DEFAULT false,
  ADD COLUMN author_name text,
  ADD COLUMN user_id uuid,
  ADD COLUMN anon_number int;

UPDATE public.posts SET status = 'approved' WHERE status = 'pending';

ALTER TABLE public.comments ADD COLUMN anon_number int;

ALTER TABLE public.comments DROP CONSTRAINT IF EXISTS comments_post_id_fkey;
ALTER TABLE public.comments
  ADD CONSTRAINT comments_post_id_fkey
  FOREIGN KEY (post_id) REFERENCES public.posts(id) ON DELETE CASCADE;

CREATE TABLE public.device_aliases (
  device_id text PRIMARY KEY,
  number int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT ON public.device_aliases TO anon, authenticated;
GRANT ALL ON public.device_aliases TO service_role;
ALTER TABLE public.device_aliases ENABLE ROW LEVEL SECURITY;
CREATE POLICY "anyone reads aliases" ON public.device_aliases FOR SELECT TO anon, authenticated USING (true);

CREATE TABLE public.admin_devices (
  device_id text PRIMARY KEY,
  note text,
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT ON public.admin_devices TO anon, authenticated;
GRANT ALL ON public.admin_devices TO service_role;
ALTER TABLE public.admin_devices ENABLE ROW LEVEL SECURITY;
CREATE POLICY "anyone checks admin devices" ON public.admin_devices FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "admins manage admin devices" ON public.admin_devices FOR ALL TO authenticated
  USING (public.has_role(auth.uid(), 'admin')) WITH CHECK (public.has_role(auth.uid(), 'admin'));

CREATE OR REPLACE FUNCTION public.assign_anon_number(_device_id text) RETURNS int
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE n int;
BEGIN
  INSERT INTO public.device_aliases(device_id) VALUES (_device_id) ON CONFLICT (device_id) DO NOTHING;
  SELECT number INTO n FROM public.device_aliases WHERE device_id = _device_id;
  RETURN n;
END $$;

CREATE OR REPLACE FUNCTION public.posts_before_insert() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  NEW.anon_number := public.assign_anon_number(NEW.device_id);
  IF NEW.user_id IS NOT NULL AND public.has_role(NEW.user_id, 'admin') THEN
    NEW.status := 'approved';
  ELSIF EXISTS (SELECT 1 FROM public.admin_devices WHERE device_id = NEW.device_id) THEN
    NEW.status := 'approved';
    NEW.pinned := false;
    NEW.user_id := NULL;
  ELSE
    NEW.status := 'pending';
    NEW.author_name := NULL;
    NEW.user_id := NULL;
    NEW.pinned := false;
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER posts_before_insert_trg BEFORE INSERT ON public.posts
  FOR EACH ROW EXECUTE FUNCTION public.posts_before_insert();

CREATE OR REPLACE FUNCTION public.comments_before_insert() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  NEW.anon_number := public.assign_anon_number(NEW.device_id);
  RETURN NEW;
END $$;
CREATE TRIGGER comments_before_insert_trg BEFORE INSERT ON public.comments
  FOR EACH ROW EXECUTE FUNCTION public.comments_before_insert();

DROP POLICY IF EXISTS "anyone can read posts" ON public.posts;
DROP POLICY IF EXISTS "non-blocked can post" ON public.posts;
DROP POLICY IF EXISTS "admins delete posts" ON public.posts;

CREATE POLICY "read approved or admin"
  ON public.posts FOR SELECT TO anon, authenticated
  USING (status = 'approved' OR public.has_role(auth.uid(), 'admin'));

CREATE POLICY "non-blocked can insert"
  ON public.posts FOR INSERT TO anon, authenticated
  WITH CHECK (
    length(content) > 0 AND length(content) <= 5000
    AND length(device_id) BETWEEN 8 AND 128
    AND NOT EXISTS (SELECT 1 FROM public.blocked_devices b WHERE b.device_id = posts.device_id)
    AND (user_id IS NULL OR user_id = auth.uid())
  );

CREATE POLICY "admins update posts"
  ON public.posts FOR UPDATE TO authenticated
  USING (public.has_role(auth.uid(), 'admin'))
  WITH CHECK (public.has_role(auth.uid(), 'admin'));

CREATE POLICY "admins delete posts"
  ON public.posts FOR DELETE TO authenticated
  USING (public.has_role(auth.uid(), 'admin'));
