# Unit 5 Review - Do Your Best (all lessons, pages 48-57)
ITEMS = [
    # ===== L1: Sports vocabulary, physical activities (8 items) =====
    ("Which sport is played on a rectangular field with goals at each end?",
     {"A": "football", "B": "tennis", "C": "basketball", "D": "volleyball"},
     "A", "easy", 48, "Review: L1",
     ["Football is played on a rectangular field with goals at each end."],
     "football = field sport", "Football requires a large pitch with two goals."),

    ("What do you call a person who plays a sport professionally?",
     {"A": "athlete", "B": "spectator", "C": "coach", "D": "referee"},
     "A", "easy", 48, "Review: L1",
     ["An athlete is a person who is skilled in sports and physical activities."],
     "athlete = professional sportsperson", "Athletes train regularly to compete."),

    ("Which word means 'to get points in a game or match'?",
     {"A": "score", "B": "throw", "C": "catch", "D": "kick"},
     "A", "easy", 48, "Review: L1",
     ["'Score' means to gain points in a game or competition."],
     "score = earn points", "She scored three goals in the match."),

    ("What equipment do you use to play tennis?",
     {"A": "a racket", "B": "a bat", "C": "a club", "D": "a paddle"},
     "A", "easy", 48, "Review: L1",
     ["Tennis is played using a racket to hit the ball over the net."],
     "tennis uses a racket", "A tennis racket has strings and a handle."),

    ("What do you call the person who watches a sports game?",
     {"A": "spectator", "B": "player", "C": "captain", "D": "coach"},
     "A", "medium", 49, "Review: L1",
     ["A spectator is a person who watches a sports event."],
     "spectator = viewer at a game", "Thousands of spectators watched the match."),

    ("Which word describes a sports competition between two teams?",
     {"A": "match", "B": "race", "C": "concert", "D": "lesson"},
     "A", "easy", 49, "Review: L1",
     ["A match is an organized sports competition between two teams."],
     "match = sports competition", "The football match ended 2-1."),

    ("What is a 'marathon'?",
     {"A": "a long-distance running race of 42 kilometres", "B": "a swimming competition", "C": "a cycling event", "D": "a wrestling match"},
     "A", "easy", 49, "Review: L1",
     ["A marathon is a long-distance running race covering 42.195 kilometres."],
     "marathon = 42 km running race", "Marathon runners need great endurance."),

    ("Which adjective means 'very fit and strong'?",
     {"A": "athletic", "B": "wooden", "C": "plastic", "D": "musical"},
     "A", "easy", 49, "Review: L1",
     ["'Athletic' describes someone who is physically strong and good at sports."],
     "athletic = physically fit", "She has an athletic build."),

    # ===== L2: Modal verbs, comparatives/superlatives (8 items) =====
    ("You ___ eat healthy food to stay fit.",
     {"A": "should", "B": "can", "C": "might", "D": "could"},
     "A", "easy", 50, "Review: L2",
     ["'Should' gives advice about what is good to do."],
     "should = advice", "Healthy eating is recommended for fitness."),

    ("Players ___ follow the rules of the game.",
     {"A": "must", "B": "might", "C": "could", "D": "would"},
     "A", "easy", 50, "Review: L2",
     ["'Must' expresses a strong obligation or rule."],
     "must = strong obligation", "Rules are not optional in sports."),

    ("She runs ___ than anyone else in her class.",
     {"A": "faster", "B": "fastest", "C": "more fast", "D": "most fast"},
     "A", "easy", 50, "Review: L2",
     ["'Faster' is the comparative form of 'fast'."],
     "faster = comparative of fast", "Comparative compares two things with '-er' or 'more'."),

    ("This is the ___ match I have ever watched.",
     {"A": "best", "B": "better", "C": "goodest", "D": "more good"},
     "A", "easy", 50, "Review: L2",
     ["'Best' is the superlative form of 'good'."],
     "best = superlative of good", "Superlatives use '-est' or 'most' for three or more."),

    ("You ___ to train every day if you want to improve.",
     {"A": "have", "B": "should", "C": "must", "D": "can"},
     "A", "medium", 50, "Review: L2",
     ["'Have to' expresses an external obligation or necessity."],
     "have to = necessity", "Daily training is necessary for improvement."),

    ("Which is the correct comparative form of 'good'?",
     {"A": "better", "B": "gooder", "C": "more good", "D": "goodest"},
     "A", "medium", 51, "Review: L2",
     ["The comparative of 'good' is the irregular form 'better'."],
     "better = comparative of good", "'Good' has irregular forms: good, better, best."),

    ("He is the ___ player on the team.",
     {"A": "strongest", "B": "stronger", "C": "more strong", "D": "most strong"},
     "A", "medium", 51, "Review: L2",
     ["'Strongest' is the superlative of 'strong'."],
     "strongest = superlative of strong", "Add '-est' to short adjectives for the superlative."),

    ("You ___ not skip practice if you want to win.",
     {"A": "should", "B": "can", "C": "may", "D": "might"},
     "A", "medium", 51, "Review: L2",
     ["'Should not' advises against skipping practice."],
     "should not = advice against", "Skipping practice is a bad idea for athletes."),

    # ===== L3: Athlete vocabulary, reading comprehension (8 items) =====
    ("An athlete who trains for the Olympic Games is often called an...",
     {"A": "Olympian", "B": "spectator", "C": "referee", "D": "captain"},
     "A", "easy", 52, "Review: L3",
     ["An Olympian is an athlete who competes in the Olympic Games."],
     "Olympian = Olympic athlete", "Olympians represent their countries."),

    ("What does 'to set a record' mean?",
     {"A": "to achieve the best result ever recorded", "B": "to break a machine", "C": "to sing a song", "D": "to lose a game"},
     "A", "easy", 52, "Review: L3",
     ["Setting a record means achieving a result better than any before."],
     "set a record = best result ever", "Usain Bolt set the 100m record."),

    ("A marathon runner needs a lot of...",
     {"A": "endurance", "B": "height", "C": "silence", "D": "weight"},
     "A", "medium", 52, "Review: L3",
     ["Endurance is the ability to keep doing something difficult for a long time."],
     "endurance = stamina", "Marathon running requires great endurance."),

    ("Which word means 'to keep trying despite difficulties'?",
     {"A": "persevere", "B": "surrender", "C": "hesitate", "D": "complain"},
     "A", "medium", 52, "Review: L3",
     ["'Persevere' means to continue trying even when it is hard."],
     "persevere = keep trying", "Great athletes persevere through challenges."),

    ("What is the meaning of 'to qualify for a competition'?",
     {"A": "to meet the required standard to enter", "B": "to win the competition", "C": "to watch the competition", "D": "to organise the competition"},
     "A", "medium", 53, "Review: L3",
     ["Qualifying means meeting the minimum standard needed to participate."],
     "qualify = meet the standard", "Runners must qualify by finishing under a certain time."),

    ("An athlete's coach helps them to...",
     {"A": "improve their performance", "B": "lose the game", "C": "forget training", "D": "avoid exercise"},
     "A", "easy", 53, "Review: L3",
     ["A coach guides athletes to become better at their sport."],
     "coach helps improvement", "Coaches design training plans for athletes."),

    ("What does 'personal best' mean?",
     {"A": "the best result a person has ever achieved", "B": "the worst result", "C": "an average score", "D": "a team record"},
     "A", "medium", 53, "Review: L3",
     ["A personal best (PB) is an individual's highest achievement so far."],
     "personal best = own top result", "She broke her personal best in the 200m."),

    ("To win a gold medal at the Olympics is a great...",
     {"A": "achievement", "B": "mistake", "C": "accident", "D": "problem"},
     "A", "easy", 53, "Review: L3",
     ["An achievement is something done successfully through effort."],
     "achievement = accomplishment", "Winning a medal requires years of hard work."),

    # ===== L4: Competition vocabulary, event words (7 items) =====
    ("What do you call the first place in a race?",
     {"A": "first place", "B": "last place", "C": "midfield", "D": "sideline"},
     "A", "easy", 54, "Review: L4",
     ["The first-place finisher wins the race."],
     "first place = the winner", "She finished in first place."),

    ("A sports event where athletes compete against each other is called a...",
     {"A": "competition", "B": "holiday", "C": "picnic", "D": "festival"},
     "A", "easy", 54, "Review: L4",
     ["A competition is an event where people or teams contest against each other."],
     "competition = contest", "The swimming competition had many participants."),

    ("What does 'to take part in' mean?",
     {"A": "to participate", "B": "to watch", "C": "to organise", "D": "to avoid"},
     "A", "easy", 54, "Review: L4",
     ["'Take part in' means to be involved in an activity or event."],
     "take part in = participate", "All students can take part in the sports day."),

    ("A team that wins a tournament is called the...",
     {"A": "winner", "B": "loser", "C": "organiser", "D": "spectator"},
     "A", "easy", 54, "Review: L4",
     ["The winner is the team or person that comes first in a competition."],
     "winner = the champion", "The winning team received a trophy."),

    ("What do you call the person who organises a sports event?",
     {"A": "organiser", "B": "spectator", "C": "opponent", "D": "coach"},
     "A", "medium", 55, "Review: L4",
     ["An organiser is the person who plans and manages an event."],
     "organiser = event planner", "The organiser announced the schedule."),

    ("What is a 'tournament'?",
     {"A": "a competition with a series of matches leading to a final", "B": "a single game", "C": "a training session", "D": "a sports lesson"},
     "A", "medium", 55, "Review: L4",
     ["A tournament is a sports competition with multiple rounds and a final."],
     "tournament = multi-round competition", "The school tournament lasted three days."),

    ("What does 'a close match' mean?",
     {"A": "a match where the scores are almost equal", "B": "a match that is far away", "C": "a match that is easy", "D": "a match that is cancelled"},
     "A", "medium", 55, "Review: L4",
     ["A close match is one where both sides score nearly the same."],
     "close match = very tight scores", "The close match ended 3-2."),

    # ===== L5: Encouragement phrases, speaking (9 items) =====
    ("Which phrase is used to encourage someone before a game?",
     {"A": "Good luck!", "B": "Bad news!", "C": "Well done!", "D": "Too bad!"},
     "A", "easy", 55, "Review: L5",
     ["'Good luck!' is said before an event to wish someone success."],
     "Good luck! = wish for success", "It is a common encouragement phrase."),

    ("What does 'You can do it!' express?",
     {"A": "encouragement", "B": "anger", "C": "sadness", "D": "confusion"},
     "A", "easy", 55, "Review: L5",
     ["'You can do it!' is a phrase used to encourage and motivate someone."],
     "You can do it! = encouragement", "It tells someone you believe in their ability."),

    ("Your friend says, 'I am nervous about the game.' Which is the best response?",
     {"A": "Don't worry, you'll do great!", "B": "That's your problem.", "C": "I don't care.", "D": "Just give up."},
     "A", "easy", 55, "Review: L5",
     ["A good response reassures and encourages the person."],
     "Don't worry = reassurance", "We should comfort nervous friends."),

    ("When your friend wins a match, you can say...",
     {"A": "Congratulations!", "B": "Better luck next time!", "C": "That's terrible!", "D": "I'm sorry."},
     "A", "easy", 55, "Review: L5",
     ["'Congratulations!' is said to praise someone on an achievement."],
     "Congratulations! = praise for success", "Use it after someone wins or achieves something."),

    ("Which phrase means 'try your hardest'?",
     {"A": "Do your best!", "B": "Take it easy!", "C": "Sit down!", "D": "Be quiet!"},
     "A", "easy", 56, "Review: L5",
     ["'Do your best!' encourages someone to put in maximum effort."],
     "Do your best! = maximum effort", "This is the title theme of Unit 5."),

    ("What does 'Cheer up!' mean?",
     {"A": "Don't be sad!", "B": "Stand up!", "C": "Go faster!", "D": "Wake up!"},
     "A", "medium", 56, "Review: L5",
     ["'Cheer up!' is used to tell someone to stop feeling sad."],
     "Cheer up! = don't be sad", "It is a common phrase of comfort."),

    ("To tell someone you believe in them, you can say...",
     {"A": "I believe in you!", "B": "I doubt you.", "C": "You will fail.", "D": "Try harder next time."},
     "A", "medium", 56, "Review: L5",
     ["'I believe in you!' expresses confidence in someone's ability."],
     "I believe in you! = expressing faith", "It builds someone's confidence."),

    ("Which phrase shows support before a competition?",
     {"A": "We're all rooting for you!", "B": "We don't care.", "C": "Goodbye forever!", "D": "You'll never win."},
     "A", "medium", 56, "Review: L5",
     ["'Rooting for you' means supporting and cheering someone on."],
     "rooting for you = supporting you", "A team of supporters roots for the player."),

    ("What is a good response to someone who says 'Good luck!'?",
     {"A": "Thank you!", "B": "No!", "C": "I don't need it!", "D": "Go away!"},
     "A", "easy", 56, "Review: L5",
     ["Saying 'Thank you!' is a polite response to being wished good luck."],
     "Thank you! = polite response", "Always thank people for their good wishes."),

    # ===== L6: Writing connectors, report language (10 items) =====
    ("Which word is used to show contrast in a sports report?",
     {"A": "however", "B": "also", "C": "finally", "D": "first"},
     "A", "easy", 56, "Review: L6",
     ["'However' shows a contrast or opposite idea."],
     "however = contrast", "The team played well; however, they lost."),

    ("To add more information in a report, you can use...",
     {"A": "furthermore", "B": "however", "C": "but", "D": "although"},
     "A", "medium", 56, "Review: L6",
     ["'Furthermore' is used to add extra information to a point."],
     "furthermore = in addition", "It is common in formal writing."),

    ("What does 'In conclusion' signal in a text?",
     {"A": "the ending or summary", "B": "the beginning", "C": "a question", "D": "a contrast"},
     "A", "easy", 57, "Review: L6",
     ["'In conclusion' introduces the final summary or closing idea."],
     "in conclusion = the end", "It tells the reader the text is finishing."),

    ("Which sequence words are used to describe a series of events?",
     {"A": "First, then, finally", "B": "But, however, although", "C": "Also, furthermore, moreover", "D": "Because, so, therefore"},
     "A", "easy", 57, "Review: L6",
     ["Sequence words like 'first, then, finally' show the order of events."],
     "first/then/finally = order", "They help readers follow the timeline."),

    ("What does 'As a result' show in a report?",
     {"A": "cause and effect", "B": "contrast", "C": "time", "D": "location"},
     "A", "medium", 57, "Review: L6",
     ["'As a result' shows the consequence or effect of something."],
     "as a result = consequence", "They trained hard; as a result, they won."),

    ("To give an example in writing, you can use...",
     {"A": "for example", "B": "in conclusion", "C": "as a result", "D": "however"},
     "A", "easy", 57, "Review: L6",
     ["'For example' introduces a specific instance to support a point."],
     "for example = instance", "Many sports, for example football, require teamwork."),

    ("Which connector shows that something happens next in time?",
     {"A": "after that", "B": "however", "C": "in contrast", "D": "nevertheless"},
     "A", "easy", 57, "Review: L6",
     ["'After that' connects events by showing what happens next."],
     "after that = next in time", "They won the semi-final; after that, they reached the final."),

    ("What is the purpose of an introduction in a sports report?",
     {"A": "to give basic information about the event", "B": "to give your final opinion", "C": "to list the results", "D": "to describe the weather"},
     "A", "medium", 56, "Review: L6",
     ["An introduction provides key facts like who, what, when, and where."],
     "introduction = basic info", "It sets the scene for the reader."),

    ("Which word means 'at the same time'?",
     {"A": "meanwhile", "B": "therefore", "C": "consequently", "D": "moreover"},
     "A", "medium", 57, "Review: L6",
     ["'Meanwhile' means during the same period of time."],
     "meanwhile = at the same time", "One team scored; meanwhile, the other rested."),

    ("To summarise your report, you can begin with...",
     {"A": "to sum up", "B": "to begin with", "C": "first of all", "D": "on the other hand"},
     "A", "medium", 57, "Review: L6",
     ["'To sum up' introduces the final summary of the main points."],
     "to sum up = in summary", "It signals the writer is wrapping up."),
]
