# Unit 1 Lesson 4 (Grammar: Continuous and perfect tenses, pages 8-9) — part 1
ITEMS = [
    ("Which tense is used in 'I've just been running'?",
     {"A": "present perfect continuous", "B": "past perfect", "C": "future continuous", "D": "present simple"},
     "A", "easy", 8, "Exercise 3: Extracts from the recording",
     ["'I've just been running' uses have + been + -ing, i.e. the present perfect continuous."],
     "I've been running = present perfect continuous.", "The extract uses the present perfect continuous to describe a recent activity."),

    ("Which tense is used in 'I'll be doing a 5k run for charity in a few weeks'?",
     {"A": "future continuous", "B": "future perfect", "C": "present perfect continuous", "D": "past continuous"},
     "A", "easy", 8, "Exercise 3: Extracts from the recording",
     ["'I'll be doing' uses will + be + -ing, i.e. the future continuous."],
     "I'll be doing = future continuous.", "The future continuous describes an action in progress at a future time."),

    ("Which tense is used in 'Had you done much running before?'?",
     {"A": "past perfect", "B": "present perfect", "C": "past continuous", "D": "past simple"},
     "A", "easy", 8, "Exercise 3: Extracts from the recording",
     ["'Had you done' uses had + past participle, i.e. the past perfect."],
     "Had you done = past perfect.", "The past perfect describes an action that happened before a past time."),

    ("Which tense is used in 'I will have been running every day for two months'?",
     {"A": "future perfect continuous", "B": "future perfect", "C": "present perfect continuous", "D": "future continuous"},
     "A", "medium", 8, "Exercise 3: Extracts from the recording",
     ["'Will have been running' uses will + have + been + -ing, i.e. the future perfect continuous."],
     "will have been running = future perfect continuous.", "This tense describes how long an action will have continued by a future time."),

    ("We use the present perfect continuous to ...",
     {"A": "focus on the activity itself or its continuity", "B": "focus on a finished result", "C": "describe a permanent state", "D": "describe a past habit"},
     "A", "medium", 8, "Grammar Reference: Continuous and perfect tenses",
     ["The present perfect continuous focuses on the activity and how long it continues."],
     "Present perfect continuous = focus on continuity.", "It emphasises the ongoing activity rather than the finished result."),

    ("We use the present perfect simple to ...",
     {"A": "focus on a finished action and its present result", "B": "focus on the duration of an activity", "C": "describe an action in progress", "D": "describe a future plan"},
     "A", "medium", 8, "Grammar Reference: Continuous and perfect tenses",
     ["The present perfect simple focuses on a completed action that has a result now."],
     "Present perfect simple = finished action with result.", "It shows a completed action connected to the present."),

    ("Which tense describes an action that was in progress at a moment in the past?",
     {"A": "past continuous", "B": "present perfect", "C": "future continuous", "D": "past perfect"},
     "A", "easy", 8, "Grammar Reference: Continuous and perfect tenses",
     ["The past continuous (was/were + -ing) describes an action in progress in the past."],
     "Past continuous = in progress in the past.", "Example: 'I was running for the bus when I tripped.'"),

    ("We use the past perfect to describe ...",
     {"A": "an action that happened before another past action", "B": "an action happening now", "C": "a future plan", "D": "a temporary habit"},
     "A", "easy", 8, "Grammar Reference: Continuous and perfect tenses",
     ["The past perfect (had + past participle) refers to the earlier of two past actions."],
     "Past perfect = earlier past action.", "Example: 'Before I trained, I had never run in a race.'"),

    ("Which tense describes an action that will be in progress at a certain time in the future?",
     {"A": "future continuous", "B": "future perfect", "C": "present continuous", "D": "past continuous"},
     "A", "easy", 8, "Grammar Reference: Continuous and perfect tenses",
     ["The future continuous (will be + -ing) describes an action in progress at a future time."],
     "Future continuous = in progress in the future.", "Example: 'This time next week I'll be doing a 5k run.'"),

    ("We use the future perfect to describe ...",
     {"A": "an action that will be finished by a certain time in the future", "B": "an action in progress now", "C": "a completed action in the past", "D": "a future intention"},
     "A", "easy", 8, "Grammar Reference: Continuous and perfect tenses",
     ["The future perfect (will have + past participle) describes an action finished by a future time."],
     "Future perfect = finished by a future time.", "Example: 'When I finish the marathon, I will have run 42 km.'"),

    ("We use the future perfect continuous to describe ...",
     {"A": "how long something will have been going on by a future time", "B": "a single finished future action", "C": "a present habit", "D": "a past experience"},
     "A", "medium", 8, "Grammar Reference: Continuous and perfect tenses",
     ["The future perfect continuous emphasises the duration of an action up to a future time."],
     "Future perfect continuous = duration up to a future time.", "Example: 'Next week I will have been running every day for two months.'"),

    ("In 'I've been reading a book about habits', the speaker ...",
     {"A": "is still reading the book", "B": "has finished the book", "C": "will read the book soon", "D": "never reads books"},
     "A", "medium", 8, "Exercise 4: Matching meanings",
     ["The present perfect continuous shows the action is still in progress, so the speaker is still reading."],
     "I've been reading = still reading.", "The continuous form shows the activity has not finished."),

    ("In 'I've read a book about habits', the speaker ...",
     {"A": "has finished the book", "B": "is still reading the book", "C": "reads books quickly", "D": "has no time to read"},
     "A", "medium", 8, "Exercise 4: Matching meanings",
     ["The present perfect simple describes a finished action."],
     "I've read = finished reading.", "The simple form focuses on the completed result."),

    ("In 'I will be working', the speaker ...",
     {"A": "will be in the middle of work", "B": "will have finished work", "C": "worked in the past", "D": "is working now"},
     "A", "medium", 8, "Exercise 4: Matching meanings",
     ["The future continuous shows the person will be in the middle of working."],
     "I will be working = in the middle of work.", "The continuous form describes an action in progress at a future time."),

    ("In 'I will have been working', the speaker ...",
     {"A": "will have finished work", "B": "will be in the middle of work", "C": "never works", "D": "is working now"},
     "A", "hard", 8, "Exercise 4: Matching meanings",
     ["The future perfect shows the work will be finished by that future time."],
     "I will have been working = finished.", "The perfect form focuses on completion."),

    ("In 'I had been eating all day', the meaning is that the person ...",
     {"A": "was eating continuously or very often", "B": "ate one meal that day", "C": "did not eat at all", "D": "will eat later"},
     "A", "hard", 8, "Exercise 4: Matching meanings",
     ["'Had been eating' is the past perfect continuous, which shows continuous or repeated eating."],
     "I had been eating all day = eating continuously.", "The continuous form emphasises the repeated or continuous activity."),

    ("In 'I had eaten that day', the meaning is that the person ...",
     {"A": "ate at some point that day", "B": "was eating all day long", "C": "will eat that day", "D": "never eats"},
     "A", "hard", 8, "Exercise 4: Matching meanings",
     ["'Had eaten' is the past perfect simple, which describes one finished action."],
     "I had eaten = ate once.", "The simple form describes a single completed action."),

    ("In 'I've come up with a great idea', the speaker ...",
     {"A": "has the idea now", "B": "had the idea long ago", "C": "will think of an idea", "D": "lost the idea"},
     "A", "medium", 8, "Exercise 4: Matching meanings",
     ["The present perfect shows the idea exists now as a result of a past action."],
     "I've come up with = I have the idea now.", "The present perfect connects the past action to the present."),

    ("In 'I had a great idea', the speaker ...",
     {"A": "came up with an idea at some point in the past", "B": "has the idea right now", "C": "will have an idea", "D": "does not remember the idea"},
     "A", "medium", 8, "Exercise 4: Matching meanings",
     ["'I had' is the past simple, describing an action at a past time."],
     "I had a great idea = idea in the past.", "The past simple refers to a finished time in the past."),

    ("'I'm playing a lot of football' means ...",
     {"A": "I've been doing it recently or temporarily", "B": "I always do it", "C": "I will never do it", "D": "I did it in the past"},
     "A", "medium", 8, "Exercise 4: Matching meanings",
     ["The present continuous describes a temporary or recent activity."],
     "I'm playing = temporary/recent activity.", "The continuous form shows it is happening around now."),

    ("'I play a lot of football' means ...",
     {"A": "this is something I always do", "B": "this is a temporary habit", "C": "I am playing now", "D": "I played once"},
     "A", "medium", 8, "Exercise 4: Matching meanings",
     ["The present simple describes a permanent or regular activity."],
     "I play = something I always do.", "The simple form shows a regular, permanent habit."),
]
