# Unit 3 Lesson 2 (Listening and Vocabulary: Persuasion, page 28)
ITEMS = [
    ("Which word describes someone who is too ready to believe things?",
     {"A": "credulous", "B": "shrewd", "C": "crafty", "D": "ingenuous"},
     "A", "medium", 28, "Exercise 1: Adjectives",
     ["'Credulous' means too ready to believe things; easily deceived."],
     "credulous = too trusting.", "It is close in meaning to gullible."),

    ("Which word describes someone who easily believes people are honest?",
     {"A": "gullible", "B": "cunning", "C": "devious", "D": "shrewd"},
     "A", "easy", 28, "Exercise 1: Adjectives",
     ["'Gullible' means easily fooled or tricked."],
     "gullible = easily tricked.", "Gullible people believe anything."),

    ("Which word means 'sly and clever at deceiving others'?",
     {"A": "cunning", "B": "naive", "C": "trusting", "D": "unsuspecting"},
     "A", "medium", 28, "Exercise 1: Adjectives",
     ["'Cunning' means clever at deceiving people."],
     "cunning = sly and deceptive.", "A cunning person is hard to fool."),

    ("Which word describes someone who is not honest and tricks others?",
     {"A": "devious", "B": "gullible", "C": "credulous", "D": "shrewd"},
     "A", "medium", 28, "Exercise 1: Adjectives",
     ["'Devious' means dishonest and cunning."],
     "devious = dishonest.", "A devious person uses tricks."),

    ("Which word describes someone who is clever and practical in business?",
     {"A": "shrewd", "B": "naive", "C": "crafty", "D": "unsuspecting"},
     "A", "medium", 28, "Exercise 1: Adjectives",
     ["'Shrewd' means clever and good at judging situations."],
     "shrewd = clever and practical.", "A shrewd businessperson makes good decisions."),

    ("Which word describes someone with little experience of the world?",
     {"A": "naive", "B": "devious", "C": "cunning", "D": "shrewd"},
     "A", "easy", 28, "Exercise 1: Adjectives",
     ["'Naive' means lacking experience and too ready to trust."],
     "naive = inexperienced.", "Naive people are easy to persuade."),

    ("Which word means 'clever at getting what you want'?",
     {"A": "crafty", "B": "credulous", "C": "gullible", "D": "trusting"},
     "A", "medium", 28, "Exercise 1: Adjectives",
     ["'Crafty' means clever, especially in a cunning way."],
     "crafty = clever and sly.", "Crafty salespeople use tricks."),

    ("Which word describes someone who does not suspect anything wrong?",
     {"A": "unsuspecting", "B": "cunning", "C": "devious", "D": "shrewd"},
     "A", "medium", 28, "Exercise 1: Adjectives",
     ["'Unsuspecting' means not realising that something bad is happening."],
     "unsuspecting = not suspicious.", "The salesperson targeted unsuspecting customers."),

    ("What is the 'scarcity principle' in persuasion?",
     {"A": "people want things more when they are rare or limited", "B": "people always buy the cheapest product", "C": "people ignore rare products", "D": "people prefer more choice"},
     "A", "easy", 28, "Exercise 2: Persuasion techniques",
     ["Scarcity works by making something seem limited, so people want it more."],
     "Scarcity = limited availability.", "'Only a few left!' creates demand."),

    ("What is 'framing' in persuasion?",
     {"A": "presenting information in a way that influences the choice", "B": "putting products in picture frames", "C": "advertising on the radio", "D": "giving free samples"},
     "A", "hard", 28, "Exercise 2: Persuasion techniques",
     ["Framing means showing the same information in a different way to change perception."],
     "framing = how the choice is presented.", "e.g. '90% fat-free' vs '10% fat'."),

    ("What is 'reciprocation' in persuasion?",
     {"A": "if someone gives you something, you feel you should give something back", "B": "copying the salesperson", "C": "repeating a question", "D": "returning a product"},
     "A", "medium", 28, "Exercise 2: Persuasion techniques",
     ["Reciprocation is the feeling of needing to return a favour."],
     "reciprocation = returning a favour.", "Free sweets with the bill make people buy more."),

    ("What is 'social proof' in persuasion?",
     {"A": "people follow what others are doing", "B": "people ignore other customers", "C": "proof that a product works", "D": "social media advertising only"},
     "A", "medium", 28, "Exercise 2: Persuasion techniques",
     ["Social proof means people copy the behaviour of others."],
     "social proof = following the crowd.", "'Best seller' badges use social proof."),

    ("What are 'yes questions' in persuasion?",
     {"A": "questions that make the customer keep saying yes", "B": "questions that are easy to ignore", "C": "questions about the price", "D": "questions nobody answers"},
     "A", "hard", 28, "Exercise 2: Persuasion techniques",
     ["Getting the customer to agree to small things first makes agreement easier."],
     "yes questions lead to agreement.", "Each 'yes' makes the next one easier."),

    ("What does the technique of leaving sweets with the bill show?",
     {"A": "reciprocation", "B": "scarcity", "C": "social proof", "D": "framing"},
     "A", "hard", 28, "Exercise 3: Listening focus",
     ["The sweets made customers feel they should buy more in return."],
     "It shows reciprocation.", "The gift created a feeling of obligation."),

    ("What did Adnan imply about the interviewer and her orange coat?",
     {"A": "she was a bit naive when she bought it", "B": "she made a great choice", "C": "she never wanted the coat", "D": "she got a discount"},
     "A", "medium", 28, "Exercise 3: Listening focus",
     ["Adnan implied the interviewer was a bit naive to be persuaded to buy it."],
     "She was a bit naive.", "The salesperson persuaded her easily."),

    ("What does 'to infer meaning' mean in listening?",
     {"A": "to work out a meaning from evidence, not direct words", "B": "to hear every word perfectly", "C": "to repeat what you heard", "D": "to translate word for word"},
     "A", "easy", 28, "Active Listening: Inferring meaning",
     ["An inference is an idea or conclusion based on evidence."],
     "infer = conclude from evidence.", "You use the speaker's words and what you know."),

    ("According to Active Listening, what should you consider while listening?",
     {"A": "the connotation of the words and what you know about the topic", "B": "only the grammar of each sentence", "C": "the number of words spoken", "D": "the speaker's accent only"},
     "A", "medium", 28, "Active Listening: Inferring meaning",
     ["Consider whether words have positive or negative connotations and what you know."],
     "Consider word connotations and knowledge.", "This helps you infer opinion and attitude."),

    ("Which word means 'to persuade by being extra nice or flattering'?",
     {"A": "coax", "B": "coerce", "C": "incite", "D": "sway"},
     "A", "medium", 28, "Exercise 4: Synonyms of persuade",
     ["'Coax' means to persuade gently and kindly."],
     "coax = persuade kindly.", "She coaxed the child to clean her teeth."),

    ("Which word means 'to persuade someone using force or threats'?",
     {"A": "coerce", "B": "entice", "C": "urge", "D": "convince"},
     "A", "easy", 28, "Exercise 4: Synonyms of persuade",
     ["'Coerce' means to force someone by threats or pressure."],
     "coerce = force.", "He tried to coerce his brother into doing it."),

    ("Which word means 'to persuade by offering something attractive'?",
     {"A": "entice", "B": "coerce", "C": "incite", "D": "pressure"},
     "A", "medium", 28, "Exercise 4: Synonyms of persuade",
     ["'Entice' means to tempt someone with an attractive offer."],
     "entice = tempt.", "They enticed her to leave with promises of a better salary."),

    ("Which word means 'to persuade someone to do something violent or unpleasant'?",
     {"A": "incite", "B": "coax", "C": "sway", "D": "convince"},
     "A", "hard", 28, "Exercise 4: Synonyms of persuade",
     ["'Incite' means to encourage something violent or unpleasant."],
     "incite = stir up violence.", "It has a negative sense."),

    ("Which word means 'to make someone believe something is true'?",
     {"A": "convince", "B": "coerce", "C": "entice", "D": "incite"},
     "A", "easy", 28, "Exercise 4: Synonyms of persuade",
     ["'Convince' means to make someone believe or agree."],
     "convince = make believe.", "She convinced the child to clean her teeth."),

    ("Which word means 'to try hard to persuade someone'?",
     {"A": "urge", "B": "entice", "C": "coax", "D": "sway"},
     "A", "easy", 28, "Exercise 4: Synonyms of persuade",
     ["'Urge' means to strongly encourage someone to do something."],
     "urge = strongly encourage.", "She urged the team to take responsibility."),

    ("Which word means 'to persuade someone with gentle pressure'?",
     {"A": "pressure", "B": "incite", "C": "coerce", "D": "entice"},
     "A", "medium", 28, "Exercise 4: Synonyms of persuade",
     ["'Pressure' as a verb means to try to persuade by putting pressure on someone."],
     "pressure = apply pressure.", "She pressured the team into taking responsibility."),

    ("Which word means 'to persuade people to choose between two things'?",
     {"A": "sway", "B": "incite", "C": "coerce", "D": "entice"},
     "A", "hard", 28, "Exercise 4: Synonyms of persuade",
     ["'Sway' means to influence someone's decision one way or another."],
     "sway = influence a decision.", "The argument swayed them towards the cheaper option."),

    ("Which word means 'to persuade by gentle talking or flattery'?",
     {"A": "cajole", "B": "coerce", "C": "incite", "D": "pressure"},
     "A", "medium", 28, "Exercise 4: Synonyms of persuade",
     ["'Cajole' means to persuade with flattery or gentle urging."],
     "cajole = persuade with flattery.", "She cajoled us into working late."),

    ("Complete: 'She ______ the child to clean her teeth.' (COAX)",
     {"A": "coaxed", "B": "coerced", "C": "incited", "D": "pressured"},
     "A", "medium", 28, "Exercise 5: Key word transformations",
     ["The past form of 'coax' is 'coaxed'."],
     "coaxed", "She persuaded the child kindly."),

    ("Complete: 'The company ______ her to leave her job with promises of a better salary.' (ENTICE)",
     {"A": "enticed", "B": "coaxed", "C": "coerced", "D": "swayed"},
     "A", "medium", 28, "Exercise 5: Key word transformations",
     ["'Enticed' means tempted with an attractive offer."],
     "enticed", "The promises tempted her to leave."),

    ("Complete: 'She ______ us to work late.' (CAJOLE)",
     {"A": "cajoled", "B": "enticed", "C": "incited", "D": "coerced"},
     "A", "medium", 28, "Exercise 5: Key word transformations",
     ["'Cajoled' means persuaded with gentle talk."],
     "cajoled", "She talked us into working late."),

    ("Complete: 'She ______ the team into taking responsibility.' (URGE)",
     {"A": "urged", "B": "coaxed", "C": "enticed", "D": "incited"},
     "A", "hard", 28, "Exercise 5: Key word transformations",
     ["The transformation uses 'urged' with a to-infinitive or into + -ing."],
     "urged", "She strongly encouraged the team."),

    ("Which phrase describes strong persuasion 'without much choice'?",
     {"A": "coerce and incite", "B": "coax and cajole", "C": "convince and sway", "D": "entice and urge"},
     "A", "hard", 28, "Exercise 4: Categories",
     ["Coerce (force) and incite (stir up) involve strong pressure."],
     "coerce, incite = strong persuasion.", "The others are gentler or neutral."),

    ("Which verb pattern is typical of 'persuade' in 'persuade someone to do something'?",
     {"A": "someone to do something", "B": "someone into doing something", "C": "someone of something", "D": "someone for something"},
     "A", "medium", 28, "Exercise 4: Verb patterns",
     ["Many of these verbs take 'someone to do something'."],
     "someone to do something", "e.g. persuade someone to stay."),

    ("Which of these adjectives describes an ideal customer for a clever salesperson?",
     {"A": "gullible", "B": "shrewd", "C": "cunning", "D": "devious"},
     "A", "easy", 28, "Exercise 1: Adjectives",
     ["A gullible customer is easy to persuade and is an ideal target."],
     "gullible", "The lesson asks which describe the man and his ideal customer."),

    ("What was Lama's attitude towards the salesperson described by the interviewer?",
     {"A": "horrified", "B": "admiring", "C": "bored", "D": "indifferent"},
     "A", "medium", 28, "Exercise 3: Listening focus",
     ["The listening asks how Lama felt; the salesperson used tricky techniques."],
     "Lama was horrified.", "She disliked the deceptive sales techniques."),

    ("How did Adnan describe the salesperson's techniques?",
     {"A": "devious", "B": "ethical", "C": "effortless", "D": "honest"},
     "A", "medium", 28, "Exercise 3: Listening focus",
     ["Adnan described the techniques as devious (dishonest)."],
     "devious", "He saw them as tricky."),

    ("What is the lesson's vocabulary focus?",
     {"A": "synonyms of 'persuade' and words for describing people", "B": "phrasal verbs for shopping", "C": "food adjectives", "D": "adverbs of frequency"},
     "A", "easy", 28, "Lesson 2A: Listening and Vocabulary",
     ["The lesson focuses on persuasion vocabulary and inferring meaning."],
     "Persuasion vocabulary", "It covers cajole, coax, coerce, etc."),

    ("Why is 'inferring opinion and attitude' useful in listening?",
     {"A": "it helps you understand the speaker's real opinion even when implied", "B": "it helps you spell words", "C": "it helps you count words", "D": "it helps you translate"},
     "A", "medium", 28, "Active Listening",
     ["Inference lets you work out attitudes from evidence in the speech."],
     "It reveals the true opinion.", "Words can have positive or negative connotations."),

    ("Which adjective is the opposite of 'naive'?",
     {"A": "shrewd", "B": "gullible", "C": "credulous", "D": "unsuspecting"},
     "A", "hard", 28, "Exercise 1: Adjectives",
     ["'Shrewd' (clever and practical) is the opposite of naive."],
     "shrewd vs naive", "Naive people are easily fooled; shrewd people are not."),

    ("Which verb means 'to encourage someone by being extra nice'?",
     {"A": "coax", "B": "coerce", "C": "threaten", "D": "demand"},
     "A", "medium", 28, "Exercise 4: Synonyms of persuade",
     ["'Coax' means to persuade gently by being extra nice."],
     "coax = gently persuade.", "She coaxed the dog with treats."),

    ("What does 'connotation' mean in the context of listening?",
     {"A": "the feeling or idea a word gives beyond its dictionary meaning", "B": "the exact dictionary definition", "C": "the sound of a word", "D": "the spelling of a word"},
     "A", "hard", 28, "Active Listening: Inferring meaning",
     ["A connotation is the extra meaning a word carries, positive or negative."],
     "connotation = associated feeling.", "Words like 'cheap' and 'affordable' have different connotations."),
]
