# Unit 3 Lesson 1 (Vocabulary and Speaking: Hard sell, pages 26-27)
ITEMS = [
    ("What is the Goat Rental Service?",
     {"A": "a company that rents goats to mow lawns and eat weeds", "B": "a pet shop", "C": "a farm that sells milk", "D": "a zoo"},
     "A", "easy", 26, "Reading: Goat Rental Service",
     ["The company brings goats to clear grass and weeds instead of using machines."],
     "Goats are rented to mow lawns.", "It is eco-friendly and cost-effective."),

    ("What is the USP of the goat rental service?",
     {"A": "it is eco-friendly", "B": "it is the cheapest service", "C": "the goats are fast", "D": "it uses electric mowers"},
     "A", "medium", 26, "Reading: Goat Rental Service",
     ["The text says the USP is that it is very eco-friendly."],
     "Its USP is being eco-friendly.", "USP = unique selling point."),

    ("How much grass can 38 goats 'mow' in a single day?",
     {"A": "50,000 square feet", "B": "5,000 square feet", "C": "500 square feet", "D": "50 square feet"},
     "A", "easy", 26, "Reading: Goat Rental Service",
     ["'Just 38 goats can 'mow' 50,000 square feet of grass in a single day.'"],
     "50,000 square feet", "The service is cost-effective."),

    ("What did Saeed want to launch?",
     {"A": "a business making furniture many people would consider an eyesore", "B": "a goat rental service", "C": "a cake shop", "D": "a furniture repair shop"},
     "A", "easy", 26, "Reading: One-of-a-kind Furniture",
     ["Saeed dreamt of launching a business based on making ugly (eyesore) furniture."],
     "A furniture business", "His wife thought he had lost his marbles."),

    ("What does 'he'd completely lost his marbles' mean?",
     {"A": "he had gone mad", "B": "he lost his toys", "C": "he was poor", "D": "he was sleeping"},
     "A", "medium", 26, "Reading: One-of-a-kind Furniture",
     ["'Lose your marbles' means to go crazy."],
     "lost his marbles = went mad.", "His wife could not believe his idea."),

    ("What was Saeed's 'bread and butter'?",
     {"A": "being skilful at making furniture", "B": "eating sandwiches", "C": "selling cakes", "D": "his salary"},
     "A", "hard", 26, "Reading: One-of-a-kind Furniture",
     ["'Bread and butter' means the way you earn a living; here, making furniture."],
     "bread and butter = main income.", "It was his basic skill and job."),

    ("How did Saeed's business perform?",
     {"A": "within three months it had a turnover of more than $10,000 a month", "B": "it went bankrupt quickly", "C": "it stayed tiny", "D": "he closed it down"},
     "A", "medium", 26, "Reading: One-of-a-kind Furniture",
     ["'Within three months, his company had a turnover of more than $10,000 a month.'"],
     "It had a big turnover.", "The 'eyesore' tag worked as a sales gimmick."),

    ("What does 'turnover' mean in business?",
     {"A": "the amount of business a company does in a set period of time", "B": "the number of workers", "C": "the size of the office", "D": "the price of one product"},
     "A", "easy", 27, "Exercise 2: Business vocabulary",
     ["Turnover is the amount of business done in a period."],
     "turnover = total business.", "It is usually measured in money."),

    ("What is a 'sales gimmick'?",
     {"A": "a trick or gimmick used to attract sales", "B": "a genuine product feature", "C": "a discount for regular customers", "D": "a type of shop"},
     "A", "hard", 26, "Reading: One-of-a-kind Furniture",
     ["The 'eyesore' tag was a bit of a sales gimmick to attract attention."],
     "sales gimmick = sales trick.", "It worked even though it was a gimmick."),

    ("What does 'branching out into' mean?",
     {"A": "expanding the work normally done into new areas", "B": "closing the business", "C": "moving to a new city", "D": "employing more staff"},
     "A", "medium", 27, "Exercise 2: Business vocabulary",
     ["Saeed is thinking about branching out into ugly accessories."],
     "branching out = expanding into.", "It extends the range of the business."),

    ("What did Nada decide to do for her own wedding?",
     {"A": "make her own cake", "B": "buy a cheap cake", "C": "order a cake online", "D": "have no cake"},
     "A", "easy", 26, "Reading: Incredible Cake",
     ["Unimpressed by expensive wedding cakes, Nada decided to make her own."],
     "She made her own cake.", "It was a work of art with edible trees and waterfalls."),

    ("Why did Nada work from home at first?",
     {"A": "she and her husband didn't have the capital for a shop", "B": "she preferred home working", "C": "her shop burned down", "D": "she had no customers"},
     "A", "medium", 26, "Reading: Incredible Cake",
     ["They didn't have the capital for a bricks-and-mortar shop, so she used e-commerce."],
     "No capital for a shop.", "She relied on e-commerce for her start-up."),

    ("What does 'bricks-and-mortar' mean?",
     {"A": "a physical building such as a shop or office", "B": "a building material", "C": "a website", "D": "a storage room"},
     "A", "medium", 27, "Exercise 2: Business vocabulary",
     ["'Bricks-and-mortar' refers to physical buildings, like a real shop."],
     "bricks-and-mortar = physical shop.", "Opposite of an online-only business."),

    ("What is a 'start-up'?",
     {"A": "a new business that is risky", "B": "a very old company", "C": "a branch of a bank", "D": "a chain store"},
     "A", "easy", 27, "Exercise 2: Business vocabulary",
     ["A start-up is a new, risky business."],
     "start-up = new risky business.", "Her cake business began as a start-up."),

    ("What was Nada's new trade name?",
     {"A": "A piece and love", "B": "One-of-a-kind Furniture", "C": "Goat Rental", "D": "Incredible Cake"},
     "A", "medium", 26, "Reading: Incredible Cake",
     ["She opened her first physical store with the trade name 'A piece and love'."],
     "A piece and love", "The name is a play on 'a piece of cake'."),

    ("What does 'bespoke' mean?",
     {"A": "specially made for a particular person", "B": "very cheap", "C": "mass-produced", "D": "broken"},
     "A", "easy", 27, "Exercise 2: Business vocabulary",
     ["Her cakes include bespoke creations for the happy couple."],
     "bespoke = made to order.", "Bespoke cakes are made specially for customers."),

    ("What does 'bargain basement prices' mean?",
     {"A": "extremely cheap prices", "B": "expensive prices", "C": "average prices", "D": "hidden prices"},
     "A", "medium", 27, "Exercise 2: Business vocabulary",
     ["Her simple designs are at bargain basement prices = very cheap."],
     "bargain basement = extremely cheap.", "The cakes cater to all budgets."),

    ("What does 'good value for money' mean?",
     {"A": "worth the price you pay", "B": "very expensive", "C": "free", "D": "poor quality"},
     "A", "easy", 27, "Exercise 2: Business vocabulary",
     ["Good value for money means the product is worth its price."],
     "good value for money = worth it.", "Customers want value for money."),

    ("What is a 'quote'?",
     {"A": "the estimated price that will be charged for a service", "B": "a famous saying", "C": "a product guarantee", "D": "a delivery time"},
     "A", "medium", 27, "Exercise 2: Business vocabulary",
     ["The goat company will provide a quote before bringing the goats."],
     "quote = estimated price.", "It is a price offered before the service."),

    ("What is a 'business concept'?",
     {"A": "an idea for a business", "B": "a finished product", "C": "a shop building", "D": "an employee"},
     "A", "medium", 27, "Exercise 2: Business vocabulary",
     ["Making cakes for a living became a business concept."],
     "business concept = business idea.", "It is the idea behind the company."),

    ("What is the 'price tag' of a product?",
     {"A": "the amount that something costs", "B": "the label with the brand", "C": "the size of the product", "D": "the expiry date"},
     "A", "easy", 27, "Exercise 2: Business vocabulary",
     ["Nada was unimpressed by the expensive price tag of wedding cakes."],
     "price tag = the cost.", "It is the price attached to a product."),

    ("Which compound noun means 'money spent to start something'?",
     {"A": "upfront investment", "B": "sales gimmick", "C": "impulse buy", "D": "start-up"},
     "A", "medium", 27, "Exercise 4: Compound nouns",
     ["Planes require a lot of upfront investment to design and make."],
     "upfront investment", "It is the money paid before a project starts."),

    ("Which compound noun means 'something bought without planning'?",
     {"A": "impulse buy", "B": "sales gimmick", "C": "upfront investment", "D": "word-of-mouth"},
     "A", "medium", 27, "Exercise 4: Compound nouns",
     ["'It was a bit of an impulse buy' = he bought it without planning."],
     "impulse buy", "You buy on impulse."),

    ("Complete: 'They're giving away free toys as a part of a sales ______.'",
     {"A": "gimmick", "B": "concept", "C": "quote", "D": "venture"},
     "A", "easy", 27, "Exercise 4: Compound nouns",
     ["The compound noun is 'sales gimmick'."],
     "sales gimmick", "It is a trick to attract buyers."),

    ("Complete: 'My friend has just established a new start-______.'",
     {"A": "up", "B": "in", "C": "out", "D": "down"},
     "A", "easy", 27, "Exercise 4: Compound nouns",
     ["The compound noun is 'start-up'."],
     "start-up", "It is a new business."),

    ("Complete: 'Planes require a lot of ______ investment.'",
     {"A": "upfront", "B": "offline", "C": "overtime", "D": "overhead"},
     "A", "medium", 27, "Exercise 4: Compound nouns",
     ["The compound noun is 'upfront investment'."],
     "upfront investment", "The money is paid at the beginning."),

    ("Complete: 'I wasn't planning on getting a new shirt, it was a bit of an impulse ______.'",
     {"A": "buy", "B": "sell", "C": "rent", "D": "loan"},
     "A", "easy", 27, "Exercise 4: Compound nouns",
     ["The compound noun is 'impulse buy'."],
     "impulse buy", "It was a sudden, unplanned purchase."),

    ("Which phrasal verb means 'to start (a business)'?",
     {"A": "set up", "B": "break into", "C": "knock off", "D": "pass up"},
     "A", "easy", 27, "Exercise 6: Phrasal verbs",
     ["'What gave you the idea to set up the business?'"],
     "set up = start.", "You set up a new company."),

    ("Which phrasal verb means 'to enter (a new market)'?",
     {"A": "break into", "B": "sign up", "C": "win over", "D": "build up"},
     "A", "medium", 27, "Exercise 6: Phrasal verbs",
     ["'It seemed like a good market to break into.'"],
     "break into = enter.", "It means to get involved with a market."),

    ("Which phrasal verb means 'to fail to take advantage of an opportunity'?",
     {"A": "pass up", "B": "set up", "C": "knock off", "D": "build up"},
     "A", "medium", 27, "Exercise 6: Phrasal verbs",
     ["'It was too good an opportunity to pass up.'"],
     "pass up = fail to use.", "He did not want to miss the chance."),

    ("Which phrasal verb means 'to commit (to a service)'?",
     {"A": "sign up", "B": "break into", "C": "win over", "D": "knock off"},
     "A", "medium", 27, "Exercise 6: Phrasal verbs",
     ["'We often get new customers to sign up on the spot.'"],
     "sign up = commit.", "Customers agree to use the service."),

    ("Which phrasal verb means 'to gradually increase'?",
     {"A": "build up", "B": "pass up", "C": "set up", "D": "break into"},
     "A", "medium", 27, "Exercise 6: Phrasal verbs",
     ["'We'd been gradually building up customer loyalty in that area.'"],
     "build up = increase gradually.", "Loyalty grows over time."),

    ("Which phrasal verb means 'to persuade someone to support you'?",
     {"A": "win over", "B": "knock off", "C": "sign up", "D": "pass up"},
     "A", "medium", 27, "Exercise 6: Phrasal verbs",
     ["'Eventually, we did manage to win them over.'"],
     "win over = persuade.", "They finally persuaded the customers."),

    ("Which phrasal verb means 'to considerably reduce a price'?",
     {"A": "knock something off", "B": "build something up", "C": "set something up", "D": "break something into"},
     "A", "medium", 27, "Exercise 6: Phrasal verbs",
     ["'We had to considerably knock the price off.'"],
     "knock off = reduce price.", "They lowered the price a lot."),

    ("How did Nada's reputation grow?",
     {"A": "through social media and word-of-mouth", "B": "through television adverts", "C": "through radio commercials", "D": "through newspaper ads"},
     "A", "medium", 26, "Reading: Incredible Cake",
     ["'Through social media and word-of-mouth, her reputation grew.'"],
     "Social media and word-of-mouth.", "Within a year she opened a physical store."),

    ("What does 'word-of-mouth' mean?",
     {"A": "people telling each other about something", "B": "advertising on the radio", "C": "speaking publicly", "D": "a written review"},
     "A", "medium", 26, "Reading: Incredible Cake",
     ["Word-of-mouth means customers recommend the business to each other."],
     "word-of-mouth = personal recommendation.", "It helped her reputation grow."),

    ("What does 'meticulous attention to detail' mean?",
     {"A": "extremely careful attention to detail", "B": "careless work", "C": "quick work", "D": "no attention at all"},
     "A", "medium", 26, "Reading: Incredible Cake",
     ["Nada and her staff pay meticulous attention to detail."],
     "meticulous = extremely careful.", "Each cake is made to be special."),

    ("What does 'cost-effective' mean?",
     {"A": "giving good value in relation to its cost", "B": "extremely expensive", "C": "free of charge", "D": "difficult to sell"},
     "A", "medium", 27, "Exercise 2: Business vocabulary",
     ["The goat service is cost-effective: 38 goats do a huge job for the money."],
     "cost-effective = worth the cost.", "It gives good value for money."),

    ("What does the unit overview say the WRITING focus is?",
     {"A": "a for-and-against essay", "B": "an email of complaint", "C": "a blog post", "D": "a restaurant review"},
     "A", "easy", 26, "Unit 3 overview",
     ["Unit 3 WRITING: A for-and-against essay."],
     "A for-and-against essay", "The GRAMMAR focus is the Passive."),

    ("What does the unit overview say the GRAMMAR focus is?",
     {"A": "the Passive", "B": "inversion", "C": "cleft sentences", "D": "conditional forms"},
     "A", "easy", 26, "Unit 3 overview",
     ["Unit 3 GRAMMAR: The Passive."],
     "The Passive", "It also covers phrasal verbs and compound nouns."),
]
