ITEMS = [
    (
        "Which modal verb is used for strong advice?",
        {"A": "Should", "B": "Could", "C": "Might", "D": "Would"},
        "A",
        "easy",
        50,
        "L2",
        ["Identify the modal verb used for giving advice."],
        "'Should' is used for advice.",
        "'Should' gives suggestions or recommendations."
    ),
    (
        "Complete: 'You ___ give up easily.'",
        {"A": "should not", "B": "should", "C": "can", "D": "may"},
        "A",
        "easy",
        50,
        "L2",
        ["Choose the correct negative modal for advice."],
        "'Should not' means it is bad advice to give up.",
        "We use 'should not' to advise against an action."
    ),
    (
        "What does 'must' express in 'You must train hard'?",
        {"A": "Strong obligation or necessity", "B": "Possibility", "C": "Permission", "D": "Future plan"},
        "A",
        "easy",
        50,
        "L2",
        ["Identify the meaning of 'must' in this sentence."],
        "'Must' expresses strong obligation.",
        "'Must' indicates something is absolutely necessary."
    ),
    (
        "Which is the comparative form of 'fast'?",
        {"A": "Faster", "B": "Fastest", "C": "More fast", "D": "Fastlier"},
        "A",
        "easy",
        51,
        "L2",
        ["Form the comparative of the one-syllable adjective 'fast'."],
        "'Faster' is the comparative of 'fast'.",
        "One-syllable adjectives usually add '-er' for comparatives."
    ),
    (
        "Choose the correct sentence: 'She runs ___ than her sister.'",
        {"A": "faster", "B": "more fast", "C": "fastest", "D": "most fast"},
        "A",
        "easy",
        51,
        "L2",
        ["Select the correct comparative form."],
        "'Faster' is correct.",
        "We use comparatives with 'than' to compare two things."
    ),
    (
        "What is the superlative of 'good'?",
        {"A": "Best", "B": "Goodest", "C": "Better", "D": "More good"},
        "A",
        "medium",
        51,
        "L2",
        ["Recall the superlative form of the irregular adjective 'good'."],
        "'Best' is the superlative of 'good'.",
        "'Good' is irregular: good, better, best."
    ),
    (
        "Complete: 'He is ___ player on the team.'",
        {"A": "the best", "B": "the better", "C": "good", "D": "best"},
        "A",
        "medium",
        51,
        "L2",
        ["Choose the correct superlative with an article."],
        "'The best' is correct with a superlative.",
        "Superlatives require the definite article 'the'."
    ),
    (
        "What does 'had better' express?",
        {"A": "Strong advice with a warning if ignored", "B": "Past obligation", "C": "Future possibility", "D": "Permission"},
        "A",
        "medium",
        50,
        "L2",
        ["Define the meaning of 'had better'."],
        "'Had better' gives strong advice with a warning.",
        "'Had better' suggests consequences if the advice is not followed."
    ),
    (
        "Choose: 'You ___ study harder if you want to pass.'",
        {"A": "had better", "B": "may", "C": "might", "D": "could"},
        "A",
        "medium",
        50,
        "L2",
        ["Select the best modal for urgent strong advice."],
        "'Had better' gives urgent strong advice.",
        "'Had better' implies a warning about consequences."
    ),
    (
        "What is the comparative of 'tall'?",
        {"A": "Taller", "B": "Tallest", "C": "More tall", "D": "Talliest"},
        "A",
        "easy",
        51,
        "L2",
        ["Form the comparative of 'tall'."],
        "'Taller' is the comparative of 'tall'.",
        "Add '-er' to short adjectives for comparatives."
    ),
    (
        "Complete: 'This race is ___ difficult ___ the last one.'",
        {"A": "more ... than", "B": "most ... than", "C": "much ... from", "D": "less ... to"},
        "A",
        "medium",
        51,
        "L2",
        ["Choose the correct comparative structure."],
        "'More ... than' is correct for multi-syllable adjectives.",
        "'More + adjective + than' is used for longer adjectives."
    ),
    (
        "What does 'have to' express?",
        {"A": "Obligation or duty", "B": "Suggestion", "C": "Ability", "D": "Possibility"},
        "A",
        "easy",
        50,
        "L2",
        ["Identify the meaning of 'have to'."],
        "'Have to' expresses obligation.",
        "'Have to' means something is required or necessary."
    ),
    (
        "Which sentence uses 'must' correctly?",
        {"A": "You must wear a helmet when cycling.", "B": "You must maybe attend.", "C": "You must will win.", "D": "You must to train."},
        "A",
        "easy",
        50,
        "L2",
        ["Identify the correct use of 'must'."],
        "'You must wear a helmet' is correct.",
        "'Must' is followed by a base verb, no 'to' or other modals."
    ),
    (
        "What is the superlative of 'bad'?",
        {"A": "Worst", "B": "Baddest", "C": "Badder", "D": "Worse"},
        "A",
        "medium",
        51,
        "L2",
        ["Recall the superlative of the irregular adjective 'bad'."],
        "'Worst' is the superlative of 'bad'.",
        "'Bad' is irregular: bad, worse, worst."
    ),
    (
        "Complete: 'She is ___ athlete I have ever seen.'",
        {"A": "the most talented", "B": "most talented", "C": "talented than", "D": "the talented"},
        "A",
        "medium",
        51,
        "L2",
        ["Choose the correct superlative form."],
        "'The most talented' is the correct superlative.",
        "Multi-syllable adjectives use 'most' for superlatives."
    ),
    (
        "What is the difference between 'must' and 'have to'?",
        {"A": "Must is personal obligation; have to is external obligation", "B": "There is no difference", "C": "Must is for past; have to is for future", "D": "Must is weaker than have to"},
        "A",
        "hard",
        50,
        "L2",
        ["Compare the meanings of 'must' and 'have to'."],
        "'Must' is internal; 'have to' is external obligation.",
        "'Must' comes from the speaker; 'have to' comes from rules or authority."
    ),
    (
        "Choose: 'You ___ not smoke in the stadium.'",
        {"A": "must", "B": "should", "C": "might", "D": "could"},
        "A",
        "easy",
        50,
        "L2",
        ["Select the modal for a strong prohibition."],
        "'Must not' expresses strong prohibition.",
        "'Must not' means something is absolutely forbidden."
    ),
    (
        "What is the comparative of 'good'?",
        {"A": "Better", "B": "Gooder", "C": "More good", "D": "Best"},
        "A",
        "easy",
        51,
        "L2",
        ["Recall the comparative of the irregular adjective 'good'."],
        "'Better' is the comparative of 'good'.",
        "'Good' is irregular: good, better, best."
    ),
    (
        "Which sentence is correct?",
        {"A": "He ran more quickly than anyone else.", "B": "He ran most quickly than anyone.", "C": "He ran quickly than anyone.", "D": "He ran the most quicklier."},
        "A",
        "medium",
        51,
        "L2",
        ["Identify the correct comparative sentence."],
        "'More quickly than' is correct.",
        "Adverbs with more than one syllable use 'more' for comparatives."
    ),
    (
        "Complete: 'If you want to win, you ___ practise every day.'",
        {"A": "should", "B": "might", "C": "could", "D": "would"},
        "A",
        "easy",
        50,
        "L2",
        ["Choose the best modal for giving advice."],
        "'Should' is the best choice for advice.",
        "'Should' is the most common modal for giving advice."
    ),
    (
        "What is the superlative of 'athletic'?",
        {"A": "Most athletic", "B": "Athleticest", "C": "Athleticer", "D": "The athleticest"},
        "A",
        "medium",
        51,
        "L2",
        ["Form the superlative of 'athletic'."],
        "'Most athletic' is the correct superlative.",
        "Adjectives with three or more syllables use 'most' for superlatives."
    ),
    (
        "Choose: 'You ___ be more careful next time.'",
        {"A": "should", "B": "must to", "C": "should to", "D": "must can"},
        "A",
        "easy",
        50,
        "L2",
        ["Select the grammatically correct modal."],
        "'Should' is followed directly by the base verb.",
        "Modal verbs are never followed by 'to' or another modal."
    ),
    (
        "What does 'can' express in 'She can run very fast'?",
        {"A": "Ability", "B": "Obligation", "C": "Advice", "D": "Permission"},
        "A",
        "easy",
        50,
        "L2",
        ["Identify the meaning of 'can' in this context."],
        "'Can' expresses ability.",
        "'Can' shows what someone is able to do."
    ),
    (
        "Which is the superlative of 'exhausted'?",
        {"A": "Most exhausted", "B": "Exhaustedest", "C": "Exhausteder", "D": "The exhaustedest"},
        "A",
        "medium",
        51,
        "L2",
        ["Form the superlative of 'exhausted'."],
        "'Most exhausted' is correct.",
        "Long adjectives use 'most' for superlatives."
    ),
    (
        "Complete: 'You ___ listen to your coach.'",
        {"A": "had better", "B": "can to", "C": "might to", "D": "could to"},
        "A",
        "medium",
        50,
        "L2",
        ["Choose the correct modal phrase."],
        "'Had better' is the correct choice.",
        "'Had better' gives strong advice with implied consequences."
    ),
    (
        "What is the comparative of 'determined'?",
        {"A": "More determined", "B": "Determineder", "C": "Most determined", "D": "Determinedest"},
        "A",
        "medium",
        51,
        "L2",
        ["Form the comparative of 'determined'."],
        "'More determined' is the correct comparative.",
        "Long adjectives use 'more' for comparatives."
    ),
    (
        "Choose: 'I ___ to finish this race even if I'm tired.'",
        {"A": "am going", "B": "must to", "C": "should to", "D": "had better to"},
        "A",
        "medium",
        50,
        "L2",
        ["Select the correct expression of intention."],
        "'Am going to' expresses a future intention.",
        "This shows determination to complete the race."
    ),
    (
        "Which sentence uses a superlative correctly?",
        {"A": "She is the fastest runner in the school.", "B": "She is fastest runner in school.", "C": "She is the faster runner.", "D": "She is more fast runner."},
        "A",
        "medium",
        51,
        "L2",
        ["Identify the correct superlative sentence."],
        "'The fastest' is the correct superlative form.",
        "Superlatives need 'the' and are followed by 'in' or 'of'."
    ),
    (
        "What does 'may' express in 'You may leave early'?",
        {"A": "Permission", "B": "Obligation", "C": "Advice", "D": "Ability"},
        "A",
        "easy",
        50,
        "L2",
        ["Identify the meaning of 'may' here."],
        "'May' expresses permission.",
        "'May' is a polite way to give or ask for permission."
    ),
    (
        "Complete: 'This is ___ goal I have scored all season.'",
        {"A": "the most important", "B": "more important", "C": "importantest", "D": "the importantest"},
        "A",
        "medium",
        51,
        "L2",
        ["Choose the correct superlative form."],
        "'The most important' is the correct superlative.",
        "Multi-syllable adjectives use 'most' with 'the' for superlatives."
    ),
    (
        "What is the difference between 'should' and 'must'?",
        {"A": "Should is advice; must is obligation", "B": "They mean the same", "C": "Must is weaker than should", "D": "Should is for commands"},
        "A",
        "medium",
        50,
        "L2",
        ["Compare 'should' and 'must'."],
        "'Should' is advice; 'must' is obligation.",
        "'Must' is stronger and more forceful than 'should'."
    ),
    (
        "Choose: 'He ___ have scored that goal!'",
        {"A": "should", "B": "must to", "C": "should to", "D": "had better to"},
        "A",
        "medium",
        50,
        "L2",
        ["Select the correct modal for criticism."],
        "'Should have' expresses criticism about the past.",
        "'Should have + past participle' regrets a past action."
    ),
    (
        "What is the comparative of 'competitive'?",
        {"A": "More competitive", "B": "Competitiver", "C": "Most competitive", "D": "Competitiveest"},
        "A",
        "medium",
        51,
        "L2",
        ["Form the comparative of 'competitive'."],
        "'More competitive' is correct.",
        "Long adjectives always use 'more' for comparatives."
    ),
    (
        "Which modal shows future possibility?",
        {"A": "Might", "B": "Must", "C": "Should", "D": "Have to"},
        "A",
        "easy",
        50,
        "L2",
        ["Identify the modal for future possibility."],
        "'Might' shows something could happen.",
        "'Might' suggests a lower probability than 'will'."
    ),
    (
        "Complete: 'She is ___ than her opponent.'",
        {"A": "stronger", "B": "strongest", "C": "more strong", "D": "most strong"},
        "A",
        "easy",
        51,
        "L2",
        ["Choose the correct comparative form."],
        "'Stronger' is the correct comparative.",
        "One-syllable adjectives add '-er' for comparatives."
    ),
    (
        "What does 'had better not' mean?",
        {"A": "Strong advice not to do something", "B": "Permission to stop", "C": "Past ability", "D": "Future possibility"},
        "A",
        "hard",
        50,
        "L2",
        ["Define 'had better not'."],
        "'Had better not' advises strongly against an action.",
        "'Had better not' implies bad consequences if the action is done."
    ),
    (
        "Choose the correct sentence:",
        {"A": "You must not cheat in a competition.", "B": "You mustn't to cheat.", "C": "You must not to cheat.", "D": "You mustn't cheating."},
        "A",
        "medium",
        50,
        "L2",
        ["Identify the grammatically correct sentence."],
        "'You must not cheat' is correct.",
        "'Must' is followed by the base form without 'to'."
    ),
    (
        "What is the superlative of 'fit'?",
        {"A": "Fittest", "B": "Most fit", "C": "Fitest", "D": "The most fit"},
        "A",
        "easy",
        51,
        "L2",
        ["Form the superlative of 'fit'."],
        "'Fittest' is the correct superlative.",
        "Short adjectives double the final consonant and add '-est'."
    ),
    (
        "Which sentence uses 'have to' correctly?",
        {"A": "You have to follow the rules.", "B": "You have to must follow.", "C": "You have to should follow.", "D": "You have to to follow."},
        "A",
        "easy",
        50,
        "L2",
        ["Identify the correct use of 'have to'."],
        "'You have to follow the rules' is correct.",
        "'Have to' is followed by the base form of the verb."
    ),
    (
        "Complete: 'This is ___ competition I have entered.'",
        {"A": "the most challenging", "B": "more challenging", "C": "challengingest", "D": "the challengingest"},
        "A",
        "hard",
        51,
        "L2",
        ["Choose the correct superlative form."],
        "'The most challenging' is correct.",
        "Multi-syllable adjectives need 'most' and 'the' for superlatives."
    ),
]
