# Unit 3 Review (all lessons, pages 26-40)
ITEMS = [
    ("What does 'bargain' mean in 'The watch was a bargain'?",
     {"A": "something bought for less than its usual price", "B": "a repair", "C": "a present", "D": "a loan"},
     "A", "easy", 40, "Review: L1 vocabulary",
     ["A bargain is something bought cheaply."],
     "a good cheap deal", "You pay less than usual."),

    ("Which word means 'badly made'?",
     {"A": "shoddy", "B": "reliable", "C": "durable", "D": "luxury"},
     "A", "medium", 40, "Review: L1 vocabulary",
     ["'Shoddy' describes poor, careless workmanship."],
     "shoddy = badly made", "Shoddy goods break quickly."),

    ("Which verb means 'to make an effort to persuade'?",
     {"A": "lobby", "B": "protest", "C": "boycott", "D": "recycle"},
     "A", "medium", 40, "Review: L1 vocabulary",
     ["'Lobby' means to persuade people in power to change things."],
     "lobby = try to persuade", "Campaigners lobby governments."),

    ("Which verb means 'to refuse to buy something as a protest'?",
     {"A": "boycott", "B": "lobby", "C": "patronise", "D": "invest"},
     "A", "easy", 40, "Review: L1 vocabulary",
     ["A boycott is a refusal to buy as protest."],
     "boycott = refuse to buy", "People boycotted the brand."),

    ("Which word means 'to support a business by buying from it'?",
     {"A": "patronise", "B": "boycott", "C": "lobby", "D": "oppose"},
     "A", "hard", 40, "Review: L1 vocabulary",
     ["'Patronise' means to shop at or use a business."],
     "patronise = support by buying", "Please patronise our sponsors."),

    ("Which word means 'a small amount of money given to help'?",
     {"A": "a contribution", "B": "a discount", "C": "a refund", "D": "an invoice"},
     "A", "medium", 40, "Review: L1 vocabulary",
     ["A contribution is money given to help a cause."],
     "contribution = donation", "They asked for a small contribution."),

    ("What does 'a deal' mean in shopping language?",
     {"A": "a good price or arrangement", "B": "a bad product", "C": "a lawsuit", "D": "an apology"},
     "A", "easy", 40, "Review: L1 vocabulary",
     ["A deal is a good offer or arrangement."],
     "deal = good offer", "It was a fantastic deal."),

    ("What does 'reliable' mean?",
     {"A": "can be trusted to work well", "B": "cheap", "C": "modern", "D": "rare"},
     "A", "easy", 40, "Review: L1 vocabulary",
     ["Reliable things or people can be trusted."],
     "reliable = trustworthy", "Buy a reliable brand."),

    ("What does 'durable' mean?",
     {"A": "strong and long-lasting", "B": "expensive", "C": "fashionable", "D": "light"},
     "A", "easy", 40, "Review: L1 vocabulary",
     ["Durable goods last a long time."],
     "durable = long-lasting", "Durable clothes survive many washes."),

    ("What does 'a valid reason' mean?",
     {"A": "a good and acceptable reason", "B": "a weak excuse", "C": "a secret plan", "D": "a lucky chance"},
     "A", "medium", 40, "Review: L1 vocabulary",
     ["A valid reason is acceptable and well-founded."],
     "valid = acceptable", "He had a valid reason for complaining."),

    ("What does 'a campaign' mean?",
     {"A": "an organised effort to achieve a change", "B": "a shopping trip", "C": "a type of shop", "D": "an argument"},
     "A", "easy", 40, "Review: L1 vocabulary",
     ["A campaign is an organised effort to make a change."],
     "campaign = organised effort", "They ran a campaign against plastic."),

    ("What does 'an aid worker' do?",
     {"A": "helps people in difficult situations", "B": "runs a shop", "C": "collects taxes", "D": "sells insurance"},
     "A", "easy", 40, "Review: L1 vocabulary",
     ["Aid workers give help to people in crisis."],
     "aid worker = helper", "They work in disaster zones."),

    ("What is 'fast fashion'?",
     {"A": "cheap clothes that follow the latest trends for a short time", "B": "clothes that last forever", "C": "designer luxury clothes", "D": "traditional national dress"},
     "A", "easy", 40, "Review: L1 vocabulary",
     ["Fast fashion is cheap, trendy clothing that changes quickly."],
     "cheap and trendy", "It has a big environmental cost."),

    ("Which word means 'a request for money from people'?",
     {"A": "an appeal", "B": "a receipt", "C": "a receipt", "D": "a label"},
     "A", "medium", 40, "Review: L1 vocabulary",
     ["An appeal is a serious request for help or money."],
     "appeal = money request", "They launched an appeal for the victims."),

    ("What is 'persuasive power'?",
     {"A": "the ability to change people's minds", "B": "the ability to make money", "C": "physical strength", "D": "good luck"},
     "A", "medium", 40, "Review: L2 persuasion",
     ["Persuasive power is the ability to convince others."],
     "ability to convince", "Persuasion influences our choices."),

    ("According to Robert Cialdini, what triggers 'the scarcity principle'?",
     {"A": "feeling that something may not be available for long", "B": "a low price", "C": "a famous brand", "D": "a friend's advice"},
     "A", "easy", 40, "Review: L2 persuasion",
     ["Scarcity works when we fear losing an opportunity."],
     "fear of missing out", "Limited offers feel more valuable."),

    ("What is 'the rule of reciprocity'?",
     {"A": "we feel obliged to return favours", "B": "we like to be first", "C": "we copy our friends", "D": "we want to be unique"},
     "A", "medium", 40, "Review: L2 persuasion",
     ["Reciprocity: if someone gives us something, we feel we owe them back."],
     "returning favours", "Free samples exploit reciprocity."),

    ("What is 'social proof'?",
     {"A": "we are influenced by what other people do", "B": "we trust nobody", "C": "we always think alone", "D": "we distrust our friends"},
     "A", "easy", 40, "Review: L2 persuasion",
     ["Social proof means copying the behaviour of others."],
     "following the crowd", "Reviews and ratings use social proof."),

    ("What is 'the authority principle'?",
     {"A": "we are persuaded by people we see as experts", "B": "we ignore experts", "C": "we only trust children", "D": "we obey nobody"},
     "A", "medium", 40, "Review: L2 persuasion",
     ["We are more likely to agree with people in authority."],
     "trusting experts", "White coats and titles signal authority."),

    ("What does 'the rule of liking' claim?",
     {"A": "we are persuaded by people we like", "B": "we buy only disliked products", "C": "we never trust anyone", "D": "friends cannot persuade us"},
     "A", "medium", 40, "Review: L2 persuasion",
     ["We tend to agree with people we like."],
     "liking leads to agreement", "Salespeople try to be likeable."),

    ("What is 'spontaneous'?",
     {"A": "done suddenly, without planning", "B": "done carefully after research", "C": "expensive", "D": "forbidden"},
     "A", "easy", 40, "Review: L2 vocabulary",
     ["Spontaneous actions are unplanned and sudden."],
     "spontaneous = unplanned", "A spontaneous decision is quick."),

    ("What does 'a scam' mean?",
     {"A": "a dishonest trick to get your money", "B": "a fair deal", "C": "a cheap offer", "D": "a long queue"},
     "A", "easy", 40, "Review: L2 vocabulary",
     ["A scam is a dishonest scheme to steal money."],
     "scam = trick", "Online shopping can hide scams."),

    ("What does 'chances are' mean?",
     {"A": "it is likely that", "B": "it is impossible that", "C": "it is certain that", "D": "nobody knows"},
     "A", "medium", 40, "Review: L2 language",
     ["'Chances are' means 'it is probable'."],
     "it is likely", "Chances are, you will get a good deal."),

    ("What is the passive of 'People speak English everywhere'?",
     {"A": "English is spoken everywhere.", "B": "English was spoken everywhere.", "C": "English is speaking everywhere.", "D": "English speaks everywhere."},
     "A", "easy", 40, "Review: L5 grammar",
     ["Present simple passive: English is spoken everywhere."],
     "is spoken", "be + past participle."),

    ("What is the passive of 'They will finish the project soon'?",
     {"A": "The project will be finished soon.", "B": "The project will finish soon.", "C": "The project was finished soon.", "D": "The project is finished soon."},
     "A", "medium", 40, "Review: L5 grammar",
     ["Future passive: will be + past participle."],
     "will be finished", "Keep the future marker."),

    ("What is the passive of 'They have sold the house'?",
     {"A": "The house has been sold.", "B": "The house has sold.", "C": "The house is sold.", "D": "The house have been sold."},
     "A", "medium", 40, "Review: L5 grammar",
     ["Present perfect passive: has been + past participle."],
     "has been sold", "'The house' is singular."),

    ("What is the passive of 'They were building a new stadium'?",
     {"A": "A new stadium was being built.", "B": "A new stadium was being building.", "C": "A new stadium is being built.", "D": "A new stadium was built."},
     "A", "hard", 40, "Review: L5 grammar",
     ["Past continuous passive: was being + past participle."],
     "was being built", "An action in progress in the past."),

    ("Which sentence has the same meaning as 'People say that she is clever'?",
     {"A": "She is said to be clever.", "B": "She is said being clever.", "C": "She says to be clever.", "D": "She is saying clever."},
     "A", "medium", 40, "Review: L5 grammar",
     ["'She is said to be clever' is the correct passive."],
     "is said to be", "Report + to-infinitive."),

    ("Which sentence means 'People believe he made a fortune'?",
     {"A": "He is believed to have made a fortune.", "B": "He is believed to make a fortune.", "C": "He believes to have made a fortune.", "D": "He is believed making a fortune."},
     "A", "hard", 40, "Review: L5 grammar",
     ["Past actions use 'to have + past participle'."],
     "believed to have made", "Perfect infinitive for the past."),

    ("What does the article say economics is really about?",
     {"A": "making choices and decisions", "B": "only money", "C": "only banks", "D": "only taxes"},
     "A", "easy", 40, "Review: L4 reading",
     ["Economics is about choices and decisions."],
     "choices and decisions", "It covers all of life."),

    ("What is 'present bias'?",
     {"A": "overvaluing immediate rewards over long-term gains", "B": "preferring the future", "C": "ignoring the present", "D": "saving too much"},
     "A", "medium", 40, "Review: L4 reading",
     ["Present bias makes the immediate reward more attractive."],
     "overvaluing now", "It causes procrastination."),

    ("What is the 'sunk-cost fallacy'?",
     {"A": "persisting because you have already invested", "B": "giving up easily", "C": "buying cheap things", "D": "a maths mistake"},
     "A", "medium", 40, "Review: L4 reading",
     ["We keep going because of what we have already invested."],
     "persist because invested", "It often works against us."),

    ("What does 'the law of diminishing returns' mean?",
     {"A": "beyond a point, extra effort gives less benefit", "B": "prices always fall", "C": "work always pays", "D": "more is always better"},
     "A", "medium", 40, "Review: L4 reading",
     ["Each extra unit of effort gives less and less benefit."],
     "less benefit per effort", "Doing your best is good enough."),

    ("What does 'no such thing as a free lunch' warn us about?",
     {"A": "hidden costs in things that seem free", "B": "free food", "C": "cheap prices", "D": "free parking"},
     "A", "easy", 40, "Review: L4 reading",
     ["Everything has a hidden cost."],
     "hidden costs", "Free offers often cost you in other ways."),

    ("What does 'negate' mean?",
     {"A": "cancel out", "B": "increase", "C": "create", "D": "explain"},
     "A", "hard", 40, "Review: L4 vocabulary",
     ["'Negate' means to cancel or make ineffective."],
     "negate = cancel out", "Worries can negate a discount."),

    ("What does 'detrimental' mean?",
     {"A": "harmful", "B": "beneficial", "C": "unclear", "D": "sudden"},
     "A", "medium", 40, "Review: L4 vocabulary",
     ["'Detrimental' means damaging or harmful."],
     "detrimental = harmful", "It had a detrimental effect."),

    ("What does 'a notion' mean?",
     {"A": "an idea or concept", "B": "a trap", "C": "a price", "D": "a shop"},
     "A", "easy", 40, "Review: L4 vocabulary",
     ["A notion is an idea or belief."],
     "notion = idea", "Consider this notion."),

    ("What is a 'cost-benefit analysis'?",
     {"A": "weighing the costs against the benefits of a choice", "B": "a bill for repairs", "C": "a shopping list", "D": "a bank account"},
     "A", "medium", 40, "Review: L4 reading",
     ["It weighs costs against benefits to make a decision."],
     "weigh costs against benefits", "Score each one out of five."),

    ("What is the topic of the for-and-against essay in the unit?",
     {"A": "whether we should buy locally or from abroad", "B": "whether to use cash", "C": "the price of fuel", "D": "online safety"},
     "A", "easy", 40, "Review: L6 writing",
     ["The essay debates buying local produce."],
     "buying local", "It balances both sides."),

    ("What does 'to shop around' mean?",
     {"A": "compare prices at different shops", "B": "buy in bulk", "C": "wander aimlessly", "D": "ask for a discount"},
     "A", "easy", 40, "Review: L6 collocations",
     ["You shop around to compare prices before buying."],
     "compare prices", "It helps you find the best deal."),

    ("What does 'to stock up' mean?",
     {"A": "buy large amounts to keep for later", "B": "sell old goods", "C": "open a shop", "D": "return items"},
     "A", "easy", 40, "Review: L6 collocations",
     ["Stock up = buy plenty of something for the future."],
     "buy in quantity", "We stocked up before the holiday."),

    ("What does 'to mooch around' mean?",
     {"A": "wander slowly with no clear purpose", "B": "shop quickly", "C": "compare prices", "D": "buy everything"},
     "A", "medium", 40, "Review: L6 collocations",
     ["Mooch around = wander about without a plan."],
     "wander aimlessly", "They mooched around the mall."),

    ("What does 'to run errands' mean?",
     {"A": "make short trips to do small jobs", "B": "run a marathon", "C": "manage a business", "D": "write notes"},
     "A", "easy", 40, "Review: L6 collocations",
     ["Running errands means doing small tasks like shopping."],
     "small jobs/trips", "I have some errands to run."),

    ("What does 'to go on a shopping spree' mean?",
     {"A": "spend a lot of money shopping in a short time", "B": "look at shops without buying", "C": "go shopping weekly", "D": "return purchases"},
     "A", "easy", 40, "Review: L6 collocations",
     ["A spree is a period of excited, expensive buying."],
     "spend a lot at once", "She went on a shopping spree."),

    ("What does 'just the ticket' mean?",
     {"A": "exactly what is needed", "B": "a free ticket", "C": "a cheap fare", "D": "a parking fine"},
     "A", "medium", 40, "Review: L6 collocations",
     ["'Just the ticket' means exactly the right thing."],
     "exactly right", "That discount is just the ticket."),

    ("Where do you state your own opinion in a for-and-against essay?",
     {"A": "in the final paragraph", "B": "in the title", "C": "in every sentence", "D": "only in the middle"},
     "A", "easy", 40, "Review: L6 writing",
     ["The personal opinion comes in the conclusion."],
     "final paragraph", "The body stays balanced."),

    ("What tense do you use for your final opinion?",
     {"A": "the present simple", "B": "the past perfect", "C": "the future perfect", "D": "the present continuous"},
     "A", "medium", 40, "Review: L6 writing",
     ["Use the present simple to state what you think."],
     "present simple", "'I think that...'"),

    ("Which expression introduces the writer's conclusion?",
     {"A": "taking everything into account", "B": "to begin with", "C": "first of all", "D": "for example"},
     "A", "easy", 40, "Review: L6 writing",
     ["'Taking everything into account' signals the conclusion."],
     "conclusion marker", "Also 'on balance'."),

    ("What is the best balance the essay's writer recommends?",
     {"A": "strike a balance between buying local and buying imported goods", "B": "buy only imported goods", "C": "never shop again", "D": "only shop online"},
     "A", "medium", 40, "Review: L6 writing",
     ["The writer says we should strike a balance."],
     "a balanced approach", "Support local but accept imports."),

    ("Which sentence about passive use is correct?",
     {"A": "Passives make writing more formal and objective.", "B": "Passives always include the agent.", "C": "Passives are only used in questions.", "D": "Passives are informal."},
     "A", "medium", 40, "Review: L5 grammar",
     ["Passives are formal and focus on the action."],
     "formal and objective", "The agent is often left out."),
]
