# Unit 1 Lesson 5 (Reading and Vocabulary: What makes you who you are?, pages 10-11)
ITEMS = [
    ("What is the main idea of the reading text?",
     {"A": "our identity is shaped by a combination of genes, upbringing and experiences", "B": "only genes determine our personality", "C": "identity never changes after childhood", "D": "personality tests are the best way to know yourself"},
     "A", "easy", 10, "Reading: main idea",
     ["The text argues that identity is shaped by multiple factors, not just one."],
     "Identity = genes + upbringing + experience.", "The text presents a balanced view of nature and nurture."),

    ("According to the text, what does 'nature' refer to in the nature vs nurture debate?",
     {"A": "the genetic information we inherit from our parents", "B": "the environment we grow up in", "C": "the education we receive", "D": "the friends we make"},
     "A", "easy", 10, "Reading: paragraph A",
     ["'Nature' refers to the genetic inheritance we receive from our parents."],
     "nature = genes/inherited traits.", "It is one side of the identity debate."),

    ("According to the text, what does 'nurture' refer to?",
     {"A": "the environment, upbringing and experiences that shape us", "B": "the genes we are born with", "C": "the food we eat", "D": "the sports we play"},
     "A", "easy", 10, "Reading: paragraph A",
     ["'Nurture' refers to how our environment and experiences shape us."],
     "nurture = environment and upbringing.", "It is the other side of the identity debate."),

    ("What evidence does the text give for the role of nature?",
     {"A": "twins separated at birth often have similar personalities", "B": "people in the same family always behave the same", "C": "identical twins never share traits", "D": "genes have no effect on personality"},
     "A", "medium", 10, "Reading: paragraph B",
     ["Studies of twins separated at birth show genetic influence on personality."],
     "Separated twins show similar traits.", "This supports the nature argument."),

    ("What does the text say about identical twins raised apart?",
     {"A": "they often develop surprisingly similar habits and interests", "B": "they are always completely different", "C": "they have nothing in common", "D": "they never meet again"},
     "A", "medium", 10, "Reading: paragraph B",
     ["Identical twins raised apart often develop similar habits, suggesting genetic influence."],
     "Separated identical twins share similarities.", "This is strong evidence for genetic influence."),

    ("What argument does the text give for the role of nurture?",
     {"A": "children raised in different cultures develop different values and behaviours", "B": "all children behave the same regardless of environment", "C": "genes determine everything about us", "D": "upbringing has no effect on personality"},
     "A", "medium", 10, "Reading: paragraph C",
     ["Children raised in different cultures develop different values, showing nurture's role."],
     "Different cultures → different behaviours.", "This supports the nurture argument."),

    ("What example does the text use to show nurture's influence?",
     {"A": "siblings raised in the same family can have very different personalities", "B": "twins always behave identically", "C": "genes determine our career choices", "D": "education has no effect on character"},
     "A", "medium", 10, "Reading: paragraph C",
     ["Siblings in the same family can be very different, suggesting environment matters."],
     "Siblings can be very different.", "Same genes but different experiences lead to different personalities."),

    ("What is the text's conclusion about the nature vs nurture debate?",
     {"A": "both nature and nurture work together to shape identity", "B": "only nature matters", "C": "only nurture matters", "D": "the debate has been fully resolved"},
     "A", "medium", 10, "Reading: paragraph D",
     ["The text concludes that both factors work together in shaping who we are."],
     "Both nature and nurture matter.", "The debate is not either/or but both/and."),

    ("What does the text say about the influence of peers?",
     {"A": "friends and classmates can significantly shape our values and behaviour", "B": "peers have no influence on identity", "C": "only family matters", "D": "peer pressure is always negative"},
     "A", "medium", 10, "Reading: paragraph D",
     ["Peers (friends, classmates) significantly influence our values and behaviour."],
     "Peers shape our identity.", "This is part of the nurture argument."),

    ("What does the word 'innate' mean in the text?",
     {"A": "natural and present from birth", "B": "learned from experience", "C": "temporary and changeable", "D": "dangerous and harmful"},
     "A", "medium", 10, "Exercise 2: Vocabulary",
     ["'Innate' means something you are born with, natural and inborn."],
     "innate = inborn/natural.", "Innate traits come from genes, not experience."),

    ("What does 'acquired' mean in the context of the text?",
     {"A": "learned or developed through experience", "B": "born with", "C": "forgotten", "D": "given as a gift"},
     "A", "medium", 10, "Exercise 2: Vocabulary",
     ["'Acquired' means gained or learned through experience rather than born with."],
     "acquired = learned/developed.", "Skills and habits can be acquired over time."),

    ("What does 'environmental' mean in 'environmental factors'?",
     {"A": "relating to the surroundings and conditions we grow up in", "B": "relating to nature and wildlife", "C": "relating to genes", "D": "relating to exams"},
     "A", "easy", 10, "Exercise 2: Vocabulary",
     ["'Environmental' refers to the conditions and surroundings that affect development."],
     "environmental = relating to surroundings.", "Environmental factors include family, school and culture."),

    ("What does 'hereditary' mean?",
     {"A": "passed from parents to children through genes", "B": "learned at school", "C": "chosen freely", "D": "temporary"},
     "A", "easy", 10, "Exercise 2: Vocabulary",
     ["'Hereditary' means inherited or passed from parent to child."],
     "hereditary = inherited.", "Eye colour is a hereditary trait."),

    ("What does 'disposition' mean in the text?",
     {"A": "a person's natural tendency or character", "B": "a mathematical position", "C": "a type of argument", "D": "a medical condition"},
     "A", "medium", 10, "Exercise 2: Vocabulary",
     ["'Disposition' means a person's natural tendency or usual mood."],
     "disposition = natural tendency.", "A cheerful disposition means someone is naturally happy."),

    ("What does the text say about personality and change?",
     {"A": "personality can change throughout life due to experiences", "B": "personality is fixed at birth and never changes", "C": "only childhood experiences matter", "D": "personality tests can predict future personality"},
     "A", "medium", 10, "Reading: paragraph D",
     ["The text says personality can develop and change throughout life."],
     "Personality can change.", "Experiences continue to shape us as we grow."),

    ("What does the text say about the role of education?",
     {"A": "it plays an important role in shaping values and attitudes", "B": "it has no effect on personality", "C": "it only teaches academic skills", "D": "it is less important than genes"},
     "A", "medium", 10, "Reading: paragraph D",
     ["Education shapes our values, attitudes and behaviour significantly."],
     "Education shapes identity.", "School is a key part of the nurture argument."),

    ("What does 'pre-determined' mean in the text?",
     {"A": "decided in advance, before something happens", "B": "chosen randomly", "C": "changed after birth", "D": "learned from others"},
     "A", "hard", 10, "Exercise 2: Vocabulary",
     ["'Pre-determined' means fixed or decided before something happens."],
     "pre-determined = decided in advance.", "The text questions whether identity is pre-determined."),

    ("What does the text suggest about self-knowledge?",
     {"A": "understanding both nature and nurture helps us know ourselves better", "B": "we can never know ourselves", "C": "self-knowledge is only for scientists", "D": "personality tests are the only way to know yourself"},
     "A", "medium", 10, "Reading: paragraph D",
     ["Understanding both factors helps us develop better self-knowledge."],
     "Self-knowledge comes from understanding both factors.", "This is the text's practical message."),

    ("What does 'potential' mean in the text?",
     {"A": "the ability to develop or achieve something in the future", "B": "a current achievement", "C": "a past mistake", "D": "a physical strength"},
     "A", "medium", 10, "Exercise 2: Vocabulary",
     ["'Potential' means the possibility of future development or achievement."],
     "potential = future possibility.", "Everyone has potential that can be developed."),

    ("What does the text say about identical twins who share the same environment?",
     {"A": "they tend to be more similar than twins raised apart", "B": "they are always completely different", "C": "they have nothing in common", "D": "environment has no effect on them"},
     "A", "medium", 10, "Reading: paragraph B",
     ["Twins raised together are more similar than those raised apart, showing nurture's role."],
     "Same environment → more similar.", "This shows both nature and nurture work together."),

    ("What does the phrase 'a product of' mean in 'we are a product of our genes and experiences'?",
     {"A": "something that is created or shaped by", "B": "something that is sold in a shop", "C": "something that is broken", "D": "something that is lost"},
     "A", "easy", 10, "Exercise 3: Vocabulary in context",
     ["'A product of' means something that is the result of specific factors."],
     "product of = shaped by.", "We are shaped by both genes and experiences."),

    ("What does 'nurture' mean as a verb?",
     {"A": "to care for and encourage the growth or development of", "B": "to ignore completely", "C": "to punish severely", "D": "to forget about"},
     "A", "easy", 10, "Exercise 2: Vocabulary",
     ["As a verb, 'nurture' means to help something grow and develop."],
     "nurture = care for and develop.", "Parents nurture their children's talents."),

    ("What does 'heritage' mean in the text?",
     {"A": "the culture, traditions and qualities passed down from previous generations", "B": "a new invention", "C": "a type of food", "D": "a modern trend"},
     "A", "medium", 10, "Exercise 2: Vocabulary",
     ["'Heritage' refers to the culture and traditions passed from previous generations."],
     "heritage = inherited culture.", "Our heritage influences our values and identity."),

    ("What does the text say about the debate itself?",
     {"A": "it is still ongoing and scientists continue to research it", "B": "it was settled centuries ago", "C": "it is not important", "D": "only philosophers care about it"},
     "A", "medium", 10, "Reading: paragraph D",
     ["The debate continues as scientists keep researching the topic."],
     "The debate is still ongoing.", "New research continues to add to our understanding."),

    ("What does 'trait' mean in the text?",
     {"A": "a particular quality or characteristic", "B": "a type of food", "C": "a mathematical formula", "D": "a musical instrument"},
     "A", "easy", 10, "Exercise 2: Vocabulary",
     ["'Trait' means a distinguishing quality or characteristic of a person."],
     "trait = characteristic.", "Honesty is a positive personality trait."),

    ("What does 'upbringing' mean?",
     {"A": "the way a child is raised and cared for", "B": "growing taller", "C": "starting school", "D": "moving to a new house"},
     "A", "easy", 10, "Exercise 2: Vocabulary",
     ["'Upbringing' refers to the way a child is raised and the values they learn."],
     "upbringing = how you were raised.", "A good upbringing shapes positive values."),

    ("What does the text suggest about nature and nurture working together?",
     {"A": "genes provide the blueprint, but experiences shape how we develop", "B": "they work against each other", "C": "only one of them matters", "D": "they are the same thing"},
     "A", "medium", 10, "Reading: paragraph D",
     ["Genes give us tendencies, but experiences and environment shape how those tendencies develop."],
     "Genes + experiences = identity.", "Neither factor works alone."),

    ("What does 'influence' mean in the text?",
     {"A": "the power to affect how someone thinks or behaves", "B": "a type of electricity", "C": "a scientific experiment", "D": "a type of music"},
     "A", "easy", 10, "Exercise 2: Vocabulary",
     ["'Influence' is the power to have an effect on someone's character or behaviour."],
     "influence = power to affect.", "Family has a strong influence on children."),

    ("What does the text say about identical twins' IQ scores?",
     {"A": "twins raised apart often have very similar IQ scores", "B": "twins always have different IQ scores", "C": "IQ is entirely determined by education", "D": "IQ tests are unreliable"},
     "A", "medium", 10, "Reading: paragraph B",
     ["Studies show separated identical twins often have similar IQ scores, supporting genetic influence."],
     "Separated twins have similar IQs.", "This is evidence for the role of nature."),

    ("What does 'determine' mean in the text?",
     {"A": "to have a decisive effect on something", "B": "to measure precisely", "C": "to guess correctly", "D": "to forget completely"},
     "A", "medium", 10, "Exercise 2: Vocabulary",
     ["'Determine' means to cause something to happen or to have a decisive effect."],
     "determine = decide/cause.", "Genes and environment both determine our personality."),

    ("What does the text say about identical twins raised together vs apart?",
     {"A": "twins raised together are more similar, showing environment also matters", "B": "there is no difference between them", "C": "twins raised apart are more similar", "D": "environment has no effect on twins"},
     "A", "medium", 10, "Reading: paragraph B",
     ["Twins raised together show more similarities than those raised apart, proving nurture's role."],
     "Together twins are more similar.", "This proves both factors matter."),

    ("What does 'cognitive' mean in 'cognitive abilities'?",
     {"A": "relating to thinking, learning and understanding", "B": "relating to physical movement", "C": "relating to emotions", "D": "relating to music"},
     "A", "hard", 10, "Exercise 2: Vocabulary",
     ["'Cognitive' relates to the mental processes of thinking and understanding."],
     "cognitive = relating to thinking.", "Cognitive abilities include memory and problem-solving."),

    ("What does the text conclude about identity?",
     {"A": "identity is complex and shaped by many interacting factors", "B": "identity is simple and fixed", "C": "identity is entirely genetic", "D": "identity is entirely environmental"},
     "A", "medium", 10, "Reading: paragraph D",
     ["Identity is complex and results from many factors working together."],
     "Identity is complex.", "No single factor explains who we are."),

    ("What does 'resilient' mean in the text?",
     {"A": "able to recover quickly from difficulties", "B": "unable to change", "C": "very tall and strong", "D": "extremely quiet"},
     "A", "medium", 10, "Exercise 2: Vocabulary",
     ["'Resilient' means able to recover quickly from problems or setbacks."],
     "resilient = able to bounce back.", "Resilient people cope well with challenges."),

    ("What does the text say about the nature vs nurture debate in schools?",
     {"A": "understanding it can help teachers support students better", "B": "schools should ignore it", "C": "only science teachers need to know about it", "D": "it is too complicated for students"},
     "A", "medium", 10, "Reading: paragraph D",
     ["Understanding the debate helps educators create better learning environments."],
     "It helps teachers support students.", "Awareness of both factors improves education."),

    ("What does 'identity' mean in the text?",
     {"A": "the qualities, beliefs and characteristics that make a person unique", "B": "a type of document", "C": "a mathematical equation", "D": "a type of food"},
     "A", "easy", 10, "Reading: introduction",
     ["'Identity' refers to the qualities and characteristics that define who a person is."],
     "identity = who you are.", "It includes personality, values and beliefs."),

    ("What does the text say about the role of culture?",
     {"A": "different cultures shape different values and behaviours", "B": "culture has no effect on personality", "C": "all cultures are the same", "D": "culture is only about food and music"},
     "A", "medium", 10, "Reading: paragraph C",
     ["Different cultures shape different values, attitudes and behaviours."],
     "Culture shapes identity.", "This is part of the nurture argument."),

    ("What does 'express' mean in 'express our identity'?",
     {"A": "to show or communicate who we are", "B": "to hide our feelings", "C": "to travel quickly", "D": "to buy something"},
     "A", "easy", 10, "Exercise 3: Vocabulary in context",
     ["'Express' means to show or communicate thoughts, feelings or identity."],
     "express = show/communicate.", "We express our identity through clothes, music and behaviour."),

    ("What does the text say about the future of the debate?",
     {"A": "new research will continue to deepen our understanding", "B": "the debate will be solved tomorrow", "C": "no more research is needed", "D": "the debate is boring"},
     "A", "medium", 10, "Reading: paragraph D",
     ["Future research will continue to add to our understanding of identity."],
     "Research will continue.", "The debate is ongoing and evolving."),

    ("What does 'self-aware' mean?",
     {"A": "having a clear understanding of your own character and feelings", "B": "not knowing anything about yourself", "C": "being very angry", "D": "being physically strong"},
     "A", "medium", 10, "Exercise 2: Vocabulary",
     ["'Self-aware' means knowing and understanding your own character, feelings and motives."],
     "self-aware = knowing yourself.", "Self-awareness helps us grow as individuals."),
]
