# Unit 1 Lesson 1 (Vocabulary and Speaking, pages 4-5)
ITEMS = [
    ("Which of the following is a compound adjective formed by 'adjective + adjective'?",
     {"A": "red-hot", "B": "forward-looking", "C": "full-time", "D": "highly strung"},
     "A", "easy", 5, "Active Vocabulary: Compound adjectives",
     ["A compound adjective of the type adjective + adjective combines two adjectives, e.g. red-hot."],
     "red-hot is adjective + adjective.", "red-hot combines the adjectives 'red' and 'hot' to describe a single idea."),

    ("What type of compound adjective is 'forward-looking'?",
     {"A": "noun + adjective", "B": "adverb + adjective", "C": "adjective + noun", "D": "noun + gerund"},
     "B", "easy", 5, "Active Vocabulary: Compound adjectives",
     ["'forward-looking' is formed from the adverb 'forward' and the adjective 'looking'."],
     "forward-looking = adverb + adjective.", "Adverbs such as 'forward' combine with adjectives to form compound adjectives."),

    ("What type of compound adjective is 'world-famous'?",
     {"A": "noun + adjective", "B": "adjective + adjective", "C": "adjective + gerund", "D": "prefix + adjective"},
     "A", "easy", 5, "Active Vocabulary: Compound adjectives",
     ["'world-famous' is formed from the noun 'world' and the adjective 'famous'."],
     "world-famous = noun + adjective.", "A noun combines with an adjective, e.g. world-famous, lifelong."),

    ("What type of compound adjective is 'full-time'?",
     {"A": "adverb + past participle", "B": "noun + gerund", "C": "adjective + noun", "D": "noun + past participle"},
     "C", "easy", 5, "Active Vocabulary: Compound adjectives",
     ["'full-time' is formed from the adjective 'full' and the noun 'time'."],
     "full-time = adjective + noun.", "Some compound adjectives combine an adjective and a noun, e.g. full-time, cutting-edge."),

    ("What type of compound adjective is 'good-looking'?",
     {"A": "adjective + gerund", "B": "adverb + adjective", "C": "noun + adjective", "D": "adjective + noun"},
     "A", "easy", 5, "Active Vocabulary: Compound adjectives",
     ["'good-looking' is formed from the adjective 'good' and the gerund 'looking'."],
     "good-looking = adjective + gerund.", "An adjective can combine with a gerund, e.g. good-looking."),

    ("What type of compound adjective is 'highly strung'?",
     {"A": "noun + gerund", "B": "adverb + past participle", "C": "adjective + noun", "D": "prefix + adjective"},
     "B", "easy", 5, "Active Vocabulary: Compound adjectives",
     ["'highly strung' is formed from the adverb 'highly' and the past participle 'strung'."],
     "highly strung = adverb + past participle.", "An adverb combines with a past participle, e.g. highly strung."),

    ("What type of compound adjective is 'eye-catching'?",
     {"A": "noun + gerund", "B": "adjective + gerund", "C": "adverb + adjective", "D": "noun + past participle"},
     "A", "easy", 5, "Active Vocabulary: Compound adjectives",
     ["'eye-catching' is formed from the noun 'eye' and the gerund 'catching'."],
     "eye-catching = noun + gerund.", "A noun can combine with a gerund, e.g. eye-catching."),

    ("What type of compound adjective is 'olive oil-based'?",
     {"A": "adjective + noun", "B": "noun + past participle", "C": "noun + adjective", "D": "adverb + past participle"},
     "B", "easy", 5, "Active Vocabulary: Compound adjectives",
     ["'olive oil-based' is formed from the noun phrase 'olive oil' and the past participle 'based'."],
     "olive oil-based = noun + past participle.", "A noun combines with a past participle, e.g. olive oil-based."),

    ("What type of compound adjective is 'underconfident'?",
     {"A": "prefix + adjective", "B": "noun + adjective", "C": "adverb + adjective", "D": "adjective + adjective"},
     "A", "easy", 5, "Active Vocabulary: Compound adjectives",
     ["'underconfident' is formed from the prefix 'under-' and the adjective 'confident'."],
     "underconfident = prefix + adjective.", "Prefixes such as 'under-' can combine with adjectives, e.g. underconfident, overcooked."),

    ("What does 'absent-minded' mean?",
     {"A": "often forgetting things", "B": "always happy", "C": "very determined", "D": "easily frightened"},
     "A", "medium", 5, "Exercise 3: Compound adjectives (personality)",
     ["'absent-minded' describes someone who forgets things easily because they are thinking about something else."],
     "absent-minded = forgetful.", "A person who is absent-minded often forgets things."),

    ("A person who thinks about the future and plans ahead can be described as ...",
     {"A": "narrow-minded", "B": "forward-looking", "C": "tight-fisted", "D": "thin-skinned"},
     "B", "medium", 5, "Exercise 3: Compound adjectives (personality)",
     ["'forward-looking' means thinking about and planning for the future."],
     "forward-looking = thinking about the future.", "The compound adjective forward-looking describes planning for the future."),

    ("What does 'high-spirited' mean?",
     {"A": "energetic and cheerful", "B": "nervous and anxious", "C": "quiet and shy", "D": "serious and strict"},
     "A", "medium", 5, "Exercise 3: Compound adjectives (personality)",
     ["'high-spirited' means lively, energetic and cheerful."],
     "high-spirited = lively and cheerful.", "Someone high-spirited is full of energy and cheerfulness."),

    ("What does 'highly strung' mean?",
     {"A": "very relaxed", "B": "easily upset and nervous", "C": "extremely lazy", "D": "very generous"},
     "B", "medium", 5, "Exercise 3: Compound adjectives (personality)",
     ["'highly strung' describes someone who is nervous and easily upset."],
     "highly strung = nervous and easily upset.", "A highly strung person tends to worry and is easily upset."),

    ("What does 'kind-hearted' mean?",
     {"A": "caring and generous", "B": "selfish and cold", "C": "stubborn and angry", "D": "lazy and careless"},
     "A", "easy", 5, "Exercise 3: Compound adjectives (personality)",
     ["'kind-hearted' means caring, generous and warm towards others."],
     "kind-hearted = caring and generous.", "Someone kind-hearted treats others with care and generosity."),

    ("What does 'laid-back' mean?",
     {"A": "anxious and worried", "B": "relaxed and easy-going", "C": "hard-working and serious", "D": "easily offended"},
     "B", "easy", 5, "Exercise 3: Compound adjectives (personality)",
     ["'laid-back' means relaxed and easy-going, not easily worried."],
     "laid-back = relaxed and easy-going.", "A laid-back person stays calm and relaxed."),

    ("What does 'like-minded' mean?",
     {"A": "having the same interests and opinions", "B": "having a sharp mind", "C": "being open to new ideas", "D": "being easily influenced"},
     "A", "easy", 5, "Exercise 3: Compound adjectives (personality)",
     ["'like-minded' means having similar interests, opinions or attitudes."],
     "like-minded = similar in interests and opinions.", "Like-minded people get on well because they share views and interests."),

    ("What does 'narrow-minded' mean?",
     {"A": "clever and quick", "B": "open to new ideas", "C": "not willing to accept new ideas", "D": "extremely patient"},
     "C", "easy", 5, "Exercise 3: Compound adjectives (personality)",
     ["'narrow-minded' means not willing to listen to or accept new ideas."],
     "narrow-minded = not open to new ideas.", "A narrow-minded person rejects ideas that differ from their own."),

    ("What does 'strong-willed' mean?",
     {"A": "determined and firm in decisions", "B": "physically powerful", "C": "weak and hesitant", "D": "friendly and sociable"},
     "A", "easy", 5, "Exercise 3: Compound adjectives (personality)",
     ["'strong-willed' means determined and having firm opinions or decisions."],
     "strong-willed = determined.", "A strong-willed person is firm in what they want to do."),

    ("What does 'thin-skinned' mean?",
     {"A": "easily upset by criticism", "B": "physically weak", "C": "sensitive to cold weather", "D": "not caring about others"},
     "A", "medium", 5, "Exercise 3: Compound adjectives (personality)",
     ["'thin-skinned' means easily upset or hurt by criticism."],
     "thin-skinned = easily upset by criticism.", "A thin-skinned person takes criticism very personally."),

    ("What does 'tight-fisted' mean?",
     {"A": "very strong", "B": "not generous with money", "C": "extremely busy", "D": "having firm control"},
     "B", "medium", 5, "Exercise 3: Compound adjectives (personality)",
     ["'tight-fisted' means unwilling to spend or share money."],
     "tight-fisted = mean with money.", "A tight-fisted person avoids spending or giving money."),

    ("Which adjective describes someone who recovers quickly after difficulties?",
     {"A": "resilient", "B": "defensive", "C": "capable", "D": "tough"},
     "A", "easy", 5, "Exercise 2: Personality adjectives",
     ["'Resilient' means able to recover quickly and return to normal after problems."],
     "resilient = able to recover quickly.", "A resilient person copes well with setbacks and recovers fast."),

    ("Which adjective describes someone who is able to do things well?",
     {"A": "compassionate", "B": "capable", "C": "enthusiastic", "D": "passionate"},
     "B", "easy", 5, "Exercise 2: Personality adjectives",
     ["'Capable' means having the ability and skill to do things well."],
     "capable = able to do things well.", "A capable person has the ability to achieve tasks successfully."),

    ("Which adjective describes someone who feels sympathy for other people's problems?",
     {"A": "self-aware", "B": "compassionate", "C": "trustworthy", "D": "dedicated"},
     "B", "easy", 5, "Exercise 2: Personality adjectives",
     ["'Compassionate' means showing sympathy and care for people who are suffering."],
     "compassionate = full of sympathy.", "A compassionate person cares about and understands other people's suffering."),

    ("Which adjective describes someone who gives a lot of time and effort to a task?",
     {"A": "defensive", "B": "laid-back", "C": "dedicated", "D": "resilient"},
     "C", "easy", 5, "Exercise 2: Personality adjectives",
     ["'Dedicated' means giving a lot of time, effort and loyalty to something."],
     "dedicated = devoted and hard-working.", "A dedicated person works very hard for a goal or cause."),

    ("Which adjective describes someone who quickly justifies or protects themselves?",
     {"A": "defensive", "B": "compassionate", "C": "trustworthy", "D": "capable"},
     "A", "medium", 5, "Exercise 2: Personality adjectives",
     ["'Defensive' means behaving as if you are being attacked and need to protect or justify yourself."],
     "defensive = quick to justify yourself.", "A defensive person reacts strongly to criticism as if under attack."),

    ("Which adjective describes someone who shows great interest and excitement?",
     {"A": "enthusiastic", "B": "resilient", "C": "tough", "D": "self-aware"},
     "A", "easy", 5, "Exercise 2: Personality adjectives",
     ["'Enthusiastic' means showing strong interest, energy and excitement about something."],
     "enthusiastic = full of interest and excitement.", "An enthusiastic person shows great energy and eagerness."),

    ("Which adjective describes someone with very strong feelings about something?",
     {"A": "passionate", "B": "defensive", "C": "capable", "D": "dedicated"},
     "A", "easy", 5, "Exercise 2: Personality adjectives",
     ["'Passionate' means having very strong emotions, e.g. about a hobby or cause."],
     "passionate = having strong feelings.", "A passionate person feels strongly and intensely about something."),

    ("Which adjective describes someone who understands their own character?",
     {"A": "self-aware", "B": "thin-skinned", "C": "tight-fisted", "D": "narrow-minded"},
     "A", "medium", 5, "Exercise 2: Personality adjectives",
     ["'Self-aware' means knowing and understanding your own character, feelings and motives."],
     "self-aware = knowing your own character.", "A self-aware person understands their own strengths and weaknesses."),

    ("Which adjective describes someone who is strong and not easily hurt?",
     {"A": "tough", "B": "shy", "C": "fragile", "D": "sensitive"},
     "A", "easy", 5, "Exercise 2: Personality adjectives",
     ["'Tough' means strong and able to deal with difficulties without being easily hurt."],
     "tough = strong, not easily hurt.", "A tough person handles pressure and criticism without breaking down."),

    ("Which adjective describes someone you can rely on and believe?",
     {"A": "trustworthy", "B": "defensive", "C": "passionate", "D": "compassionate"},
     "A", "easy", 5, "Exercise 2: Personality adjectives",
     ["'Trustworthy' means deserving trust because you are honest and reliable."],
     "trustworthy = honest and reliable.", "A trustworthy person can be depended on to tell the truth and keep promises."),

    ("Which adjective describes someone who lacks confidence in themselves?",
     {"A": "underconfident", "B": "overcooked", "C": "strong-willed", "D": "kind-hearted"},
     "A", "medium", 5, "Exercise 2: Personality adjectives",
     ["'Underconfident' means not confident enough about your abilities."],
     "underconfident = lacking confidence.", "An underconfident person doubts their own abilities."),

    ("What noun do we form from the adjective 'assertive'?",
     {"A": "assertiveness", "B": "assertation", "C": "assertioning", "D": "assertness"},
     "A", "medium", 5, "Exercise 7: Nouns from adjectives",
     ["The adjective 'assertive' forms the noun 'assertiveness'."],
     "assertive → assertiveness.", "Adding the suffix '-ness' to 'assertive' gives the noun assertiveness."),

    ("What noun do we form from the adjective 'discreet'?",
     {"A": "discretion", "B": "discreetness", "C": "discreetion", "D": "discrete"},
     "A", "hard", 5, "Exercise 7: Nouns from adjectives",
     ["The adjective 'discreet' forms the irregular noun 'discretion'."],
     "discreet → discretion.", "Discretion (careful, tactful behaviour) is the noun form of discreet."),

    ("What noun do we form from the adjective 'humble'?",
     {"A": "humbleness", "B": "humility", "C": "humblenessness", "D": "humilness"},
     "B", "hard", 5, "Exercise 7: Nouns from adjectives",
     ["The adjective 'humble' forms the irregular noun 'humility'."],
     "humble → humility.", "Humility means the quality of being modest, and is the noun form of humble."),

    ("What noun do we form from the adjective 'merciful'?",
     {"A": "mercy", "B": "mercifulness", "C": "merciness", "D": "mercidom"},
     "A", "hard", 5, "Exercise 7: Nouns from adjectives",
     ["The adjective 'merciful' forms the noun 'mercy'."],
     "merciful → mercy.", "Mercy (kindness and forgiveness) is the noun form of merciful."),

    ("What noun do we form from the adjective 'sincere'?",
     {"A": "sincerity", "B": "sincereness", "C": "sinceration", "D": "sincerism"},
     "A", "hard", 5, "Exercise 7: Nouns from adjectives",
     ["The adjective 'sincere' forms the noun 'sincerity'."],
     "sincere → sincerity.", "Sincerity (honesty of feeling) is the noun form of sincere."),

    ("What noun do we form from the adjective 'inclusive'?",
     {"A": "inclusiveness", "B": "inclusionment", "C": "inclusiveity", "D": "inclusivityness"},
     "A", "hard", 5, "Exercise 7: Nouns from adjectives",
     ["The adjective 'inclusive' forms the noun 'inclusiveness' (also 'inclusion')."],
     "inclusive → inclusiveness.", "Adding the suffix '-ness' to 'inclusive' gives inclusiveness."),

    ("Which fixed expression means 'feel excitement and enjoyment'?",
     {"A": "get a kick out of", "B": "set great store by", "C": "plump for", "D": "hit it off with"},
     "A", "medium", 5, "Exercise 8: Fixed expressions",
     ["'Get a kick out of' means to feel excitement and enjoyment from something."],
     "get a kick out of = enjoy very much.", "If you get a kick out of something, it gives you excitement and pleasure."),

    ("Which fixed expression means 'choose'?",
     {"A": "plump for", "B": "get a kick out of", "C": "be wild about", "D": "keep yourself to yourself"},
     "A", "medium", 5, "Exercise 8: Fixed expressions",
     ["'Plump for' means to choose one thing from a number of possibilities."],
     "plump for = choose.", "To plump for something is to choose or decide on it."),

    ("Which fixed expression means 'consider something to be important'?",
     {"A": "set great store by", "B": "reveal our traits", "C": "be wild about", "D": "plump for"},
     "A", "medium", 5, "Exercise 8: Fixed expressions",
     ["'Set great store by' means to consider something to be very important."],
     "set great store by = consider important.", "If you set great store by values, you consider them very important."),
]
