# Unit 1 Lesson 2 (Speaking and Vocabulary, pages 6-7)
ITEMS = [
    ("What does 'a cold fish' mean?",
     {"A": "an unfriendly person who hides their feelings", "B": "a person who loves cold weather", "C": "a very calm person", "D": "a shy but talented person"},
     "A", "medium", 6, "Personality idioms",
     ["'A cold fish' is an idiom for an unfriendly person who does not show emotions."],
     "a cold fish = an unfriendly person.", "The idiom 'a cold fish' describes someone who seems cold and distant."),

    ("What does 'a dark horse' mean?",
     {"A": "a person with hidden ability who is not well known", "B": "a person who rides horses", "C": "an unlucky person", "D": "a mysterious criminal"},
     "A", "medium", 6, "Personality idioms",
     ["'A dark horse' is an idiom for someone who keeps their abilities secret and surprises others."],
     "a dark horse = someone with hidden ability.", "A dark horse seems quiet but turns out to be surprisingly able."),

    ("What does 'a go-getter' mean?",
     {"A": "an energetic, ambitious person who works hard to succeed", "B": "a person who gets lost easily", "C": "someone who takes things too quickly", "D": "a person who gives up easily"},
     "A", "easy", 6, "Personality idioms",
     ["'A go-getter' is an energetic and determined person who tries hard to succeed."],
     "a go-getter = an ambitious, hard-working person.", "A go-getter is active and determined to achieve success."),

    ("What does 'a mover and shaker' mean?",
     {"A": "an important person with power and influence", "B": "a person who works out at the gym", "C": "someone who changes jobs often", "D": "a restless, active person"},
     "A", "hard", 6, "Personality idioms",
     ["'A mover and shaker' is an idiom for an important, influential person."],
     "a mover and shaker = an influential person.", "Movers and shakers are people who have power and influence in an organisation."),

    ("What does 'a smart alec' mean?",
     {"A": "a person who annoyingly shows off their cleverness", "B": "a person who is intelligent and kind", "C": "a quiet, modest genius", "D": "a person who tells good jokes"},
     "A", "hard", 6, "Personality idioms",
     ["'A smart alec' describes someone who is irritatingly eager to show how clever they are."],
     "a smart alec = an annoying know-it-all.", "A smart alec keeps showing off their knowledge in an annoying way."),

    ("What does 'a smart cookie' mean?",
     {"A": "a clever and sensible person", "B": "a person who loves cakes", "C": "an unfriendly person", "D": "a person who makes quick decisions"},
     "A", "medium", 6, "Personality idioms",
     ["'A smart cookie' means a clever, intelligent and sensible person."],
     "a smart cookie = a clever person.", "The idiom 'a smart cookie' is a compliment meaning someone is smart."),

    ("What does 'a soft touch' mean?",
     {"A": "a person who is easy to persuade to give money or help", "B": "a person who is gentle to touch", "C": "a strict, unkind person", "D": "a person who avoids contact with others"},
     "A", "hard", 6, "Personality idioms",
     ["'A soft touch' is a person who is easily persuaded, especially to lend money or help."],
     "a soft touch = someone easy to persuade.", "A soft touch finds it hard to refuse requests for money or help."),

    ("What does 'a social butterfly' mean?",
     {"A": "a friendly person who enjoys spending time with many people", "B": "a person who collects butterflies", "C": "a shy person who avoids parties", "D": "a person who talks about insects"},
     "A", "easy", 6, "Personality idioms",
     ["'A social butterfly' is a very sociable person who loves being with lots of people."],
     "a social butterfly = a very sociable person.", "A social butterfly moves easily among many people and enjoys social events."),

    ("What does 'keep yourself to yourself' mean?",
     {"A": "to be private and not mix with other people", "B": "to keep your own secrets from yourself", "C": "to take care of your own health", "D": "to control your own feelings"},
     "A", "medium", 6, "Personality idioms",
     ["'Keep yourself to yourself' means to stay private and avoid mixing with others."],
     "keep yourself to yourself = stay private.", "People who keep themselves to themselves avoid socialising much."),

    ("In the quiz, 'I want to make sure that I am playing to my strengths' means the person ...",
     {"A": "wants to use the things they are good at", "B": "wants to win at sports", "C": "wants to learn new skills", "D": "wants to appear strong"},
     "A", "medium", 6, "Exercise 1: Quiz answers",
     ["'Playing to your strengths' means making the most of your abilities."],
     "playing to your strengths = using your abilities.", "If you play to your strengths, you focus on what you do well."),

    ("A quiz answer says: 'I'm a bit thin-skinned and not competitive, so I'll pass.' This means the person ...",
     {"A": "is easily hurt and does not like competing, so refuses", "B": "is tough and loves winning", "C": "will take part because they enjoy challenges", "D": "has no opinion about the quiz"},
     "A", "medium", 6, "Exercise 1: Quiz answers",
     ["'Thin-skinned' means easily upset and 'not competitive' means not liking to compete, so the person refuses."],
     "The person refuses because they are easily hurt and not competitive.", "The answer 'I'll pass' shows the person does not want to take part."),

    ("In the quiz answer 'I know that deep down I'm a go-getter', the phrase 'deep down' means ...",
     {"A": "in my true feelings", "B": "at the bottom of a sea", "C": "in a secret place", "D": "for a long time"},
     "A", "hard", 6, "Exercise 1: Quiz answers",
     ["'Deep down' means in one's true or real feelings, hidden underneath."],
     "deep down = in your true feelings.", "Saying something is true deep down means it is what you really feel inside."),

    ("Complete: 'A personality test is a 1 ______ questionnaire created by psychologists.'",
     {"A": "personal", "B": "professional", "C": "public", "D": "physical"},
     "A", "easy", 6, "Exercise 3: Gap fill",
     ["The correct word is 'personal' — a personal questionnaire."],
     "A personality test is a personal questionnaire.", "Psychologists create personal questionnaires used in the job process."),

    ("Complete: 'It is used by companies to help them in their 2 ______ process.'",
     {"A": "job", "B": "leisure", "C": "shopping", "D": "learning"},
     "A", "easy", 6, "Exercise 3: Gap fill",
     ["The correct word is 'job' — the job (hiring) process."],
     "Companies use the tests in their job process.", "Personality tests help companies choose candidates during the job process."),

    ("Complete: 'The test is usually presented by a 3 ______ or an online platform.'",
     {"A": "speaker", "B": "singer", "C": "candidate", "D": "manager"},
     "A", "medium", 6, "Exercise 3: Gap fill",
     ["The correct word is 'speaker'."],
     "A speaker presents the test.", "A personality test is presented by a speaker or an online platform."),

    ("Complete: 'A 4 ______ person fills it in.'",
     {"A": "quiz", "B": "clever", "C": "random", "D": "busy"},
     "A", "hard", 6, "Exercise 3: Gap fill",
     ["The correct word is 'quiz' — a quiz person fills it in."],
     "A quiz person fills in the questionnaire.", "The person taking the test fills in the questionnaire."),

    ("Complete: 'Then, a 5 ______ reads the answers and gives the results.'",
     {"A": "interviewer", "B": "psychologist", "C": "colleague", "D": "viewer"},
     "A", "easy", 6, "Exercise 3: Gap fill",
     ["The correct word is 'interviewer'."],
     "An interviewer reads the answers.", "After the test, an interviewer reads the answers and gives the results."),

    ("Which of these phrases is used to CHECK that you have understood someone?",
     {"A": "In other words, ...", "B": "In my opinion, ...", "C": "To sum up, ...", "D": "On the one hand, ..."},
     "A", "easy", 6, "Speaking box: Paraphrasing what you hear",
     ["'In other words ...' restates what someone said to check understanding."],
     "In other words = checking understanding.", "The phrases 'In other words', 'If I'm hearing you correctly' and 'Let me get this straight' check understanding."),

    ("Which phrase from the Speaking box would you use to restate an idea in a different way?",
     {"A": "To put it another way, ...", "B": "Essentially, ...", "C": "In a nutshell, ...", "D": "Simply put, ..."},
     "A", "medium", 6, "Speaking box: Paraphrasing what you hear",
     ["'To put it another way' introduces a paraphrase of what someone said."],
     "To put it another way = restating differently.", "This phrase shows you are re-expressing an idea in different words."),

    ("Which phrase means you want to confirm that what you understood is correct?",
     {"A": "If I'm hearing you correctly, ...", "B": "In a nutshell, ...", "C": "So, what it boils down to is ...", "D": "On the whole, ..."},
     "A", "easy", 6, "Speaking box: Paraphrasing what you hear",
     ["'If I'm hearing you correctly' is used to check your understanding of what was said."],
     "If I'm hearing you correctly = checking understanding.", "This phrase politely checks that you understood the speaker correctly."),

    ("Which phrase is used to check understanding before repeating what someone said?",
     {"A": "Let me get this straight ...", "B": "Essentially, ...", "C": "To sum up, ...", "D": "Generally speaking, ..."},
     "A", "medium", 6, "Speaking box: Paraphrasing what you hear",
     ["'Let me get this straight' introduces a question that checks your understanding."],
     "Let me get this straight = checking understanding.", "You use this phrase to confirm the facts before continuing."),

    ("Which phrase below is used to check understanding?",
     {"A": "So you're saying (that) ...", "B": "In a nutshell, ...", "C": "Simply put, ...", "D": "Essentially, ..."},
     "A", "easy", 6, "Speaking box: Paraphrasing what you hear",
     ["'So you're saying (that) ...' checks that you understood the speaker's meaning."],
     "So you're saying (that) = checking understanding.", "This phrase repeats the other person's point to confirm it."),

    ("Which phrase would you use to SUMMARISE what someone has said?",
     {"A": "In a nutshell, ...", "B": "Let me get this straight ...", "C": "If I'm hearing you correctly, ...", "D": "To put it another way, ..."},
     "A", "easy", 6, "Speaking box: Paraphrasing what you hear",
     ["'In a nutshell' introduces a short summary of the main points."],
     "In a nutshell = summarising.", "You use 'In a nutshell' to give a brief summary of what was said."),

    ("Which of the following phrases is used to SUMMARISE rather than to check understanding?",
     {"A": "Simply put, ...", "B": "In other words, ...", "C": "So you're saying (that) ...", "D": "Let me get this straight ..."},
     "A", "medium", 6, "Speaking box: Paraphrasing what you hear",
     ["'Simply put' introduces a summary in simple terms."],
     "Simply put = summarising.", "'Simply put', 'Essentially', 'In a nutshell' and 'boils down to' are summarising phrases."),

    ("Complete: '______ , what it boils down to is that the test is not reliable.'",
     {"A": "So", "B": "But", "C": "Because", "D": "Although"},
     "A", "hard", 6, "Speaking box: Paraphrasing what you hear",
     ["The phrase is 'So, what it boils down to is that ...' — a summarising expression."],
     "So, what it boils down to is ... = summarising.", "This expression summarises the essential point of what was said."),

    ("Which of these phrases would you use to introduce a summary of the main idea?",
     {"A": "Essentially, ...", "B": "If I'm hearing you correctly, ...", "C": "To put it another way, ...", "D": "Let me get this straight ..."},
     "A", "easy", 6, "Speaking box: Paraphrasing what you hear",
     ["'Essentially' introduces the main, essential point of what was said."],
     "Essentially = summarising.", "You use 'Essentially' when giving the key point in short."),

    ("Which of the following statements is a point IN FAVOUR of using psychometric tests?",
     {"A": "It's better to know as much about a candidate as possible.", "B": "If a candidate is nervous, they may not perform well.", "C": "People may do badly in the tests.", "D": "It can be expensive to administer and mark the tests."},
     "A", "medium", 6, "Exercise 5: Discussion statements",
     ["Knowing as much as possible about a candidate supports the use of tests."],
     "In favour: more information about the candidate.", "The other options list drawbacks of psychometric tests."),

    ("Which of the following statements is a point IN FAVOUR of psychometric tests?",
     {"A": "They are usually quick and easy to do.", "B": "A candidate may know what the interviewer wants to hear.", "C": "They can be expensive to administer.", "D": "Candidates may do badly in them."},
     "A", "medium", 6, "Exercise 5: Discussion statements",
     ["That tests are quick and easy is given as a positive point."],
     "In favour: quick and easy.", "The other statements present reasons against using the tests."),

    ("Which of the following statements is a point AGAINST using psychometric tests?",
     {"A": "A nervous candidate may not perform well in an interview.", "B": "It's better to know as much about a candidate as possible.", "C": "They help companies understand candidates.", "D": "They give a fair chance to quiet candidates."},
     "A", "medium", 6, "Exercise 5: Discussion statements",
     ["That a nervous candidate may not perform well is a drawback of the tests."],
     "Against: nervous candidates may do badly.", "Nervousness could cause good candidates to fail, so this argues against the tests."),

    ("Which of the following is a point AGAINST relying on psychometric tests?",
     {"A": "People may do badly in them.", "B": "They save the company time.", "C": "They are quick and easy to do.", "D": "They give a lot of useful information."},
     "A", "medium", 6, "Exercise 5: Discussion statements",
     ["That people may do badly in the tests is a reason against relying on them."],
     "Against: people may do badly.", "If capable people can fail the tests, the tests are not reliable."),

    ("Which of the following is a point AGAINST psychometric tests?",
     {"A": "The candidate may know what the interviewer wants to hear.", "B": "They are usually quick to do.", "C": "They reveal more about the candidate.", "D": "They are easy to mark."},
     "A", "medium", 6, "Exercise 5: Discussion statements",
     ["If the candidate can guess what the interviewer wants, the test result is less reliable."],
     "Against: candidates may give expected answers.", "Candidates might answer what they think the interviewer wants rather than truthfully."),

    ("Which of the following is a point AGAINST psychometric tests?",
     {"A": "It can be expensive to administer and mark the tests.", "B": "They are quick and easy to do.", "C": "They help choose the best candidate.", "D": "They are based on science."},
     "A", "medium", 6, "Exercise 5: Discussion statements",
     ["The cost of administering and marking the tests is a drawback."],
     "Against: they can be expensive.", "Companies may find the tests costly to run and mark."),

    ("According to the discussion statements, what is described as unusual?",
     {"A": "someone leaving school without a career idea", "B": "a candidate feeling nervous in an interview", "C": "a candidate doing badly in a test", "D": "a company using personality tests"},
     "A", "hard", 6, "Exercise 5: Discussion statements",
     ["One statement says it is unusual for someone to leave school without a career idea."],
     "It is unusual to leave school with no career idea.", "The statement questions how common it is to finish school without an idea of a career."),

    ("In the listening, 'For many people, the word 1 ______ has negative associations.'",
     {"A": "personality tests", "B": "interviews", "C": "universities", "D": "careers"},
     "A", "easy", 7, "Listening gap fill: gap 1",
     ["The psychologist says the word 'personality tests' has negative associations for many people."],
     "The word is 'personality tests'.", "Many people see personality tests as gimmicky or pseudo-scientific."),

    ("In the listening, the psychologist says the results are not ______ .",
     {"A": "fixed", "B": "chosen", "C": "free", "D": "found"},
     "A", "easy", 7, "Listening gap fill: gap 3",
     ["The talk says 'it is not 3 ______ - the results are not fixed'."],
     "The results are not fixed.", "Test results can change over time."),

    ("In the listening, 'an individual's job ______ can change over time.'",
     {"A": "performance", "B": "salary", "C": "contract", "D": "location"},
     "A", "medium", 7, "Listening gap fill: gap 4",
     ["The talk says an individual's job performance can change over time."],
     "Job performance can change.", "Test results and job performance are not permanent."),

    ("In the listening, what can also affect the results of a personality test?",
     {"A": "mental and physical health", "B": "the weather", "C": "the time of day", "D": "the number of questions"},
     "A", "easy", 7, "Listening gap fill: gap 5",
     ["The talk says an individual's mental and physical health can also affect the results."],
     "Mental and physical health affect the results.", "Changes in life and health can change test results."),

    ("In the listening, 'No one is hired on the basis of a ______ personality test alone.'",
     {"A": "single", "B": "double", "C": "weekly", "D": "monthly"},
     "A", "medium", 7, "Listening gap fill",
     ["The talk says no one is hired on the basis of a single personality test alone."],
     "No one is hired on one test alone.", "Employers should use a combination of methods, not a single test."),

    ("In the listening, what is 'always best' according to the psychologist?",
     {"A": "a combination of methods", "B": "one long interview", "C": "more personality tests", "D": "no hiring process"},
     "A", "medium", 7, "Listening gap fill",
     ["The talk says 'a combination of methods is always best'."],
     "A combination of methods is always best.", "Recruiters should combine several methods to judge candidates."),

    ("What should people in recruiting consider as crucial to performance?",
     {"A": "the working environment", "B": "the office design", "C": "the applicant's age", "D": "the number of applications"},
     "A", "hard", 7, "Listening gap fill",
     ["The talk says 'The working environment is crucial to performance'."],
     "The working environment is crucial.", "Recruiters should also consider the working environment."),
]
