# Unit 2 Lesson 3 (Grammar: Inversion and cleft sentences, pages 18-19)
ITEMS = [
    ("Which sentence is an example of negative inversion?",
     {"A": "Never before had I experienced such intense heat.", "B": "I had never experienced such intense heat before.", "C": "The heat was very intense.", "D": "I experienced intense heat."},
     "A", "easy", 18, "Exercise 2: Inversion and cleft sentences",
     ["'Never before had I experienced' inverts the subject and auxiliary after a negative adverbial."],
     "Negative inversion: Never + had + I.", "Inversion is used for emphasis."),

    ("What is the normal word order of 'Never before had I experienced such intense heat'?",
     {"A": "I had never experienced such intense heat before.", "B": "Had I never experienced heat before.", "C": "Never I had experienced heat.", "D": "I never had experienced heat before."},
     "A", "medium", 18, "Exercise 2: Inversion and cleft sentences",
     ["In normal order: subject + auxiliary: I had never experienced such intense heat before."],
     "I had never experienced such intense heat before.", "Inversion swaps the subject and auxiliary for emphasis."),

    ("What do we call it when we begin a sentence with a negative adverbial and invert the subject?",
     {"A": "inversion", "B": "cleft sentence", "C": "passive voice", "D": "reported speech"},
     "A", "easy", 18, "Exercise 4: Grammar explanation",
     ["The text calls this 'inversion'."],
     "It is inversion.", "We use it to add emphasis."),

    ("Which words can begin a sentence with inversion?",
     {"A": "Seldom, Rarely, Never, Only", "B": "and, but, or, so", "C": "the, a, an", "D": "in, on, at"},
     "A", "easy", 18, "Exercise 4: Grammar explanation",
     ["We begin with negative adverbials such as Seldom and Rarely, or words like Only, So and Such."],
     "Seldom, Rarely, Never, Only, etc.", "These words trigger inversion."),

    ("What does 'Little did I realise how differently I would feel about them soon' mean?",
     {"A": "I did not realise at all", "B": "I realised a little bit", "C": "I realised everything", "D": "I knew all along"},
     "A", "medium", 18, "Reading text: Speeding in the sand",
     ["'Little did I realise' means I did not realise at all."],
     "Little did I realise = I did not realise.", "This is inversion after 'little'."),

    ("Which sentence uses inversion correctly?",
     {"A": "Only when we reached the top did I realise how high the dunes were.", "B": "Only when we reached the top I realised how high the dunes were.", "C": "Only did when we reached the top I realise.", "D": "We reached only the top did I realise."},
     "A", "medium", 18, "Exercise 3: Inversion",
     ["After 'Only when...' the subject and auxiliary are inverted: did I realise."],
     "Only when... did I realise.", "The auxiliary 'did' comes before the subject."),

    ("What is the normal word order of 'Only when we reached the top did I realise how high the dunes were'?",
     {"A": "I only realised how high the dunes were when we reached the top.", "B": "Only I realised when we reached the top.", "C": "I realised only the dunes were high.", "D": "We reached the top and I only realised."},
     "A", "hard", 18, "Exercise 3: Inversion",
     ["In normal order: I only realised how high the dunes were when we reached the top."],
     "I only realised... when we reached the top.", "Inversion moves 'did' before 'I' for emphasis."),

    ("Complete: 'Rarely ______ such a crazy experience as a family.'",
     {"A": "have we had", "B": "we have had", "C": "we had have", "D": "had we"},
     "A", "medium", 18, "Reading text: Speeding in the sand",
     ["After 'Rarely' we invert: Rarely have we had such a crazy experience."],
     "Rarely have we had...", "Rarely is a negative adverbial, so the auxiliary comes first."),

    ("In the text, 'Rarely have we had such a crazy experience' means ...",
     {"A": "we have hardly ever had such a crazy experience", "B": "we often have crazy experiences", "C": "we always have crazy experiences", "D": "we will never have fun"},
     "A", "medium", 18, "Reading text: Speeding in the sand",
     ["'Rarely' = seldom; the family hardly ever has such a crazy experience."],
     "Rarely = hardly ever.", "The dune bashing was extraordinary for them."),

    ("Which sentence uses 'Not only... but also' with correct inversion?",
     {"A": "Not only was it clear that the coach had not been serviced, but also that care had not been taken.", "B": "Not only it was clear that...", "C": "Not only was clear it that...", "D": "Not only it was clearly..."},
     "A", "hard", 18, "Unit 2 review of inversion",
     ["With 'Not only' at the start, we invert: Not only was it clear..."],
     "Not only was it clear...", "The auxiliary 'was' comes before the subject 'it'."),

    ("What is the purpose of using inversion?",
     {"A": "to add emphasis", "B": "to make the sentence shorter", "C": "to avoid using commas", "D": "to make the sentence informal"},
     "A", "easy", 18, "Exercise 4: Grammar explanation",
     ["The text says 'To add emphasis, we can begin sentences with negative adverbials...'"],
     "Inversion adds emphasis.", "It makes the sentence sound stronger and more dramatic."),

    ("Which sentence is a cleft sentence?",
     {"A": "It was the flowing golden dunes which really impressed me.", "B": "The flowing golden dunes impressed me.", "C": "I was impressed by the dunes.", "D": "The dunes were impressive."},
     "A", "medium", 18, "Exercise 3: Cleft sentences",
     ["A cleft sentence begins with It's/What and splits the information into two parts."],
     "It was X which... = cleft sentence.", "Cleft sentences make information more memorable."),

    ("In 'It was the flowing golden dunes which really impressed me', what is emphasised?",
     {"A": "the flowing golden dunes", "B": "me", "C": "really", "D": "impressed"},
     "A", "medium", 18, "Exercise 3: Cleft sentences",
     ["The cleft structure 'It was X which...' emphasises X, the dunes."],
     "The dunes are emphasised.", "The structure puts the important information first."),

    ("Complete: 'What I was really wild about was ______.'",
     {"A": "seeing the desert", "B": "the intense heat", "C": "the plane journey", "D": "the hotel room"},
     "A", "medium", 18, "Reading text: Speeding in the sand",
     ["'What I was really wild about though, was seeing the desert for the first time.'"],
     "seeing the desert", "The cleft with 'What' emphasises seeing the desert."),

    ("What do cleft sentences begin with?",
     {"A": "It's, What, The only thing that", "B": "Never, Rarely, Seldom", "C": "and, but, or", "D": "in, on, at"},
     "A", "easy", 19, "Watch Out!: Cleft sentences",
     ["Cleft sentences start with It's and What, and also The (only) thing that, The day when, etc."],
     "It's / What / The only thing that.", "These structures add emphasis."),

    ("Complete: 'What you can expect is good food, fast cars and great ______.'",
     {"A": "roads", "B": "races", "C": "meals", "D": "hotels"},
     "A", "easy", 19, "Exercise 8: Jordan Rally advert",
     ["The advert says 'What you can expect is good food, fast cars and great roads.'"],
     "great roads", "This is from the Jordan Rally advert."),

    ("Complete: 'What you'll find amazing is the ______.'",
     {"A": "camaraderie", "B": "speed", "C": "desert", "D": "weather"},
     "A", "medium", 19, "Exercise 8: Jordan Rally advert",
     ["The advert says 'What you'll find amazing is the camaraderie.'"],
     "camaraderie", "Camaraderie means friendship between people."),

    ("What does 'camaraderie' mean?",
     {"A": "friendship and trust between people", "B": "speed and excitement", "C": "money and profit", "D": "danger and risk"},
     "A", "easy", 19, "Exercise 8: Jordan Rally advert",
     ["'Camaraderie' means friendship and mutual trust, especially among a group."],
     "camaraderie = friendship.", "A passion for cars unites the group."),

    ("Complete: 'It's the camaraderie ______ amazing.'",
     {"A": "that's", "B": "what's", "C": "it's", "D": "which's"},
     "A", "medium", 19, "Exercise 9: Cleft sentences",
     ["'It's the camaraderie that's amazing.'"],
     "that's", "The cleft structure is It's X that's Y."),

    ("Rewrite the cleft sentence 'It's the camaraderie that's amazing' using 'What'. What would it be?",
     {"A": "What you'll find amazing is the camaraderie.", "B": "What amazing is the camaraderie.", "C": "What the camaraderie is amazing.", "D": "What is amazing the camaraderie."},
     "A", "hard", 19, "Exercise 9: Cleft sentences",
     ["The 'What' cleft version: What you'll find amazing is the camaraderie."],
     "What you'll find amazing is the camaraderie.", "Both versions emphasise the same information."),

    ("Complete the inversion: 'He never felt sorry for himself. → NOT ONCE ______ sorry for himself.'",
     {"A": "did he feel", "B": "he did feel", "C": "felt he did", "D": "he felt"},
     "A", "medium", 19, "Exercise 7: Rewrite using inversion",
     ["With 'Not once' at the start, invert: Not once did he feel sorry for himself."],
     "Not once did he feel sorry for himself.", "Negative adverbial + inversion."),

    ("Complete the inversion: 'He didn't know what was going to happen. → LITTLE ______ what was going to happen.'",
     {"A": "did he know", "B": "he knew", "C": "he did know", "D": "knew he"},
     "A", "medium", 19, "Exercise 7: Rewrite using inversion",
     ["With 'Little' at the start: Little did he know what was going to happen."],
     "Little did he know...", "'Little' here is a negative adverbial."),

    ("Complete the inversion: 'She was so happy that she thought she would never stop smiling. → SO ______ that she thought she would never stop smiling.'",
     {"A": "happy was she", "B": "she was happy", "C": "was she happy", "D": "happy she was"},
     "A", "hard", 19, "Exercise 7: Rewrite using inversion",
     ["With 'So' at the start: So happy was she that she thought she would never stop smiling."],
     "So happy was she...", "The complement 'happy' moves before the verb."),

    ("Complete the inversion: 'The speed was so great that they started to feel scared. → SUCH ______ that they started to feel scared.'",
     {"A": "was the speed", "B": "the speed was", "C": "was speed the", "D": "speed the was"},
     "A", "hard", 19, "Exercise 7: Rewrite using inversion",
     ["With 'Such' at the start: Such was the speed that they started to feel scared."],
     "Such was the speed that...", "'Such' + inverted be-verb."),

    ("What is the text 'Speeding in the sand' about?",
     {"A": "a family trying dune bashing in the desert", "B": "a car race in Jordan", "C": "a train journey", "D": "a skiing holiday"},
     "A", "easy", 18, "Reading text: Speeding in the sand",
     ["The text is about a family's first experience of dune bashing."],
     "It is about dune bashing.", "They surged up the dunes in a special car."),

    ("What is 'dune bashing'?",
     {"A": "driving over sand dunes in a special vehicle", "B": "building sandcastles", "C": "walking through the desert", "D": "racing camels"},
     "A", "medium", 18, "Reading text: Speeding in the sand",
     ["They went dune bashing in a car especially equipped for the sport."],
     "dune bashing = driving over dunes.", "It is a thrilling desert activity."),

    ("What did the writer's father say the experience was like?",
     {"A": "a rollercoaster without the feeling of safety", "B": "a boat trip in a storm", "C": "a quiet walk", "D": "a theme park ride with seatbelts"},
     "A", "medium", 18, "Reading text: Speeding in the sand",
     ["Dad said it was like a rollercoaster without the feeling of safety."],
     "It was like a rollercoaster.", "Everyone agreed with him."),

    ("What does 'we got a real kick out of it' mean?",
     {"A": "we really enjoyed it", "B": "we were kicked out", "C": "we got hurt", "D": "we were bored"},
     "A", "medium", 18, "Reading text: Speeding in the sand",
     ["'Get a kick out of something' means to enjoy it a lot."],
     "got a kick out of it = really enjoyed it.", "They loved the high speeds and scenery."),

    ("Where was the writer when they went dune bashing?",
     {"A": "in the desert near Dubai", "B": "in the mountains", "C": "at the beach", "D": "in a city park"},
     "A", "easy", 18, "Reading text: Speeding in the sand",
     ["The family arrived in Dubai on holiday and then went to the desert."],
     "They went to the desert near Dubai.", "It was the writer's first time in the Middle East."),

    ("What was the guide's name?",
     {"A": "Saeed", "B": "Malek", "C": "Adnan", "D": "Amer"},
     "A", "easy", 18, "Reading text: Speeding in the sand",
     ["The text says 'we set off with our guide, Saeed'."],
     "The guide was Saeed.", "He took them to a car equipped for the sport."),

    ("Complete the cleft sentence: '______ the camaraderie that's amazing.'",
     {"A": "It's", "B": "What", "C": "That", "D": "Which"},
     "A", "medium", 19, "Exercise 9: Cleft sentences",
     ["'It's the camaraderie that's amazing.'"],
     "It's", "The cleft begins with 'It's'."),

    ("Which structure is NOT used to begin a cleft sentence?",
     {"A": "Never before", "B": "The day when", "C": "The reason why", "D": "The person who"},
     "A", "hard", 19, "Watch Out!: Cleft sentences",
     ["Clefts begin with It's, What, The (only) thing that, The day when, etc.; 'Never before' starts an inversion."],
     "'Never before' starts an inversion.", "The others are all cleft starters."),

    ("Complete: 'The day when I learnt how to use cleft sentences was the best day of my life!' What does this cleft sentence emphasise?",
     {"A": "the day", "B": "cleft sentences", "C": "my life", "D": "learning"},
     "A", "hard", 19, "Watch Out!: Cleft sentences",
     ["'The day when...' emphasises the day itself."],
     "It emphasises the day.", "'The day when' is one of the cleft starters."),

    ("Which word can begin an inversion meaning 'not very often'?",
     {"A": "Seldom", "B": "Always", "C": "Often", "D": "Sometimes"},
     "A", "easy", 18, "Exercise 4: Negative adverbials",
     ["'Seldom' and 'Rarely' are negative adverbials meaning not often."],
     "Seldom = not often.", "With them we invert the subject."),

    ("What did the writer's mother do during the dune bashing ride?",
     {"A": "she laughed in fear for the entire ride", "B": "she slept", "C": "she shouted at the driver", "D": "she took photos"},
     "A", "medium", 18, "Reading text: Speeding in the sand",
     ["'Mum just laughed in fear for the entire ride.'"],
     "She laughed in fear.", "The ride was scary but thrilling for her."),

    ("Complete: 'Only when the lights went out ______ how dark it was.'",
     {"A": "did I realise", "B": "I realised", "C": "realised I did", "D": "I did realise"},
     "A", "medium", 18, "Grammar: Inversion after Only",
     ["After 'Only when...', invert: Only when the lights went out did I realise."],
     "did I realise", "Inversion follows the negative adverbial phrase."),

    ("Which sentence is written in normal (non-inverted) word order?",
     {"A": "The coach was half an hour late.", "B": "Never have I experienced such discomfort.", "C": "Little did he know the truth.", "D": "So cold was the water that we left."},
     "A", "medium", 19, "Grammar: Inversion",
     ["'The coach was half an hour late' follows normal subject + verb order."],
     "Normal order = subject first.", "The others all start with negative adverbials or 'So'."),

    ("What is the effect of using a cleft sentence like 'It was Dad who said it was like a rollercoaster'?",
     {"A": "it makes the sentence more emphatic and memorable", "B": "it makes the sentence longer for no reason", "C": "it changes the meaning completely", "D": "it makes the sentence informal"},
     "A", "medium", 19, "Grammar: Cleft sentences",
     ["Cleft sentences emphasise information and make it sound more memorable."],
     "Clefts add emphasis.", "The focus is put on 'Dad'."),

    ("Complete the inversion with 'Not until': 'Not until the train arrived ______ that we were late.'",
     {"A": "did we realise", "B": "we realised", "C": "realised we", "D": "we did realise"},
     "A", "hard", 19, "Grammar: Inversion",
     ["After 'Not until...', invert: Not until the train arrived did we realise that we were late."],
     "did we realise", "'Not until' is a negative expression that causes inversion."),

    ("Which pair of sentences mean the same: 'What impressed me most was the desert' and ...",
     {"A": "The desert impressed me most.", "B": "The desert was impressed.", "C": "I was impressing the desert.", "D": "Most desert impressed me."},
     "A", "hard", 19, "Grammar: Cleft sentences",
     ["'What impressed me most was the desert' equals 'The desert impressed me most', with emphasis added."],
     "Both mean the desert impressed me most.", "The cleft adds emphasis to the desert."),
]
