# Unit 4 Review - Tastes (all lessons, pages 38-48)
ITEMS = [
    # L1: Food vocabulary, expressing preferences (pages 38-39) — 8 questions
    ("What does 'to be fond of' mean when talking about food?",
     {"A": "to like something very much", "B": "to hate something", "C": "to avoid something", "D": "to cook something"},
     "A", "easy", 38, "Review: L1",
     ["'Be fond of' means to have a liking for something."],
     "be fond of = like very much", "I am fond of Italian food."),

    ("What does 'to have a sweet tooth' mean?",
     {"A": "to enjoy sweet food very much", "B": "to have a toothache", "C": "to brush your teeth", "D": "to eat healthily"},
     "A", "medium", 38, "Review: L1",
     ["'Have a sweet tooth' means you love sweet things like cakes and chocolate."],
     "sweet tooth = loves sweets", "My sister has a sweet tooth."),

    ("Which phrase means 'I strongly dislike'?",
     {"A": "I can't stand", "B": "I'm into", "C": "I'm fond of", "D": "I'm keen on"},
     "A", "easy", 38, "Review: L1",
     ["'Can't stand' expresses strong dislike for something."],
     "can't stand = hate", "I can't stand boiled eggs."),

    ("What does 'junk food' mean?",
     {"A": "unhealthy food with lots of fat, sugar or salt", "B": "recycled food", "C": "very expensive food", "D": "home-cooked food"},
     "A", "easy", 38, "Review: L1",
     ["Junk food is unhealthy food that is high in fat, sugar or salt."],
     "junk food = unhealthy food", "Burgers and chips are junk food."),

    ("What does 'to be vegetarian' mean?",
     {"A": "to not eat meat or fish", "B": "to not eat vegetables", "C": "to only eat fruit", "D": "to not eat at all"},
     "A", "easy", 38, "Review: L1",
     ["A vegetarian does not eat meat or fish."],
     "vegetarian = no meat or fish", "She is vegetarian."),

    ("What does 'organic' mean when describing food?",
     {"A": "grown without using chemicals", "B": "very expensive", "C": "very sweet", "D": "very spicy"},
     "A", "medium", 38, "Review: L1",
     ["'Organic' food is grown without artificial chemicals or pesticides."],
     "organic = natural, chemical-free", "Organic vegetables are healthier."),

    ("Which phrase means 'I prefer one choice over another'?",
     {"A": "I'd rather have", "B": "I'm sick of", "C": "I'm bored with", "D": "I've had enough of"},
     "A", "medium", 39, "Review: L1",
     ["'I'd rather have' expresses a preference for one option."],
     "I'd rather have = I prefer", "I'd rather have salad than chips."),

    ("What does 'to eat out' mean?",
     {"A": "to eat at a restaurant instead of at home", "B": "to eat outside in the garden", "C": "to eat on the floor", "D": "to eat at a friend's house"},
     "A", "easy", 39, "Review: L1",
     ["'Eat out' means to go to a restaurant to eat."],
     "eat out = dine at a restaurant", "We eat out on Fridays."),

    # L2: International food culture, food adjectives (pages 40-41) — 8 questions
    ("What is 'cuisine'?",
     {"A": "a style of cooking from a particular country or region", "B": "a kitchen tool", "C": "a type of restaurant", "D": "a food ingredient"},
     "A", "easy", 40, "Review: L2",
     ["'Cuisine' refers to the style of cooking typical of a country or region."],
     "cuisine = style of cooking", "French cuisine is famous worldwide."),

    ("What does 'bland' mean when describing food?",
     {"A": "having very little flavour", "B": "very spicy", "C": "very sweet", "D": "very salty"},
     "A", "easy", 40, "Review: L2",
     ["'Bland' describes food that has very little flavour."],
     "bland = tasteless", "The soup was bland."),

    ("What does 'crispy' mean when describing food?",
     {"A": "hard and crunchy", "B": "soft and smooth", "C": "sweet and sour", "D": "hot and spicy"},
     "A", "easy", 40, "Review: L2",
     ["'Crispy' describes food that is firm and crunches when you bite it."],
     "crispy = crunchy", "Crispy fried chicken is popular."),

    ("What does 'creamy' mean when describing food?",
     {"A": "smooth and thick like cream", "B": "very hard", "C": "very spicy", "D": "very sour"},
     "A", "easy", 40, "Review: L2",
     ["'Creamy' describes food that is smooth and thick like cream."],
     "creamy = smooth like cream", "The sauce was thick and creamy."),

    ("Which cuisine is known for sushi and ramen?",
     {"A": "Japanese", "B": "Mexican", "C": "Italian", "D": "Indian"},
     "A", "easy", 41, "Review: L2",
     ["Sushi and ramen are traditional Japanese dishes."],
     "Japanese cuisine", "Japan is famous for its seafood dishes."),

    ("Which cuisine is known for tacos and burritos?",
     {"A": "Mexican", "B": "Chinese", "C": "French", "D": "Greek"},
     "A", "easy", 41, "Review: L2",
     ["Tacos and burritos are staples of Mexican cuisine."],
     "Mexican cuisine", "Mexican food often uses corn tortillas."),

    ("What does 'spicy' mean when describing food?",
     {"A": "containing strong flavours from herbs and spices", "B": "very sweet", "C": "very cold", "D": "very bland"},
     "A", "easy", 41, "Review: L2",
     ["'Spicy' describes food seasoned with strong-tasting herbs or spices."],
     "spicy = strongly seasoned", "Indian food is often spicy."),

    ("What does 'sour' mean when describing taste?",
     {"A": "a sharp acidic taste like lemon", "B": "very sweet", "C": "salty", "D": "bitter"},
     "A", "easy", 41, "Review: L2",
     ["'Sour' describes a sharp, acidic taste."],
     "sour = acidic taste", "Lemons are sour."),

    # L3: Countable/uncountable nouns, quantifiers (pages 42-43) — 8 questions
    ("Which noun is uncountable?",
     {"A": "rice", "B": "apple", "C": "egg", "D": "sandwich"},
     "A", "easy", 42, "Review: L3",
     ["'Rice' is uncountable — we cannot say 'a rice' or 'two rices'."],
     "rice = uncountable", "We say 'some rice', not 'a rice'."),

    ("Which noun is countable?",
     {"A": "bread", "B": "water", "C": "banana", "D": "milk"},
     "C", "easy", 42, "Review: L3",
     ["'Banana' is countable — we can say 'a banana' or 'two bananas'."],
     "banana = countable", "I ate two bananas."),

    ("Which quantifier is used with uncountable nouns?",
     {"A": "much", "B": "many", "C": "few", "D": "several"},
     "A", "medium", 42, "Review: L3",
     ["'Much' is used with uncountable nouns: much water, much time."],
     "much + uncountable", "How much sugar do you need?"),

    ("Which quantifier is used with countable nouns?",
     {"A": "many", "B": "much", "C": "little", "D": "a bit of"},
     "A", "medium", 42, "Review: L3",
     ["'Many' is used with countable plural nouns: many apples, many people."],
     "many + countable plural", "How many eggs do we have?"),

    ("Choose the correct sentence:",
     {"A": "There isn't much butter left.", "B": "There aren't much butter left.", "C": "There isn't many butter left.", "D": "There aren't many butter left."},
     "A", "medium", 43, "Review: L3",
     ["'Butter' is uncountable, so we use 'much' with the negative form 'isn't'."],
     "isn't much + uncountable", "Butter is uncountable."),

    ("Choose the correct sentence:",
     {"A": "There are many tomatoes on the table.", "B": "There is many tomatoes on the table.", "C": "There are much tomatoes on the table.", "D": "There is much tomatoes on the table."},
     "A", "medium", 43, "Review: L3",
     ["'Tomatoes' are countable and plural, so we use 'are' and 'many'."],
     "many + countable plural", "Tomatoes are countable."),

    ("Which sentence is correct?",
     {"A": "I'd like some water, please.", "B": "I'd like a water, please.", "C": "I'd like waters, please.", "D": "I'd like any water, please."},
     "A", "easy", 43, "Review: L3",
     ["'Water' is uncountable, so we use 'some' in polite requests."],
     "some + uncountable", "'Some' works for both countable and uncountable nouns."),

    ("How much / How many — complete: '___ apples do we need for the cake?'",
     {"A": "How many", "B": "How much", "C": "How few", "D": "How little"},
     "A", "easy", 43, "Review: L3",
     ["'Apples' is countable and plural, so we use 'How many'."],
     "How many + countable", "Apples are countable nouns."),

    # L4: Ordering food, restaurant dialogues (page 44) — 6 questions
    ("Which is a polite way to order food in a restaurant?",
     {"A": "Could I have the chicken salad, please?", "B": "Give me the chicken salad.", "C": "I want the chicken salad now.", "D": "Bring me the chicken salad."},
     "A", "easy", 44, "Review: L4",
     ["'Could I have... please?' is a polite way to order."],
     "polite ordering", "Use 'Could I have' or 'I'd like' to be polite."),

    ("What does 'I'd like' mean in a restaurant?",
     {"A": "I would like to order", "B": "I don't like", "C": "I can't eat", "D": "I have eaten"},
     "A", "easy", 44, "Review: L4",
     ["'I'd like' is a short form of 'I would like', used for ordering."],
     "I'd like = I want to order", "I'd like the pasta, please."),

    ("Which phrase asks for the bill in a restaurant?",
     {"A": "Could we have the bill, please?", "B": "Where is my money?", "C": "Give me the price.", "D": "How much do you owe me?"},
     "A", "easy", 44, "Review: L4",
     ["'Could we have the bill, please?' is the standard polite request."],
     "asking for the bill", "You say this at the end of your meal."),

    ("What does 'a starter' mean in a restaurant?",
     {"A": "a small dish served before the main course", "B": "the main dish", "C": "the dessert", "D": "a drink"},
     "A", "medium", 44, "Review: L4",
     ["A starter is a small dish served before the main course."],
     "starter = first course", "I'll have soup as a starter."),

    ("What does 'a main course' mean?",
     {"A": "the largest and most important dish in a meal", "B": "a small snack", "C": "a dessert", "D": "a drink before the meal"},
     "A", "easy", 44, "Review: L4",
     ["The main course is the principal dish of a meal."],
     "main course = principal dish", "The steak is our main course."),

    ("Which phrase is used to make a special request about food?",
     {"A": "Could I have it without cheese, please?", "B": "No cheese.", "C": "Remove cheese.", "D": "I hate cheese."},
     "A", "medium", 44, "Review: L4",
     ["'Could I have it without...?' is a polite way to request a change."],
     "special requests", "Restaurants often accommodate dietary needs."),

    # L5: Kitchen vocabulary, cooking verbs (pages 45-46) — 10 questions
    ("What does 'to chop' mean in the kitchen?",
     {"A": "to cut food into pieces with a knife", "B": "to heat food on the stove", "C": "to mix ingredients together", "D": "to serve food"},
     "A", "easy", 45, "Review: L5",
     ["'Chop' means to cut food into rough pieces."],
     "chop = cut into pieces", "Chop the onions finely."),

    ("What does 'to boil' mean?",
     {"A": "to heat a liquid until it reaches 100°C and bubbles", "B": "to cook food in hot oil", "C": "to freeze food", "D": "to wash food"},
     "A", "easy", 45, "Review: L5",
     ["'Boil' means to heat a liquid until it reaches boiling point and bubbles."],
     "boil = heat to bubbling", "Boil the water before adding the pasta."),

    ("What does 'to fry' mean?",
     {"A": "to cook food in hot oil or fat", "B": "to boil food in water", "C": "to bake food in an oven", "D": "to freeze food"},
     "A", "easy", 45, "Review: L5",
     ["'Fry' means to cook food in a pan with hot oil or fat."],
     "fry = cook in oil", "Fry the eggs in a little butter."),

    ("What does 'to bake' mean?",
     {"A": "to cook food in an oven using dry heat", "B": "to cook in boiling water", "C": "to cook in hot oil", "D": "to cook on a grill"},
     "A", "easy", 45, "Review: L5",
     ["'Bake' means to cook food in an oven with dry heat."],
     "bake = oven cooking", "Bake the cake at 180°C for 30 minutes."),

    ("What does 'to grill' mean?",
     {"A": "to cook food on a metal frame over direct heat", "B": "to cook in boiling water", "C": "to freeze food quickly", "D": "to cut food into slices"},
     "A", "easy", 46, "Review: L5",
     ["'Grill' means to cook food on a metal rack under or over direct heat."],
     "grill = cook over direct heat", "Grill the chicken for ten minutes on each side."),

    ("What does 'a whisk' do in the kitchen?",
     {"A": "mixes ingredients together quickly by hand", "B": "cuts food into pieces", "C": "measures liquid ingredients", "D": "stores food"},
     "A", "medium", 46, "Review: L5",
     ["A whisk is a kitchen tool used to mix and beat ingredients."],
     "whisk = mix quickly", "Whisk the eggs and sugar together."),

    ("What does 'to peel' mean?",
     {"A": "to remove the outer skin of a fruit or vegetable", "B": "to cut food into pieces", "C": "to cook food slowly", "D": "to serve food"},
     "A", "medium", 46, "Review: L5",
     ["'Peel' means to remove the outer covering of fruit or vegetables."],
     "peel = remove skin", "Peel the potatoes before boiling them."),

    ("What does 'a chopping board' used for?",
     {"A": "a surface for cutting food with a knife", "B": "a plate for serving food", "C": "a pan for frying food", "D": "a container for storing food"},
     "A", "easy", 46, "Review: L5",
     ["A chopping board is a flat board used as a surface for cutting food."],
     "chopping board = cutting surface", "Always use a chopping board to protect the countertop."),

    ("What does 'to stir' mean?",
     {"A": "to move a spoon or tool around in a liquid or mixture", "B": "to cut food into pieces", "C": "to apply heat to food", "D": "to serve food on a plate"},
     "A", "easy", 46, "Review: L5",
     ["'Stir' means to move a spoon or utensil in circles inside a mixture."],
     "stir = mix by moving in circles", "Stir the sauce until it thickens."),

    ("What does 'to season' food mean?",
     {"A": "to add salt, pepper or spices to improve taste", "B": "to cook food slowly", "C": "to cut food into pieces", "D": "to serve food hot"},
     "A", "medium", 46, "Review: L5",
     ["'Season' means to add salt, pepper, herbs or spices to improve flavour."],
     "season = add flavour", "Season the soup with salt and pepper."),

    # L6: Recipe writing, food reviews, connectors (pages 47-48) — 10 questions
    ("What is the first step you usually write in a recipe?",
     {"A": "List the ingredients", "B": "Write the conclusion", "C": "Describe the taste", "D": "Give a rating"},
     "A", "easy", 47, "Review: L6",
     ["A recipe begins by listing all the ingredients needed."],
     "first step = list ingredients", "The ingredients list tells you what you need."),

    ("Which imperative verb is commonly used in recipes?",
     {"A": "Add", "B": "Added", "C": "Adding", "D": "Adds"},
     "A", "easy", 47, "Review: L6",
     ["Recipes use imperative verbs: 'Add the eggs', 'Stir the mixture'."],
     "imperative verb = command form", "Recipe instructions are commands."),

    ("What does 'First' do in a recipe?",
     {"A": "it introduces the first step", "B": "it gives a rating", "C": "it describes the taste", "D": "it lists the ingredients"},
     "A", "easy", 47, "Review: L6",
     ["'First' is a sequencing word used to introduce step one."],
     "First = step 1", "First, preheat the oven to 180°C."),

    ("What does 'Meanwhile' mean in a recipe?",
     {"A": "at the same time", "B": "before", "C": "after", "D": "never"},
     "A", "medium", 48, "Review: L6",
     ["'Meanwhile' means 'during the same time period'."],
     "Meanwhile = at the same time", "Meanwhile, prepare the salad."),

    ("What does 'Then' do in a recipe?",
     {"A": "it introduces the next step", "B": "it introduces the final step", "C": "it lists ingredients", "D": "it gives a rating"},
     "A", "easy", 47, "Review: L6",
     ["'Then' introduces the next action in a sequence."],
     "Then = next step", "Then, add the flour and mix well."),

    ("Which is an example of writing a food review?",
     {"A": "The pasta was overcooked and bland.", "B": "Add two eggs to the bowl.", "C": "Peel the potatoes first.", "D": "Preheat the oven to 200°C."},
     "A", "easy", 48, "Review: L6",
     ["A food review describes and evaluates the quality of food."],
     "food review = evaluates taste", "Reviews help other diners choose restaurants."),

    ("What does 'On the other hand' introduce in a food review?",
     {"A": "an opposite or contrasting point", "B": "the first argument", "C": "the conclusion", "D": "a supporting detail"},
     "A", "medium", 48, "Review: L6",
     ["'On the other hand' introduces a contrasting or different point."],
     "on the other hand = contrast", "The starters were good; on the other hand, the desserts were poor."),

    ("Which word is used to list ingredients in a recipe?",
     {"A": "you will need", "B": "you will eat", "C": "you will love", "D": "you will enjoy"},
     "A", "easy", 47, "Review: L6",
     ["'You will need' introduces the list of ingredients."],
     "you will need = ingredients list", "You will need flour, sugar, and eggs."),

    ("What does 'Finally' mean in a recipe?",
     {"A": "it introduces the last step", "B": "it introduces the first step", "C": "it introduces a pause", "D": "it introduces an ingredient"},
     "A", "easy", 47, "Review: L6",
     ["'Finally' signals the last step in the instructions."],
     "Finally = last step", "Finally, garnish with fresh herbs."),

    ("What does 'To sum up' mean in a food review?",
     {"A": "it introduces the conclusion", "B": "it introduces the first point", "C": "it introduces a contrasting point", "D": "it lists ingredients"},
     "A", "medium", 48, "Review: L6",
     ["'To sum up' introduces the final summary or conclusion."],
     "to sum up = conclusion", "To sum up, it was an excellent meal."),
]
