# Unit 2 Review - part 2 (Trip of my dreams + Life Skills + unit vocabulary)
ITEMS = [
    ("What 'cast a shadow over the trip'?",
     {"A": "the friendship problems between Sultan and Adnan", "B": "the bad weather", "C": "the long flights", "D": "the expensive hotels"},
     "A", "medium", 25, "Reading: paragraph 8",
     ["'Something happened which cast a shadow over the trip' - the friendship was strained."],
     "The friendship problems spoiled it partly.", "Cast a shadow = made it less happy."),

    ("Where is Valparaiso?",
     {"A": "just north of Santiago, on the Pacific coast", "B": "south of the Atacama Desert", "C": "in Argentina", "D": "on the Atlantic coast"},
     "A", "easy", 25, "Reading: paragraph 8",
     ["Valparaiso is a beautiful old city just north of Santiago, on the Pacific coast."],
     "North of Santiago on the coast.", "It is a gorgeous and special place."),

    ("What did Adnan want to do in Valparaiso?",
     {"A": "hang out in the hotel room all day", "B": "walk around and see the sights", "C": "visit the museums", "D": "go sailing"},
     "A", "easy", 25, "Reading: paragraph 8",
     ["Adnan just wanted to hang out in the hotel room all day."],
     "He wanted to stay in the hotel.", "Sultan could not believe it."),

    ("What conclusion did the two friends reach at the end?",
     {"A": "they were not very compatible travelling companions", "B": "they would travel together again next year", "C": "they would never speak again", "D": "they were perfect travel partners"},
     "A", "easy", 25, "Reading: paragraph 9",
     ["'We finally understood that we weren't very compatible travelling companions.'"],
     "They were not compatible as travel partners.", "They had different ideas about being a tourist."),

    ("What does 'compatible' mean?",
     {"A": "able to exist or work together well", "B": "able to travel fast", "C": "very rich", "D": "very old"},
     "A", "medium", 25, "Reading: paragraph 9",
     ["'Compatible' means able to get along or work together well."],
     "compatible = able to work together.", "They had different ideas about tourism."),

    ("According to the Life Skills box, what is the first step to make a good decision?",
     {"A": "gather relevant information - do your research", "B": "make the decision immediately", "C": "ask everyone else to decide", "D": "ignore the facts"},
     "A", "easy", 24, "Life Skills: How to make a good decision",
     ["The first step is to gather relevant information."],
     "Gather relevant information.", "It is the foundation of good decisions."),

    ("According to the Life Skills box, what should you do with your list of options?",
     {"A": "consider the pros and cons and drawbacks of each", "B": "throw the list away", "C": "choose the first option", "D": "hide the list"},
     "A", "easy", 24, "Life Skills: How to make a good decision",
     ["You make a list of options and consider the pros and cons and drawbacks of each."],
     "Consider pros, cons and drawbacks.", "This helps you compare choices."),

    ("What should you do to get different perspectives before deciding?",
     {"A": "ask others for their views or experience", "B": "decide alone without help", "C": "ignore other people's advice", "D": "read only one opinion"},
     "A", "easy", 24, "Life Skills: How to make a good decision",
     ["The box says 'Get some different perspectives - ask others for their views or experience'."],
     "Ask others for their views.", "Other perspectives help the decision."),

    ("After making the decision, what should you later consider?",
     {"A": "what you learned from this experience", "B": "what you spent on lunch", "C": "whether to cancel the trip", "D": "who to blame"},
     "A", "easy", 24, "Life Skills: How to make a good decision",
     ["You make the decision and later consider what you learned from this experience."],
     "Consider what you learned.", "It helps you make better decisions next time."),

    ("In the Life Skills project, what is the dilemma?",
     {"A": "your best friend invites you on a holiday that may harm the environment", "B": "you have no money for a holiday", "C": "your friend wants to stay home", "D": "the flights are cancelled"},
     "A", "medium", 24, "Life Skills: Project",
     ["The friend invites you to an exciting destination, but tourism might harm the local environment."],
     "Tourism may hurt the environment.", "You must analyse the situation and decide."),

    ("Which verb of movement means 'walked with long, confident steps'?",
     {"A": "strode", "B": "shuffled", "C": "wobbled", "D": "lurched"},
     "A", "easy", 14, "Unit 2 Vocabulary review",
     ["'Strode' means walking with long, confident steps."],
     "strode", "The angry father strode up to the manager."),

    ("Which verb of movement means 'walked with difficulty because of injury'?",
     {"A": "hobbled", "B": "surged", "C": "staggered", "D": "strode"},
     "A", "easy", 14, "Unit 2 Vocabulary review",
     ["'Hobbled' means walking with difficulty, e.g. with an injured ankle."],
     "hobbled", "He hobbled off the pitch."),

    ("Which idiom means 'easy and without problems'?",
     {"A": "plain sailing", "B": "going downhill", "C": "in the same boat", "D": "up the wall"},
     "A", "easy", 15, "Unit 2 Vocabulary review",
     ["'Plain sailing' means easy and trouble-free."],
     "plain sailing", "It wasn't all plain sailing for the trainee pilot."),

    ("Which idiom means 'the main person or thing behind a project'?",
     {"A": "the driving force", "B": "a soft touch", "C": "a dark horse", "D": "a go-getter"},
     "A", "easy", 15, "Unit 2 Vocabulary review",
     ["'The driving force' is the main person or thing making something happen."],
     "the driving force", "Suha was the driving force behind the project."),

    ("Which idiom means 'to avoid'?",
     {"A": "steer clear of", "B": "fall into step with", "C": "get a kick out of", "D": "plump for"},
     "A", "easy", 15, "Unit 2 Vocabulary review",
     ["'Steer clear of' means to avoid."],
     "steer clear of", "Steer clear of the main junction."),

    ("What does 'in the same boat' mean?",
     {"A": "in the same difficult situation", "B": "in the same boat on a lake", "C": "working on a ship", "D": "sharing a meal"},
     "A", "easy", 15, "Unit 2 Vocabulary review",
     ["'In the same boat' means sharing the same (usually difficult) situation."],
     "in the same boat = same situation.", "We're all in the same boat with the parking fees."),

    ("What does 'be taken for a ride' mean?",
     {"A": "to be tricked or deceived", "B": "to go on a fun trip", "C": "to be driven around", "D": "to be kidnapped"},
     "A", "medium", 15, "Unit 2 Vocabulary review",
     ["'Be taken for a ride' means to be deceived."],
     "be taken for a ride = be tricked.", "No one likes to be taken for a ride."),

    ("What does 'sailed through the interview' mean?",
     {"A": "succeeded easily", "B": "failed badly", "C": "arrived late", "D": "gave up"},
     "A", "medium", 15, "Unit 2 Vocabulary review",
     ["'Sail through' means to succeed at something easily."],
     "sailed through = succeeded easily.", "Reem sailed through her interview."),

    ("Which word means 'a major discovery or advance'?",
     {"A": "breakthrough", "B": "setback", "C": "outcry", "D": "outlay"},
     "A", "easy", 20, "Unit 2 Vocabulary review",
     ["A 'breakthrough' is a major advance."],
     "breakthrough", "They made a breakthrough in driverless cars."),

    ("Which word means 'a problem that delays progress'?",
     {"A": "setback", "B": "breakaway", "C": "outcome", "D": "outlook"},
     "A", "easy", 20, "Unit 2 Vocabulary review",
     ["A 'setback' delays progress."],
     "setback", "Due to a setback, it won't be finished until next week."),

    ("Which word means 'a strong public protest'?",
     {"A": "outcry", "B": "outset", "C": "outcome", "D": "outlook"},
     "A", "medium", 20, "Unit 2 Vocabulary review",
     ["An 'outcry' is a strong public reaction or protest."],
     "outcry", "There would be an outcry if the company delayed too much."),

    ("Which phrase means 'after considering everything'?",
     {"A": "On balance", "B": "No contest", "C": "In two minds", "D": "At first"},
     "A", "medium", 21, "Unit 2 Vocabulary review",
     ["'On balance' means after weighing up all the facts."],
     "On balance", "On balance, I'd say a small group is better."),

    ("Which phrase means 'I can't decide'?",
     {"A": "I'm in two minds", "B": "I'd go for it anytime", "C": "No two ways about it", "D": "It's clear cut"},
     "A", "easy", 21, "Unit 2 Vocabulary review",
     ["'In two minds' means undecided."],
     "in two minds", "I'm in two minds about which trip to choose."),

    ("What does 'there is no contest' mean?",
     {"A": "one option is clearly the best", "B": "there is no game", "C": "nobody wants to compete", "D": "the decision is hard"},
     "A", "hard", 21, "Unit 2 Vocabulary review",
     ["'No contest' means there is no real comparison; one choice is clearly better."],
     "no contest = clearly best.", "A canal trip - no contest! Definitely!"),

    ("Which phrase is formal?",
     {"A": "in excess of 30 minutes late", "B": "more than half an hour late", "C": "so late!", "D": "late by ages"},
     "A", "medium", 23, "Unit 2 Vocabulary review",
     ["'In excess of' is the formal version used in a formal complaint."],
     "in excess of", "Email B uses formal equivalents."),
]
