# Unit 1 Lesson 3 (Listening and Vocabulary, page 7)
ITEMS = [
    ("Which word means 'character or personality'?",
     {"A": "disposition", "B": "destiny", "C": "vulnerability", "D": "offspring"},
     "A", "easy", 7, "Exercise 1: Matching definitions",
     ["'Disposition' means a person's character or usual mood."],
     "disposition = character or personality.", "The text defines disposition as character or personality."),

    ("Which word means 'influenced or changed'?",
     {"A": "moulded", "B": "nurtured", "C": "implied", "D": "deduced"},
     "A", "medium", 7, "Exercise 1: Matching definitions",
     ["'Moulded' means influenced or shaped into something."],
     "moulded = influenced or changed.", "Personality can be moulded by experiences and upbringing."),

    ("Which word means 'people who publicly support an idea'?",
     {"A": "proponents", "B": "opponents", "C": "employees", "D": "offspring"},
     "A", "easy", 7, "Exercise 1: Matching definitions",
     ["'Proponents' are people who publicly support an idea or theory."],
     "proponents = public supporters.", "Proponents argue in favour of a cause or theory."),

    ("Which word means 'the quality of being easily hurt'?",
     {"A": "vulnerability", "B": "versatility", "C": "sincerity", "D": "humility"},
     "A", "easy", 7, "Exercise 1: Matching definitions",
     ["'Vulnerability' is the quality of being easily hurt physically or emotionally."],
     "vulnerability = being easily hurt.", "A person's vulnerability makes them easy to hurt."),

    ("Which word means 'a particular characteristic or way of behaving'?",
     {"A": "trait", "B": "tray", "C": "treat", "D": "trance"},
     "A", "easy", 7, "Exercise 1: Matching definitions",
     ["'Trait' means a particular characteristic or way of behaving."],
     "trait = a characteristic.", "Honesty and kindness are examples of personality traits."),

    ("Which word means 'helping somebody to develop'?",
     {"A": "nurture", "B": "numb", "C": "mock", "D": "spark"},
     "A", "medium", 7, "Exercise 1: Matching definitions",
     ["'Nurture' means helping somebody to grow and develop."],
     "nurture = helping to develop.", "Parents nurture their children's talents and growth."),

    ("Which word describes something that passes from parent to child?",
     {"A": "hereditary", "B": "hierarchical", "C": "temporary", "D": "heredity"},
     "A", "easy", 7, "Exercise 1: Matching definitions",
     ["'Hereditary' means passed from parent to child through genes."],
     "hereditary = passed from parents to children.", "Some personality traits are hereditary."),

    ("Which word means 'children'?",
     {"A": "offspring", "B": "onshore", "C": "upbringing", "D": "proponents"},
     "A", "easy", 7, "Exercise 1: Matching definitions",
     ["'Offspring' means children or young of a person or animal."],
     "offspring = children.", "Parents pass their traits to their offspring."),

    ("Which word means 'what will happen in the future'?",
     {"A": "destiny", "B": "density", "C": "disposition", "D": "decency"},
     "A", "easy", 7, "Exercise 1: Matching definitions",
     ["'Destiny' means the future that is considered to be decided for someone."],
     "destiny = what will happen in the future.", "Some people believe personality and destiny are connected."),

    ("Which word means 'suggest'?",
     {"A": "imply", "B": "impress", "C": "impose", "D": "imitate"},
     "A", "medium", 7, "Exercise 1: Matching definitions",
     ["'Imply' means to suggest something without saying it directly."],
     "imply = suggest.", "If someone implies something, they suggest it indirectly."),

    ("Which word means 'making something so easy to understand that it is no longer accurate'?",
     {"A": "oversimplification", "B": "exaggeration", "C": "overpopulation", "D": "understatement"},
     "A", "hard", 7, "Exercise 1: Matching definitions",
     ["'Oversimplification' makes something so simple that it becomes inaccurate."],
     "oversimplification = too simple to be accurate.", "Saying personality is only in our genes is an oversimplification."),

    ("Complete: 'Scientists who support this theory are called ______ .'",
     {"A": "proponents", "B": "opponents", "C": "employees", "D": "patients"},
     "A", "easy", 7, "Vocabulary application",
     ["People who publicly support an idea are its proponents."],
     "Supporters are proponents.", "Proponents publicly support the theory."),

    ("Complete: 'His ______ made it easy for others to hurt his feelings.'",
     {"A": "vulnerability", "B": "credibility", "C": "ability", "D": "stability"},
     "A", "easy", 7, "Vocabulary application",
     ["Vulnerability means being easily hurt."],
     "His vulnerability made him easy to hurt.", "A person's vulnerability makes them sensitive to being hurt."),

    ("Complete: 'Honesty is a ______ I really admire in people.'",
     {"A": "trait", "B": "treat", "C": "track", "D": "trade"},
     "A", "easy", 7, "Vocabulary application",
     ["A trait is a particular characteristic or way of behaving."],
     "Honesty is a trait.", "Traits are characteristic ways of behaving, like honesty."),

    ("Complete: 'Parents should ______ their children's natural talents.'",
     {"A": "nurture", "B": "neglect", "C": "mock", "D": "prevent"},
     "A", "medium", 7, "Vocabulary application",
     ["To nurture is to help somebody to develop."],
     "Parents nurture talents.", "Nurturing means helping talents and skills to grow."),

    ("Complete: 'Some personality characteristics are ______ ; they pass from parents to children.'",
     {"A": "hereditary", "B": "temporary", "C": "voluntary", "D": "imaginary"},
     "A", "easy", 7, "Vocabulary application",
     ["Hereditary traits pass from parent to child."],
     "Some traits are hereditary.", "Genes can pass personality characteristics from parents to children."),

    ("Complete: 'Her warm personality was ______ by years of loving care.'",
     {"A": "moulded", "B": "missed", "C": "measured", "D": "moved"},
     "A", "medium", 7, "Vocabulary application",
     ["To be moulded means to be influenced or shaped."],
     "Her personality was moulded by care.", "Experience and care moulded her warm personality."),

    ("Complete: 'Nobody knows for sure what ______ has in store for them.'",
     {"A": "destiny", "B": "density", "C": "disposition", "D": "decency"},
     "A", "easy", 7, "Vocabulary application",
     ["Destiny means what will happen in the future."],
     "Destiny = the future in store for us.", "Destiny refers to what the future holds."),

    ("Complete: 'Are you ______ that I should leave?', she asked quietly.",
     {"A": "implying", "B": "impressing", "C": "imposing", "D": "imitating"},
     "A", "medium", 7, "Vocabulary application",
     ["To imply is to suggest something indirectly."],
     "implying = suggesting indirectly.", "She was suggesting without saying it directly."),

    ("Complete: 'Saying personality is purely genetic is an ______ .'",
     {"A": "oversimplification", "B": "overstatement", "C": "underestimation", "D": "overproduction"},
     "A", "hard", 7, "Vocabulary application",
     ["An oversimplification makes something too simple to be accurate."],
     "This claim is an oversimplification.", "Personality depends on many factors, so this is an oversimplification."),

    ("Complete: 'Mariam has a calm ______ ; she rarely gets angry.'",
     {"A": "disposition", "B": "destiny", "C": "vulnerability", "D": "offspring"},
     "A", "easy", 7, "Vocabulary application",
     ["A disposition is a person's character or usual mood."],
     "a calm disposition = a calm nature.", "Disposition describes a person's usual character."),

    ("What does the verb 'imply' mean?",
     {"A": "to suggest something without saying it directly", "B": "to explain something in detail", "C": "to force someone to do something", "D": "to repeat something many times"},
     "A", "easy", 7, "Exercise 1: Matching definitions",
     ["To imply is to suggest something without stating it directly."],
     "imply = suggest indirectly.", "The definition given in the lesson is 'suggest'."),

    ("What is the listening talk mainly about?",
     {"A": "whether personality tests really reveal your personality", "B": "how to pass an interview", "C": "why genes control everything", "D": "how to create a quiz"},
     "A", "easy", 7, "Listening: main idea",
     ["The talk is called 'Do personality tests really reveal your personality?'"],
     "The talk questions whether tests reveal personality.", "The psychologist discusses the reliability of personality tests."),

    ("According to the talk, what do many people think of personality tests?",
     {"A": "gimmicky and pseudo-scientific", "B": "reliable and accurate", "C": "cheap and simple", "D": "modern and useful"},
     "A", "easy", 7, "Listening: gap 1",
     ["Many people think the word 'personality tests' is gimmicky and pseudo-scientific."],
     "People see the tests as gimmicky.", "For many, the word has negative associations."),

    ("According to the talk, why can results change over time?",
     {"A": "Because the results are not fixed", "B": "Because the tests are too short", "C": "Because candidates cheat", "D": "Because the questions are difficult"},
     "A", "medium", 7, "Listening: gap 3",
     ["The talk says the results are not fixed and can often change."],
     "Results are not fixed.", "An individual's job performance and health can also affect results."),

    ("According to the talk, what can change over time?",
     {"A": "an individual's job performance", "B": "the number of questions", "C": "the price of the test", "D": "the length of the interview"},
     "A", "medium", 7, "Listening: gap 4",
     ["The talk says an individual's job performance can change over time."],
     "Job performance can change over time.", "Both test results and job performance can change."),

    ("According to the talk, what can also affect personality test results?",
     {"A": "mental and physical health", "B": "the interviewer's mood", "C": "the time of day", "D": "the candidate's clothes"},
     "A", "easy", 7, "Listening: gap 5",
     ["The talk says mental and physical health can affect the results."],
     "Health can affect the results.", "Changes in mental and physical health change test results."),

    ("According to the talk, what is always best when hiring?",
     {"A": "a combination of methods", "B": "one personality test", "C": "a longer interview", "D": "no tests at all"},
     "A", "easy", 7, "Listening: gap 10",
     ["The talk says 'a combination of methods is always best'."],
     "A combination of methods is best.", "No one should be hired on the basis of a single test alone."),

    ("According to the talk, what should recruiters also consider?",
     {"A": "the working environment", "B": "the candidate's hobbies", "C": "the salary offered", "D": "the office furniture"},
     "A", "medium", 7, "Listening: gap 8",
     ["The talk says the working environment is crucial to performance."],
     "The working environment is crucial.", "Recruiters should consider the working environment too."),

    ("How does the psychologist describe personality tests?",
     {"A": "a useful tool, but the results are not fixed", "B": "a complete waste of time", "C": "the only way to hire people", "D": "always accurate and reliable"},
     "A", "medium", 7, "Listening: comprehension",
     ["The talk says 'It is a useful tool, but it is not fixed - the results are not fixed'."],
     "A useful tool that is not fixed.", "The psychologist sees tests as useful but not final."),

    ("Which syllable carries the main stress in the word 'disposition'?",
     {"A": "the second syllable (po)", "B": "the first syllable (dis)", "C": "the last syllable (tion)", "D": "the third syllable (si)"},
     "A", "hard", 7, "Exercise 2: Word stress",
     ["The main stress in dis-PO-si-tion falls on the second syllable 'po'."],
     "dis-PO-si-tion", "The stressed syllable is the second one."),

    ("Which syllable carries the main stress in the word 'personality'?",
     {"A": "the third syllable (al)", "B": "the first syllable (per)", "C": "the second syllable (son)", "D": "the last syllable (ty)"},
     "A", "hard", 7, "Exercise 2: Word stress",
     ["The main stress in per-son-AL-i-ty falls on the third syllable 'al'."],
     "per-son-AL-i-ty", "The stressed syllable is 'al'."),

    ("Which syllable carries the main stress in the word 'vulnerability'?",
     {"A": "the fourth syllable (bil)", "B": "the first syllable (vul)", "C": "the second syllable (ner)", "D": "the fifth syllable (i)"},
     "A", "hard", 7, "Exercise 2: Word stress",
     ["The main stress in vul-ne-ra-BIL-i-ty falls on the fourth syllable 'bil'."],
     "vul-ne-ra-BIL-i-ty", "The stressed syllable is 'bil'."),

    ("Which syllable carries the main stress in the word 'hereditary'?",
     {"A": "the second syllable (red)", "B": "the first syllable (her)", "C": "the third syllable (i)", "D": "the last syllable (ry)"},
     "A", "hard", 7, "Exercise 2: Word stress",
     ["The main stress in he-RED-i-ta-ry falls on the second syllable 'red'."],
     "he-RED-i-ta-ry", "The stressed syllable is 'red'."),

    ("Which syllable carries the main stress in the word 'oversimplification'?",
     {"A": "the sixth syllable (ca)", "B": "the first syllable (o)", "C": "the third syllable (sim)", "D": "the last syllable (tion)"},
     "A", "hard", 7, "Exercise 2: Word stress",
     ["The main stress in o-ver-sim-pli-fi-CA-tion falls on the syllable 'ca'."],
     "o-ver-sim-pli-fi-CA-tion", "The stressed syllable is 'ca'."),

    ("Which word's main stress falls on the FIRST syllable?",
     {"A": "destiny", "B": "disposition", "C": "personality", "D": "vulnerability"},
     "A", "medium", 7, "Exercise 2: Word stress",
     ["DES-ti-ny has the main stress on the first syllable."],
     "DES-ti-ny", "The other words are stressed on later syllables."),

    ("Which word has the main stress on its FIRST syllable?",
     {"A": "offspring", "B": "hereditary", "C": "proponents", "D": "oversimplification"},
     "A", "medium", 7, "Exercise 2: Word stress",
     ["OFF-spring is stressed on the first syllable."],
     "OFF-spring", "The other words carry stress on later syllables."),

    ("In the discussion statement 'It is unusual for someone to leave school without a career idea', the speaker thinks that ...",
     {"A": "most students have some idea of their future career", "B": "students never think about careers", "C": "schools should give career tests", "D": "leaving school is a bad idea"},
     "A", "hard", 7, "Exercise 5: Discussion statements",
     ["The statement says it is unusual (rare) to leave school with no career idea."],
     "Most students have a career idea.", "If it is unusual, then it rarely happens."),

    ("In 'the candidate may know what the interviewer wants to hear', the phrase 'wants to hear' means the interviewer wants ...",
     {"A": "the answer the interviewer expects or likes", "B": "the candidate to sing", "C": "the candidate to leave", "D": "a truthful but different answer"},
     "A", "hard", 7, "Exercise 5: Discussion statements",
     ["The phrase means the candidate may give the answer the interviewer expects."],
     "The interviewer wants the expected answer.", "This is given as a weakness of personality tests."),

    ("Which word is closest in meaning to 'implied'?",
     {"A": "suggested", "B": "stated", "C": "denied", "D": "proved"},
     "A", "medium", 7, "Word List 1.3",
     ["'Implied' is the past form of 'imply', which means 'suggest'."],
     "implied = suggested.", "To imply something is to suggest it indirectly."),
]
