# Unit 2 Review - part 1 (Trip of my dreams, page 25)
ITEMS = [
    ("Which country did Sultan visit?",
     {"A": "Chile", "B": "Argentina", "C": "Peru", "D": "Brazil"},
     "A", "easy", 25, "Reading: The trip of my dreams",
     ["Sultan describes Chile: the Atacama Desert and the edge of Antarctica."],
     "Chile", "Santiago, Valparaiso and the desert are all in Chile."),

    ("What are the two contrasts of Chile mentioned in the blog?",
     {"A": "the Atacama Desert at one end and the edge of Antarctica at the other", "B": "old beaches and new mountains", "C": "desert in the north and jungle in the south", "D": "city in the east and ocean in the west"},
     "A", "easy", 25, "Reading: paragraph 1",
     ["Chile has amazing contrasts: the Atacama Desert at one end and the edge of Antarctica at the other."],
     "Desert and Antarctica are the contrasts.", "There are also old colonial towns and modern skyscrapers."),

    ("What does 'it had always been on my bucket list' mean?",
     {"A": "it was something I always wanted to do before I die", "B": "it was written on a shopping list", "C": "it was a work duty", "D": "it was a school project"},
     "A", "medium", 25, "Reading: paragraph 1",
     ["A 'bucket list' is a list of things you want to do in your life."],
     "bucket list = things to do in life.", "Visiting Chile was a lifelong dream."),

    ("How long had Sultan and Adnan known each other?",
     {"A": "not that long", "B": "since childhood", "C": "for ten years", "D": "their whole lives"},
     "A", "easy", 25, "Reading: paragraph 2",
     ["The text says 'We hadn't known each other that long'."],
     "They had not known each other long.", "They had hit it off right from the start."),

    ("What does 'we'd really hit it off right from the start' mean?",
     {"A": "we got on well with each other immediately", "B": "we argued from the beginning", "C": "we met by accident", "D": "we were in the same class"},
     "A", "medium", 25, "Reading: paragraph 2",
     ["'Hit it off' means to like each other and get on well from the first meeting."],
     "hit it off = got on well at once.", "They became friends quickly."),

    ("How does Sultan describe himself and Adnan?",
     {"A": "Sultan is reserved; Adnan is a social butterfly", "B": "Sultan is outgoing; Adnan is shy", "C": "they are both quiet", "D": "they are both very loud"},
     "A", "easy", 25, "Reading: paragraph 2",
     ["'I'm quite reserved, whereas he is a real social butterfly.'"],
     "Sultan reserved, Adnan sociable.", "They seemed to complement each other well."),

    ("What does 'they complement each other well' mean?",
     {"A": "their characters balance and suit each other", "B": "they pay each other compliments", "C": "they are exactly the same", "D": "they compete with each other"},
     "A", "hard", 25, "Reading: paragraph 2",
     ["'Complement' means their different qualities fit together well."],
     "Their qualities balance each other.", "Reserved and sociable can work together."),

    ("What did Adnan become for Sultan's dream?",
     {"A": "the driving force in making it happen", "B": "a serious problem", "C": "a careless companion", "D": "a tour guide"},
     "A", "medium", 25, "Reading: paragraph 2",
     ["Adnan 'became the driving force in actually making my dream happen'."],
     "Adnan made the dream happen.", "He pushed the trip forward."),

    ("What did Sultan love doing in Santiago?",
     {"A": "walking around the neighbourhoods and trying typical dishes", "B": "shopping in big malls", "C": "sunbathing on the beach", "D": "visiting museums all day"},
     "A", "medium", 25, "Reading: paragraph 3",
     ["He loved walking around the neighbourhoods, trying dishes like caldillo de congrio."],
     "Walking and trying local food.", "He soaked up the atmosphere."),

    ("What is 'caldillo de congrio'?",
     {"A": "eel soup", "B": "chicken rice", "C": "fish and chips", "D": "bread pudding"},
     "A", "hard", 25, "Reading: paragraph 3",
     ["The text calls it 'caldillo de congrio (eel soup)'."],
     "eel soup", "Sultan says don't knock it 'til you've tried it."),

    ("What does 'don't knock it 'til you've tried it' mean?",
     {"A": "don't criticise something before you have tried it", "B": "don't touch the door", "C": "don't eat too fast", "D": "don't talk with your mouth full"},
     "A", "hard", 25, "Reading: paragraph 3",
     ["'Don't knock it' means don't criticise or reject it."],
     "Try it before criticising.", "The eel soup is worth trying."),

    ("What does 'things started to go downhill' mean?",
     {"A": "the situation started to get worse", "B": "they walked down a hill", "C": "they started to ski", "D": "the trip became cheaper"},
     "A", "medium", 25, "Reading: paragraph 4",
     ["'Go downhill' means to get worse."],
     "Things got worse.", "After a few days, Adnan was bored."),

    ("What did Adnan want to do in the Valle Nevado?",
     {"A": "go skiing", "B": "go camping", "C": "climb a volcano", "D": "visit a museum"},
     "A", "easy", 25, "Reading: paragraph 4",
     ["'He wanted to go skiing in the Valle Nevado.'"],
     "Go skiing", "It was a big problem for Sultan."),

    ("Why was the skiing trip a problem for Sultan?",
     {"A": "he had never been skiing and it would blow his budget", "B": "he had no warm clothes", "C": "he was afraid of heights", "D": "he had to work"},
     "A", "medium", 25, "Reading: paragraph 4",
     ["Not only had Sultan never been skiing, but it would completely blow his budget."],
     "Never skied + too expensive.", "Both were problems for him."),

    ("What does 'blow my budget' mean?",
     {"A": "spend much more money than I planned", "B": "save a lot of money", "C": "earn extra money", "D": "lose my wallet"},
     "A", "medium", 25, "Reading: paragraph 4",
     ["'Blow your budget' means to spend far more than you had planned."],
     "blow my budget = spend too much.", "The skiing would be too expensive."),

    ("Why did Sultan agree to go skiing?",
     {"A": "because he knew it meant a lot to Adnan", "B": "because he loved skiing", "C": "because Adnan paid for it", "D": "because the guide insisted"},
     "A", "medium", 25, "Reading: paragraph 4",
     ["Sultan knew it would mean a lot to Adnan, so he agreed."],
     "It meant a lot to Adnan.", "He felt bad and then Sultan felt bad too."),

    ("What happened when Adnan was in the mountains?",
     {"A": "he made a whole load of new friends", "B": "he stayed in his room", "C": "he went home early", "D": "he argued with everyone"},
     "A", "easy", 25, "Reading: paragraph 5",
     ["Being so social, Adnan soon made a whole load of new friends."],
     "Adnan made many new friends.", "Sultan did not click with the new crowd."),

    ("What does 'I didn't click with the new crowd' mean?",
     {"A": "I did not get on well with them", "B": "I pressed a button", "C": "I took photos with them", "D": "I made friends easily"},
     "A", "medium", 25, "Reading: paragraph 5",
     ["'Click with someone' means to get on well with them."],
     "didn't click = didn't get on.", "Sultan felt out of place with the group."),

    ("What does 'I was itching to get on with our tour' mean?",
     {"A": "I was very eager to continue the tour", "B": "I felt ill during the tour", "C": "I wanted to stop the tour", "D": "I was bored with the tour"},
     "A", "hard", 25, "Reading: paragraph 5",
     ["'Be itching to do something' means to be very keen and impatient to do it."],
     "itching to = very eager to.", "Sultan wanted to visit the Atacama Desert."),

    ("What did Moon Valley and Mars Valley feel like?",
     {"A": "being on another planet", "B": "being at the beach", "C": "being in a city", "D": "being at home"},
     "A", "easy", 25, "Reading: paragraph 6",
     ["'It really did feel as if we were on another planet.'"],
     "Like another planet", "The landscape was extraordinary."),

    ("What problem 'reared its head' in the desert?",
     {"A": "Adnan had posted unflattering photos of Sultan online", "B": "the car broke down", "C": "they got lost", "D": "their money ran out"},
     "A", "medium", 25, "Reading: paragraph 7",
     ["'Another problem reared its head' when Sultan saw Adnan's photos online."],
     "The photo problem appeared.", "Some of the pictures were not very flattering."),

    ("What does 'another problem reared its head' mean?",
     {"A": "another problem appeared", "B": "another problem disappeared", "C": "another problem was solved", "D": "a headache started"},
     "A", "medium", 25, "Reading: paragraph 6",
     ["'Reared its head' means appeared or came up."],
     "A new problem appeared.", "It caused tension between the friends."),

    ("What should Adnan have done before posting the photos?",
     {"A": "asked Sultan's permission", "B": "asked Sultan to pay", "C": "shown Sultan how to take photos", "D": "deleted his account"},
     "A", "easy", 25, "Reading: paragraph 7",
     ["Sultan felt Adnan should have asked permission before posting the photos."],
     "He should have asked permission.", "Some photos of Sultan were unflattering."),

    ("What does 'unflattering' mean?",
     {"A": "not attractive or not making someone look good", "B": "very beautiful", "C": "funny", "D": "ancient"},
     "A", "medium", 25, "Reading: paragraph 7",
     ["'Unflattering' photos do not make the person look good."],
     "unflattering = not attractive.", "A few pictures of Sultan were unflattering."),

    ("What does 'I just bit my tongue' mean?",
     {"A": "I did not say what I wanted to say", "B": "I hurt myself accidentally", "C": "I shouted loudly", "D": "I ate something"},
     "A", "medium", 25, "Reading: paragraph 7",
     ["'Bite your tongue' means to stop yourself from saying something."],
     "bit my tongue = stayed silent.", "He kept quiet to protect the friendship."),
]
