# Unit 3 Lesson 6 (Writing: A for-and-against essay, pages 34-35)
ITEMS = [
    ("What is the topic of the essay in the unit?",
     {"A": "whether we should buy locally or buy from anywhere in the world", "B": "whether online shopping is dangerous", "C": "how to save money", "D": "the history of supermarkets"},
     "A", "easy", 34, "Writing: topic",
     ["The essay asks whether we should buy local produce or buy from abroad."],
     "Buying local", "It weighs the two sides of the argument."),

    ("Why is 'buying local' a good title for the essay?",
     {"A": "it summarises the topic in just two words", "B": "it is long and detailed", "C": "it names the writer", "D": "it gives the conclusion"},
     "A", "easy", 34, "Writing: title",
     ["'Buying local' instantly tells the reader what the essay is about."],
     "A good title is short and clear.", "It shows the subject immediately."),

    ("Why should the opening paragraph do more than repeat the title?",
     {"A": "it should also grab the reader's attention", "B": "it should be very short", "C": "it should include facts", "D": "it should give the opinion"},
     "A", "medium", 34, "Writing: opening",
     ["A good opening catches the reader's attention and introduces the debate."],
     "Grab the reader's attention", "Then introduce the issue being argued."),

    ("In the opening paragraph, what example is used?",
     {"A": "packaged food, books and cheap clothes", "B": "cars and petrol", "C": "houses and land", "D": "machinery and tools"},
     "A", "medium", 34, "Writing: opening",
     ["Packaged food, books and cheap clothes are given as examples."],
     "Food, books and clothes", "These are things we can buy from anywhere."),

    ("What surprise does the opening paragraph mention?",
     {"A": "a label showing that a product was made in another country", "B": "a price that is too cheap", "C": "a free gift", "D": "a new shop"},
     "A", "medium", 34, "Writing: opening",
     ["It is surprising when a label reveals a product was made far away."],
     "A label shows a foreign origin.", "This surprises some buyers."),

    ("What is a 'shop around'?",
     {"A": "compare prices in different shops before buying", "B": "buy everything in one shop", "C": "ask for a refund", "D": "order online"},
     "A", "easy", 34, "Collocations",
     ["'Shop around' means to compare prices before deciding."],
     "Compare prices", "You shop around to find the best deal."),

    ("What is 'to stock up'?",
     {"A": "buy large quantities for the future", "B": "put goods on shelves", "C": "open a new shop", "D": "sell items cheaply"},
     "A", "easy", 34, "Collocations",
     ["'Stock up' means to buy a lot of something to keep for later."],
     "Buy in large quantities", "We stock up on essentials."),

    ("What is 'to run errands'?",
     {"A": "make short journeys to do jobs like buying things", "B": "run a shop", "C": "work for a company", "D": "go on holiday"},
     "A", "easy", 34, "Collocations",
     ["'Run errands' means make short trips to do small tasks."],
     "Short trips for tasks", "Like going to the shop or the bank."),

    ("What is 'to go on a shopping spree'?",
     {"A": "go shopping and spend a lot of money in a short time", "B": "buy only food", "C": "window-shop without buying", "D": "return goods to a shop"},
     "A", "medium", 34, "Collocations",
     ["A shopping spree means buying lots of things at once."],
     "Spend a lot quickly", "It is an exciting but expensive activity."),

    ("What does 'mooch around' mean?",
     {"A": "wander slowly around the shops with no clear purpose", "B": "run quickly through the mall", "C": "compare prices carefully", "D": "buy in bulk"},
     "A", "medium", 34, "Collocations",
     ["'Mooch around' means wander without a fixed aim."],
     "Wander aimlessly", "People mooch around the shops on Saturdays."),

    ("Which phrase means 'exactly what I need'?",
     {"A": "just the ticket", "B": "up to the minute", "C": "a piece of cake", "D": "in the red"},
     "A", "medium", 34, "Collocations",
     ["'Just the ticket' means exactly what is wanted or needed."],
     "just the ticket", "A shopping-related idiom."),

    ("What does 'weigh up the pros and cons' mean?",
     {"A": "consider the advantages and disadvantages", "B": "weigh the goods you bought", "C": "decide immediately", "D": "count your money"},
     "A", "medium", 34, "Writing: essay language",
     ["'Weigh up the pros and cons' means think about the good and bad points."],
     "Consider pros and cons", "This is the core of a for-and-against essay."),

    ("In a for-and-against essay, where do you usually state your own opinion?",
     {"A": "in the final paragraph", "B": "only in the title", "C": "at the start of every sentence", "D": "in the middle of a list"},
     "A", "easy", 34, "Writing: structure",
     ["The essay generally ends with the writer's own opinion."],
     "In the final paragraph", "You reach your conclusion at the end."),

    ("What tense do you normally use to give your opinion at the end?",
     {"A": "the present simple", "B": "the past perfect", "C": "the future continuous", "D": "the present perfect continuous"},
     "A", "medium", 34, "Writing: opinion",
     ["Use the present simple when giving your own opinion."],
     "Present simple", "'I think that...', 'In my opinion...'"),

    ("Why do you NOT use the past tense to give your final opinion?",
     {"A": "opinions are about the present, not the past", "B": "the past is too informal", "C": "it is grammatically wrong", "D": "nobody uses the past"},
     "A", "hard", 34, "Writing: opinion",
     ["A final opinion states what you think now, so the present simple fits."],
     "The opinion is true now.", "Present simple matches this."),

    ("Which words help you paraphrase in an essay?",
     {"A": "nearly the same as, identical, a different way to say", "B": "however, therefore, but", "C": "a, an, the", "D": "and, or, but"},
     "A", "medium", 34, "Writing: paraphrasing",
     ["Paraphrasing words include 'nearly the same as' and 'a different way to say'."],
     "Paraphrasing phrases", "They help you avoid repeating words."),

    ("Why is paraphrasing useful in an essay?",
     {"A": "it lets you show the same idea in a different way", "B": "it makes the essay longer", "C": "it adds new ideas", "D": "it changes the topic"},
     "A", "easy", 34, "Writing: paraphrasing",
     ["Paraphrasing expresses the same idea without repeating it."],
     "Say the same thing differently", "It keeps the essay natural."),

    ("Which of these is a way to introduce a contrast?",
     {"A": "on the other hand", "B": "for example", "C": "in addition", "D": "first of all"},
     "A", "easy", 34, "Writing: linking words",
     ["'On the other hand' introduces the opposite side of an argument."],
     "on the other hand", "Use it in a for-and-against essay."),

    ("Which expression introduces a conclusion?",
     {"A": "taking everything into account", "B": "to begin with", "C": "furthermore", "D": "as well as"},
     "A", "easy", 34, "Writing: linking words",
     ["'Taking everything into account' signals the final opinion."],
     "taking everything into account", "Other options include 'on balance'."),

    ("What does 'in my view' do in a final paragraph?",
     {"A": "marks your personal opinion", "B": "adds an example", "C": "starts a new topic", "D": "gives a fact"},
     "A", "easy", 34, "Writing: opinion",
     ["'In my view' clearly marks a personal opinion."],
     "Marks the opinion", "Similar: 'I believe that', 'as I see it'."),

    ("Which word means 'finally' or 'in conclusion'?",
     {"A": "eventually", "B": "suddenly", "C": "fortunately", "D": "obviously"},
     "A", "hard", 34, "Writing: linking words",
     ["'Eventually' can mean finally, in the end."],
     "eventually = in conclusion", "It signals the final paragraph."),

    ("Which phrase means 'considering everything'?",
     {"A": "on balance", "B": "in the red", "C": "up to the minute", "D": "in the black"},
     "A", "medium", 34, "Writing: linking words",
     ["'On balance' means when all things are considered."],
     "on balance", "Used before giving a final opinion."),

    ("Complete the essay opener: 'The internet means that we can now buy things ______ all over the world.'",
     {"A": "from", "B": "at", "C": "by", "D": "to"},
     "A", "medium", 34, "Writing: opening",
     ["'...buy things from all over the world.'"],
     "from", "We buy things from places."),

    ("Which argument FOR buying locally is given in the essay?",
     {"A": "it protects jobs in your local community", "B": "it is cheaper", "C": "it saves time", "D": "it is more convenient"},
     "A", "medium", 34, "Writing: for-arguments",
     ["Buying local keeps money in the local community and protects jobs."],
     "Protects local jobs", "Supporting local businesses helps your area."),

    ("Which argument AGAINST buying locally is given in the essay?",
     {"A": "local goods can be more expensive and limited in choice", "B": "local goods are always better", "C": "foreign goods are dangerous", "D": "local shops close early"},
     "A", "medium", 34, "Writing: against-arguments",
     ["Local products may cost more and the choice may be smaller."],
     "More expensive, less choice", "Foreign goods are often cheaper."),

    ("What does 'exclusive' mean in 'exclusive goods'?",
     {"A": "special and not available everywhere", "B": "cheap and simple", "C": "broken and old", "D": "dangerous and risky"},
     "A", "hard", 34, "Writing: vocabulary",
     ["'Exclusive' means special, limited to certain places or people."],
     "special and rare", "An exclusive product is not mass-produced."),

    ("What does 'high-end' mean?",
     {"A": "expensive and of good quality", "B": "cheap and basic", "C": "out of fashion", "D": "sold everywhere"},
     "A", "medium", 34, "Writing: vocabulary",
     ["'High-end' describes luxury, quality goods."],
     "luxury, top quality", "High-end products cost more."),

    ("What does 'globally' mean in the essay?",
     {"A": "all over the world", "B": "in one town", "C": "on the internet", "D": "in the past"},
     "A", "easy", 34, "Writing: vocabulary",
     ["'Globally' means across the whole world."],
     "all over the world", "Goods can now be sold globally."),

    ("What does 'imported' mean?",
     {"A": "brought into a country from another", "B": "made in your own town", "C": "sold at a loss", "D": "thrown away"},
     "A", "easy", 34, "Writing: vocabulary",
     ["'Imported' goods come from another country."],
     "brought from abroad", "Opposite: exported or local."),

    ("Which word means 'exported'?",
     {"A": "sold to other countries", "B": "bought from abroad", "C": "made at home", "D": "given for free"},
     "A", "medium", 34, "Writing: vocabulary",
     ["'Exported' means sold or sent to other countries."],
     "sold abroad", "The opposite of imported."),

    ("What is the basic structure of a for-and-against essay?",
     {"A": "introduction, arguments for, arguments against, conclusion", "B": "one long paragraph", "C": "title only", "D": "questions and answers"},
     "A", "easy", 34, "Writing: structure",
     ["It has an opening, the two sides, and a final opinion."],
     "Intro, for, against, conclusion", "Each point is in its own paragraph."),

    ("Why should each paragraph contain only ONE main idea?",
     {"A": "it makes the argument clear to the reader", "B": "it makes the essay shorter", "C": "it avoids grammar mistakes", "D": "it is a rule of spelling"},
     "A", "medium", 34, "Writing: paragraphs",
     ["One idea per paragraph keeps the essay clear and logical."],
     "Clear and logical", "Readers can follow the argument easily."),

    ("Which linking word best adds another argument FOR?",
     {"A": "moreover", "B": "on the other hand", "C": "however", "D": "whereas"},
     "A", "easy", 34, "Writing: linking words",
     ["'Moreover' adds another supporting point."],
     "moreover", "Use 'however' to contrast."),

    ("Which linking word best introduces an AGAINST point?",
     {"A": "however", "B": "in addition", "C": "firstly", "D": "for instance"},
     "A", "easy", 34, "Writing: linking words",
     ["'However' introduces a point that contrasts with the last one."],
     "however", "It signals the opposing view."),

    ("Complete: 'The writer of a for-and-against essay should be ________ in the main paragraphs.'",
     {"A": "balanced", "B": "angry", "C": "funny", "D": "emotional"},
     "A", "medium", 34, "Writing: style",
     ["In the body you present both sides fairly; emotion comes in the conclusion."],
     "balanced and fair", "Only the final opinion is personal."),

    ("What does 'cutting-edge' mean in 'cutting-edge technology'?",
     {"A": "the most advanced and modern", "B": "cheap and basic", "C": "broken", "D": "outdated"},
     "A", "medium", 34, "Writing: vocabulary",
     ["'Cutting-edge' means the newest and most advanced."],
     "most advanced", "Another phrase: state-of-the-art."),

    ("Which phrase means 'the most fashionable'?",
     {"A": "up to the minute", "B": "behind the times", "C": "old-fashioned", "D": "second-hand"},
     "A", "medium", 34, "Writing: vocabulary",
     ["'Up to the minute' means the very latest."],
     "up to the minute", "Used about fashion and news."),

    ("What is the final paragraph mainly for?",
     {"A": "stating your own opinion", "B": "adding new facts", "C": "listing shops", "D": "asking questions"},
     "A", "easy", 34, "Writing: conclusion",
     ["The last paragraph gives your personal conclusion."],
     "Your own opinion", "It balances everything together."),

    ("In the model essay, what is the writer's final opinion?",
     {"A": "it is best to strike a balance between local and imported goods", "B": "never buy anything imported", "C": "only buy imported goods", "D": "stop shopping completely"},
     "A", "medium", 34, "Writing: conclusion",
     ["The writer concludes we should strike a balance between the two."],
     "Strike a balance", "Buy local when possible, but accept imports too."),

    ("Which word best completes: 'Buying local is good for the ________ economy.'",
     {"A": "local", "B": "global", "C": "foreign", "D": "central"},
     "A", "easy", 34, "Writing: collocation",
     ["'The local economy' is the standard collocation."],
     "local economy", "Buying local helps it grow."),
]
