# Unit 3 Lesson 3 (Speaking: Negotiating, page 29)
ITEMS = [
    ("Which phrase is used to ask for something politely?",
     {"A": "This is a bit awkward, but ...", "B": "It has to be a 'no'.", "C": "Let's shake on that, then.", "D": "OK, I can live with that."},
     "A", "easy", 29, "Speaking box: Asking for what you want",
     ["'This is a bit awkward, but...' politely introduces a request."],
     "This is a bit awkward, but...", "It softens an awkward request."),

    ("Which phrase means 'would you be willing to...'?",
     {"A": "Would you be prepared to ...?", "B": "How does that sound?", "C": "The bottom line is ...", "D": "I'd like to say yes, but ..."},
     "A", "easy", 29, "Speaking box: Asking for what you want",
     ["'Would you be prepared to...?' politely asks if someone will accept."],
     "Would you be prepared to...?", "It is a polite request."),

    ("Which phrase asks about the possibility of change?",
     {"A": "I'm wondering if there's any flexibility ...?", "B": "It has to be a 'no'.", "C": "Great, you've got yourself a deal.", "D": "Let's shake on that, then."},
     "A", "easy", 29, "Speaking box: Asking for what you want",
     ["'I'm wondering if there's any flexibility?' asks if the offer can change."],
     "I'm wondering if there's any flexibility?", "It checks if the other side can move."),

    ("Which phrase suggests a proposal?",
     {"A": "How about if we were to ...?", "B": "At the end of the day ...", "C": "I can see what you're saying, but ...", "D": "Provided you ..., I see no reason why I couldn't ..."},
     "A", "medium", 29, "Speaking box: Asking for what you want",
     ["'How about if we were to...?' makes a suggestion to negotiate."],
     "How about if we were to...?", "It proposes a possible solution."),

    ("Which phrase politely refuses an offer?",
     {"A": "I'd like to say yes, but ...", "B": "Would you be prepared to ...?", "C": "How about if we were to ...?", "D": "I'm wondering if there's any flexibility?"},
     "A", "easy", 29, "Speaking box: Refusing an offer",
     ["'I'd like to say yes, but...' refuses while being polite."],
     "I'd like to say yes, but...", "It softens the refusal."),

    ("What does 'I'm afraid that's a bit out of my price range' mean?",
     {"A": "that is more than I can afford", "B": "that is a very good price", "C": "I have no money at all", "D": "the price is negotiable"},
     "A", "easy", 29, "Speaking box: Refusing an offer",
     ["'Out of my price range' means the price is too high for the speaker."],
     "out of my price range = too expensive.", "It is a polite refusal of a price."),

    ("What does 'The bottom line is...' mean?",
     {"A": "the most important point is...", "B": "the final price is...", "C": "the last line is...", "D": "the problem is..."},
     "A", "medium", 29, "Speaking box: Refusing an offer",
     ["'The bottom line' is the essential or final point."],
     "The bottom line = key point.", "It states the essential fact."),

    ("What does 'At the end of the day...' mean in a negotiation?",
     {"A": "when you consider everything...", "B": "when it gets dark...", "C": "at midnight...", "D": "on the last day..."},
     "A", "medium", 29, "Speaking box: Refusing an offer",
     ["'At the end of the day' means 'when all is considered'."],
     "At the end of the day = ultimately.", "It introduces the final judgement."),

    ("Which phrase clearly rejects an offer?",
     {"A": "It has to be a 'no'.", "B": "OK, I can live with that.", "C": "Great, you've got yourself a deal.", "D": "Let's shake on that, then."},
     "A", "easy", 29, "Speaking box: Refusing an offer",
     ["'It has to be a no' is a firm refusal."],
     "It has to be a 'no'.", "It makes the refusal clear."),

    ("Which phrase accepts an offer happily?",
     {"A": "Great, you've got yourself a deal.", "B": "I'm afraid that's out of my budget.", "C": "It has to be a 'no'.", "D": "I'm wondering if there's any flexibility?"},
     "A", "easy", 29, "Speaking box: Accepting an offer",
     ["'Great, you've got yourself a deal' accepts the offer."],
     "You've got yourself a deal = agreement.", "It confirms the deal."),

    ("What does 'Let's shake on that, then.' mean?",
     {"A": "let's agree by shaking hands", "B": "let's leave now", "C": "let's think about it", "D": "let's change the deal"},
     "A", "easy", 29, "Speaking box: Accepting an offer",
     ["'Shake on it' means to confirm an agreement by shaking hands."],
     "shake on that = confirm the deal.", "It seals the agreement."),

    ("What does 'OK, I can live with that.' mean?",
     {"A": "I can accept that even though it's not perfect", "B": "I refuse that", "C": "that will kill me", "D": "I don't understand that"},
     "A", "medium", 29, "Speaking box: Accepting an offer",
     ["'I can live with that' means I can accept the compromise."],
     "I can live with that = I accept it.", "It is a willing but not thrilled acceptance."),

    ("Which phrase tries to find a middle ground?",
     {"A": "Can we try and meet halfway on this?", "B": "It has to be a 'no'.", "C": "I'd like to say yes, but ...", "D": "The bottom line is ..."},
     "A", "easy", 29, "Speaking box: Win-win situation",
     ["'Meet halfway' means compromise in the middle."],
     "meet halfway = compromise.", "Each side gives a little."),

    ("What does 'Is there any room for compromise?' mean?",
     {"A": "can we make some changes to reach an agreement?", "B": "is the meeting room free?", "C": "do we have any space?", "D": "is the offer final?"},
     "A", "medium", 29, "Speaking box: Win-win situation",
     ["'Room for compromise' means a chance to adjust the deal."],
     "room for compromise = possibility to adjust.", "It seeks a solution both sides accept."),

    ("What does 'Provided you ..., I see no reason why I couldn't ...' express?",
     {"A": "a conditional acceptance", "B": "a final refusal", "C": "a question", "D": "an apology"},
     "A", "hard", 29, "Speaking box: Win-win situation",
     ["'Provided you...' means 'if you...'; the speaker accepts conditionally."],
     "Provided = if, condition.", "It opens the door to a deal."),

    ("What does 'I can see what you're saying, but ...' do?",
     {"A": "it acknowledges the other side before disagreeing", "B": "it ends the negotiation", "C": "it changes the subject", "D": "it threatens the other side"},
     "A", "medium", 29, "Speaking box: Win-win situation",
     ["It shows understanding before presenting a different view."],
     "It acknowledges then disagrees.", "It keeps the discussion friendly."),

    ("What does 'How does that sound?' mean?",
     {"A": "what do you think of that proposal?", "B": "is that too loud?", "C": "can you hear me?", "D": "is that correct grammar?"},
     "A", "easy", 29, "Speaking box: Win-win situation",
     ["'How does that sound?' asks for the other person's opinion of a proposal."],
     "How does that sound? = what do you think?", "It checks the proposal's acceptability."),

    ("Complete: 'Huda: Well, I'd like to say ______, but midnight is a bit late for me.'",
     {"A": "yes", "B": "no", "C": "maybe", "D": "sorry"},
     "A", "medium", 29, "Exercise 4: Conversation",
     ["Huda uses 'I'd like to say yes, but...' to refuse politely."],
     "yes", "She refuses 11.30-8-midnight politely."),

    ("Complete: 'Mrs Alra'i: ______ 11.30? Would that be OK?'",
     {"A": "How about", "B": "The bottom line is", "C": "At the end of the day", "D": "Let's shake on that"},
     "A", "medium", 29, "Exercise 4: Conversation",
     ["Mrs Alra'i suggests 'How about 11.30?'."],
     "How about", "She offers an alternative time."),

    ("Complete: 'Mrs Alra'i: Oh, I'm afraid that's a bit out of my ______.'",
     {"A": "budget", "B": "reach", "C": "house", "D": "plan"},
     "A", "medium", 29, "Exercise 4: Conversation",
     ["She says the price is out of her budget."],
     "budget", "She cannot pay 8 dinars an hour."),

    ("Complete: 'Huda: Can we try and ______ ? Would 7.50 dinars be OK?'",
     {"A": "meet halfway", "B": "shake on it", "C": "start again", "D": "call it a day"},
     "A", "medium", 29, "Exercise 4: Conversation",
     ["Huda asks to meet halfway between 8 and 7 dinars."],
     "meet halfway", "7.50 is the middle point."),

    ("What is Huda's normal charge?",
     {"A": "8 dinars an hour", "B": "7 dinars an hour", "C": "7.50 dinars an hour", "D": "10 dinars an hour"},
     "A", "easy", 29, "Exercise 4: Conversation",
     ["'I usually charge 8 dinars an hour.'"],
     "8 dinars an hour", "Mrs Alra'i asked for 7, and they settled on 7.50."),

    ("What did Huda and Mrs Alra'i finally agree on?",
     {"A": "7.50 dinars an hour", "B": "8 dinars an hour", "C": "7 dinars an hour", "D": "no deal"},
     "A", "medium", 29, "Exercise 4: Conversation",
     ["They met halfway at 7.50 dinars an hour."],
     "7.50 dinars an hour", "Both sides accepted the compromise."),

    ("When does Mrs Alra'i need a babysitter?",
     {"A": "a Friday or Saturday night for about four hours", "B": "every weekday evening", "C": "Sunday mornings", "D": "the whole weekend"},
     "A", "easy", 29, "Exercise 4: Conversation",
     ["'It'll be a Friday or Saturday night for about four hours, say eight 'til midnight.'"],
     "Friday or Saturday night", "They agreed on until 11.30."),

    ("What is 'negotiating'?",
     {"A": "discussing to reach an agreement both sides accept", "B": "fighting to get your way", "C": "selling products cheaply", "D": "giving a presentation"},
     "A", "easy", 29, "Lesson 3A: Speaking",
     ["Negotiation is discussion to find an acceptable agreement."],
     "negotiating = reaching an agreement.", "It often involves compromise."),

    ("Which phrase describes 'trying to get to a win-win situation'?",
     {"A": "Can we try and meet halfway on this?", "B": "It has to be a 'no'.", "C": "I'm afraid that's out of my price range.", "D": "Great, you've got yourself a deal."},
     "A", "medium", 29, "Speaking box: Win-win situation",
     ["'Meet halfway' aims for a result good for both sides."],
     "meet halfway = win-win.", "Both sides compromise."),

    ("Which is a polite way to refuse?",
     {"A": "I'd like to say yes, but ...", "B": "No way!", "C": "Forget it.", "D": "Never!"},
     "A", "easy", 29, "Speaking box: Refusing an offer",
     ["'I'd like to say yes, but...' is a polite refusal."],
     "I'd like to say yes, but...", "It is soft and courteous."),

    ("Which phrase is used to check the other person's reaction?",
     {"A": "How does that sound?", "B": "It has to be a 'no'.", "C": "The bottom line is ...", "D": "At the end of the day ..."},
     "A", "easy", 29, "Speaking box: Win-win situation",
     ["'How does that sound?' checks whether the proposal is acceptable."],
     "How does that sound?", "It invites feedback."),

    ("In the negotiation conversation, who negotiates with Mrs Alra'i?",
     {"A": "Huda", "B": "Malek", "C": "Adnan", "D": "Saeed"},
     "A", "easy", 29, "Exercise 4: Conversation",
     ["Huda negotiates the babysitting job with Mrs Alra'i."],
     "Huda", "Huda wants the babysitting job."),

    ("What did Mrs Alra'i say about the children?",
     {"A": "they're quite self-sufficient and won't be any bother", "B": "they are very difficult", "C": "they sleep all day", "D": "they need constant care"},
     "A", "medium", 29, "Exercise 4: Conversation",
     ["She said the children are self-sufficient; Huda will only need to watch TV."],
     "They are self-sufficient.", "That is why she asked for a lower price."),

    ("Which phrase means 'I accept even though it isn't perfect'?",
     {"A": "OK, I can live with that.", "B": "I'd like to say yes, but ...", "C": "It has to be a 'no'.", "D": "I'm wondering if there's any flexibility?"},
     "A", "medium", 29, "Speaking box: Accepting an offer",
     ["'I can live with that' shows acceptance of an imperfect deal."],
     "I can live with that = accept.", "It is a realistic acceptance."),

    ("Which phrase introduces a firm final point?",
     {"A": "The bottom line is ...", "B": "How about if we were to ...?", "C": "Would you be prepared to ...?", "D": "Provided you ..."},
     "A", "easy", 29, "Speaking box: Refusing an offer",
     ["'The bottom line is...' states the essential final point."],
     "The bottom line = final point.", "It often precedes a refusal or condition."),

    ("Which of these is NOT a phrase for asking for what you want?",
     {"A": "Let's shake on that, then.", "B": "This is a bit awkward, but ...", "C": "Would you be prepared to ...?", "D": "How about if we were to ...?"},
     "A", "medium", 29, "Speaking box: Negotiating",
     ["'Let's shake on that' is for accepting, not asking."],
     "Let's shake on that = accepting.", "The others are requests."),

    ("Which expression means 'when you consider everything'?",
     {"A": "At the end of the day ...", "B": "In the beginning ...", "C": "At the moment ...", "D": "After lunch ..."},
     "A", "easy", 29, "Speaking box: Refusing an offer",
     ["'At the end of the day' means ultimately, all things considered."],
     "At the end of the day = ultimately.", "It frames the final point."),

    ("What does 'win-win situation' mean?",
     {"A": "a result that is good for both sides", "B": "a result good for only one side", "C": "a game where nobody wins", "D": "a competition"},
     "A", "easy", 29, "Speaking box: Win-win situation",
     ["A win-win outcome benefits both people in the negotiation."],
     "win-win = good for both.", "Compromise can create win-win results."),

    ("What is a 'compromise'?",
     {"A": "an agreement where each side gives up something", "B": "a decision made by one side only", "C": "a fight between two sides", "D": "a suggestion nobody accepts"},
     "A", "easy", 29, "Speaking box: Win-win situation",
     ["A compromise is a settlement reached by both sides giving a little."],
     "compromise = give-and-take.", "Meeting halfway is a compromise."),

    ("Complete: 'Great, you've got yourself a ______.'",
     {"A": "deal", "B": "job", "C": "price", "D": "time"},
     "A", "easy", 29, "Speaking box: Accepting an offer",
     ["The phrase is 'you've got yourself a deal'."],
     "deal", "It confirms the agreement."),

    ("Which phrase could end a successful negotiation?",
     {"A": "Let's shake on that, then.", "B": "It has to be a 'no'.", "C": "I'm afraid that's out of my budget.", "D": "I'd like to say yes, but ..."},
     "A", "easy", 29, "Speaking box: Accepting an offer",
     ["'Let's shake on that' seals a successful agreement."],
     "Let's shake on that, then.", "Both sides agree."),

    ("Which question asks if a price can change?",
     {"A": "I'm wondering if there's any flexibility?", "B": "How does that sound?", "C": "Is there a deal?", "D": "Are you sure?"},
     "A", "medium", 29, "Speaking box: Asking for what you want",
     ["'Any flexibility?' asks whether the terms can be adjusted."],
     "Is there any flexibility?", "It invites a better offer."),

    ("What did Mrs Alra'i suggest about Huda's hours?",
     {"A": "she wanted midnight to be changed to 11.30", "B": "she wanted a full day", "C": "she wanted Sunday morning", "D": "she wanted a different babysitter"},
     "A", "medium", 29, "Exercise 4: Conversation",
     ["Mrs Alra'i asked if 11.30 would be OK instead of midnight."],
     "Change midnight to 11.30.", "Huda agreed to this change."),
]
