# Unit 2 Lesson 6 (Writing and Vocabulary: An email of complaint, pages 22-23)
ITEMS = [
    ("Who is email A written to?",
     {"A": "a friend (Amer)", "B": "the coach company", "C": "the hotel manager", "D": "the airline"},
     "A", "easy", 22, "Model emails A and B",
     ["Email A begins 'Hi Amer' and is informal, written to a friend."],
     "Email A is to a friend.", "It uses informal language."),

    ("Who is email B written to?",
     {"A": "the coach company", "B": "a friend", "C": "the tour guide", "D": "the pilot"},
     "A", "easy", 22, "Model emails A and B",
     ["Email B begins 'Dear Sir' and is a formal complaint to the company."],
     "Email B is a formal complaint.", "It is signed 'Yours faithfully, Malek Alhayek'."),

    ("Who wrote email B?",
     {"A": "Malek Alhayek", "B": "Amer", "C": "M", "D": "Saeed"},
     "A", "easy", 22, "Model email B",
     ["The formal email is signed 'Yours faithfully, Malek Alhayek'."],
     "Malek Alhayek", "He is writing about his family's coach journey."),

    ("What does 'What a nightmare journey!' in email A mean?",
     {"A": "the journey was a terrible experience", "B": "the journey was short", "C": "the journey was very cheap", "D": "the journey was by night"},
     "A", "medium", 22, "Model email A",
     ["'A nightmare journey' means a journey full of problems and stress."],
     "It was a terrible journey.", "Email A describes everything that went wrong."),

    ("What is the formal equivalent of 'It didn't arrive on time' in email B?",
     {"A": "the coach failed to arrive on time", "B": "the coach arrived early", "C": "the coach never arrived", "D": "the coach arrived on time"},
     "A", "medium", 23, "Exercise 2: Formal equivalents",
     ["Email B says 'We were disappointed when the coach failed to arrive on time'."],
     "failed to arrive on time", "'Failed to' is more formal than 'didn't'."),

    ("What is the formal equivalent of 'more than 30 minutes late'?",
     {"A": "in excess of 30 minutes late", "B": "about 30 minutes late", "C": "exactly 30 minutes late", "D": "less than 30 minutes late"},
     "A", "medium", 23, "Exercise 2: Formal equivalents",
     ["Email B says 'it was in excess of 30 minutes late'."],
     "in excess of 30 minutes", "'In excess of' is formal for 'more than'."),

    ("What is the formal equivalent of 'The next thing that went wrong was...'?",
     {"A": "The second issue was...", "B": "The last problem was...", "C": "The best part was...", "D": "The first surprise was..."},
     "A", "medium", 23, "Exercise 2: Formal equivalents",
     ["Email B structures the complaint with 'The second issue was...'."],
     "The second issue was...", "It is a formal way of listing problems."),

    ("What is the formal equivalent of 'You know that...'?",
     {"A": "You may remember that...", "B": "You must know that...", "C": "You will never know that...", "D": "I know that..."},
     "A", "medium", 23, "Exercise 2: Formal equivalents",
     ["Email B uses 'You may remember that last Thursday was a particularly cold morning'."],
     "You may remember that...", "'May' makes it polite and formal."),

    ("What is the formal equivalent of 'To top it all...'?",
     {"A": "Finally, ...", "B": "First of all, ...", "C": "Surprisingly, ...", "D": "Of course, ..."},
     "A", "medium", 23, "Exercise 2: Formal equivalents",
     ["Email B uses 'Finally, to our utter disbelief...'."],
     "Finally, ...", "It introduces the last and worst problem."),

    ("What is the formal equivalent of 'Not an apology from anyone.'?",
     {"A": "at no time were we offered an apology", "B": "nobody said sorry", "C": "someone apologised", "D": "an apology was expected"},
     "A", "hard", 23, "Exercise 2: Formal equivalents",
     ["Email B says 'at no time were we offered an apology of any kind'."],
     "at no time were we offered an apology", "This uses inversion and the passive for formality."),

    ("What is the formal equivalent of 'Luckily...'?",
     {"A": "we were extremely fortunate in that...", "B": "by luck, ...", "C": "with good luck, ...", "D": "lucky us, ..."},
     "A", "hard", 23, "Exercise 2: Formal equivalents",
     ["Email B says 'While we were extremely fortunate in that we reached the airport just in time'."],
     "we were extremely fortunate", "It is a formal way to say 'luckily'."),

    ("What is the formal equivalent of 'by the skin of our teeth'?",
     {"A": "just in time to catch our flight", "B": "very late for our flight", "C": "with no time at all", "D": "on a different flight"},
     "A", "hard", 23, "Exercise 2: Formal equivalents",
     ["Email B says 'just in time to catch our flight' instead of 'by the skin of our teeth'."],
     "just in time to catch our flight", "'By the skin of our teeth' is informal."),

    ("Why do we use the passive voice in a formal email of complaint?",
     {"A": "to be less direct and more formal", "B": "to make the email shorter", "C": "to sound angry", "D": "to hide the facts"},
     "A", "easy", 23, "Writing box: An email of complaint",
     ["The Writing box says passives are used 'to be less direct and more formal'."],
     "Passives are less direct.", "Example: 'We were only informed of the timetable change...'"),

    ("Which example uses a clause of concession?",
     {"A": "Although your company had been recommended to us, the service did not meet our expectations.", "B": "The coach was late.", "C": "We booked the coach at 8.15.", "D": "We caught our flight."},
     "A", "medium", 23, "Writing box: Clauses of concession",
     ["'Although...' is a clause of concession, used to give balance."],
     "Although... gives balance.", "It concedes a point before complaining."),

    ("Which adverb is described as an 'initial comment adverb' in the Writing box?",
     {"A": "ultimately", "B": "quickly", "C": "never", "D": "always"},
     "A", "medium", 23, "Writing box: Initial comment adverbs",
     ["The box lists realistically and ultimately as initial comment adverbs."],
     "ultimately", "It comments on the whole sentence."),

    ("Complete: '______, the fault lies with the supplier.'",
     {"A": "Ultimately", "B": "Luckily", "C": "Happily", "D": "Suddenly"},
     "A", "easy", 23, "Writing box: Initial comment adverbs",
     ["The example is 'Ultimately, the fault lies with the supplier'."],
     "Ultimately", "It gives the final judgement."),

    ("Complete the collocation: 'deeply ______'.",
     {"A": "disappointed", "B": "improved", "C": "inexcusable", "D": "mistaken"},
     "A", "easy", 23, "Exercise 4: Adverb-adjective collocations",
     ["Email B uses 'deeply disappointed'."],
     "deeply disappointed", "We were deeply disappointed with the service."),

    ("Complete the collocation: 'drastically ______'.",
     {"A": "improved", "B": "disappointed", "C": "flawed", "D": "overrated"},
     "A", "easy", 23, "Exercise 4: Adverb-adjective collocations",
     ["Email B says the service 'will be drastically improved'."],
     "drastically improved", "It means greatly improved."),

    ("Complete the collocation: 'completely ______'.",
     {"A": "inexcusable", "B": "improved", "C": "disappointed", "D": "mistaken"},
     "A", "easy", 23, "Exercise 4: Adverb-adjective collocations",
     ["Email B says 'what was, in my view, completely inexcusable'."],
     "completely inexcusable", "It means unforgivable."),

    ("How late was the coach in email B?",
     {"A": "in excess of 30 minutes", "B": "exactly 5 minutes", "C": "two hours", "D": "on time"},
     "A", "easy", 22, "Model email B",
     ["The coach failed to arrive on time and was in excess of 30 minutes late."],
     "More than 30 minutes late", "The driver went to a different pick-up point."),

    ("Why was the coach late according to the driver?",
     {"A": "he had first gone to a completely different pick-up point", "B": "the traffic was terrible", "C": "the coach had a flat tyre", "D": "he overslept"},
     "A", "medium", 22, "Model email B",
     ["Email B says the driver admitted to having gone to a completely different pick-up point."],
     "He went to the wrong place.", "This was the first problem."),

    ("What was the second issue with the coach?",
     {"A": "the heating system was faulty", "B": "the seats were broken", "C": "the windows were open", "D": "the radio was too loud"},
     "A", "medium", 22, "Model email B",
     ["The coach's heating system was faulty and did not work properly."],
     "The heating was faulty.", "It was a particularly cold morning."),

    ("What happened on the motorway?",
     {"A": "the coach broke down because of an engine problem", "B": "the coach ran out of petrol", "C": "there was an accident", "D": "the coach turned back"},
     "A", "easy", 22, "Model email B",
     ["The coach suffered an engine problem and broke down on the motorway."],
     "The coach broke down.", "A replacement coach was arranged."),

    ("What did Malek ask for in his email?",
     {"A": "monetary compensation", "B": "a new coach", "C": "a free holiday", "D": "a written apology only"},
     "A", "medium", 22, "Model email B",
     ["Malek believes they should receive monetary compensation for the inconvenience."],
     "He asked for compensation.", "He also hopes the service will improve."),

    ("Complete the collocation: 'gravely ______'.",
     {"A": "mistaken", "B": "obvious", "C": "opposed", "D": "overrated"},
     "A", "medium", 23, "Exercise 5: Collocations",
     ["The collocation is 'gravely mistaken'."],
     "gravely mistaken", "If you think I won't take this further, you are gravely mistaken."),

    ("Complete the collocation: 'wildly ______' (about information).",
     {"A": "inaccurate", "B": "improved", "C": "overrated", "D": "flawed"},
     "A", "medium", 23, "Exercise 5: Collocations",
     ["The collocation is 'wildly inaccurate'."],
     "wildly inaccurate", "The information was wildly inaccurate, causing me to miss my plane."),

    ("Complete the collocation: 'fundamentally ______' (about a process).",
     {"A": "flawed", "B": "mistaken", "C": "justified", "D": "obvious"},
     "A", "medium", 23, "Exercise 5: Collocations",
     ["The collocation is 'fundamentally flawed'."],
     "fundamentally flawed", "The delivery process was fundamentally flawed."),

    ("Complete the collocation: 'vastly ______' (about quality).",
     {"A": "overrated", "B": "inaccurate", "C": "obvious", "D": "opposed"},
     "A", "medium", 23, "Exercise 5: Collocations",
     ["The collocation is 'vastly overrated'."],
     "vastly overrated", "The shoes were vastly overrated; they needed repairs after a month."),

    ("Complete the collocation: 'vehemently ______ to'.",
     {"A": "opposed", "B": "mistaken", "C": "justified", "D": "inaccurate"},
     "A", "medium", 23, "Exercise 5: Collocations",
     ["The collocation is 'vehemently opposed to'."],
     "vehemently opposed", "I am vehemently opposed to travelling with your company again."),

    ("Complete the collocation: 'wholly ______' (about the way you were treated).",
     {"A": "unjustified", "B": "overrated", "C": "improved", "D": "inaccurate"},
     "A", "medium", 23, "Exercise 5: Collocations",
     ["The collocation is 'wholly unjustified'."],
     "wholly unjustified", "The way I was treated was wholly unjustified."),

    ("Complete the collocation: 'blindingly ______' (about a problem).",
     {"A": "obvious", "B": "mistaken", "C": "opposed", "D": "flawed"},
     "A", "medium", 23, "Exercise 5: Collocations",
     ["The collocation is 'blindingly obvious'."],
     "blindingly obvious", "It is blindingly obvious that there is a serious issue."),

    ("What is the main difference between emails A and B?",
     {"A": "A is informal (to a friend) and B is formal (to the company)", "B": "A is longer than B", "C": "A is about a flight and B is about a hotel", "D": "A is formal and B is informal"},
     "A", "easy", 22, "Exercise 1: Comparing emails",
     ["Email A uses informal language for a friend, while email B is formal to the company."],
     "A = informal, B = formal.", "The register changes with the reader."),

    ("Which informal phrase in email A means 'it started badly'?",
     {"A": "it didn't get off to a great start", "B": "it was plain sailing", "C": "it went downhill", "D": "it was in excess of time"},
     "A", "medium", 22, "Model email A",
     ["'Get off to a bad/great start' means to begin badly or well."],
     "didn't get off to a great start = began badly.", "The coach was half an hour late from the start."),

    ("What does 'down it came! In buckets!' mean in email A?",
     {"A": "it rained very heavily", "B": "the rain stopped", "C": "the coach arrived", "D": "the sky cleared"},
     "A", "hard", 22, "Model email A",
     ["'Rain in buckets' or 'bucket down' means to rain very heavily."],
     "It rained heavily.", "They got soaked while waiting for the coach."),

    ("What does 'we caught the plane by the skin of our teeth' mean?",
     {"A": "we only just caught it, at the last moment", "B": "we missed the plane", "C": "we caught a different plane", "D": "we caught it easily"},
     "A", "medium", 22, "Model email A",
     ["'By the skin of our teeth' means by a very small margin, barely."],
     "They only just caught the plane.", "Email B says the same idea formally: 'just in time'."),

    ("Why does the Writing box say to 'remain polite and be assertive but not aggressive'?",
     {"A": "a firm but polite tone is more effective in a complaint", "B": "you should shout to be heard", "C": "you should never complain", "D": "aggression wins arguments"},
     "A", "medium", 23, "Writing box: An email of complaint",
     ["A good complaint is assertive but polite, so the reader takes it seriously."],
     "Polite but assertive is best.", "It keeps the email effective and professional."),

    ("Complete: 'I would like to express in the strongest terms, how deeply ______ we were with your company's service.'",
     {"A": "disappointed", "B": "improved", "C": "mistaken", "D": "opposed"},
     "A", "medium", 22, "Model email B",
     ["Email B says 'how deeply disappointed we were'."],
     "disappointed", "'Deeply' collocates with 'disappointed'."),

    ("Which sentence uses the passive voice?",
     {"A": "We were only informed of the timetable change at the last minute.", "B": "The company informed us at the last minute.", "C": "We received information at the last minute.", "D": "Someone told us at the last minute."},
     "A", "hard", 23, "Writing box: Passives",
     ["'We were only informed' is passive; the agent is not emphasised."],
     "We were informed = passive.", "It is less direct and more formal."),

    ("Which phrase from email A is informal?",
     {"A": "guess what", "B": "in excess of", "C": "we were extremely fortunate", "D": "to our utter disbelief"},
     "A", "easy", 22, "Exercise 1: Comparing emails",
     ["'Guess what' is informal and typical of a message to a friend."],
     "guess what", "Email B uses formal equivalents like 'in excess of'."),

    ("What should a good email of complaint include at the end?",
     {"A": "a clear statement of what you want (e.g. compensation)", "B": "a joke", "C": "a threat", "D": "a new topic"},
     "A", "easy", 23, "Writing task",
     ["Malek ends by requesting monetary compensation."],
     "State what you want.", "It makes the complaint effective."),
]
