# Unit 2 Lesson 1 (Vocabulary and Speaking: On the move, pages 14-15)
ITEMS = [
    ("Which verb of movement means 'walked with difficulty because of an injury'?",
     {"A": "hobbled", "B": "strode", "C": "surged", "D": "wobbled"},
     "A", "easy", 14, "Exercise 2: Verbs of movement",
     ["'Hobbled' means walking with difficulty, for example because of an injured ankle."],
     "hobbled = walked with difficulty.", "After hurting his ankle, the footballer hobbled off the pitch."),

    ("Which verb of movement means 'walked slowly without lifting your feet'?",
     {"A": "shuffled", "B": "strode", "C": "surged", "D": "staggered"},
     "A", "easy", 14, "Exercise 2: Verbs of movement",
     ["'Shuffled' means walking slowly, sliding your feet along the ground."],
     "shuffled = walked slowly, dragging feet.", "Half asleep, she shuffled out of her bedroom."),

    ("Which verb of movement means 'walked unsteadily, as if about to fall'?",
     {"A": "staggered", "B": "strode", "C": "shuffled", "D": "surged"},
     "A", "easy", 14, "Exercise 2: Verbs of movement",
     ["'Staggered' means walking in an unsteady way, for example because of carrying something heavy."],
     "staggered = walked unsteadily.", "They staggered across the room with the heavy sofa."),

    ("Which verb means 'suddenly moved forward in an unsteady way'?",
     {"A": "lurched", "B": "strode", "C": "hobbled", "D": "shuffled"},
     "A", "medium", 14, "Exercise 2: Verbs of movement",
     ["'Lurched' means moved suddenly and unsteadily."],
     "lurched = moved suddenly and unsteadily.", "The train lurched forward as it left the station."),

    ("Which verb of movement means 'walked with long, confident steps'?",
     {"A": "strode", "B": "wobbled", "C": "shuffled", "D": "hobbled"},
     "A", "easy", 14, "Exercise 2: Verbs of movement",
     ["'Strode' means walking with long, confident steps."],
     "strode = walked confidently.", "The angry father strode up to the manager and demanded an explanation."),

    ("Which verb means 'moved unsteadily from side to side'?",
     {"A": "wobbled", "B": "strode", "C": "surged", "D": "lurched"},
     "A", "medium", 14, "Exercise 2: Verbs of movement",
     ["'Wobbled' means moving unsteadily from side to side, like someone balancing a tray."],
     "wobbled = moved unsteadily side to side.", "Mariam wobbled into the room, terrified of dropping the tray."),

    ("Which verb means 'moved forward suddenly in a large group'?",
     {"A": "surged", "B": "strode", "C": "shuffled", "D": "wobbled"},
     "A", "easy", 14, "Exercise 2: Verbs of movement",
     ["'Surged' describes a crowd moving forward suddenly."],
     "surged = moved forward suddenly (crowd).", "The workers surged out of the office after the fire alarm went off."),

    ("Complete: 'After hurting his ankle, the footballer ______ off the pitch to get some help.'",
     {"A": "hobbled", "B": "strode", "C": "surged", "D": "staggered"},
     "A", "easy", 14, "Exercise 2: Verbs of movement",
     ["An injured person walks with difficulty, so the correct verb is 'hobbled'."],
     "hobbled", "He walked painfully because of his injured ankle."),

    ("Complete: 'My brother and I lifted up the sofa with some difficulty and ______ across the room with it.'",
     {"A": "staggered", "B": "strode", "C": "surged", "D": "wobbled"},
     "A", "medium", 14, "Exercise 2: Verbs of movement",
     ["Carrying something much heavier than expected makes you walk unsteadily, so: staggered."],
     "staggered", "The sofa was far heavier than they expected."),

    ("Complete: 'While still half asleep, she ______ out of her bedroom and asked me where I had been.'",
     {"A": "shuffled", "B": "strode", "C": "surged", "D": "lurched"},
     "A", "medium", 14, "Exercise 2: Verbs of movement",
     ["A sleepy person drags their feet, so the verb is 'shuffled'."],
     "shuffled", "She was half asleep and walked slowly."),

    ("Complete: 'Angry at having to wait so long, my father ______ up to the manager and demanded an explanation.'",
     {"A": "strode", "B": "shuffled", "C": "hobbled", "D": "wobbled"},
     "A", "medium", 14, "Exercise 2: Verbs of movement",
     ["An angry, confident walk uses 'strode'."],
     "strode", "He walked with long, confident, angry steps."),

    ("Complete: 'Mariam ______ into the room with a tray of tea and cake, terrified of dropping it.'",
     {"A": "wobbled", "B": "strode", "C": "surged", "D": "marched"},
     "A", "medium", 14, "Exercise 2: Verbs of movement",
     ["Trying not to spill something makes you move unsteadily, so: wobbled."],
     "wobbled", "She was terrified of dropping the tray on the carpet."),

    ("Complete: 'Shortly after the fire alarm went off, the workers ______ out of the office looking very worried.'",
     {"A": "surged", "B": "strode", "C": "shuffled", "D": "lurched"},
     "A", "medium", 14, "Exercise 2: Verbs of movement",
     ["A crowd leaving quickly in alarm uses 'surged'."],
     "surged", "The whole workforce moved out suddenly."),

    ("What does the idiom 'drive someone up the wall' mean?",
     {"A": "make someone very annoyed", "B": "give someone a lift", "C": "make someone run fast", "D": "help someone move house"},
     "A", "easy", 15, "Exercise 3: Idioms related to movement",
     ["The roadworks are driving motorists up the wall = making them very annoyed."],
     "drive someone up the wall = annoy greatly.", "The roadworks are driving motorists up the wall."),

    ("Complete: 'The roadworks are driving motorists up the ______.'",
     {"A": "wall", "B": "road", "C": "hill", "D": "corner"},
     "A", "easy", 15, "Exercise 3: Idioms related to movement",
     ["The idiom is 'drive someone up the wall'."],
     "up the wall", "It means to make someone very annoyed."),

    ("What does the idiom 'steer clear of' mean?",
     {"A": "avoid", "B": "drive along", "C": "explore", "D": "pass by quickly"},
     "A", "easy", 15, "Exercise 3: Idioms related to movement",
     ["You'd better steer clear of the main junction = you should avoid it."],
     "steer clear of = avoid.", "Avoid the main junction for at least a week."),

    ("Complete: 'You'd better ______ clear of the main junction for at least a week.'",
     {"A": "steer", "B": "drive", "C": "run", "D": "sail"},
     "A", "easy", 15, "Exercise 3: Idioms related to movement",
     ["The idiom is 'steer clear of', meaning avoid."],
     "steer", "The main junction is best avoided."),

    ("What does the idiom 'plain sailing' mean?",
     {"A": "easy and without problems", "B": "slow and boring", "C": "dangerous and risky", "D": "very expensive"},
     "A", "easy", 15, "Exercise 3: Idioms related to movement",
     ["It wasn't all plain sailing = it wasn't always easy."],
     "plain sailing = easy, without problems.", "He encountered obstacles; it wasn't all plain sailing."),

    ("Complete: 'He encountered some obstacles while training to become a pilot. It wasn't all ______ sailing.'",
     {"A": "plain", "B": "clear", "C": "straight", "D": "fast"},
     "A", "medium", 15, "Exercise 3: Idioms related to movement",
     ["The idiom is 'plain sailing'."],
     "plain sailing", "It means easy and trouble-free."),

    ("What does the idiom 'the driving force behind' mean?",
     {"A": "the main person or thing that makes something happen", "B": "the engine of a car", "C": "the driver of a bus", "D": "a strong wind"},
     "A", "easy", 15, "Exercise 3: Idioms related to movement",
     ["Suha was the driving force behind the project = the main reason it succeeded."],
     "the driving force = the main motivation.", "Suha's commitment made the project successful."),

    ("Complete: 'She was the ______ force behind the new rail project.'",
     {"A": "driving", "B": "pushing", "C": "pulling", "D": "running"},
     "A", "easy", 15, "Exercise 3: Idioms related to movement",
     ["The idiom is 'the driving force behind something'."],
     "driving force", "She was the reason the project succeeded."),

    ("What does the idiom 'going downhill' mean?",
     {"A": "getting worse", "B": "getting better", "C": "going too fast", "D": "going on holiday"},
     "A", "easy", 15, "Exercise 3: Idioms related to movement",
     ["The airline's reputation has been going downhill = getting worse."],
     "going downhill = getting worse.", "The airline's reputation is declining."),

    ("What does the idiom 'to be in the same boat' mean?",
     {"A": "to be in the same difficult situation", "B": "to go sailing together", "C": "to work on a ship", "D": "to have the same opinion"},
     "A", "medium", 15, "Exercise 3: Idioms related to movement",
     ["Everyone is furious about the parking fees; we're all in the same boat = we share the same problem."],
     "in the same boat = in the same situation.", "They all have no other option."),

    ("What does the idiom 'to be taken for a ride' mean?",
     {"A": "to be deceived or tricked", "B": "to enjoy a car trip", "C": "to go on a rollercoaster", "D": "to be given a lift"},
     "A", "medium", 15, "Exercise 3: Idioms related to movement",
     ["'No one likes to be taken for a ride' means no one likes to be tricked, for example over fees."],
     "taken for a ride = deceived.", "The people do not want to be tricked about the fees."),

    ("Complete: 'Everyone's furious about the increase in car parking fees. We're all in the same ______ – we have no other option.'",
     {"A": "boat", "B": "car", "C": "bus", "D": "train"},
     "A", "easy", 15, "Exercise 3: Idioms related to movement",
     ["The idiom is 'in the same boat'."],
     "boat", "They share the same situation."),

    ("According to the Active Vocabulary box, an idiom such as 'completely at sea' with a computer system means ...",
     {"A": "totally confused", "B": "on a boat", "C": "very relaxed", "D": "working at sea"},
     "A", "medium", 15, "Active Vocabulary: Idioms",
     ["The example says 'completely at sea' means totally confused or not sure what to do."],
     "completely at sea = totally confused.", "It is a figurative meaning."),

    ("Which statement about idioms is TRUE according to the Active Vocabulary box?",
     {"A": "they are used mainly in informal or colloquial language", "B": "they must always be used in formal essays", "C": "you can change the words in an idiom", "D": "you should use as many idioms as possible"},
     "A", "medium", 15, "Active Vocabulary: Idioms",
     ["The box says idioms are used mainly in informal or colloquial language."],
     "Idioms are informal.", "It is important not to change any word in an idiom."),

    ("What is the LITERAL meaning of the verb 'fly'?",
     {"A": "to move through the air", "B": "to move quickly and suddenly", "C": "to escape", "D": "to disappear"},
     "A", "easy", 15, "Watch Out!: literal and figurative meanings",
     ["Literally, to fly is to move through the air, like a bird."],
     "fly = move through the air.", "This is the literal meaning."),

    ("What is the FIGURATIVE meaning of the verb 'fly'?",
     {"A": "to move quickly and suddenly", "B": "to travel by plane", "C": "to sing like a bird", "D": "to fly a kite"},
     "A", "medium", 15, "Watch Out!: literal and figurative meanings",
     ["Figuratively, to fly means to move quickly and suddenly, e.g. 'I flew down the platform'."],
     "fly = move quickly and suddenly.", "I saw an opening in the crowd and flew down the platform."),

    ("What does 'sailed through her interview' mean?",
     {"A": "succeeded easily", "B": "failed the interview", "C": "arrived late", "D": "gave up"},
     "A", "medium", 15, "Exercise 4: Travel verbs",
     ["'Sail through' means to succeed at something easily."],
     "sailed through = succeeded easily.", "Reem sailed through her interview to become a tour guide."),

    ("What does 'drives himself too hard' mean?",
     {"A": "he works too much and pushes himself too far", "B": "he drives his car badly", "C": "he works very slowly", "D": "he refuses to work"},
     "A", "medium", 15, "Exercise 4: Travel verbs",
     ["'Drive yourself too hard' means to push yourself to work too much."],
     "drives himself too hard = overworks.", "He'll be ill if he's not careful."),

    ("What does 'stumbled over some of the words' mean while reading a speech?",
     {"A": "made mistakes or hesitated on the words", "B": "read every word perfectly", "C": "shouted the words", "D": "forgot the whole speech"},
     "A", "medium", 15, "Exercise 4: Travel verbs",
     ["'Stumble over words' means to make mistakes or hesitate while speaking or reading."],
     "stumbled over = made mistakes on.", "He was so stressed that he made mistakes."),

    ("What does 'we were staggered by the amount of work' mean?",
     {"A": "we were amazed or shocked", "B": "we were walking unsteadily", "C": "we were bored", "D": "we were confused"},
     "A", "hard", 15, "Exercise 4: Travel verbs",
     ["'Be staggered by' means to be amazed or shocked by something."],
     "staggered by = amazed/shocked.", "Here 'staggered' has a figurative meaning."),

    ("What does 'I flew down the road to catch the bus' mean?",
     {"A": "I moved very quickly", "B": "I walked slowly", "C": "I jumped over the road", "D": "I travelled by plane"},
     "A", "medium", 15, "Exercise 4: Travel verbs",
     ["'Fly' here means to move quickly and suddenly."],
     "flew down the road = went very quickly.", "He was late, so he ran quickly to catch the bus."),

    ("What does 'let's just park that idea for now' mean?",
     {"A": "let's leave that idea aside for now", "B": "let's write the idea down", "C": "let's reject the idea forever", "D": "let's drive to the idea"},
     "A", "hard", 15, "Exercise 4: Travel verbs",
     ["'Park an idea' means to leave it aside and come back to it later."],
     "park an idea = set it aside.", "They cannot agree now, so they will return to it later."),

    ("What does 'he jumped the lights' mean?",
     {"A": "he drove through red traffic lights", "B": "he crossed the road at a crossing", "C": "he repaired the traffic lights", "D": "he waited at the lights"},
     "A", "hard", 15, "Exercise 4: Travel verbs",
     ["'Jump the lights' means to drive through red traffic lights."],
     "jumped the lights = drove through red lights.", "He was in such a hurry that he nearly crashed."),

    ("What does 'he backpedalled very quickly' mean?",
     {"A": "he quickly changed his opinion", "B": "he cycled backwards", "C": "he walked backwards slowly", "D": "he apologised for cycling"},
     "A", "hard", 15, "Exercise 4: Travel verbs",
     ["'Backpedal' here means to quickly change an opinion or decision."],
     "backpedalled = quickly changed his mind.", "He changed his attitude when he realised they were police officers."),

    ("Why should you NOT overuse idioms?",
     {"A": "because it can sound unnatural", "B": "because idioms are too long", "C": "because idioms are always rude", "D": "because idioms are old-fashioned"},
     "A", "medium", 15, "Active Vocabulary: Idioms",
     ["The box says 'It is better not to overuse idioms, as this can sound unnatural.'"],
     "Overuse sounds unnatural.", "Use idioms in the right places."),

    ("What happens if you change a word in an idiom?",
     {"A": "the meaning is lost", "B": "the idiom becomes more formal", "C": "the idiom becomes easier", "D": "the idiom becomes longer"},
     "A", "easy", 15, "Active Vocabulary: Idioms",
     ["The box says 'It is important not to change any word in an idiom or the meaning is lost.'"],
     "The meaning is lost.", "Idioms must keep all their words."),

    ("In 'I saw an opening in the crowd and flew down the platform', 'flew' is used ...",
     {"A": "figuratively, meaning moved quickly and suddenly", "B": "literally, meaning flew like a bird", "C": "to describe a plane", "D": "to describe a dream"},
     "A", "medium", 15, "Watch Out!: literal and figurative meanings",
     ["Here 'flew' has its figurative meaning: to move quickly and suddenly."],
     "flew = moved quickly (figurative).", "He is not flying like a bird; he is moving fast."),
]
