# Unit 4 L1 - Vocabulary and Speaking (pages 38-39)
# Food vocabulary, expressing preferences, like/dislike phrases
ITEMS = [
    ("Which word means 'a sweet fruit with a hard stone inside'?",
     {"A": "peach", "B": "pepper", "C": "pear", "D": "pea"},
     "A", "easy", 38, "L1",
     ["A peach is a soft, sweet fruit with a large stone in the centre."],
     "peach = a soft sweet fruit.", "Peaches grow on trees in warm climates."),

    ("Which word means 'a long green vegetable often used in salads'?",
     {"A": "cucumber", "B": "courgette", "C": "carrot", "D": "celery"},
     "A", "easy", 38, "L1",
     ["A cucumber is a long, green vegetable with a watery taste, often used in salads."],
     "cucumber = a green salad vegetable.", "Cucumbers are often served cold."),

    ("Which word means 'a bright orange vegetable rich in vitamin A'?",
     {"A": "carrot", "B": "cauliflower", "C": "cabbage", "D": "celery"},
     "A", "easy", 38, "L1",
     ["A carrot is an orange root vegetable that is good for your eyes."],
     "carrot = an orange root vegetable.", "Carrots are rich in vitamin A."),

    ("Which word means 'a vegetable with large green leaves used in salads'?",
     {"A": "lettuce", "B": "leek", "C": "lentil", "D": "lime"},
     "A", "easy", 38, "L1",
     ["Lettuce is a leafy green vegetable commonly used in salads and sandwiches."],
     "lettuce = a leafy green vegetable.", "Lettuce is crunchy and fresh."),

    ("Which word means 'a yellow fruit that monkeys love'?",
     {"A": "banana", "B": "berry", "C": "melon", "D": "mango"},
     "A", "easy", 38, "L1",
     ["A banana is a long curved yellow fruit with a soft inside."],
     "banana = a long yellow fruit.", "Bananas are rich in potassium."),

    ("Which word means 'a large round fruit with thick red or green skin'?",
     {"A": "watermelon", "B": "grapefruit", "C": "pomegranate", "D": "papaya"},
     "A", "medium", 38, "L1",
     ["A watermelon is a very large fruit with green skin, red flesh, and black seeds."],
     "watermelon = a large green fruit.", "Watermelons are mostly water."),

    ("Which word means 'a small round red or green fruit used in salads and cooking'?",
     {"A": "tomato", "B": "turnip", "C": "tangerine", "D": "tofu"},
     "A", "easy", 38, "L1",
     ["A tomato is a soft, round, red fruit used in cooking and salads."],
     "tomato = a red fruit used as a vegetable.", "Tomatoes are used in sauces and salads."),

    ("Which word means 'a small green vegetable with a round shape'?",
     {"A": "pea", "B": "pear", "C": "peach", "D": "prawn"},
     "A", "easy", 38, "L1",
     ["A pea is a small, round, green seed that grows in a pod."],
     "pea = a small green seed.", "Peas are often served with fish and chips."),

    ("What does 'crispy' mean when describing food?",
     {"A": "hard and crunchy", "B": "soft and smooth", "C": "sweet and sour", "D": "hot and spicy"},
     "A", "easy", 38, "L1",
     ["'Crispy' describes food that is firm, dry and crunches when you bite it."],
     "crispy = crunchy.", "Crispy fried chicken is very popular."),

    ("What does 'bitter' mean when describing taste?",
     {"A": "an unpleasant sharp taste like strong coffee", "B": "very sweet", "C": "salty", "D": "sour"},
     "A", "easy", 38, "L1",
     ["'Bitter' describes a strong, sharp, unpleasant taste like black coffee."],
     "bitter = sharp unpleasant taste.", "Dark chocolate can taste bitter."),

    ("What does 'sour' mean when describing taste?",
     {"A": "a sharp acidic taste like lemon", "B": "very sweet", "C": "salty", "D": "bitter"},
     "A", "easy", 38, "L1",
     ["'Sour' describes a sharp, acidic taste like lemon juice or vinegar."],
     "sour = acidic taste.", "Lemons and limes are sour fruits."),

    ("What does 'tasty' mean?",
     {"A": "having a pleasant flavour", "B": "having no taste", "C": "very salty", "D": "very spicy"},
     "A", "easy", 38, "L1",
     ["'Tasty' means having a good, pleasant flavour."],
     "tasty = delicious.", "The pizza was very tasty."),

    ("What does 'bland' mean when describing food?",
     {"A": "having very little flavour", "B": "very spicy", "C": "very sweet", "D": "very salty"},
     "A", "medium", 38, "L1",
     ["'Bland' describes food that has very little flavour or taste."],
     "bland = tasteless.", "Boiled chicken can be quite bland."),

    ("What does 'spicy' mean when describing food?",
     {"A": "containing strong flavours from herbs and spices", "B": "very sweet", "C": "very cold", "D": "very bland"},
     "A", "easy", 38, "L1",
     ["'Spicy' describes food seasoned with strong-tasting herbs, chilli or spices."],
     "spicy = strongly seasoned.", "Indian food is often spicy."),

    ("What does 'crunchy' mean when describing food?",
     {"A": "making a loud noise when chewed because it is hard", "B": "very soft", "C": "very smooth", "D": "very liquid"},
     "A", "easy", 38, "L1",
     ["'Crunchy' describes food that makes a noise when you chew it because it is firm."],
     "crunchy = crispy.", "Carrots and apples are crunchy."),

    ("What does 'creamy' mean when describing food?",
     {"A": "smooth and thick like cream", "B": "very hard", "C": "very spicy", "D": "very sour"},
     "A", "easy", 38, "L1",
     ["'Creamy' describes food that is smooth, soft and thick like cream."],
     "creamy = smooth like cream.", "The soup was thick and creamy."),

    ("What does 'delicious' mean?",
     {"A": "extremely pleasant to taste", "B": "terrible", "C": "bland", "D": "bitter"},
     "A", "easy", 38, "L1",
     ["'Delicious' means extremely pleasant to taste, very enjoyable to eat."],
     "delicious = very tasty.", "The meal was absolutely delicious."),

    ("What does 'yummy' mean?",
     {"A": "very tasty (informal)", "B": "very boring", "C": "very salty", "D": "very hot"},
     "A", "easy", 38, "L1",
     ["'Yummy' is an informal word meaning very tasty or delicious."],
     "yummy = delicious (informal).", "Kids often say food is yummy."),

    ("What does 'to be fond of' mean when talking about food?",
     {"A": "to like food very much", "B": "to hate food", "C": "to cook food", "D": "to buy food"},
     "A", "medium", 38, "L1",
     ["'Be fond of' means to like something very much."],
     "be fond of = like very much.", "I am fond of Italian food."),

    ("What does 'to have a sweet tooth' mean?",
     {"A": "to enjoy sweet food very much", "B": "to have a toothache", "C": "to brush your teeth", "D": "to eat healthily"},
     "A", "medium", 38, "L1",
     ["'Have a sweet tooth' means you love eating sweet things like chocolate and cakes."],
     "have a sweet tooth = love sweets.", "My sister has a sweet tooth."),

    ("What does 'to be vegetarian' mean?",
     {"A": "to not eat meat or fish", "B": "to not eat vegetables", "C": "to only eat fruit", "D": "to not eat at all"},
     "A", "easy", 38, "L1",
     ["A vegetarian is someone who does not eat meat or fish."],
     "vegetarian = no meat or fish.", "Many people choose to be vegetarian."),

    ("What does 'organic' mean when describing food?",
     {"A": "grown without using chemicals", "B": "very expensive", "C": "very sweet", "D": "very spicy"},
     "A", "medium", 38, "L1",
     ["'Organic' food is grown without artificial chemicals or pesticides."],
     "organic = natural, chemical-free.", "Organic vegetables are healthier."),

    ("What does 'junk food' mean?",
     {"A": "unhealthy food with lots of fat, sugar or salt", "B": "recycled food", "C": "very expensive food", "D": "home-cooked food"},
     "A", "easy", 38, "L1",
     ["'Junk food' is food that is unhealthy, containing too much fat, sugar or salt."],
     "junk food = unhealthy food.", "Burgers and chips are examples of junk food."),

    ("What does 'to be on a diet' mean?",
     {"A": "to eat less food to lose weight", "B": "to eat more food", "C": "to skip meals", "D": "to only eat junk food"},
     "A", "medium", 38, "L1",
     ["Being on a diet means eating less or differently to lose weight."],
     "on a diet = restricting food intake.", "She is on a diet so she eats less sugar."),

    ("What does 'a foodie' mean?",
     {"A": "a person who is very interested in food and cooking", "B": "a person who does not eat", "C": "a person who works in a restaurant", "D": "a person who hates food"},
     "A", "medium", 38, "L1",
     ["A foodie is someone who has a great interest in food and enjoys trying different dishes."],
     "foodie = food enthusiast.", "My dad is a real foodie."),

    ("What does 'to eat out' mean?",
     {"A": "to eat at a restaurant instead of at home", "B": "to eat outside in the garden", "C": "to eat on the floor", "D": "to eat at a friend's house"},
     "A", "easy", 38, "L1",
     ["'Eat out' means to go to a restaurant to eat instead of eating at home."],
     "eat out = dine at a restaurant.", "We usually eat out on Fridays."),

    ("Which phrase means 'I like very much'?",
     {"A": "I'm really into", "B": "I'm fed up with", "C": "I'm tired of", "D": "I'm sick of"},
     "A", "medium", 38, "L1",
     ["'I'm really into' means I really like and enjoy something."],
     "I'm really into = I like very much.", "I'm really into sushi."),

    ("Which phrase means 'I don't like'?",
     {"A": "I can't stand", "B": "I'm into", "C": "I'm fond of", "D": "I'm keen on"},
     "A", "easy", 38, "L1",
     ["'I can't stand' means I strongly dislike something."],
     "can't stand = hate.", "I can't stand broccoli."),

    ("Which phrase means 'I don't mind'?",
     {"A": "I don't care either way", "B": "I love it", "C": "I hate it", "D": "I prefer it"},
     "A", "easy", 38, "L1",
     ["'I don't mind' means it doesn't bother you either way, you are OK with it."],
     "don't mind = no strong feeling.", "I don't mind what we eat for dinner."),

    ("Which phrase means 'I prefer one thing over another'?",
     {"A": "I'd rather have", "B": "I'm sick of", "C": "I'm bored with", "D": "I've had enough of"},
     "A", "medium", 38, "L1",
     ["'I'd rather have' means you would prefer one choice over another."],
     "I'd rather have = I prefer.", "I'd rather have salad than chips."),

    ("What does 'to be allergic to' something mean?",
     {"A": "to have a bad reaction when you eat or touch something", "B": "to love eating something", "C": "to be afraid of food", "D": "to not be hungry"},
     "A", "easy", 38, "L1",
     ["Being 'allergic to' something means your body reacts badly when you eat or touch it."],
     "allergic to = body reacts badly.", "I am allergic to peanuts."),

    ("What does 'gluten-free' mean?",
     {"A": "food that does not contain gluten", "B": "food with lots of sugar", "C": "food that is very spicy", "D": "food that is very salty"},
     "A", "medium", 38, "L1",
     ["'Gluten-free' food does not contain gluten, a protein found in wheat."],
     "gluten-free = no gluten.", "Some people must eat gluten-free food."),

    ("What does 'lactose-free' mean?",
     {"A": "food that does not contain lactose (milk sugar)", "B": "food with lots of milk", "C": "food made from plants", "D": "food that is very sweet"},
     "A", "medium", 38, "L1",
     ["'Lactose-free' food does not contain lactose, the sugar found in milk."],
     "lactose-free = no milk sugar.", "Lactose-free milk is made for people who cannot drink regular milk."),

    ("What does 'processed food' mean?",
     {"A": "food that has been changed from its natural state by adding chemicals", "B": "fresh fruit", "C": "home-cooked meals", "D": "organic vegetables"},
     "A", "medium", 38, "L1",
     ["Processed food has been changed from its natural state, often by adding salt, sugar or preservatives."],
     "processed food = man-made food.", "Processed food is often less healthy."),

    ("What does 'home-made' mean?",
     {"A": "food cooked at home", "B": "food bought from a shop", "C": "food from another country", "D": "food that is frozen"},
     "A", "easy", 38, "L1",
     ["'Home-made' means food that is prepared and cooked at home, not bought from a shop."],
     "home-made = cooked at home.", "Home-made cakes taste better than shop ones."),

    ("What does 'a balanced diet' mean?",
     {"A": "eating the right amounts of different types of food", "B": "only eating vegetables", "C": "eating a lot of sugar", "D": "not eating breakfast"},
     "A", "easy", 38, "L1",
     ["A balanced diet means eating a variety of foods in the right proportions for good health."],
     "balanced diet = healthy mix of foods.", "A balanced diet includes fruit, vegetables, protein and carbohydrates."),

    ("What does 'portion size' mean?",
     {"A": "the amount of food served at one time", "B": "the price of food", "C": "the taste of food", "D": "the colour of food"},
     "A", "medium", 38, "L1",
     ["Portion size is the amount of food that is served or eaten at one time."],
     "portion size = amount served.", "Large portion sizes can lead to overeating."),

    ("What does 'to recipe' mean?",
     {"A": "a set of instructions for cooking a dish", "B": "a type of food", "C": "a kitchen tool", "D": "a restaurant"},
     "A", "easy", 38, "L1",
     ["A recipe is a set of instructions that tells you how to prepare and cook a particular dish."],
     "recipe = cooking instructions.", "I followed the recipe to make a cake."),

    ("What does 'an ingredient' mean?",
     {"A": "something used to make a dish", "B": "a cooking tool", "C": "a finished meal", "D": "a recipe book"},
     "A", "easy", 38, "L1",
     ["An ingredient is a food item used to make a particular dish."],
     "ingredient = food item in a recipe.", "Flour, sugar and eggs are ingredients for a cake."),

    ("What does 'to season' food mean?",
     {"A": "to add salt, pepper or spices to improve the taste", "B": "to cook food slowly", "C": "to cut food into pieces", "D": "to serve food hot"},
     "A", "medium", 38, "L1",
     ["To season food means to add salt, pepper, herbs or spices to make it taste better."],
     "season = add flavour.", "Season the soup with salt and pepper."),
]
