# Unit 1 Lesson 6 (Writing and Vocabulary: A personal profile, pages 12-13)
ITEMS = [
    ("What is a personal profile?",
     {"A": "a short description of a person's character, interests and qualities", "B": "a long essay about history", "C": "a type of exam", "D": "a recipe for food"},
     "A", "easy", 12, "Writing: introduction",
     ["A personal profile is a brief description of who you are, your interests and qualities."],
     "A personal profile = a self-description.", "It is used on social media, job applications and websites."),

    ("What should a personal profile include?",
     {"A": "your name, age, interests, personality traits and goals", "B": "your bank details and passwords", "C": "only your phone number", "D": "a list of your enemies"},
     "A", "easy", 12, "Writing: structure",
     ["A good profile includes basic information, interests, personality and goals."],
     "Name, age, interests, traits, goals.", "It gives a clear picture of who you are."),

    ("Which of these is a good opening sentence for a personal profile?",
     {"A": "Hi, I'm Sarah and I'm a passionate, creative person who loves reading.", "B": "The weather is nice today.", "C": "I went to the shop yesterday.", "D": "My cat is black."},
     "A", "easy", 12, "Writing: opening",
     ["A strong opening introduces your name and key personality traits."],
     "Introduce yourself with personality.", "The opening should grab the reader's attention."),

    ("What is the purpose of a personal profile?",
     {"A": "to introduce yourself and share your key qualities with others", "B": "to hide your identity", "C": "to write a letter to a friend", "D": "to describe a place you visited"},
     "A", "easy", 12, "Writing: purpose",
     ["The purpose is to present yourself positively and clearly to others."],
     "To introduce yourself.", "It helps others understand who you are quickly."),

    ("Which adjective best describes a good personal profile?",
     {"A": "honest and positive", "B": "long and complicated", "C": "negative and boring", "D": "secret and hidden"},
     "A", "easy", 12, "Writing: style",
     ["A good profile is honest about who you are while presenting you positively."],
     "Honest and positive.", "It should be authentic but also appealing."),

    ("What is a 'first impression'?",
     {"A": "the opinion someone forms about you when they first meet you", "B": "the first time you eat a meal", "C": "your first day at school", "D": "the first book you read"},
     "A", "medium", 12, "Writing: vocabulary",
     ["A first impression is the initial opinion someone forms about you."],
     "first impression = initial opinion.", "First impressions are formed very quickly."),

    ("Why are first impressions important?",
     {"A": "they are formed quickly and can be hard to change", "B": "they are always wrong", "C": "they don't matter at all", "D": "they change every minute"},
     "A", "medium", 12, "Writing: vocabulary",
     ["First impressions are formed in seconds and can be difficult to change."],
     "First impressions last.", "Research shows they form within seconds."),

    ("What does 'to come across as' mean?",
     {"A": "to give the impression of being a certain way", "B": "to walk across a road", "C": "to find something", "D": "to understand something"},
     "A", "medium", 12, "Writing: vocabulary",
     ["'Come across as' means to give a particular impression to others."],
     "come across as = appear to be.", "You come across as friendly and approachable."),

    ("What does 'to get on well with' mean?",
     {"A": "to have a good relationship with someone", "B": "to travel on a bus", "C": "to finish a task", "D": "to wake up early"},
     "A", "easy", 12, "Writing: vocabulary",
     ["'Get on well with' means to have a friendly, harmonious relationship."],
     "get on well with = have a good relationship.", "I get on well with my classmates."),

    ("What does 'to be into' something mean?",
     {"A": "to be very interested in or enjoy something", "B": "to enter a room", "C": "to be inside a building", "D": "to fall into water"},
     "A", "easy", 12, "Writing: vocabulary",
     ["'Be into' means to have a strong interest in or enjoyment of something."],
     "be into = be interested in.", "I'm into music and reading."),

    ("What does 'to look forward to' mean?",
     {"A": "to feel excited about something that will happen in the future", "B": "to look in front of you", "C": "to think about the past", "D": "to forget about something"},
     "A", "easy", 12, "Writing: vocabulary",
     ["'Look forward to' means to feel pleased and excited about something coming."],
     "look forward to = be excited about.", "I look forward to meeting new people."),

    ("What does 'to be keen on' mean?",
     {"A": "to be very interested in and enthusiastic about something", "B": "to be sharp", "C": "to be angry", "D": "to be tired"},
     "A", "medium", 12, "Writing: vocabulary",
     ["'Be keen on' means to have a strong interest in and enthusiasm for something."],
     "be keen on = be enthusiastic about.", "She is keen on photography and painting."),

    ("What does 'to get along with' mean?",
     {"A": "to have a friendly relationship with someone", "B": "to walk along a road", "C": "to finish something", "D": "to understand a lesson"},
     "A", "easy", 12, "Writing: vocabulary",
     ["'Get along with' means to have a good, friendly relationship."],
     "get along with = get on well with.", "I get along with everyone in my class."),

    ("What is a 'hobby'?",
     {"A": "an activity you do regularly for enjoyment in your free time", "B": "a type of job", "C": "a school subject", "D": "a type of food"},
     "A", "easy", 12, "Writing: vocabulary",
     ["A hobby is an activity done regularly for pleasure in free time."],
     "hobby = leisure activity.", "Reading and painting are common hobbies."),

    ("What does 'open-minded' mean?",
     {"A": "willing to listen to new ideas and consider different opinions", "B": "having an open door", "C": "not thinking at all", "D": "being very angry"},
     "A", "medium", 12, "Writing: vocabulary",
     ["'Open-minded' means willing to accept and consider new ideas."],
     "open-minded = receptive to new ideas.", "An open-minded person listens to different views."),

    ("What does 'adaptable' mean?",
     {"A": "able to adjust easily to new situations", "B": "unable to change", "C": "very slow", "D": "extremely loud"},
     "A", "medium", 12, "Writing: vocabulary",
     ["'Adaptable' means able to change and adjust to new conditions."],
     "adaptable = flexible.", "Adaptable people handle change well."),

    ("What does 'to set goals' mean?",
     {"A": "to decide what you want to achieve in the future", "B": "to play a sport", "C": "to cook a meal", "D": "to read a book"},
     "A", "easy", 12, "Writing: vocabulary",
     ["'Set goals' means to decide on specific targets you want to reach."],
     "set goals = plan targets.", "Setting goals helps you stay focused and motivated."),

    ("What does 'self-confident' mean?",
     {"A": "believing in your own abilities and qualities", "B": "not believing in yourself", "C": "being very shy", "D": "being afraid of everything"},
     "A", "easy", 12, "Writing: vocabulary",
     ["'Self-confident' means having confidence in your own abilities and judgement."],
     "self-confident = believing in yourself.", "A self-confident person speaks clearly and calmly."),

    ("What does 'motivated' mean?",
     {"A": "having a strong desire and energy to achieve something", "B": "feeling tired and lazy", "C": "not interested in anything", "D": "always complaining"},
     "A", "medium", 12, "Writing: vocabulary",
     ["'Motivated' means having the desire and energy to do something."],
     "motivated = driven/determined.", "Motivated students work hard to achieve their goals."),

    ("What does 'creative' mean?",
     {"A": "having the ability to use imagination to produce new ideas", "B": "following rules exactly", "C": "being very quiet", "D": "being extremely tall"},
     "A", "easy", 12, "Writing: vocabulary",
     ["'Creative' means having the ability to think of new and original ideas."],
     "creative = imaginative.", "Creative people enjoy art, music and writing."),

    ("What does 'reliable' mean?",
     {"A": "dependable and able to be trusted", "B": "always late", "C": "very expensive", "D": "extremely fast"},
     "A", "easy", 12, "Writing: vocabulary",
     ["'Reliable' means trustworthy and able to be depended on."],
     "reliable = dependable.", "A reliable person always keeps their promises."),

    ("What does 'to be good at' mean?",
     {"A": "to have a natural ability or skill in something", "B": "to be kind to something", "C": "to be near something", "D": "to be angry about something"},
     "A", "easy", 12, "Writing: vocabulary",
     ["'Be good at' means to have a natural skill or ability in a particular area."],
     "be good at = have skill in.", "She is good at mathematics and science."),

    ("What does 'to be afraid of' mean?",
     {"A": "to feel fear or worry about something", "B": "to be angry with something", "C": "to be happy about something", "D": "to be close to something"},
     "A", "easy", 12, "Writing: vocabulary",
     ["'Be afraid of' means to feel fear or anxiety about something."],
     "be afraid of = fear.", "Some people are afraid of spiders or the dark."),

    ("What does 'to be proud of' mean?",
     {"A": "to feel pleased and satisfied about something you have achieved", "B": "to feel sad about something", "C": "to be angry about something", "D": "to be tired of something"},
     "A", "easy", 12, "Writing: vocabulary",
     ["'Be proud of' means to feel pleasure and satisfaction about an achievement."],
     "be proud of = feel satisfied about.", "I am proud of my exam results."),

    ("Which sentence is a good way to describe a hobby?",
     {"A": "I'm really into playing football and I play every weekend.", "B": "Football is a ball.", "C": "I don't like football.", "D": "Football exists."},
     "A", "easy", 12, "Writing: describing hobbies",
     ["A good description uses interest phrases like 'be into' and adds detail."],
     "Use interest phrases + detail.", "This makes the description more interesting."),

    ("What is the correct structure for a personal profile?",
     {"A": "introduction, hobbies and interests, personality traits, goals", "B": "a list of numbers", "C": "only your name and age", "D": "a poem about the weather"},
     "A", "easy", 12, "Writing: structure",
     ["A personal profile typically has four main sections: intro, hobbies, personality and goals."],
     "Intro → hobbies → personality → goals.", "This structure gives a clear, complete picture."),

    ("Which phrase is used to describe personality?",
     {"A": "I would describe myself as hard-working and friendly.", "B": "I went to the park.", "C": "The weather is cold.", "D": "I like pizza."},
     "A", "easy", 12, "Writing: describing personality",
     ["'I would describe myself as...' introduces personality traits clearly."],
     "I would describe myself as...", "This is a standard way to present personality."),

    ("What does 'to be interested in' mean?",
     {"A": "to want to learn more about something", "B": "to be inside something", "C": "to be frightened of something", "D": "to be angry about something"},
     "A", "easy", 12, "Writing: vocabulary",
     ["'Be interested in' means to want to know more about or enjoy something."],
     "be interested in = want to learn about.", "I am interested in science and technology."),

    ("What does 'to be fond of' mean?",
     {"A": "to like something or someone very much", "B": "to be afraid of something", "C": "to be tired of something", "D": "to be angry with someone"},
     "A", "medium", 12, "Writing: vocabulary",
     ["'Be fond of' means to have a liking or affection for something."],
     "be fond of = like very much.", "She is fond of animals and nature."),

    ("What does 'to take part in' mean?",
     {"A": "to join in an activity or event", "B": "to take something away", "C": "to give something to someone", "D": "to break something"},
     "A", "easy", 12, "Writing: vocabulary",
     ["'Take part in' means to participate in an activity or event."],
     "take part in = participate.", "I take part in school drama productions."),

    ("What does 'to be able to' mean?",
     {"A": "to have the skill or opportunity to do something", "B": "to be unable to do something", "C": "to be very tired", "D": "to be very hungry"},
     "A", "easy", 12, "Writing: vocabulary",
     ["'Be able to' means to have the ability or opportunity to do something."],
     "be able to = can.", "I am able to speak two languages."),

    ("What does 'to be good at dealing with' mean?",
     {"A": "to handle difficult situations well", "B": "to be bad at handling things", "C": "to avoid all problems", "D": "to ignore everything"},
     "A", "medium", 12, "Writing: vocabulary",
     ["'Good at dealing with' means skilled at handling or managing situations."],
     "good at dealing with = handle well.", "I am good at dealing with pressure."),

    ("What does 'to be well-known for' mean?",
     {"A": "to be famous or recognised for a particular quality or action", "B": "to be unknown", "C": "to be lost", "D": "to be confused"},
     "A", "medium", 12, "Writing: vocabulary",
     ["'Well-known for' means famous or recognised because of something."],
     "well-known for = famous for.", "She is well-known for her kindness."),

    ("Which is the best way to end a personal profile?",
     {"A": "I'm looking forward to meeting new people and learning new things.", "B": "Goodbye forever.", "C": "I hate everything.", "D": "The end."},
     "A", "easy", 12, "Writing: closing",
     ["A positive closing statement leaves a good final impression."],
     "End with a positive statement.", "It shows enthusiasm and openness."),

    ("What does 'to be creative' mean in a personal profile?",
     {"A": "to enjoy coming up with new ideas and expressing yourself", "B": "to follow rules exactly", "C": "to be very quiet", "D": "to be very old"},
     "A", "medium", 12, "Writing: describing personality",
     ["Being creative means enjoying new ideas and original thinking."],
     "creative = imaginative.", "It is a positive personality trait to mention."),

    ("What does 'to be hard-working' mean?",
     {"A": "to put a lot of effort into your work", "B": "to work very little", "C": "to avoid work completely", "D": "to only work on holidays"},
     "A", "easy", 12, "Writing: describing personality",
     ["'Hard-working' means putting a lot of effort and time into tasks."],
     "hard-working = diligent.", "Hard-working students achieve more."),

    ("What does 'to be honest' mean in a personal profile?",
     {"A": "to tell the truth and be sincere about who you are", "B": "to lie about yourself", "C": "to keep secrets", "D": "to be rude to others"},
     "A", "easy", 12, "Writing: describing personality",
     ["Being honest means telling the truth and being genuine."],
     "honest = truthful.", "Honesty is an important quality in a profile."),

    ("What does 'to be curious' mean?",
     {"A": "to want to learn and know more about things", "B": "to be bored with everything", "C": "to be angry about everything", "D": "to be afraid of everything"},
     "A", "medium", 12, "Writing: describing personality",
     ["'Curious' means wanting to learn and discover new things."],
     "curious = wanting to know.", "Curious people ask lots of questions."),

    ("What does 'to be sociable' mean?",
     {"A": "to enjoy being with other people and making friends", "B": "to avoid other people", "C": "to be very quiet", "D": "to be very angry"},
     "A", "easy", 12, "Writing: describing personality",
     ["'Sociable' means enjoying the company of other people."],
     "sociable = friendly and outgoing.", "Sociable people enjoy parties and gatherings."),

     ("What does 'to be dependable' mean?",
      {"A": "to be reliable and trustworthy", "B": "to be unreliable", "C": "to be very lazy", "D": "to be very rude"},
      "A", "medium", 12, "Writing: describing personality",
      ["'Dependable' means reliable and worthy of trust."],
      "dependable = reliable.", "A dependable friend always keeps promises."),
]
