ITEMS = [
    (
        "What is a 'medal' awarded for?",
        {"A": "Achieving a top position in a competition", "B": "Buying a ticket to a game", "C": "Watching a match on TV", "D": "Wearing sports clothes"},
        "A",
        "easy",
        52,
        "L3",
        ["Define 'medal' in the context of sports."],
        "A medal is awarded for winning in competition.",
        "Medals are given to athletes who finish first, second, or third."
    ),
    (
        "What does 'champion' mean?",
        {"A": "A person who wins a competition", "B": "A person who watches sports", "C": "A type of sport", "D": "A type of food"},
        "A",
        "easy",
        52,
        "L3",
        ["Define 'champion' in sports."],
        "A champion is a competition winner.",
        "Champions are the best performers in their sport."
    ),
    (
        "What is a 'record' in sports?",
        {"A": "The best performance ever achieved", "B": "A type of music", "C": "A score of zero", "D": "A rest period"},
        "A",
        "easy",
        52,
        "L3",
        ["Define 'record' in a sports context."],
        "A record is the best performance ever.",
        "Breaking a record means surpassing the best previous achievement."
    ),
    (
        "What does 'achievement' mean?",
        {"A": "Something accomplished through effort", "B": "A type of exercise", "C": "A score in a game", "D": "A type of food"},
        "A",
        "easy",
        52,
        "L3",
        ["Define the noun 'achievement'."],
        "An achievement is something accomplished with effort.",
        "Achievements require dedication and hard work."
    ),
    (
        "What does 'perseverance' mean?",
        {"A": "Continuing to try despite difficulties", "B": "Giving up quickly", "C": "Running very fast", "D": "Eating healthy food"},
        "A",
        "medium",
        52,
        "L3",
        ["Define 'perseverance' in the context of sports."],
        "Perseverance means continuing despite difficulties.",
        "Athletes need perseverance to overcome setbacks."
    ),
    (
        "What is a 'tournament'?",
        {"A": "A competition with many participants and rounds", "B": "A single game", "C": "A practice session", "D": "A type of shoe"},
        "A",
        "easy",
        52,
        "L3",
        ["Define 'tournament'."],
        "A tournament is a large multi-round competition.",
        "Tournaments involve many athletes competing over several days."
    ),
    (
        "What does 'dedication' mean?",
        {"A": "Committing time and energy to a goal", "B": "Taking a break", "C": "Watching others train", "D": "Sleeping early"},
        "A",
        "medium",
        52,
        "L3",
        ["Define 'dedication' in sports."],
        "Dedication means committing to a goal.",
        "Dedicated athletes spend many hours training."
    ),
    (
        "What is an 'athlete'?",
        {"A": "A person who competes in sports", "B": "A person who watches sports", "C": "A type of coach", "D": "A type of referee"},
        "A",
        "easy",
        52,
        "L3",
        ["Define 'athlete'."],
        "An athlete is a sports competitor.",
        "Athletes train regularly to compete in their sport."
    ),
    (
        "What does 'championship' mean?",
        {"A": "A series of games to determine the best team or player", "B": "A type of training", "C": "A single practice", "D": "A sports shop"},
        "A",
        "easy",
        52,
        "L3",
        ["Define 'championship' in sports."],
        "A championship is a series of deciding games.",
        "Championships determine the overall winner of a league or event."
    ),
    (
        "What does 'sacrifice' mean in sports?",
        {"A": "Giving up something for a goal", "B": "Losing a game", "C": "Scoring a goal", "D": "Wearing a uniform"},
        "A",
        "medium",
        52,
        "L3",
        ["Define 'sacrifice' in a sports context."],
        "Sacrifice means giving up something for success.",
        "Athletes often sacrifice free time to train."
    ),
    (
        "What is 'ambition' in the context of sports?",
        {"A": "A strong desire to achieve something", "B": "A type of exercise", "C": "A type of food", "D": "A rest day"},
        "A",
        "medium",
        53,
        "L3",
        ["Define 'ambition' in sports."],
        "Ambition is a strong desire to succeed.",
        "Ambitious athletes set high goals for themselves."
    ),
    (
        "What does 'defeat' mean?",
        {"A": "To lose a competition", "B": "To win a game", "C": "To train hard", "D": "To rest after a game"},
        "A",
        "easy",
        53,
        "L3",
        ["Define 'defeat' in sports."],
        "Defeat means to lose or be beaten.",
        "Experiencing defeat can motivate athletes to train harder."
    ),
    (
        "What does 'victory' mean?",
        {"A": "Winning a game or competition", "B": "Losing a match", "C": "Tying a game", "D": "Giving up"},
        "A",
        "easy",
        53,
        "L3",
        ["Define 'victory' in sports."],
        "Victory means winning.",
        "Victory is the reward for hard work and preparation."
    ),
    (
        "What does 'setback' mean?",
        {"A": "A problem that delays progress", "B": "A type of victory", "C": "A training method", "D": "A type of equipment"},
        "A",
        "medium",
        53,
        "L3",
        ["Define 'setback' in a sports context."],
        "A setback is something that slows progress.",
        "Athletes face setbacks like injuries or losses."
    ),
    (
        "What is 'resilience'?",
        {"A": "The ability to recover from difficulties", "B": "The ability to run fast", "C": "The ability to jump high", "D": "The ability to score goals"},
        "A",
        "medium",
        53,
        "L3",
        ["Define 'resilience'."],
        "Resilience is the ability to bounce back.",
        "Resilient athletes recover quickly from losses or injuries."
    ),
    (
        "What does 'role model' mean?",
        {"A": "A person who inspires others by their example", "B": "A type of sport", "C": "A type of training", "D": "A type of food"},
        "A",
        "easy",
        53,
        "L3",
        ["Define 'role model'."],
        "A role model is someone who inspires others.",
        "Athletes often become role models for young people."
    ),
    (
        "What is an 'inspiration'?",
        {"A": "Something that motivates or encourages someone", "B": "A type of exercise", "C": "A type of food", "D": "A type of equipment"},
        "A",
        "easy",
        52,
        "L3",
        ["Define 'inspiration'."],
        "Inspiration is something that motivates people.",
        "Many athletes find inspiration in their families or heroes."
    ),
    (
        "What does 'overcome' mean?",
        {"A": "To succeed despite a difficulty", "B": "To lose a competition", "C": "To train with a coach", "D": "To watch a game"},
        "A",
        "medium",
        53,
        "L3",
        ["Define 'overcome'."],
        "Overcome means to succeed despite difficulty.",
        "Overcoming challenges is a key part of any athlete's story."
    ),
    (
        "What is 'determination'?",
        {"A": "The quality of continuing to try despite obstacles", "B": "A type of exercise", "C": "A type of sport", "D": "A type of medal"},
        "A",
        "medium",
        52,
        "L3",
        ["Define 'determination' in sports."],
        "Determination is the will to keep trying.",
        "Determination helps athletes push through tough moments."
    ),
    (
        "What does 'talent' mean?",
        {"A": "A natural ability to do something well", "B": "A type of training", "C": "A type of food", "D": "A type of game"},
        "A",
        "easy",
        52,
        "L3",
        ["Define 'talent'."],
        "Talent is a natural ability.",
        "Talent alone is not enough; it must be developed with practice."
    ),
    (
        "What is a 'coach' in the context of reading?",
        {"A": "A person who trains and guides athletes", "B": "A type of bus", "C": "A type of chair", "D": "A type of referee"},
        "A",
        "easy",
        53,
        "L3",
        ["Define 'coach' in the context of athletes."],
        "A coach trains and guides athletes.",
        "Coaches play a vital role in an athlete's development."
    ),
    (
        "What does 'injury' mean?",
        {"A": "Physical harm to the body", "B": "A type of sport", "C": "A type of victory", "D": "A type of medal"},
        "A",
        "easy",
        52,
        "L3",
        ["Define 'injury' in sports."],
        "An injury is physical harm to the body.",
        "Injuries can delay an athlete's progress."
    ),
    (
        "What does 'recover' mean?",
        {"A": "To get better after being hurt or sick", "B": "To lose a game", "C": "To train harder", "D": "To score a goal"},
        "A",
        "easy",
        53,
        "L3",
        ["Define 'recover' in sports."],
        "Recover means to get better after harm.",
        "Athletes must recover properly after injuries."
    ),
    (
        "What is 'commitment'?",
        {"A": "Being devoted to a goal or activity", "B": "A type of sport", "C": "A type of game", "D": "A type of medal"},
        "A",
        "medium",
        52,
        "L3",
        ["Define 'commitment' in sports."],
        "Commitment is devotion to a goal.",
        "Commitment requires consistency and effort over time."
    ),
    (
        "What does 'triumph' mean?",
        {"A": "A great victory or achievement", "B": "A type of exercise", "C": "A type of injury", "D": "A type of equipment"},
        "A",
        "medium",
        53,
        "L3",
        ["Define 'triumph'."],
        "Triumph means a great victory.",
        "Triumphs are celebrated moments of success."
    ),
    (
        "What is a 'legend' in sports?",
        {"A": "A famous and admired athlete", "B": "A type of sport", "C": "A type of coach", "D": "A type of game"},
        "A",
        "easy",
        53,
        "L3",
        ["Define 'legend' in a sports context."],
        "A legend is a famous and admired athlete.",
        "Sports legends are remembered for their great achievements."
    ),
    (
        "What does 'endeavour' mean?",
        {"A": "A serious effort or attempt", "B": "A type of sport", "C": "A type of food", "D": "A type of rest"},
        "A",
        "hard",
        53,
        "L3",
        ["Define 'endeavour'."],
        "Endeavour means a serious effort.",
        "Athletes make great endeavours to reach their goals."
    ),
    (
        "What does 'conquer' mean in sports?",
        {"A": "To overcome a challenge or opponent", "B": "To give up", "C": "To rest", "D": "To watch"},
        "A",
        "medium",
        53,
        "L3",
        ["Define 'conquer' in a sports context."],
        "Conquer means to overcome a challenge.",
        "Conquering fear is part of being a great athlete."
    ),
    (
        "What is 'potential'?",
        {"A": "The ability to develop or improve in the future", "B": "A type of sport", "C": "A type of medal", "D": "A type of game"},
        "A",
        "medium",
        52,
        "L3",
        ["Define 'potential' in sports."],
        "Potential is the ability to improve.",
        "Young athletes show great potential when they train hard."
    ),
    (
        "What does 'fail' mean?",
        {"A": "Not succeeding at something", "B": "Winning a race", "C": "Scoring a goal", "D": "Training hard"},
        "A",
        "easy",
        53,
        "L3",
        ["Define 'fail'."],
        "Fail means not succeeding.",
        "Failure can teach important lessons."
    ),
    (
        "What is a 'challenge'?",
        {"A": "A difficult task or situation", "B": "A type of sport", "C": "A type of medal", "D": "A type of rest"},
        "A",
        "easy",
        52,
        "L3",
        ["Define 'challenge' in sports."],
        "A challenge is a difficult task.",
        "Athletes face many challenges throughout their careers."
    ),
    (
        "What does 'believe' mean in the context of sports?",
        {"A": "To have confidence in oneself or others", "B": "To rest", "C": "To watch", "D": "To lose"},
        "A",
        "easy",
        53,
        "L3",
        ["Define 'believe' in sports context."],
        "Believe means to have confidence.",
        "Believing in yourself helps you perform better."
    ),
    (
        "What is 'progress'?",
        {"A": "Moving forward or improving over time", "B": "A type of sport", "C": "A type of game", "D": "A type of medal"},
        "A",
        "easy",
        52,
        "L3",
        ["Define 'progress'."],
        "Progress means improving over time.",
        "Training leads to gradual progress in skills."
    ),
    (
        "What does 'compete' mean in a reading passage?",
        {"A": "To take part in a contest", "B": "To watch a game", "C": "To rest", "D": "To eat"},
        "A",
        "easy",
        52,
        "L3",
        ["Define 'compete' from reading context."],
        "Compete means to take part in a contest.",
        "Athletes compete to test their abilities against others."
    ),
    (
        "What does 'opportunity' mean?",
        {"A": "A chance to do something", "B": "A type of exercise", "C": "A type of sport", "D": "A type of food"},
        "A",
        "easy",
        53,
        "L3",
        ["Define 'opportunity'."],
        "An opportunity is a chance to do something.",
        "Athletes look for opportunities to compete and improve."
    ),
    (
        "What is 'self-belief'?",
        {"A": "Confidence in your own abilities", "B": "A type of sport", "C": "A type of training", "D": "A type of food"},
        "A",
        "medium",
        53,
        "L3",
        ["Define 'self-belief' in sports."],
        "Self-belief is confidence in your own abilities.",
        "Self-belief helps athletes perform under pressure."
    ),
    (
        "What does 'inspire' mean?",
        {"A": "To make someone want to do something great", "B": "To lose a game", "C": "To rest", "D": "To watch"},
        "A",
        "easy",
        52,
        "L3",
        ["Define 'inspire'."],
        "Inspire means to encourage someone to act.",
        "Great athletes inspire others through their achievements."
    ),
    (
        "What is 'hard work'?",
        {"A": "Putting in a lot of effort over time", "B": "A type of sport", "C": "A type of food", "D": "A type of game"},
        "A",
        "easy",
        52,
        "L3",
        ["Define 'hard work' in a sports context."],
        "Hard work means putting in lots of effort.",
        "Hard work is essential for achieving success in sports."
    ),
    (
        "What does 'goal' mean in sports?",
        {"A": "An aim or target to achieve", "B": "A type of exercise", "C": "A type of ball", "D": "A type of race"},
        "A",
        "easy",
        52,
        "L3",
        ["Define 'goal' in a sports context."],
        "A goal is an aim or target.",
        "Setting clear goals helps athletes focus their training."
    ),
    (
        "What does 'hero' mean in a sports reading?",
        {"A": "A person admired for courage or great deeds", "B": "A type of sport", "C": "A type of coach", "D": "A type of referee"},
        "A",
        "easy",
        53,
        "L3",
        ["Define 'hero' in a sports context."],
        "A hero is someone admired for great deeds.",
        "Sports heroes inspire future generations of athletes."
    ),
]
