# Unit 2 Lesson 2 (Reading and Vocabulary: Lost words on the metro, pages 16-17)
ITEMS = [
    ("Where was Malek from?",
     {"A": "the countryside", "B": "a big capital city", "C": "an island", "D": "a mountain village"},
     "A", "easy", 16, "Reading text: line 1",
     ["The text says back home in the countryside, life moved at a gentle pace."],
     "Malek was from the countryside.", "This was his first trip to a big city."),

    ("What was Malek's dream since childhood?",
     {"A": "to visit the Camp Nou football stadium", "B": "to live in Barcelona", "C": "to ride the metro", "D": "to become a tour guide"},
     "A", "easy", 16, "Reading text: paragraph 1",
     ["It was a dream since childhood to visit the great football stadium, Camp Nou."],
     "His dream was to visit Camp Nou.", "He was in his early 20s and making it happen."),

    ("How did people react when Malek announced his plan to travel alone?",
     {"A": "everyone tried to talk him out of it", "B": "everyone offered to come with him", "C": "nobody believed him", "D": "everyone congratulated him"},
     "A", "medium", 16, "Reading text: paragraph 1",
     ["Everyone tried to talk him out of it, but he was determined."],
     "They tried to change his mind.", "He was determined to go."),

    ("How would you describe life back home for Malek?",
     {"A": "it moved at a gentle pace", "B": "it was noisy and chaotic", "C": "it was very dangerous", "D": "it was full of tourists"},
     "A", "medium", 16, "Reading text: paragraph 1",
     ["The text says life moved at a gentle pace in the countryside."],
     "Life was calm and slow.", "The city square was startlingly noisy in contrast."),

    ("What does 'the city square was teeming with tourists' mean?",
     {"A": "it was full of tourists", "B": "it was empty", "C": "the tourists were leaving", "D": "the square was closed"},
     "A", "easy", 16, "Reading text: paragraph 1",
     ["'Teeming with' means full of, or swarming with."],
     "teeming with = full of.", "Tourists and locals filled the square."),

    ("Why did Malek stand back from the track on the platform?",
     {"A": "for safety", "B": "to see the train better", "C": "to wait for a friend", "D": "to buy a ticket"},
     "A", "medium", 16, "Reading text: paragraph 3",
     ["In the interest of safety, he stood back from the track."],
     "He stood back for safety.", "Unfortunately it was a poor choice of spot."),

    ("What problem did Malek's safe spot cause?",
     {"A": "he was blocking the path of commuters", "B": "he fell onto the track", "C": "he missed his train", "D": "he lost his wallet"},
     "A", "medium", 16, "Reading text: paragraph 3",
     ["Inadvertently, he was blocking the path of commuters milling around the platform."],
     "He blocked the commuters' path.", "He dragged himself towards the wall to let them pass."),

    ("What does 'inadvertently' mean in the text?",
     {"A": "without meaning to", "B": "deliberately", "C": "secretly", "D": "happily"},
     "A", "hard", 16, "Reading text: paragraph 3",
     ["'Inadvertently' means unintentionally, not on purpose."],
     "inadvertently = without intending to.", "He did not mean to block anyone."),

    ("What did Malek wonder about the commuters?",
     {"A": "whether they always dashed everywhere", "B": "where they bought their tickets", "C": "whether they enjoyed their jobs", "D": "why they carried phones"},
     "A", "medium", 16, "Reading text: paragraph 3",
     ["He wondered 'Did they always dash everywhere?'."],
     "He wondered if they always rushed.", "Everyone moved quickly, heads down, wordless."),

    ("What happened when the express train passed?",
     {"A": "Malek felt its wind in his eyes", "B": "it knocked him over", "C": "he got on it", "D": "it stopped at the platform"},
     "A", "easy", 16, "Reading text: paragraph 4",
     ["An express train thundered past and Malek felt its wind in his eyes."],
     "The train's wind hit his eyes.", "Just as quickly, it was gone."),

    ("What does 'the crowd inched closer to the yellow line' mean?",
     {"A": "it moved very slowly closer", "B": "it moved back quickly", "C": "it measured the line", "D": "it stayed still"},
     "A", "medium", 16, "Reading text: paragraph 4",
     ["'Inch' as a verb means to move very slowly."],
     "inched = moved very slowly.", "The crowd gradually got closer to the yellow line."),

    ("What does 'the train rumbled to a stop' mean?",
     {"A": "it stopped slowly with a low noise", "B": "it stopped suddenly with a bang", "C": "it never stopped", "D": "it stopped silently"},
     "A", "medium", 16, "Reading text: paragraph 4",
     ["'Rumble' describes a low, continuous noise; the train gradually came to a stop."],
     "rumbled to a stop = slowed down noisily.", "The train arrived and slowed with a low sound."),

    ("How did the passengers alighting leave the train?",
     {"A": "they elbowed their way through the people entering", "B": "they waited politely", "C": "they stayed on the train", "D": "they climbed out the windows"},
     "A", "medium", 16, "Reading text: paragraph 4",
     ["Passengers alighting had to elbow their way through the sea of people entering."],
     "They pushed through with their elbows.", "There were too many people trying to get on."),

    ("What does 'alight' mean in this text?",
     {"A": "to get off a train or bus", "B": "to catch fire", "C": "to board a train", "D": "to fall asleep"},
     "A", "hard", 16, "Reading text: paragraph 4",
     ["'Alighting' means getting off a vehicle such as a train."],
     "alight = get off.", "The passengers alighting elbowed their way out."),

    ("What does 'the train lurched forward' mean?",
     {"A": "it suddenly moved forward unsteadily", "B": "it reversed slowly", "C": "it glided smoothly", "D": "it stopped suddenly"},
     "A", "medium", 16, "Reading text: paragraph 4",
     ["'Lurch' means to move suddenly and unsteadily."],
     "lurched forward = moved suddenly.", "The doors slammed shut and the train moved off."),

    ("In the carriage, what did those who could reach do?",
     {"A": "they grasped the handrail to steady themselves", "B": "they sat on the floor", "C": "they opened the windows", "D": "they held their phones"},
     "A", "easy", 17, "Reading text: paragraph 5",
     ["Those who could reach overhead grasped the handrail to steady themselves."],
     "They held the handrail to stay steady.", "Others struggled to keep their balance."),

    ("What happened to Malek when he was unaccustomed to the motion?",
     {"A": "he faltered once or twice", "B": "he fell over completely", "C": "he felt sick", "D": "he sat down at once"},
     "A", "medium", 17, "Reading text: paragraph 5",
     ["Unaccustomed to the motion, Malek faltered once or twice, then stood firm."],
     "He faltered, then stood firm.", "He soon stabilised himself."),

    ("What does 'to forge ahead' mean?",
     {"A": "to move forward with determination", "B": "to stay behind", "C": "to move sideways", "D": "to turn back"},
     "A", "medium", 17, "Reading text: paragraph 5",
     ["'Forge ahead' means to move forward forcefully and determinedly."],
     "forge ahead = move forward with determination.", "The leaving passengers forged ahead to the doors."),

    ("What did Malek count on the Metro map?",
     {"A": "the stops until Les Corts", "B": "the number of passengers", "C": "the trains passing", "D": "the seats in the carriage"},
     "A", "easy", 17, "Reading text: paragraph 5",
     ["He counted the stops until Les Corts, even though he had already counted them many times."],
     "He counted the stops to Les Corts.", "He had counted them umpteen times."),

    ("Who was sitting facing Malek?",
     {"A": "an older couple", "B": "two students", "C": "a family with children", "D": "a group of tourists"},
     "A", "easy", 17, "Reading text: paragraph 6",
     ["Malek noticed an older couple who were sitting down facing him."],
     "An older couple sat facing him.", "The old man was reading a novel."),

    ("What happened when the old man noticed Malek staring?",
     {"A": "he nodded politely and Malek nodded back", "B": "he moved to another seat", "C": "he shouted at Malek", "D": "he laughed at him"},
     "A", "medium", 17, "Reading text: paragraph 6",
     ["The man glanced up, nodded politely, and Malek nodded back, blushing."],
     "They nodded to each other.", "Malek was embarrassed about staring."),

    ("Why was Malek embarrassed?",
     {"A": "he worried it might look as if he had been staring", "B": "he had lost his ticket", "C": "he did not know the way", "D": "he was late for the match"},
     "A", "medium", 17, "Reading text: paragraph 6",
     ["Malek worried that the man might think he had been staring at him."],
     "He felt guilty about staring.", "In fact the man just nodded politely."),

    ("What did the old man forget when he left the train?",
     {"A": "his book", "B": "his umbrella", "C": "his glasses", "D": "his hat"},
     "A", "easy", 17, "Reading text: paragraph 7",
     ["Malek saw that the old man had forgotten his book; it was still on the seat."],
     "He forgot his book.", "Malek noticed it on the seat after the doors closed."),

    ("Why was Malek 'strangely lost for words'?",
     {"A": "he wanted to say something friendly but could not think what to say", "B": "he could not speak Spanish", "C": "he had forgotten his mobile phone", "D": "he was angry with the couple"},
     "A", "medium", 17, "Reading text: paragraph 7",
     ["He desperately wanted to make a friendly comment but was strangely lost for words."],
     "He could not find the words.", "He missed the chance to speak before they left."),

    ("What does 'caught his eye' mean?",
     {"A": "attracted his attention", "B": "hurt his eye", "C": "made him blink", "D": "surprised him"},
     "A", "medium", 17, "Exercise 4: Figurative meaning",
     ["'Catch someone's eye' means to attract their attention."],
     "caught his eye = attracted his attention.", "The old man glanced up and caught Malek's eye."),

    ("What does 'swept along with the crowds' mean?",
     {"A": "carried along by the movement of the crowd", "B": "cleaned by the crowd", "C": "pushed against the crowd", "D": "ignored by the crowd"},
     "A", "medium", 17, "Exercise 4: Figurative meaning",
     ["Malek was swept along with the crowds = carried along by them."],
     "swept along = carried along.", "He could not easily choose his own direction."),

    ("What does 'fell into step with' mean?",
     {"A": "started walking in the same rhythm as others", "B": "tripped over a step", "C": "walked behind everyone", "D": "left the group"},
     "A", "medium", 17, "Exercise 4: Figurative meaning",
     ["He fell into step with those heading the same way = he matched their pace."],
     "fell into step = matched their pace.", "He walked in rhythm with the crowd."),

    ("What does 'milling around' mean?",
     {"A": "moving around in a crowd without a clear purpose", "B": "making flour in a mill", "C": "standing in a line", "D": "running quickly"},
     "A", "medium", 17, "Exercise 4: Figurative meaning",
     ["Commuters were milling around the platform = moving about aimlessly."],
     "milling around = moving about aimlessly.", "They were bolting this way and that, wordless."),

    ("What does 'thundered past' describe?",
     {"A": "moved past very loudly and quickly", "B": "moved past silently", "C": "moved very slowly", "D": "stopped suddenly"},
     "A", "medium", 17, "Exercise 4: Figurative meaning",
     ["'Thunder past' means to move very fast and noisily."],
     "thundered past = passed noisily and fast.", "The express train thundered past."),

    ("What does 'find his footing' mean?",
     {"A": "become steady or get used to a situation", "B": "lose his balance", "C": "find his shoes", "D": "get on the train"},
     "A", "medium", 17, "Exercise 4: Figurative meaning",
     ["He was pleased to find his footing = to become steady and comfortable."],
     "find his footing = become steady.", "He began to relax into the journey."),

    ("What type of reference device is 'this/that, these/those'?",
     {"A": "demonstratives", "B": "relative pronouns", "C": "indefinite pronouns", "D": "determiners"},
     "A", "easy", 16, "Active Reading: Understanding reference devices",
     ["The box lists this/that, these/those as demonstratives."],
     "This/that/these/those are demonstratives.", "They point to specific things."),

    ("Which of these is an indefinite pronoun?",
     {"A": "something", "B": "who", "C": "his", "D": "another"},
     "A", "easy", 16, "Active Reading: Understanding reference devices",
     ["Indefinite pronouns include something, anything, everything, no one."],
     "something = indefinite pronoun.", "It refers to a thing without naming it exactly."),

    ("Which of these is a relative pronoun?",
     {"A": "whose", "B": "those", "C": "one", "D": "it"},
     "A", "easy", 16, "Active Reading: Understanding reference devices",
     ["Relative pronouns include who, whom, whose."],
     "whose = relative pronoun.", "Relative pronouns connect parts of a sentence."),

    ("Why are reference devices used in a text?",
     {"A": "to avoid repetition", "B": "to make sentences longer", "C": "to confuse the reader", "D": "to add new information only"},
     "A", "easy", 16, "Active Reading: Understanding reference devices",
     ["Reference devices are often used to avoid repetition."],
     "They avoid repetition.", "They refer back to earlier information or forward to later information."),

    ("In 'I usually get on the last car of the train. I go for that one', what does 'that one' refer to?",
     {"A": "the last car of the train", "B": "the first car", "C": "the ticket", "D": "the station"},
     "A", "medium", 16, "Active Reading: Referring back",
     ["'That one' refers back to the last car of the train."],
     "that one = the last car.", "He chooses the last car because it's nearly empty."),

    ("In 'Although she hated travelling by tube, Huda decided that it would be the fastest way home', who does 'she' refer to?",
     {"A": "Huda", "B": "a friend", "C": "Malek's mother", "D": "the writer"},
     "A", "medium", 16, "Active Reading: Referring forward",
     ["'She' refers to Huda, who is named later in the sentence."],
     "she = Huda.", "This is an example of referring forward."),

    ("What type of text is 'Lost words on the metro'?",
     {"A": "an extract from a story", "B": "a newspaper report", "C": "an advertisement", "D": "a formal email"},
     "A", "medium", 16, "Reading: text type",
     ["The text is a narrative extract following Malek's journey on the metro."],
     "It is a narrative extract.", "It tells a story with characters and a sequence of events."),

    ("What does 'dispersing on the platform' mean?",
     {"A": "spreading out in different directions", "B": "waiting in a queue", "C": "getting on the train", "D": "buying tickets"},
     "A", "medium", 17, "Exercise 2: Synonyms",
     ["'Dispersing' means spreading out or moving apart."],
     "dispersing = spreading out.", "People got off and spread out in different directions."),

    ("Which word in the text means the same as 'rushing'?",
     {"A": "dashing", "B": "inching", "C": "settling", "D": "scrolling"},
     "A", "hard", 17, "Exercise 2: Synonyms",
     ["'Dashing' means rushing or moving quickly."],
     "dashing = rushing.", "Malek wondered if they always dashed everywhere."),

    ("What does 'anchored' mean in 'he was pleased to find his footing and feel anchored'?",
     {"A": "stable and steady", "B": "heavy and tired", "C": "lost and confused", "D": "excited and nervous"},
     "A", "hard", 17, "Reading text: paragraph 5",
     ["'Anchored' here means feeling stable, like a ship fixed by an anchor."],
     "anchored = stable.", "He felt steady and relaxed in the journey."),
]
