# Unit 3 Lesson 4 (Reading and Vocabulary: Behavioural economics, pages 30-31)
ITEMS = [
    ("According to the article, what is economics really about?",
     {"A": "making choices and decisions", "B": "money and banks only", "C": "buying and selling shares", "D": "government taxes"},
     "A", "easy", 31, "Reading: introduction",
     ["'Economics is really all about making choices and decisions.'"],
     "Economics is about choices.", "It is far broader than just money."),

    ("Why is a pros and cons list not very effective?",
     {"A": "just one of the cons might easily outweigh all of the pros", "B": "it is too long to write", "C": "nobody uses lists anymore", "D": "it takes too much time"},
     "A", "medium", 31, "Reading: paragraph A",
     ["'Just one of the cons might easily outweigh all of the pros.'"],
     "One con can outweigh all pros.", "The list does not weigh importance."),

    ("What is a cost-benefit analysis better at?",
     {"A": "allowing you to be more objective", "B": "making things cheaper", "C": "speeding up decisions", "D": "removing all risks"},
     "A", "medium", 31, "Reading: paragraph A",
     ["A cost-benefit analysis is more sophisticated and allows you to be more objective."],
     "It makes you more objective.", "You score costs and benefits."),

    ("In the train vs aeroplane example, what other costs should you consider?",
     {"A": "the cost in your time, tiredness and the environment", "B": "the price of food", "C": "the cost of parking", "D": "the price of luggage"},
     "A", "medium", 31, "Reading: paragraph A",
     ["Other costs include your time, tiredness on arrival and the environmental cost."],
     "Time, tiredness and environment.", "You score each cost out of five."),

    ("What is 'present bias'?",
     {"A": "people overvalue immediate rewards over long-term payoffs", "B": "people prefer the future", "C": "people ignore the present", "D": "people spend too much"},
     "A", "medium", 31, "Reading: paragraph B",
     ["'People have a tendency to overvalue immediate rewards over long-term payoffs.'"],
     "Present bias = overvaluing now.", "It explains procrastination."),

    ("In the famous money study, what did most people choose?",
     {"A": "less money now, even though they'd end up less well-off", "B": "more money later", "C": "no money", "D": "equal amounts"},
     "A", "medium", 31, "Reading: paragraph B",
     ["Most people chose less money now over more money later."],
     "They chose the immediate reward.", "Even though it made them worse off."),

    ("Why do people procrastinate, according to the article?",
     {"A": "because of present bias", "B": "because they are lazy people", "C": "because they are too busy", "D": "because they lack intelligence"},
     "A", "medium", 31, "Reading: paragraph B",
     ["Present bias is also the reason why people procrastinate."],
     "Present bias causes procrastination.", "Immediate rewards beat long-term ones."),

    ("Why should you never go food shopping when hungry?",
     {"A": "you overvalue the immediate reward of food", "B": "you will buy too little", "C": "the shop is crowded", "D": "food costs more at night"},
     "A", "hard", 31, "Reading: paragraph B",
     ["When hungry, immediate rewards (food) seem more valuable, so you overbuy."],
     "Hunger increases present bias.", "Awareness helps you avoid it."),

    ("What is one way to overcome the tendency to spend money immediately?",
     {"A": "put money in a savings account where you can't get at it easily", "B": "carry more cash", "C": "avoid all shops", "D": "spend it all at once"},
     "A", "medium", 31, "Reading: paragraph B",
     ["A savings account you can't access easily helps you wait."],
     "Use a savings account.", "It overcomes the urge to spend."),

    ("What is the 'sunk-cost fallacy'?",
     {"A": "the idea that because you've invested, you should persist no matter what", "B": "the idea that invested money is lost", "C": "a belief about cheap products", "D": "a type of maths error"},
     "A", "easy", 31, "Reading: paragraph C",
     ["The sunk-cost fallacy: because you've invested time or money, you should persist."],
     "sunk-cost = persist because invested.", "It often works against our best interests."),

    ("What is a 'fallacy'?",
     {"A": "an idea often believed to be true but which is false", "B": "a scientific law", "C": "a useful trick", "D": "a type of argument"},
     "A", "medium", 31, "Reading: paragraph C",
     ["'A fallacy is an idea that is often believed to be true, but which is, in fact, false.'"],
     "fallacy = false belief.", "The sunk-cost idea is a fallacy."),

    ("In the chocolate cake study, what made people more likely to eat the cake?",
     {"A": "being told the cake required a significant investment of time and money", "B": "how hungry they were", "C": "how much they loved chocolate", "D": "how big the cake was"},
     "A", "medium", 31, "Reading: paragraph C",
     ["Those told the cake was expensive and far away were more likely to eat it all."],
     "The investment made them eat more.", "They felt it would be wasted otherwise."),

    ("Even though they felt full, why did people eat the cake?",
     {"A": "because of the sunk-cost fallacy", "B": "because they were hungry", "C": "because it was delicious", "D": "because they were polite"},
     "A", "medium", 31, "Reading: paragraph C",
     ["The expensive cake seemed to require finishing, so they ate it all."],
     "The sunk-cost fallacy made them finish it.", "It went against their best interests."),

    ("Which is an example of the sunk-cost fallacy in daily life?",
     {"A": "maintaining a friendship because you've known the person a long time", "B": "buying a new phone", "C": "starting a new hobby", "D": "moving to a new city"},
     "A", "medium", 31, "Reading: paragraph C",
     ["Keeping a friendship you no longer enjoy because of time invested is an example."],
     "Friendship sunk-cost example.", "Also persisting with a failing business idea."),

    ("What does 'falling prey to' in the article mean?",
     {"A": "being influenced by (in a bad way)", "B": "being left unaffected by", "C": "being improved by", "D": "being protected from"},
     "A", "hard", 30, "Exercise 2: Question 4",
     ["'Falling prey to this fallacy' means being harmed or influenced by it."],
     "falling prey = being influenced by.", "You should recognise when it happens."),

    ("What is the 'law of diminishing returns'?",
     {"A": "after a point, investing more does not lead to increased benefits", "B": "prices always go down", "C": "investments always fail", "D": "returns are never guaranteed"},
     "A", "medium", 31, "Reading: paragraph D",
     ["After a certain point, more money or effort does not bring more benefit."],
     "Diminishing returns = less benefit per effort.", "More input gives less extra output."),

    ("What example shows the law of diminishing returns?",
     {"A": "inviting 20 or 30 people to paint one room", "B": "buying one pizza", "C": "hiring one worker", "D": "painting a room alone"},
     "A", "medium", 31, "Reading: paragraph D",
     ["Too many helpers make the decorating inefficient."],
     "Too many people = diminishing returns.", "At first more help is constructive."),

    ("What does the pizza example teach us?",
     {"A": "the first few slices are great, but then it becomes less pleasant", "B": "pizza is always delicious", "C": "you should eat all the pizza", "D": "pizza is cheap"},
     "A", "hard", 31, "Reading: paragraph D",
     ["The first slices are great, but the benefit drops as you eat more."],
     "The pleasure decreases.", "It shows diminishing returns."),

    ("What lesson does the article draw from the law of diminishing returns?",
     {"A": "doing your best is good enough - don't overdo things", "B": "always expect more", "C": "make risky investments", "D": "never stop pushing"},
     "A", "medium", 31, "Reading: paragraph D",
     ["'It is really a reminder that doing your best is good enough.'"],
     "Don't overdo things.", "If you keep pushing, you get diminishing returns."),

    ("What does 'there's no such thing as a free lunch' mean?",
     {"A": "everything has a cost, even if it isn't obvious", "B": "lunch is never free", "C": "restaurants give free food", "D": "food is expensive"},
     "A", "easy", 31, "Reading: paragraph E",
     ["Nothing is truly free; there is always a hidden cost."],
     "Everything has a hidden cost.", "The expression warns against free offers."),

    ("Why was the free lunch made as salty as possible?",
     {"A": "so people would buy expensive drinks", "B": "to make the lunch taste better", "C": "to stop people eating too much", "D": "to show off the chef's skill"},
     "A", "hard", 31, "Reading: paragraph E",
     ["The salty lunch made people thirsty, so they spent far more on beverages."],
     "The salt made people buy drinks.", "That was the hidden cost."),

    ("What does 'if you aren't paying for a product, you ARE the product' mean?",
     {"A": "free services make money from you (e.g. your data)", "B": "you get products for free", "C": "products are people", "D": "prices are invisible"},
     "A", "hard", 31, "Reading: paragraph E",
     ["Free social media sites use your attention or data to profit."],
     "You are the product.", "Free sites still make money from users."),

    ("Which word means the same as 'outweigh' in the text?",
     {"A": "cancel out", "B": "add to", "C": "explain", "D": "ignore"},
     "A", "medium", 30, "Exercise 3: Synonyms",
     ["One con can outweigh all the pros; 'cancel out' means to balance or counter."],
     "cancel out", "The pros are cancelled by the cons."),

    ("Which word means 'objective'?",
     {"A": "dispassionate / impartial", "B": "emotional", "C": "angry", "D": "confused"},
     "A", "medium", 30, "Exercise 3: Synonyms",
     ["'Dispassionate' and 'impartial' both mean objective and fair."],
     "dispassionate = impartial = objective.", "A cost-benefit analysis is more objective."),

    ("Which phrase means 'take into account'?",
     {"A": "bear in mind", "B": "put away", "C": "throw out", "D": "give up"},
     "A", "easy", 30, "Exercise 3: Synonyms",
     ["'Bear in mind' means to remember or consider."],
     "bear in mind = consider.", "There are other costs to bear in mind."),

    ("Which word means 'a tendency'?",
     {"A": "propensity", "B": "notion", "C": "snare", "D": "pitfall"},
     "A", "hard", 30, "Exercise 3: Synonyms",
     ["'Propensity' means a natural tendency or inclination."],
     "propensity = tendency.", "People have a propensity to overvalue rewards."),

    ("Which word means 'a trap or a danger'?",
     {"A": "snare / pitfall", "B": "notion", "C": "benefit", "D": "analysis"},
     "A", "medium", 30, "Exercise 3: Synonyms",
     ["'Snare' and 'pitfall' both mean a trap or hidden danger."],
     "snare = pitfall = trap.", "Another trap is the sunk-cost fallacy."),

    ("Which word means 'to persist' or 'continue despite difficulty'?",
     {"A": "persevere / plough on", "B": "give up", "C": "pause", "D": "worry"},
     "A", "medium", 30, "Exercise 3: Synonyms",
     ["'Persevere' and 'plough on' mean to keep going despite problems."],
     "persevere = plough on = persist.", "You should persist with the plan."),

    ("Which word means 'damaging or harmful'?",
     {"A": "detrimental", "B": "beneficial", "C": "neutral", "D": "obvious"},
     "A", "medium", 30, "Exercise 3: Synonyms",
     ["'Detrimental' means harmful or damaging."],
     "detrimental = harmful.", "The impact may be detrimental."),

    ("Which word means 'an idea or concept'?",
     {"A": "notion", "B": "snare", "C": "pitfall", "D": "propensity"},
     "A", "easy", 30, "Exercise 3: Synonyms",
     ["'Notion' means an idea or belief."],
     "notion = concept.", "Consider this notion when using social media."),

    ("Which word means 'to remove or make ineffective'?",
     {"A": "negate", "B": "create", "C": "boost", "D": "keep"},
     "A", "hard", 30, "Exercise 3: Synonyms",
     ["'Negate' means to cancel out or make something ineffective."],
     "negate = cancel out.", "The worries negate the discount."),

    ("What should you score out of five in a cost-benefit analysis?",
     {"A": "each cost and each potential benefit", "B": "each friend's opinion", "C": "each year of work", "D": "each kilometre travelled"},
     "A", "medium", 31, "Reading: paragraph A",
     ["Give each cost a score out of five, then weigh them against benefits scored the same way."],
     "Score costs and benefits out of five.", "It makes the choice easier."),

    ("What is the main message of the article?",
     {"A": "behavioural economics can be applied to daily decisions", "B": "economics is only about money", "C": "you should never analyse decisions", "D": "biases cannot be avoided"},
     "A", "medium", 31, "Reading: overall message",
     ["Economic principles, especially behavioural economics, apply to all areas of life."],
     "Economics applies to daily life.", "Recognising biases improves decisions."),

    ("Which of these is NOT one of the biases or concepts in the article?",
     {"A": "the scarcity principle", "B": "present bias", "C": "the sunk-cost fallacy", "D": "the law of diminishing returns"},
     "A", "medium", 31, "Reading: concepts",
     ["The scarcity principle is from the persuasion lesson, not this article."],
     "Scarcity principle is not here.", "The article covers present bias, sunk cost and diminishing returns."),

    ("According to the article, when can decision-making ability be dramatically improved?",
     {"A": "when we recognise we may be falling prey to the sunk-cost fallacy", "B": "when we ignore our biases", "C": "when we spend more money", "D": "when we stop analysing"},
     "A", "medium", 31, "Reading: paragraph C",
     ["Recognising the fallacy dramatically improves our decision-making ability."],
     "Recognition improves decisions.", "Awareness is the first step."),

    ("What does 'notwithstanding the objective risk' mean?",
     {"A": "even though there is a real risk", "B": "because there is no risk", "C": "without any risk", "D": "despite the profit"},
     "A", "hard", 31, "Reading: paragraph D",
     ["'Notwithstanding' means despite or regardless of."],
     "notwithstanding = despite.", "There may be an adverse impact despite the risk."),

    ("What does the expression 'no such thing as a free lunch' warn us about?",
     {"A": "hidden costs in things that seem free", "B": "free food in restaurants", "C": "cheap meals", "D": "eating too much"},
     "A", "easy", 31, "Reading: paragraph E",
     ["It warns that everything has a hidden cost."],
     "Beware hidden costs.", "Free offers usually cost you something."),

    ("What example shows 'negate' in the article?",
     {"A": "worries about modern slavery negating a discount", "B": "a cheap price for a good product", "C": "a free lunch", "D": "a chocolate cake"},
     "A", "hard", 31, "Reading: paragraph E",
     ["'Worries about modern slavery often negate any discount' - they cancel out the saving."],
     "The worries cancel the discount.", "Cheap items may have terrible costs."),

    ("In the study about retirement savings, what made people save more?",
     {"A": "seeing a digitally-aged photo of themselves", "B": "a lecture about saving", "C": "more income", "D": "a tax cut"},
     "A", "hard", 31, "Reading: paragraph B",
     ["Participants shown an aged photo of themselves chose to save more."],
     "The aged photo increased saving.", "It is a study about present bias."),

    ("What does 'propensity' mean in 'a propensity to overvalue rewards'?",
     {"A": "a natural tendency or inclination", "B": "a decision", "C": "a mistake", "D": "a benefit"},
     "A", "hard", 30, "Exercise 3: Synonyms",
     ["'Propensity' means a natural tendency to do something."],
     "propensity = tendency.", "People have a propensity to overvalue the present."),
]
