ITEMS = [
    (
        "What is the stage of a competition where the last two teams play?",
        {"A": "the final", "B": "the round", "C": "the knockout", "D": "the elimination"},
        "A",
        "easy",
        "54",
        "L4",
        ["The final is the last match that decides the winner."],
        "Final means the last stage of a competition.",
        "The final is the match that determines the champion."
    ),
    (
        "A competition where the loser is immediately out is called a ___ competition.",
        {"A": "knockout", "B": "semi-final", "C": "round", "D": "pool"},
        "A",
        "easy",
        "54",
        "L4",
        ["In a knockout competition, the losing team is eliminated right away."],
        "Knockout means elimination after losing.",
        "A knockout competition removes the loser immediately."
    ),
    (
        "What do you use to hit the ball in tennis?",
        {"A": "a racket", "B": "a bat", "C": "a stick", "D": "a club"},
        "A",
        "easy",
        "54",
        "L4",
        ["In tennis, players use a racket to hit the ball."],
        "A racket is used in tennis and badminton.",
        "Tennis players hit the ball with a racket."
    ),
    (
        "A match played before the final to decide who goes to the final is a ___.",
        {"A": "semi-final", "B": "round", "C": "knockout", "D": "group stage"},
        "A",
        "medium",
        "54",
        "L4",
        ["A semi-final is the round before the final."],
        "Semi-final is the match before the final.",
        "The semi-final decides who reaches the final."
    ),
    (
        "Where is a football match played?",
        {"A": "on a pitch", "B": "in a pool", "C": "on a court", "D": "in a ring"},
        "A",
        "easy",
        "54",
        "L4",
        ["Football is played on a pitch, which is a large grass field."],
        "A pitch is a field for football or cricket.",
        "Football matches are played on a pitch."
    ),
    (
        "A very large building where many spectators watch sports is a ___.",
        {"A": "stadium", "B": "gym", "C": "court", "D": "net"},
        "A",
        "easy",
        "55",
        "L4",
        ["A stadium is a large venue for outdoor sports events."],
        "A stadium holds thousands of spectators.",
        "Stadiums are large venues for watching sports."
    ),
    (
        "In a competition, a ___ is one section where teams or players compete before moving on.",
        {"A": "round", "B": "net", "C": "bat", "D": "racket"},
        "A",
        "medium",
        "54",
        "L4",
        ["A round is one stage or level in a competition."],
        "A round is a stage in a tournament.",
        "Competitions are divided into rounds."
    ),
    (
        "What is the name for the area where basketball is played?",
        {"A": "a court", "B": "a pitch", "C": "a pool", "D": "a field"},
        "A",
        "easy",
        "54",
        "L4",
        ["Basketball is played on a court with hard flooring."],
        "A court is used for basketball, tennis, and volleyball.",
        "Basketball is played on a court."
    ),
    (
        "When all players or teams from a group continue to the next stage, this is called ___.",
        {"A": "qualification", "B": "elimination", "C": "knockout", "D": "defeat"},
        "A",
        "medium",
        "55",
        "L4",
        ["Qualification means successfully passing to the next stage."],
        "Qualification means earning the right to continue.",
        "Teams qualify by finishing at the top of their group."
    ),
    (
        "What equipment do you need to play volleyball?",
        {"A": "a net and a ball", "B": "a racket and a ball", "C": "a bat and a ball", "D": "a stick and a puck"},
        "A",
        "easy",
        "54",
        "L4",
        ["Volleyball is played with a net in the middle and a ball."],
        "Volleyball needs a net and a ball.",
        "Players hit a ball over a net in volleyball."
    ),
    (
        "The opposite of winning is ___.",
        {"A": "losing", "B": "playing", "C": "training", "D": "scoring"},
        "A",
        "easy",
        "54",
        "L4",
        ["Losing is the opposite of winning in a competition."],
        "When you lose, you do not win.",
        "Losing means you did not win the match."
    ),
    (
        "What is an indoor sports facility with exercise equipment?",
        {"A": "a gymnasium", "B": "a stadium", "C": "a court", "D": "a pitch"},
        "A",
        "medium",
        "55",
        "L4",
        ["A gymnasium is an indoor place for exercise and sports."],
        "A gymnasium or gym is for indoor exercise.",
        "People train in a gymnasium."
    ),
    (
        "When one team beats another team, we say they ___.",
        {"A": "defeated them", "B": "visited them", "C": "invited them", "D": "followed them"},
        "A",
        "easy",
        "54",
        "L4",
        ["To defeat someone means to win against them."],
        "Defeating means winning against an opponent.",
        "Our team defeated the other team 3-1."
    ),
    (
        "A swimming competition takes place in a ___.",
        {"A": "pool", "B": "pitch", "C": "court", "D": "ring"},
        "A",
        "easy",
        "55",
        "L4",
        ["Swimming competitions are held in a pool."],
        "A pool is where swimming competitions happen.",
        "Swimmers race in a pool."
    ),
    (
        "Which word means the act of taking part in a sport or competition?",
        {"A": "participation", "B": "observation", "C": "imitation", "D": "navigation"},
        "A",
        "medium",
        "55",
        "L4",
        ["Participation means taking part in something."],
        "Participation means being involved in an event.",
        "Every athlete's participation in the event was impressive."
    ),
    (
        "In a round-robin tournament, every team plays ___.",
        {"A": "every other team", "B": "only the winner", "C": "one match", "D": "the final"},
        "A",
        "hard",
        "55",
        "L4",
        ["In a round-robin, each team plays against every other team."],
        "Round-robin means everyone plays everyone.",
        "A round-robin tournament ensures all teams face each other."
    ),
    (
        "What is the person called who watches a sports match?",
        {"A": "a spectator", "B": "a player", "C": "a coach", "D": "a referee"},
        "A",
        "easy",
        "55",
        "L4",
        ["A spectator is a person who watches a sports event."],
        "Spectators watch sports events.",
        "Thousands of spectators came to watch the match."
    ),
    (
        "The person who makes sure the rules are followed in a game is the ___.",
        {"A": "referee", "B": "spectator", "C": "captain", "D": "coach"},
        "A",
        "easy",
        "54",
        "L4",
        ["The referee enforces the rules during a match."],
        "A referee controls the game and checks rules.",
        "The referee gave a yellow card to the player."
    ),
    (
        "When a team scores more goals than the other, they have ___.",
        {"A": "won", "B": "lost", "C": "drawn", "D": "tied"},
        "A",
        "easy",
        "54",
        "L4",
        ["Winning means scoring more than the opponent."],
        "You win when you score more goals.",
        "Our team won the match 4-2."
    ),
    (
        "A competition where teams are grouped and play a set number of matches is a ___ stage.",
        {"A": "group", "B": "final", "C": "knockout", "D": "semi-final"},
        "A",
        "medium",
        "55",
        "L4",
        ["A group stage divides teams into groups to play each other."],
        "The group stage is the first part of many tournaments.",
        "Teams compete in a group stage before the knockout rounds."
    ),
    (
        "What do we call it when a match ends with no winner?",
        {"A": "a draw", "B": "a win", "C": "a loss", "D": "a goal"},
        "A",
        "easy",
        "54",
        "L4",
        ["A draw means both teams score the same number of points."],
        "A draw means the result is equal.",
        "The match ended in a draw at 2-2."
    ),
    (
        "Which word means to throw the ball into the goal in football?",
        {"A": "to score", "B": "to catch", "C": "to kick", "D": "to throw"},
        "A",
        "easy",
        "54",
        "L4",
        ["To score means to get a goal or point."],
        "Scoring means putting the ball in the goal.",
        "He managed to score in the last minute."
    ),
    (
        "A person who trains and leads a sports team is called a ___.",
        {"A": "coach", "B": "referee", "C": "spectator", "D": "umpire"},
        "A",
        "easy",
        "54",
        "L4",
        ["A coach trains and guides a sports team."],
        "The coach gives advice and plans strategies.",
        "Our coach prepared us well for the final."
    ),
    (
        "The sport of hitting a small ball with a club into a hole is ___.",
        {"A": "golf", "B": "tennis", "C": "cricket", "D": "hockey"},
        "A",
        "easy",
        "55",
        "L4",
        ["Golf is played with clubs and balls on a large course."],
        "Golf uses a club to hit a ball into holes.",
        "Golf requires patience and precision."
    ),
    (
        "A place where indoor sports like basketball and volleyball are played is called a(n) ___.",
        {"A": "arena", "B": "pitch", "C": "pool", "D": "field"},
        "A",
        "medium",
        "55",
        "L4",
        ["An arena is a large indoor venue for sports and events."],
        "An arena hosts indoor sports competitions.",
        "The basketball game was held in a big arena."
    ),
    (
        "When athletes compete against each other in sports, this is called ___.",
        {"A": "rivalry", "B": "friendship", "C": "training", "D": "休息"},
        "A",
        "medium",
        "55",
        "L4",
        ["Rivalry is strong competition between opponents."],
        "Rivalry means competing fiercely against someone.",
        "The rivalry between the two teams is very old."
    ),
    (
        "What is the person who plays a sport called?",
        {"A": "athlete", "B": "spectator", "C": "coach", "D": "manager"},
        "A",
        "easy",
        "54",
        "L4",
        ["An athlete is a person who plays sports."],
        "Athletes compete in sports competitions.",
        "She is a talented athlete who runs very fast."
    ),
    (
        "When you practice before a competition, you are ___.",
        {"A": "training", "B": "resting", "C": "winning", "D": "losing"},
        "A",
        "easy",
        "54",
        "L4",
        ["Training means practicing to improve your performance."],
        "Training prepares you for competition.",
        "The team trained hard before the final."
    ),
    (
        "A hard surface for playing basketball and tennis is called a ___.",
        {"A": "court", "B": "pitch", "C": "pool", "D": "track"},
        "A",
        "easy",
        "54",
        "L4",
        ["A court is a hard-surface playing area."],
        "Courts are used for basketball, tennis, and volleyball.",
        "The tennis court was in excellent condition."
    ),
    (
        "Which word means a competition with many rounds leading to a winner?",
        {"A": "tournament", "B": "practice", "C": "exercise", "D": "lesson"},
        "A",
        "medium",
        "55",
        "L4",
        ["A tournament is a competition with several rounds of matches."],
        "A tournament has multiple stages and rounds.",
        "The school organized a basketball tournament."
    ),
    (
        "The first place in a competition is called ___.",
        {"A": "first prize", "B": "last place", "C": "starting point", "D": "warm-up"},
        "A",
        "easy",
        "54",
        "L4",
        ["First prize is awarded to the winner of a competition."],
        "The winner receives the first prize.",
        "She won first prize in the swimming competition."
    ),
    (
        "What does a captain do in a sports team?",
        {"A": "leads the team", "B": "watches the game", "C": "plays music", "D": "sells tickets"},
        "A",
        "easy",
        "54",
        "L4",
        ["The captain is the leader of the team on the field."],
        "A captain leads and motivates the team.",
        "The captain lifted the trophy after the final."
    ),
    (
        "In swimming, the different strokes include freestyle, breaststroke, and ___.",
        {"A": "butterfly", "B": "cricket", "C": "tennis", "D": "boxing"},
        "A",
        "medium",
        "55",
        "L4",
        ["Butterfly is one of the swimming strokes."],
        "Butterfly is a difficult but fast swimming style.",
        "She won the gold medal in the butterfly event."
    ),
    (
        "A large grass area for playing football is called a ___.",
        {"A": "pitch", "B": "court", "C": "pool", "D": "ring"},
        "A",
        "easy",
        "54",
        "L4",
        ["A pitch is a grass field for football or cricket."],
        "Football is played on a green pitch.",
        "The pitch was wet after the rain."
    ),
    (
        "When two teams play and the score is equal, we say it is a ___.",
        {"A": "draw", "B": "win", "C": "loss", "D": "goal"},
        "A",
        "easy",
        "54",
        "L4",
        ["A draw means both teams have the same score."],
        "Draw means no winner at the end.",
        "The game ended in a 1-1 draw."
    ),
    (
        "What is the area around a sports field where people sit?",
        {"A": "the stands", "B": "the court", "C": "the pitch", "D": "the pool"},
        "A",
        "medium",
        "55",
        "L4",
        ["The stands are seats for spectators around a sports field."],
        "Spectators sit in the stands to watch games.",
        "The stands were full during the championship."
    ),
    (
        "To get better at a sport, you need to ___.",
        {"A": "practice regularly", "B": "sleep all day", "C": "watch TV", "D": "eat sweets"},
        "A",
        "easy",
        "54",
        "L4",
        ["Regular practice improves your sporting skills."],
        "Practice makes you better at sports.",
        "She practices every day to improve her speed."
    ),
    (
        "A competition between two people is called a ___.",
        {"A": "match", "B": "class", "C": "lesson", "D": "meeting"},
        "A",
        "easy",
        "54",
        "L4",
        ["A match is a contest between two players or teams."],
        "A match is a sporting competition.",
        "The tennis match lasted for three hours."
    ),
    (
        "Which sport uses a net, a shuttlecock, and rackets?",
        {"A": "badminton", "B": "football", "C": "swimming", "D": "running"},
        "A",
        "medium",
        "54",
        "L4",
        ["Badminton is played with rackets, a net, and a shuttlecock."],
        "Badminton needs rackets and a shuttlecock.",
        "Badminton is a popular indoor sport."
    ),
    (
        "When an athlete retires from professional sport, they ___.",
        {"A": "stop competing permanently", "B": "start training", "C": "join a new team", "D": "win a medal"},
        "A",
        "hard",
        "55",
        "L4",
        ["Retiring means permanently stopping from professional sport."],
        "Retirement means ending a professional career.",
        "After winning the gold medal, he decided to retire."
    ),
]
