# Unit 2 Lesson 4 (Listening and Vocabulary: Space tourism, page 20)
ITEMS = [
    ("What is the lesson about?",
     {"A": "space tourism", "B": "farming", "C": "public transport", "D": "hotel management"},
     "A", "easy", 20, "Lesson 4A: Listening and Vocabulary",
     ["The lesson is about space tourism, based on three conversations."],
     "The topic is space tourism.", "The conversations discuss space travel."),

    ("Complete: 'Do you think the employees get their fair ______ of the money?'",
     {"A": "share", "B": "part", "C": "half", "D": "amount"},
     "A", "easy", 20, "Exercise 3: Collocations",
     ["The collocation is 'a fair share of something'."],
     "fair share", "It means a fair amount that you deserve."),

    ("What does 'a fair share' mean?",
     {"A": "a fair part or amount that someone deserves", "B": "a share in a company", "C": "an equal price", "D": "a small piece"},
     "A", "easy", 20, "Exercise 3: Collocations",
     ["'A fair share' means the amount that is fair for you to have."],
     "fair share = fair amount.", "Do the employees get their fair share of the money?"),

    ("Complete: 'What ______ might you have to overcome to be successful in your career?'",
     {"A": "hurdles", "B": "walls", "C": "gates", "D": "fences"},
     "A", "easy", 20, "Exercise 3: Collocations",
     ["The collocation is 'overcome hurdles'."],
     "hurdles", "Hurdles are problems or obstacles."),

    ("What does 'overcome hurdles' mean?",
     {"A": "to deal with obstacles or difficulties", "B": "to jump over fences", "C": "to run a race", "D": "to avoid problems"},
     "A", "easy", 20, "Exercise 3: Collocations",
     ["'Hurdles' are difficulties; to overcome them means to deal with them successfully."],
     "overcome hurdles = deal with obstacles.", "You may have hurdles to overcome in your career."),

    ("Complete: 'Do you think you would enjoy travelling at ______ speed?'",
     {"A": "breakneck", "B": "slow", "C": "lightning", "D": "gentle"},
     "A", "medium", 20, "Exercise 3: Collocations",
     ["The collocation is 'breakneck speed'."],
     "breakneck speed", "Breakneck means extremely fast and dangerous."),

    ("What does 'breakneck speed' mean?",
     {"A": "extremely fast, dangerously fast", "B": "a slow, steady speed", "C": "the speed of walking", "D": "average speed"},
     "A", "easy", 20, "Exercise 3: Collocations",
     ["'Breakneck speed' means dangerously fast."],
     "breakneck = extremely fast.", "Travelling in space would be at breakneck speed."),

    ("Complete: 'Do you think there are any areas on Earth where humans have not left their ______?'",
     {"A": "mark", "B": "sign", "C": "footstep", "D": "trace"},
     "A", "medium", 20, "Exercise 3: Collocations",
     ["The collocation is 'leave your mark'."],
     "left their mark", "It means having an effect or influence on a place."),

    ("What does 'leave your mark' mean?",
     {"A": "to have a noticeable effect or influence", "B": "to write your name", "C": "to make a mess", "D": "to lose something"},
     "A", "medium", 20, "Exercise 3: Collocations",
     ["'Leave your mark' means to have an effect on something that lasts."],
     "leave your mark = have an influence.", "Humans have left their mark almost everywhere."),

    ("Complete: 'Have you done anything recently that you might be tempted to ______ about?'",
     {"A": "brag", "B": "complain", "C": "forget", "D": "apologise"},
     "A", "medium", 20, "Exercise 3: Collocations",
     ["'Brag' means to talk about yourself with too much pride."],
     "brag", "You brag about things you are proud of."),

    ("What does 'brag' mean?",
     {"A": "to talk proudly about yourself or your achievements", "B": "to complain loudly", "C": "to whisper secretly", "D": "to ask questions"},
     "A", "easy", 20, "Exercise 3: Collocations",
     ["'Brag' means to boast, to talk proudly."],
     "brag = boast.", "People may brag about exciting experiences."),

    ("Complete: 'What might be the knock-on ______ of more spending on space research?'",
     {"A": "effect", "B": "causes", "C": "answers", "D": "benefits"},
     "A", "easy", 20, "Exercise 3: Collocations",
     ["The collocation is 'knock-on effect'."],
     "knock-on effect", "A knock-on effect is an indirect result."),

    ("What does 'knock-on effect' mean?",
     {"A": "an indirect result caused by something else", "B": "a small accident", "C": "a direct order", "D": "a sudden change of plan"},
     "A", "medium", 20, "Exercise 3: Collocations",
     ["A knock-on effect happens as an indirect result of another action."],
     "knock-on effect = indirect result.", "More spending on research would have knock-on effects."),

    ("Complete: 'We're going for a quick ______ (away) to Amman at the weekend.'",
     {"A": "breakaway", "B": "breakdown", "C": "breakthrough", "D": "breakup"},
     "A", "medium", 20, "Exercise 4: Phrasal nouns",
     ["'Breakaway' = a short trip away from home."],
     "breakaway", "A quick breakaway is a short holiday."),

    ("What does 'breakaway' mean in 'a quick breakaway to Amman'?",
     {"A": "a short trip or holiday away", "B": "a business deal", "C": "a flight delay", "D": "an argument"},
     "A", "medium", 20, "Exercise 4: Phrasal nouns",
     ["'Breakaway' here means a short holiday away from home."],
     "breakaway = short trip away.", "They are going for the weekend."),

    ("Complete: 'The ______ (out) of the investigation into the collision will not be known before March.'",
     {"A": "outcome", "B": "outlet", "C": "outline", "D": "outlook"},
     "A", "medium", 20, "Exercise 4: Phrasal nouns",
     ["'Outcome' = the final result of something."],
     "outcome", "The outcome of the investigation is the result."),

    ("What does 'outcome' mean?",
     {"A": "the final result of an activity", "B": "the beginning of a process", "C": "a mistake in a plan", "D": "a question"},
     "A", "easy", 20, "Exercise 4: Phrasal nouns",
     ["'Outcome' is the final result."],
     "outcome = final result.", "We will know the outcome of the investigation in March."),

    ("Complete: 'They've recently made an amazing ______ (through) in developing driverless cars.'",
     {"A": "breakthrough", "B": "breakdown", "C": "breakaway", "D": "breakout"},
     "A", "easy", 20, "Exercise 4: Phrasal nouns",
     ["'Breakthrough' = an important discovery or development."],
     "breakthrough", "Driverless cars had an amazing breakthrough."),

    ("What does 'breakthrough' mean?",
     {"A": "an important discovery or advance", "B": "a small accident", "C": "an old-fashioned idea", "D": "a broken machine"},
     "A", "easy", 20, "Exercise 4: Phrasal nouns",
     ["A breakthrough is a major advance or discovery."],
     "breakthrough = major advance.", "It changed the development of driverless cars."),

    ("Complete: 'The weather ______ (out) for May sounds really good, so let's book a holiday.'",
     {"A": "outlook", "B": "outcome", "C": "outcry", "D": "outlay"},
     "A", "medium", 20, "Exercise 4: Phrasal nouns",
     ["'Outlook' = the forecast or expected situation for the future."],
     "outlook", "The weather outlook for May is good."),

    ("What does 'outlook' mean?",
     {"A": "the expected situation for the future", "B": "a view from a window", "C": "a type of email", "D": "a sudden problem"},
     "A", "medium", 20, "Exercise 4: Phrasal nouns",
     ["'Outlook' can mean the forecast for the future, like the weather outlook."],
     "outlook = forecast.", "The weather outlook for May sounds good."),

    ("Complete: 'Due to a ______ (back), it won't be finished until next week.'",
     {"A": "setback", "B": "setoff", "C": "setup", "D": "setdown"},
     "A", "medium", 20, "Exercise 4: Phrasal nouns",
     ["'Setback' = a problem that delays progress."],
     "setback", "The printing had a setback."),

    ("What does 'setback' mean?",
     {"A": "a problem that delays progress", "B": "a positive result", "C": "a new beginning", "D": "a quick decision"},
     "A", "easy", 20, "Exercise 4: Phrasal nouns",
     ["A setback is a difficulty that causes delay."],
     "setback = a delaying problem.", "The report won't be finished on time."),

    ("Complete: 'From the ______ (out), scientists have warned of the potential dangers of space junk.'",
     {"A": "outset", "B": "output", "C": "outlook", "D": "outbreak"},
     "A", "medium", 20, "Exercise 4: Phrasal nouns",
     ["'Outset' = the beginning."],
     "outset", "From the outset = from the start."),

    ("What does 'from the outset' mean?",
     {"A": "from the beginning", "B": "from the end", "C": "from outside", "D": "from time to time"},
     "A", "easy", 20, "Exercise 4: Phrasal nouns",
     ["'Outset' means the start or beginning."],
     "from the outset = from the beginning.", "Scientists warned of the dangers from the start."),

    ("Complete: 'The initial ______ (out) for developing a space tourist programme was immense.'",
     {"A": "outlay", "B": "outlet", "C": "outcome", "D": "outline"},
     "A", "hard", 20, "Exercise 4: Phrasal nouns",
     ["'Outlay' = money spent on something."],
     "outlay", "The initial outlay was immense."),

    ("What does 'outlay' mean?",
     {"A": "money that you have to spend", "B": "money that you earn", "C": "a type of tax", "D": "a discount"},
     "A", "hard", 20, "Exercise 4: Phrasal nouns",
     ["'Outlay' is the amount of money spent, especially to start something."],
     "outlay = money spent.", "The start-up outlay was immense but it will make a profit."),

    ("Complete: 'There would be an ______ (out) if the company made too many comebacks.'",
     {"A": "outcry", "B": "outfit", "C": "outlook", "D": "outset"},
     "A", "hard", 20, "Exercise 4: Phrasal nouns",
     ["'Outcry' = a strong public protest or reaction."],
     "outcry", "People would protest strongly."),

    ("What does 'outcry' mean?",
     {"A": "a strong public protest", "B": "a loud shout of joy", "C": "a quiet agreement", "D": "a written complaint"},
     "A", "medium", 20, "Exercise 4: Phrasal nouns",
     ["An outcry is an angry public reaction."],
     "outcry = strong protest.", "Too many delays would cause an outcry."),

    ("What does 'comeback' mean?",
     {"A": "a return or a way of returning", "B": "a new product", "C": "a holiday", "D": "a mistake"},
     "A", "hard", 20, "Exercise 4: Phrasal nouns",
     ["'Comeback' means a return to an activity or situation, or a quick answer."],
     "comeback = a return.", "The company should not make too many comebacks (delays)."),

    ("What are 'phrasal nouns'?",
     {"A": "nouns formed from a verb and a preposition", "B": "verbs formed from nouns", "C": "adjectives formed from verbs", "D": "nouns that never change form"},
     "A", "medium", 20, "Exercise 4: Phrasal nouns",
     ["Phrasal nouns are made from a verb and a preposition, e.g. breakaway from 'break away'."],
     "phrasal nouns = verb + preposition.", "Examples: breakaway, outcome, breakthrough."),

    ("Complete: 'They've made an amazing ______ in developing driverless cars.'",
     {"A": "breakthrough", "B": "breakaway", "C": "breakdown", "D": "breakup"},
     "A", "easy", 20, "Exercise 4: Phrasal nouns",
     ["'Breakthrough' is the right phrasal noun here."],
     "breakthrough", "It is a major advance in technology."),

    ("What topic is discussed in the space tourism conversations?",
     {"A": "the costs of tickets to go into space", "B": "the best space hotels", "C": "how to become an astronaut quickly", "D": "space food recipes"},
     "A", "medium", 20, "Exercise 1: Space tourism topics",
     ["The topics include costs of tickets, collisions, life on the Space Station and space junk."],
     "The costs of tickets is a topic.", "One of the five topics is ticket costs."),

    ("What is 'space junk'?",
     {"A": "old spacecraft and debris left in space", "B": "litter left by tourists on Earth", "C": "rubbish in the ocean", "D": "space food wrappers"},
     "A", "easy", 20, "Exercise 1: Space tourism topics",
     ["Space junk is debris or old objects orbiting the Earth."],
     "space junk = debris in orbit.", "There are projects to clear space junk."),

    ("What is one problem caused by space junk mentioned in the lesson?",
     {"A": "possible collisions of objects in space", "B": "higher ticket prices", "C": "fewer flights to the moon", "D": "noisy launches"},
     "A", "medium", 20, "Exercise 1: Space tourism topics",
     ["One topic is possible collisions of objects in space."],
     "Space junk could cause collisions.", "Objects in space travel at high speed."),

    ("Which of these is a topic in the lesson?",
     {"A": "likelihood of future settlements on planets", "B": "building hotels under the sea", "C": "farming on Earth", "D": "holidays at the beach"},
     "A", "medium", 20, "Exercise 1: Space tourism topics",
     ["The topics include future settlements on planets."],
     "Future settlements is a topic.", "The lesson also covers life on the Space Station."),

    ("What might be a 'knock-on effect' of more spending on space research?",
     {"A": "new technologies that benefit people on Earth", "B": "fewer jobs for scientists", "C": "less money for food", "D": "bigger traffic jams"},
     "A", "hard", 20, "Exercise 3: Knock-on effect",
     ["A knock-on effect is an indirect result; research often leads to new useful technologies."],
     "New technologies would be a knock-on effect.", "It is an indirect result of the spending."),

    ("Complete: 'Do you think you would enjoy travelling at breakneck ______?'",
     {"A": "speed", "B": "rate", "C": "pace", "D": "tempo"},
     "A", "easy", 20, "Exercise 3: Collocations",
     ["The collocation is 'breakneck speed'."],
     "speed", "Breakneck speed = extremely fast."),

    ("In space, what speed do objects travel at?",
     {"A": "very high speed", "B": "no speed at all", "C": "walking speed", "D": "the speed of light exactly"},
     "A", "hard", 20, "Exercise 2: Listening focus",
     ["The listening mentions the speed at which items in space are travelling."],
     "Objects travel at great speed.", "Speed is a key detail in the conversations."),

    ("Complete: 'What hurdles might you have to ______ to be successful in your chosen career?'",
     {"A": "overcome", "B": "undermine", "C": "ignore", "D": "create"},
     "A", "easy", 20, "Exercise 3: Collocations",
     ["The collocation is 'overcome hurdles'."],
     "overcome", "Hurdles are obstacles to overcome."),
]
