# Unit 3 Lesson 5 (Grammar: The Passive, pages 32-33)
ITEMS = [
    ("When do we use the passive rather than the active?",
     {"A": "when we don't know who did something or want to focus on the action", "B": "when we want to talk about the agent", "C": "when we write informal emails", "D": "when the subject is a person"},
     "A", "easy", 32, "Grammar reference",
     ["Use the passive when the agent is unknown or less important."],
     "Focus on the action or object.", "We use it when the doer is obvious or unknown."),

    ("What is the structure of a passive sentence?",
     {"A": "be + past participle", "B": "have + past participle", "C": "do + infinitive", "D": "be + -ing"},
     "A", "easy", 32, "Grammar reference",
     ["The passive uses the verb 'be' plus a past participle."],
     "be + past participle", "The past participle changes with tenses."),

    ("Which sentence is passive?",
     {"A": "The bananas were being taken away.", "B": "I took the bananas away.", "C": "They took the bananas away.", "D": "Taking the bananas away."},
     "A", "easy", 32, "Exercise 1",
     ["'were being taken away' is be + being + past participle."],
     "were being taken = passive", "The other options have active subjects."),

    ("What do passive constructions allow you to do?",
     {"A": "express points of view without saying who has them", "B": "make sentences longer", "C": "hide the truth", "D": "avoid writing verbs"},
     "A", "easy", 32, "Grammar text",
     ["'Passive constructions allow you to express points of view without saying who holds them.'"],
     "Give opinions without naming the person.", "It makes statements sound neutral."),

    ("Why does economics writing use the passive a lot?",
     {"A": "it is formal and allows objective statements", "B": "it is easier to write", "C": "it is a new fashion", "D": "it sounds more emotional"},
     "A", "medium", 32, "Grammar text",
     ["Economics is about reasoned, formal argument, so the passive suits it."],
     "Formal, objective writing.", "Economists avoid emotional statements."),

    ("Which sentence is more formal?",
     {"A": "The data were analysed.", "B": "I analysed the data.", "C": "We looked at the data.", "D": "Somebody checked the data."},
     "A", "medium", 32, "Grammar text",
     ["The passive removes the personal agent, which is more formal."],
     "Passive is more formal.", "It is common in academic writing."),

    ("To express a present general truth, which is correct?",
     {"A": "It is said that money makes the world go round.", "B": "It was said that money makes the world go round.", "C": "It is saying that money...", "D": "Money is make the world go round."},
     "A", "easy", 32, "Exercise: grammar",
     ["For present general truths, use 'It is said' + that clause."],
     "is said (present passive)", "Past would be 'It was said'."),

    ("What is the passive form of 'The government increased taxes'?",
     {"A": "Taxes were increased (by the government).", "B": "Taxes are increase.", "C": "The government was increased taxes.", "D": "Taxes were increasing."},
     "A", "easy", 32, "Exercise 2",
     ["The object becomes the subject: Taxes were increased."],
     "Taxes were increased", "The agent is often omitted."),

    ("What is the passive of 'An economist wrote the report'?",
     {"A": "The report was written by an economist.", "B": "The report was writing by an economist.", "C": "An economist was written the report.", "D": "The report is wrote by an economist."},
     "A", "easy", 32, "Exercise 2",
     ["The report was written by an economist."],
     "The report was written", "The agent stays with 'by'."),

    ("What is the passive of 'They will build a new road'?",
     {"A": "A new road will be built.", "B": "A new road will build.", "C": "A new road was built.", "D": "They will be built a new road."},
     "A", "medium", 32, "Exercise 2",
     ["Future passive: will be + past participle."],
     "will be built", "Future simple passive."),

    ("What is the passive of 'They have raised the price'?",
     {"A": "The price has been raised.", "B": "The price has raised.", "C": "The price was raising.", "D": "The price have been raised."},
     "A", "medium", 32, "Exercise 2",
     ["Present perfect passive: has/have been + past participle."],
     "has been raised", "Note 'the price' is singular."),

    ("What is the passive of 'Someone stole my wallet'?",
     {"A": "My wallet was stolen.", "B": "My wallet was stealing.", "C": "My wallet is stolen.", "D": "Someone was stolen my wallet."},
     "A", "easy", 32, "Exercise 2",
     ["My wallet was stolen."],
     "was stolen", "Past simple passive."),

    ("What is the passive of 'They are repairing the bridge'?",
     {"A": "The bridge is being repaired.", "B": "The bridge is repairing.", "C": "The bridge was repaired.", "D": "The bridge repairs."},
     "A", "medium", 32, "Exercise 2",
     ["Present continuous passive: is/are being + past participle."],
     "is being repaired", "Emphasises an ongoing action."),

    ("Two-object passives: 'The company gave him a bonus.' What is the first passive form?",
     {"A": "He was given a bonus (by the company).", "B": "A bonus was giving him.", "C": "He was gave a bonus.", "D": "Him was given a bonus."},
     "A", "hard", 32, "Grammar reference",
     ["With two objects, make the person the subject: He was given a bonus."],
     "He was given a bonus", "This is the more common passive form."),

    ("What is the second passive form of 'The company gave him a bonus'?",
     {"A": "A bonus was given (to him) by the company.", "B": "A bonus was given him by the company.", "C": "A bonus was gave him.", "D": "A bonus was giving by the company."},
     "A", "hard", 32, "Grammar reference",
     ["Make the thing the subject: A bonus was given to him by the company."],
     "A bonus was given to him", "Both forms are possible."),

    ("Two-object passives: 'They offered her a job.' Which is correct?",
     {"A": "She was offered a job.", "B": "A job was offering her.", "C": "She was offer a job.", "D": "Her was offered a job."},
     "A", "hard", 32, "Grammar reference",
     ["The person becomes the subject: She was offered a job."],
     "She was offered a job", "Also: A job was offered to her."),

    ("Which preposition introduces the agent in a passive sentence?",
     {"A": "by", "B": "for", "C": "with", "D": "from"},
     "A", "easy", 32, "Grammar reference",
     ["The agent is introduced with 'by'."],
     "by + agent", "The report was written BY an economist."),

    ("When do we NOT use 'by + agent'?",
     {"A": "when it is obvious or not important who did it", "B": "when the sentence is long", "C": "when the verb is irregular", "D": "when we want to be clear"},
     "A", "medium", 32, "Grammar reference",
     ["The agent is left out when it is obvious or unimportant."],
     "Leave out the agent when obvious.", "'The thief was arrested' - we know by police."),

    ("What does the word 'puzzling' in the economics text mean?",
     {"A": "confusing / surprising", "B": "easy", "C": "boring", "D": "perfect"},
     "A", "hard", 32, "Exercise: vocabulary",
     ["'Puzzling' describes something confusing or hard to explain."],
     "puzzling = confusing", "It refers to something odd that needs explaining."),

    ("What does 'clever' mean in the phrase 'those who design ways to make us spend'?",
     {"A": "cunning and skilful", "B": "honest and simple", "C": "slow and careful", "D": "rich and famous"},
     "A", "hard", 32, "Exercise: vocabulary",
     ["In this context 'clever' means skilful and cunning."],
     "clever = cunning here.", "They design traps to make us spend."),

    ("Complete: Money is what makes the world ____ round.",
     {"A": "go", "B": "going", "C": "gone", "D": "to go"},
     "A", "easy", 33, "Grammar text",
     ["'It is said that money makes the world go round.'"],
     "go", "A present general truth."),

    ("Why is it not simply the rich who enjoy the fruits of the economy?",
     {"A": "wealth is distributed - some of it reaches us all", "B": "the rich spend nothing", "C": "everyone is rich", "D": "the economy is closed"},
     "A", "hard", 33, "Grammar text",
     ["Despite growing inequality, some wealth is distributed through the economy."],
     "Some wealth reaches everyone.", "The sentence introduces the text's topic."),

    ("Complete the gap: It is generally ____ that the economy is doing well.",
     {"A": "believed", "B": "believing", "C": "believe", "D": "believes"},
     "A", "medium", 33, "Grammar gap",
     ["'It is believed that...' is a common passive structure."],
     "is believed", "Present passive + that clause."),

    ("Complete the gap: The price of oil ____ by the crisis.",
     {"A": "was affected", "B": "was affecting", "C": "affected", "D": "is affect"},
     "A", "medium", 33, "Grammar gap",
     ["The price was affected by the crisis."],
     "was affected", "Past passive with 'by + agent'."),

    ("Which structure means the same as 'People say that he is rich'?",
     {"A": "He is said to be rich.", "B": "He is saying to be rich.", "C": "He says to be rich.", "D": "He is said being rich."},
     "A", "medium", 33, "Grammar: transformation",
     ["'He is said to be rich' = people say he is rich."],
     "He is said to be rich", "A common reporting passive."),

    ("Which structure means the same as 'People think she works hard'?",
     {"A": "She is thought to work hard.", "B": "She is thought working hard.", "C": "She thought to work hard.", "D": "She is thought to working hard."},
     "A", "medium", 33, "Grammar: transformation",
     ["Subject + be + past participle + to + infinitive."],
     "She is thought to work hard", "Present infinitive after 'to'."),

    ("Which structure means the same as 'People believe he built a fortune'?",
     {"A": "He is believed to have built a fortune.", "B": "He is believed to build a fortune.", "C": "He is believed building a fortune.", "D": "He was believed to building a fortune."},
     "A", "hard", 33, "Grammar: transformation",
     ["For the past, use 'to have + past participle'."],
     "is believed to have built", "Perfect infinitive shows an earlier action."),

    ("Which structure means the same as 'It was reported that sales fell'?",
     {"A": "Sales were reported to have fallen.", "B": "Sales are reported to fall.", "C": "Sales reported to have fallen.", "D": "It was reported sales fall."},
     "A", "hard", 33, "Grammar: transformation",
     ["'Sales were reported to have fallen' matches the past report."],
     "were reported to have fallen", "Keep both verbs in the past."),

    ("Why does the writer of the economics text use 'It is said' rather than 'People say'?",
     {"A": "to sound neutral and formal", "B": "to sound angry", "C": "to make the text shorter", "D": "to make a joke"},
     "A", "medium", 33, "Grammar text",
     ["Passives with 'It is said' give an impersonal, formal tone."],
     "Impersonal and formal", "A typical economics style."),

    ("In the text, what is described as 'extremely puzzling'?",
     {"A": "the fact that we keep buying things we don't need", "B": "the rise in prices", "C": "the weather", "D": "the stock market"},
     "A", "hard", 33, "Grammar text",
     ["The writer finds our continued spending puzzling."],
     "We keep buying what we don't need.", "It seems to make no sense."),

    ("What 'puzzling' question does the text ask?",
     {"A": "whether money brings happiness", "B": "whether taxes are fair", "C": "how banks work", "D": "who is richest"},
     "A", "hard", 33, "Grammar text",
     ["The text asks whether money actually makes us happier."],
     "Does money bring happiness?", "It questions the value of wealth."),

    ("Complete the gap: The film ____ by millions of people.",
     {"A": "was watched", "B": "was watching", "C": "watched", "D": "is watch"},
     "A", "easy", 33, "Grammar gap",
     ["The film was watched by millions of people."],
     "was watched", "Past passive."),

    ("Complete the gap: The exam results ____ tomorrow.",
     {"A": "will be announced", "B": "will announce", "C": "will be announce", "D": "are announcing"},
     "A", "medium", 33, "Grammar gap",
     ["Future passive: will be + past participle."],
     "will be announced", "Results will be announced tomorrow."),

    ("Complete the gap: The homework ____ already been checked.",
     {"A": "has", "B": "have", "C": "is", "D": "was"},
     "A", "medium", 33, "Grammar gap",
     ["'The homework has already been checked.'"],
     "has", "has been checked."),

    ("Which of these is an advantage of the passive in academic writing?",
     {"A": "it makes statements sound more authoritative and objective", "B": "it makes writing less clear", "C": "it hides important information", "D": "it is informal"},
     "A", "easy", 32, "Grammar text",
     ["Passives sound objective, formal and authoritative."],
     "Objective and authoritative", "It removes the personal."),

    ("Transform to passive: 'They send emails every day.'",
     {"A": "Emails are sent every day.", "B": "Emails are sending every day.", "C": "Emails was sent every day.", "D": "Emails is sent every day."},
     "A", "easy", 32, "Exercise 2",
     ["Present simple passive: Emails are sent every day."],
     "Emails are sent", "Present simple passive."),

    ("Transform to passive: 'They built this tower in 1920.'",
     {"A": "This tower was built in 1920.", "B": "This tower is built in 1920.", "C": "This tower was building in 1920.", "D": "This tower built in 1920."},
     "A", "easy", 32, "Exercise 2",
     ["Past simple passive: This tower was built in 1920."],
     "was built", "The agent is unimportant here."),

    ("Transform to passive: 'We must pay the bill by Friday.'",
     {"A": "The bill must be paid by Friday.", "B": "The bill must pay by Friday.", "C": "The bill must be pay by Friday.", "D": "The bill must be paying by Friday."},
     "A", "hard", 32, "Exercise 2",
     ["Modal passive: must + be + past participle."],
     "must be paid", "Modal verbs use 'be + pp'."),

    ("Transform to passive: 'They have cancelled the match.'",
     {"A": "The match has been cancelled.", "B": "The match has cancelled.", "C": "The match have been cancelled.", "D": "The match is cancelled by."},
     "A", "medium", 32, "Exercise 2",
     ["Present perfect passive: has/have been + past participle."],
     "has been cancelled", "'The match' is singular."),

    ("Which sentence correctly uses 'it' + passive?",
     {"A": "It is believed that prices will rise.", "B": "It is believing that prices will rise.", "C": "It believed that prices will rise.", "D": "It is believed prices will rising."},
     "A", "medium", 33, "Grammar: it + passive",
     ["'It is believed that...' is the standard structure."],
     "It is believed that", "Use the past participle after 'is'."),
]
