# Unit 1 Review (all lessons, pages 4-13)
ITEMS = [
    ("What type of compound adjective is 'world-famous'?",
     {"A": "noun + adjective", "B": "adjective + adjective", "C": "adverb + adjective", "D": "prefix + adjective"},
     "A", "easy", 5, "Review: L1",
     ["'world-famous' is formed from the noun 'world' and the adjective 'famous'."],
     "noun + adjective", "World combines with famous."),

    ("What does 'narrow-minded' mean?",
     {"A": "not willing to accept new ideas", "B": "very clever", "C": "very generous", "D": "very relaxed"},
     "A", "easy", 5, "Review: L1",
     ["'Narrow-minded' means not willing to listen to or accept new ideas."],
     "narrow-minded = not open to ideas.", "The opposite is open-minded."),

    ("Which adjective describes someone who recovers quickly after difficulties?",
     {"A": "resilient", "B": "defensive", "C": "capable", "D": "tough"},
     "A", "easy", 5, "Review: L1",
     ["'Resilient' means able to recover quickly and return to normal after problems."],
     "resilient = able to recover quickly.", "A resilient person copes well with setbacks."),

    ("Which adjective describes someone who shows great interest and excitement?",
     {"A": "enthusiastic", "B": "resilient", "C": "tough", "D": "self-aware"},
     "A", "easy", 5, "Review: L1",
     ["'Enthusiastic' means showing strong interest, energy and excitement."],
     "enthusiastic = full of interest.", "An enthusiastic person shows great energy."),

    ("What does 'to set great store by' mean?",
     {"A": "to consider something important", "B": "to set up a shop", "C": "to store food", "D": "to keep something safe"},
     "A", "medium", 5, "Review: L1",
     ["'Set great store by' means to consider something to be very important."],
     "set great store by = consider important.", "If you set great store by values, you consider them important."),

    ("What does 'to plump for' mean?",
     {"A": "to choose", "B": "to become fat", "C": "to fall asleep", "D": "to give up"},
     "A", "medium", 5, "Review: L1",
     ["'Plump for' means to choose one thing from a number of possibilities."],
     "plump for = choose.", "To plump for something is to decide on it."),

    ("What does 'to get a kick out of' mean?",
     {"A": "to feel excitement and enjoyment", "B": "to kick something", "C": "to be angry", "D": "to be tired"},
     "A", "medium", 5, "Review: L1",
     ["'Get a kick out of' means to feel excitement and enjoyment from something."],
     "get a kick out of = enjoy very much.", "It gives you excitement and pleasure."),

    ("What does 'a dark horse' mean?",
     {"A": "a person with hidden ability", "B": "a horse that runs at night", "C": "a criminal", "D": "a farmer"},
     "A", "medium", 6, "Review: L2",
     ["'A dark horse' is someone who keeps their abilities secret and surprises others."],
     "a dark horse = someone with hidden ability.", "It is a personality idiom."),

    ("What does 'a go-getter' mean?",
     {"A": "an energetic, ambitious person", "B": "a person who gets lost", "C": "someone who steals", "D": "a lazy person"},
     "A", "easy", 6, "Review: L2",
     ["'A go-getter' is an energetic and determined person who tries hard to succeed."],
     "a go-getter = ambitious person.", "It describes someone who works hard."),

    ("What does 'a cold fish' mean?",
     {"A": "an unfriendly person who hides feelings", "B": "a person who loves cold weather", "C": "a very calm person", "D": "a shy person"},
     "A", "medium", 6, "Review: L2",
     ["'A cold fish' is an idiom for an unfriendly person who does not show emotions."],
     "a cold fish = unfriendly.", "The idiom describes someone cold and distant."),

    ("What does 'a social butterfly' mean?",
     {"A": "a very sociable person", "B": "a person who collects insects", "C": "a shy person", "D": "a scientist"},
     "A", "easy", 6, "Review: L2",
     ["'A social butterfly' is a very sociable person who loves being with many people."],
     "a social butterfly = very sociable.", "It describes someone who enjoys social events."),

    ("What does 'a smart cookie' mean?",
     {"A": "a clever and sensible person", "B": "a person who loves cakes", "C": "an unfriendly person", "D": "a person who makes quick decisions"},
     "A", "medium", 6, "Review: L2",
     ["'A smart cookie' means a clever, intelligent and sensible person."],
     "a smart cookie = a clever person.", "It is a compliment."),

    ("What does 'a soft touch' mean?",
     {"A": "a person who is easy to persuade", "B": "a person who is gentle", "C": "a strict person", "D": "a person who avoids contact"},
     "A", "hard", 6, "Review: L2",
     ["'A soft touch' is a person who is easily persuaded, especially to lend money."],
     "a soft touch = easy to persuade.", "A soft touch finds it hard to refuse requests."),

    ("Which phrase is used to paraphrase what someone said?",
     {"A": "In other words, ...", "B": "I agree with you, ...", "C": "That is wrong, ...", "D": "I don't care, ..."},
     "A", "easy", 6, "Review: L2",
     ["'In other words' is used to restate what someone said in different words."],
     "In other words = paraphrasing.", "It checks your understanding."),

    ("What does 'keep yourself to yourself' mean?",
     {"A": "to be private and not mix with others", "B": "to keep secrets from yourself", "C": "to take care of your health", "D": "to control your feelings"},
     "A", "medium", 6, "Review: L2",
     ["'Keep yourself to yourself' means to stay private and avoid mixing with others."],
     "keep yourself to yourself = stay private.", "People who keep to themselves avoid socialising."),

    ("Which word means 'character or personality'?",
     {"A": "disposition", "B": "destiny", "C": "vulnerability", "D": "offspring"},
     "A", "easy", 7, "Review: L3",
     ["'Disposition' means a person's character or usual mood."],
     "disposition = personality.", "It describes someone's natural tendency."),

    ("Which word means 'children'?",
     {"A": "offspring", "B": "onshore", "C": "upbringing", "D": "proponents"},
     "A", "easy", 7, "Review: L3",
     ["'Offspring' means children or young of a person or animal."],
     "offspring = children.", "It is a formal word for children."),

    ("Which word means 'suggest'?",
     {"A": "imply", "B": "impress", "C": "impose", "D": "imitate"},
     "A", "easy", 7, "Review: L3",
     ["'Imply' means to suggest something without saying it directly."],
     "imply = suggest indirectly.", "If someone implies something, they hint at it."),

    ("Which word means 'a particular characteristic'?",
     {"A": "trait", "B": "tray", "C": "treat", "D": "trance"},
     "A", "easy", 7, "Review: L3",
     ["'Trait' means a particular characteristic or way of behaving."],
     "trait = characteristic.", "Honesty is a personality trait."),

    ("Which word means 'what will happen in the future'?",
     {"A": "destiny", "B": "density", "C": "disposition", "D": "decency"},
     "A", "easy", 7, "Review: L3",
     ["'Destiny' means the future that is considered to be decided for someone."],
     "destiny = future fate.", "Some people believe personality and destiny are connected."),

    ("Which word means 'helping somebody to develop'?",
     {"A": "nurture", "B": "numb", "C": "mock", "D": "spark"},
     "A", "medium", 7, "Review: L3",
     ["'Nurture' means helping somebody to grow and develop."],
     "nurture = help to develop.", "Parents nurture their children's talents."),

    ("Which word describes something that passes from parent to child?",
     {"A": "hereditary", "B": "hierarchical", "C": "temporary", "D": "heredity"},
     "A", "easy", 7, "Review: L3",
     ["'Hereditary' means passed from parent to child through genes."],
     "hereditary = inherited.", "Some personality traits are hereditary."),

    ("Which word means 'the quality of being easily hurt'?",
     {"A": "vulnerability", "B": "versatility", "C": "sincerity", "D": "humility"},
     "A", "easy", 7, "Review: L3",
     ["'Vulnerability' is the quality of being easily hurt physically or emotionally."],
     "vulnerability = being easily hurt.", "A person's vulnerability makes them easy to hurt."),

    ("Which word means 'people who publicly support an idea'?",
     {"A": "proponents", "B": "opponents", "C": "employees", "D": "offspring"},
     "A", "easy", 7, "Review: L3",
     ["'Proponents' are people who publicly support an idea or theory."],
     "proponents = supporters.", "Proponents argue in favour of a cause."),

    ("Which word means 'making something so easy to understand that it is no longer accurate'?",
     {"A": "oversimplification", "B": "exaggeration", "C": "overpopulation", "D": "understatement"},
     "A", "hard", 7, "Review: L3",
     ["'Oversimplification' makes something so simple that it becomes inaccurate."],
     "oversimplification = too simple.", "Saying personality is only genetic is an oversimplification."),

    ("Which tense is used in 'I've just been running'?",
     {"A": "present perfect continuous", "B": "past perfect", "C": "future continuous", "D": "present simple"},
     "A", "easy", 8, "Review: L4",
     ["'I've just been running' uses have + been + -ing, i.e. the present perfect continuous."],
     "present perfect continuous", "It describes a recent activity."),

    ("We use the past perfect to describe ...",
     {"A": "an action that happened before another past action", "B": "an action happening now", "C": "a future plan", "D": "a temporary habit"},
     "A", "easy", 8, "Review: L4",
     ["The past perfect (had + past participle) refers to the earlier of two past actions."],
     "earlier past action", "It shows which action happened first."),

    ("Which tense describes an action in progress at a future time?",
     {"A": "future continuous", "B": "future perfect", "C": "present continuous", "D": "past continuous"},
     "A", "easy", 8, "Review: L4",
     ["The future continuous (will be + -ing) describes an action in progress at a future time."],
     "future continuous", "Example: 'This time next week I'll be studying.'"),

    ("Which sentence uses the past perfect continuous correctly?",
     {"A": "I had been waiting for two hours when the bus arrived.", "B": "I had been waiting for two hours when the bus will arrive.", "C": "I have been waiting when the bus arrived.", "D": "I was waiting when the bus had arrived."},
     "A", "medium", 8, "Review: L4",
     ["The past perfect continuous describes an action continuing up to a past moment."],
     "had been waiting", "The bus arrived while the waiting was in progress."),

    ("What is the main idea of the reading text?",
     {"A": "identity is shaped by genes, upbringing and experiences", "B": "only genes matter", "C": "identity never changes", "D": "personality tests are perfect"},
     "A", "easy", 10, "Review: L5",
     ["Identity is shaped by multiple factors working together."],
     "genes + upbringing + experience", "Both nature and nurture matter."),

    ("What does 'innate' mean?",
     {"A": "natural and present from birth", "B": "learned from experience", "C": "temporary", "D": "dangerous"},
     "A", "medium", 10, "Review: L5",
     ["'Innate' means something you are born with, natural and inborn."],
     "innate = inborn.", "Innate traits come from genes."),

    ("What does 'acquired' mean?",
     {"A": "learned or developed through experience", "B": "born with", "C": "forgotten", "D": "given as a gift"},
     "A", "medium", 10, "Review: L5",
     ["'Acquired' means gained or learned through experience."],
     "acquired = learned.", "Skills can be acquired over time."),

    ("What does 'to be self-aware' mean?",
     {"A": "to understand your own character and feelings", "B": "to not know yourself", "C": "to be very angry", "D": "to be very tall"},
     "A", "medium", 10, "Review: L5",
     ["'Self-aware' means knowing and understanding your own character."],
     "self-aware = knowing yourself.", "Self-awareness helps us grow."),

    ("What does 'to be resilient' mean?",
     {"A": "to recover quickly from difficulties", "B": "to be unable to change", "C": "to be very tall", "D": "to be very quiet"},
     "A", "medium", 10, "Review: L5",
     ["'Resilient' means able to recover quickly from problems."],
     "resilient = able to bounce back.", "Resilient people cope well with challenges."),

    ("What is a personal profile?",
     {"A": "a short description of a person's character and interests", "B": "a long essay", "C": "a type of exam", "D": "a recipe"},
     "A", "easy", 12, "Review: L6",
     ["A personal profile is a brief description of who you are."],
     "a self-description", "It introduces your qualities and interests."),

    ("What does 'to come across as' mean?",
     {"A": "to give the impression of being", "B": "to walk across", "C": "to find", "D": "to understand"},
     "A", "medium", 12, "Review: L6",
     ["'Come across as' means to give a particular impression to others."],
     "come across as = appear to be.", "You come across as friendly."),

    ("What does 'to get on well with' mean?",
     {"A": "to have a good relationship with", "B": "to travel on", "C": "to finish", "D": "to wake up"},
     "A", "easy", 12, "Review: L6",
     ["'Get on well with' means to have a friendly, harmonious relationship."],
     "get on well with = have a good relationship.", "I get on well with my classmates."),

    ("What does 'to be into' mean?",
     {"A": "to be very interested in", "B": "to enter a room", "C": "to be inside", "D": "to fall into water"},
     "A", "easy", 12, "Review: L6",
     ["'Be into' means to have a strong interest in or enjoyment of something."],
     "be into = be interested in.", "I'm into music and reading."),

    ("What does 'to look forward to' mean?",
     {"A": "to feel excited about something future", "B": "to look in front", "C": "to think about the past", "D": "to forget"},
     "A", "easy", 12, "Review: L6",
     ["'Look forward to' means to feel pleased and excited about something coming."],
     "look forward to = be excited about.", "I look forward to meeting new people."),

    ("What does 'to be keen on' mean?",
     {"A": "to be very interested in and enthusiastic about", "B": "to be sharp", "C": "to be angry", "D": "to be tired"},
     "A", "medium", 12, "Review: L6",
     ["'Be keen on' means to have a strong interest in and enthusiasm for something."],
     "be keen on = be enthusiastic about.", "She is keen on photography."),

    ("What does 'to get along with' mean?",
     {"A": "to have a friendly relationship with", "B": "to walk along", "C": "to finish", "D": "to understand"},
     "A", "easy", 12, "Review: L6",
     ["'Get along with' means to have a good, friendly relationship."],
     "get along with = get on well with.", "I get along with everyone."),

    ("What does 'to be good at' mean?",
     {"A": "to have a natural ability in something", "B": "to be kind to", "C": "to be near", "D": "to be angry about"},
     "A", "easy", 12, "Review: L6",
     ["'Be good at' means to have a natural skill or ability."],
     "be good at = have skill in.", "She is good at mathematics."),

    ("What does 'to be afraid of' mean?",
     {"A": "to feel fear or worry about", "B": "to be angry with", "C": "to be happy about", "D": "to be close to"},
     "A", "easy", 12, "Review: L6",
     ["'Be afraid of' means to feel fear or anxiety about something."],
     "be afraid of = fear.", "Some people are afraid of spiders."),

    ("What does 'to be proud of' mean?",
     {"A": "to feel pleased about an achievement", "B": "to feel sad about", "C": "to be angry about", "D": "to be tired of"},
     "A", "easy", 12, "Review: L6",
     ["'Be proud of' means to feel pleasure and satisfaction about an achievement."],
     "be proud of = feel satisfied about.", "I am proud of my exam results."),

    ("What does 'to be honest' mean?",
     {"A": "to tell the truth and be sincere", "B": "to lie", "C": "to keep secrets", "D": "to be rude"},
     "A", "easy", 12, "Review: L6",
     ["Being honest means telling the truth and being genuine."],
     "honest = truthful.", "Honesty is an important quality."),

    ("What does 'to be creative' mean?",
     {"A": "to enjoy coming up with new ideas", "B": "to follow rules exactly", "C": "to be very quiet", "D": "to be very old"},
     "A", "medium", 12, "Review: L6",
     ["Being creative means enjoying new ideas and original thinking."],
     "creative = imaginative.", "It is a positive personality trait."),

    ("What does 'to be hard-working' mean?",
     {"A": "to put a lot of effort into your work", "B": "to work very little", "C": "to avoid work", "D": "to only work on holidays"},
     "A", "easy", 12, "Review: L6",
     ["'Hard-working' means putting a lot of effort and time into tasks."],
     "hard-working = diligent.", "Hard-working students achieve more."),

    ("What does 'to be curious' mean?",
     {"A": "to want to learn and know more", "B": "to be bored", "C": "to be angry", "D": "to be afraid"},
     "A", "medium", 12, "Review: L6",
     ["'Curious' means wanting to learn and discover new things."],
     "curious = wanting to know.", "Curious people ask lots of questions."),

    ("What does 'to be sociable' mean?",
     {"A": "to enjoy being with other people", "B": "to avoid people", "C": "to be very quiet", "D": "to be very angry"},
     "A", "easy", 12, "Review: L6",
     ["'Sociable' means enjoying the company of other people."],
     "sociable = friendly and outgoing.", "Sociable people enjoy parties."),

    ("What does 'to be dependable' mean?",
     {"A": "to be reliable and trustworthy", "B": "to be unreliable", "C": "to be very lazy", "D": "to be very rude"},
     "A", "medium", 12, "Review: L6",
     ["'Dependable' means reliable and worthy of trust."],
     "dependable = reliable.", "A dependable friend keeps promises."),
]
