# Unit 2 Lesson 5 (Speaking: Considering options, page 21)
ITEMS = [
    ("What does 'There's a lot to be said for...' mean?",
     {"A": "there are good reasons to support something", "B": "something is difficult to say", "C": "nobody wants to talk", "D": "the speech is too long"},
     "A", "easy", 21, "Speaking box: Considering alternatives",
     ["'There's a lot to be said for X' means there are strong arguments in favour of X."],
     "There are good reasons for it.", "You use it to give a positive point."),

    ("Which phrase introduces the opposite side of an argument?",
     {"A": "But on the other hand, ...", "B": "I'd go for ... anytime!", "C": "No two ways about it, ...", "D": "It's pretty clear cut to me that ..."},
     "A", "easy", 21, "Speaking box: Considering alternatives",
     ["'But on the other hand' introduces the other point of view."],
     "But on the other hand = the opposite side.", "It balances an argument."),

    ("What does 'There are a lot of points in favour of...' mean?",
     {"A": "there are many things that support it", "B": "there are many people against it", "C": "it is a lucky choice", "D": "it is a very popular idea"},
     "A", "easy", 21, "Speaking box: Considering alternatives",
     ["'Points in favour of' = reasons that support an option."],
     "in favour of = supporting.", "You list the advantages."),

    ("What does 'You have to consider the fact that...' mean?",
     {"A": "you must think about the fact that", "B": "you should forget the fact that", "C": "the fact is not important", "D": "you must prove the fact"},
     "A", "easy", 21, "Speaking box: Considering alternatives",
     ["It means you should take a particular fact into account."],
     "You must think about it.", "It draws attention to an important point."),

    ("What does 'Alternatively, we could put forward the idea of...' mean?",
     {"A": "as another option, we could suggest...", "B": "we should cancel the idea", "C": "the idea is final", "D": "nobody supports the idea"},
     "A", "medium", 21, "Speaking box: Considering alternatives",
     ["'Alternatively' introduces another option; 'put forward an idea' means to suggest it."],
     "We could suggest another option.", "It offers a different choice."),

    ("What does 'put forward an idea' mean?",
     {"A": "to suggest or propose an idea", "B": "to reject an idea", "C": "to forget an idea", "D": "to copy an idea"},
     "A", "easy", 21, "Speaking box: Considering alternatives",
     ["'Put forward' means to propose or suggest."],
     "put forward = suggest.", "We could put forward the idea of a canal trip."),

    ("What does 'Well, you could argue that...' mean?",
     {"A": "you could say that...", "B": "you must fight for that...", "C": "you are wrong about that...", "D": "you have proved that..."},
     "A", "easy", 21, "Speaking box: Considering alternatives",
     ["It means 'it is possible to say that...'."],
     "you could argue = you could say.", "It introduces a point of view."),

    ("What does 'I'd go for ... anytime!' mean?",
     {"A": "I'd choose it without hesitation", "B": "I'd wait forever for it", "C": "I'd never choose it", "D": "I'd think about it for years"},
     "A", "medium", 21, "Speaking box: Giving preferences",
     ["'I'd go for... anytime' means I'd choose that option immediately and happily."],
     "I'd choose it at once.", "It shows a strong preference."),

    ("What does 'Oh, a canal trip – no contest! Definitely!' mean?",
     {"A": "there is no comparison; the canal trip is clearly best", "B": "the canal trip is a competition", "C": "nobody wants the canal trip", "D": "the canal trip is very long"},
     "A", "hard", 21, "Speaking box: Giving preferences",
     ["'No contest' means one option is so much better that there is no real choice."],
     "no contest = no comparison.", "The speaker clearly prefers the canal trip."),

    ("What does 'It's pretty clear cut to me that...' mean?",
     {"A": "the decision is very clear and obvious to me", "B": "the decision is impossible to make", "C": "I need more information", "D": "the situation is confusing"},
     "A", "medium", 21, "Speaking box: Giving preferences",
     ["'Clear cut' means clear and definite."],
     "clear cut = obvious and definite.", "The speaker has no doubts."),

    ("What does 'On balance, I'd say...' mean?",
     {"A": "after considering everything, I'd say...", "B": "without thinking, I'd say...", "C": "on one side only, I'd say...", "D": "secretly, I'd say..."},
     "A", "medium", 21, "Speaking box: Giving preferences",
     ["'On balance' means after weighing up all the pros and cons."],
     "On balance = considering everything.", "It gives a final, considered opinion."),

    ("What does 'No two ways about it, my choice would be...' mean?",
     {"A": "there is no doubt about my choice", "B": "I cannot decide between two options", "C": "my choice depends on the weather", "D": "two people must agree first"},
     "A", "hard", 21, "Speaking box: Giving preferences",
     ["'No two ways about it' means it is certain, without doubt."],
     "No two ways about it = without doubt.", "The speaker is completely sure."),

    ("What does 'I'm split between the... and...' mean?",
     {"A": "I can't decide between two options", "B": "I have chosen the first option", "C": "I reject both options", "D": "I have two tickets"},
     "A", "medium", 21, "Speaking box: Giving preferences",
     ["'I'm split between X and Y' means I like both and find it hard to choose."],
     "I'm split = undecided between two.", "Both options attract the speaker."),

    ("What does 'I'm in two minds here' mean?",
     {"A": "I'm undecided or uncertain", "B": "I have two opinions that are wrong", "C": "I'm sure about my choice", "D": "two people share my mind"},
     "A", "medium", 21, "Speaking box: Giving preferences",
     ["'In two minds' means unable to decide."],
     "in two minds = undecided.", "The speaker is hesitating between options."),

    ("What does 'There are pros and cons for each' mean?",
     {"A": "each option has advantages and disadvantages", "B": "each option is perfect", "C": "each option is terrible", "D": "only one option is possible"},
     "A", "easy", 21, "Speaking box: Giving preferences",
     ["'Pros and cons' are advantages and disadvantages."],
     "pros = advantages; cons = disadvantages.", "You consider both sides of each option."),

    ("What does 'If you really wanted to pin me down, I'd probably say...' mean?",
     {"A": "if you forced me to give a definite answer, I'd say...", "B": "if you helped me, I'd say...", "C": "if you were angry, I'd say...", "D": "if you asked nicely, I'd say..."},
     "A", "hard", 21, "Speaking box: Giving preferences",
     ["'Pin someone down' means to force them to make a clear decision or give an answer."],
     "pin me down = force a decision.", "The speaker gives a final answer with some hesitation."),

    ("Which phrase is used to give a strong preference?",
     {"A": "I'd go for ... anytime!", "B": "Alternatively, we could ...", "C": "Well, you could argue that ...", "D": "But on the other hand, ..."},
     "A", "medium", 21, "Speaking box: Giving preferences",
     ["'I'd go for... anytime!' expresses a strong preference."],
     "It gives a preference.", "The alternatives explore options."),

    ("Which phrase is used to consider an alternative?",
     {"A": "Alternatively, we could put forward the idea of ...", "B": "On balance, I'd say ...", "C": "No contest!", "D": "I'm in two minds here."},
     "A", "medium", 21, "Speaking box: Considering alternatives",
     ["'Alternatively...' introduces another option to consider."],
     "It offers an alternative.", "The others express a decision or hesitation."),

    ("Which phrase shows hesitation between options?",
     {"A": "I'm in two minds here.", "B": "I'd go for ... anytime!", "C": "It's pretty clear cut to me that ...", "D": "No two ways about it, ..."},
     "A", "easy", 21, "Speaking box: Giving preferences",
     ["'In two minds' shows uncertainty or hesitation."],
     "It shows hesitation.", "The others show certainty."),

    ("Which phrase shows certainty about a choice?",
     {"A": "No two ways about it, my choice would be ...", "B": "I'm split between the ... and ...", "C": "I'm in two minds here.", "D": "There are pros and cons for each."},
     "A", "medium", 21, "Speaking box: Giving preferences",
     ["'No two ways about it' shows there is no doubt."],
     "It shows certainty.", "The others express hesitation."),

    ("Complete: 'There's a lot to be ______ for the idea of a staycation.'",
     {"A": "said", "B": "done", "C": "seen", "D": "felt"},
     "A", "easy", 21, "Speaking box: Considering alternatives",
     ["The phrase is 'There's a lot to be said for...'."],
     "said", "It means there are good reasons for it."),

    ("Complete: 'There are a lot of points in ______ of visiting other countries.'",
     {"A": "favour", "B": "help", "C": "support", "D": "need"},
     "A", "easy", 21, "Speaking box: Considering alternatives",
     ["The phrase is 'points in favour of'."],
     "favour", "It lists the positive points."),

    ("Complete: 'On ______, I'd say a small group is better.'",
     {"A": "balance", "B": "average", "C": "general", "D": "whole"},
     "A", "easy", 21, "Speaking box: Giving preferences",
     ["The phrase is 'On balance'."],
     "balance", "It means after weighing everything up."),

    ("Complete: 'If you really wanted to ______ me down, I'd probably say the reef.'",
     {"A": "pin", "B": "hold", "C": "put", "D": "set"},
     "A", "hard", 21, "Speaking box: Giving preferences",
     ["The phrase is 'pin me down'."],
     "pin", "It means force me to make a definite choice."),

    ("Complete: 'Oh, a canal trip – no ______! Definitely!'",
     {"A": "contest", "B": "competition", "C": "match", "D": "game"},
     "A", "medium", 21, "Speaking box: Giving preferences",
     ["The phrase is 'no contest'."],
     "contest", "It means there is no real comparison."),

    ("What are 'last chance holidays'?",
     {"A": "holidays to places that may not exist in the same way for much longer", "B": "holidays taken at the last minute", "C": "the final holiday of the year", "D": "holidays that are cancelled"},
     "A", "hard", 21, "Exercise 3: Discussion topics",
     ["'Last chance holidays' means travelling to see threatened places before they change or disappear."],
     "Places that may not last much longer.", "One of the discussion topics is last chance holidays."),

    ("Where can you visit 'The Great Barrier Reef'?",
     {"A": "Australia", "B": "Antarctica", "C": "Jordan", "D": "Chile"},
     "A", "easy", 21, "Exercise 1: Holiday options",
     ["The Great Barrier Reef is in Australia; it was one of the holiday options discussed."],
     "Australia", "The reef was one of the options."),

    ("Which famous place was offered as a holiday option in the listening?",
     {"A": "Antarctica", "B": "Sahara", "C": "Himalayas", "D": "Amazon"},
     "A", "medium", 21, "Exercise 1: Holiday options",
     ["The options shown include The Great Barrier Reef and Antarctica."],
     "Antarctica", "Students discuss which trip to choose."),

    ("Who said: 'Travelling leaves you speechless, then turns you into a storyteller'?",
     {"A": "Ibn Battuta", "B": "Anonymous", "C": "Sultan", "D": "Malek"},
     "A", "medium", 21, "Exercise 4: Quotations",
     ["The quotation about travelling is attributed to Ibn Battuta."],
     "Ibn Battuta", "He was a famous traveller."),

    ("What does 'Travelling leaves you speechless, then turns you into a storyteller' mean?",
     {"A": "travel amazes you at first, and later gives you stories to tell", "B": "travel makes you unable to speak forever", "C": "only storytellers should travel", "D": "travel is boring"},
     "A", "hard", 21, "Exercise 4: Quotations",
     ["It means the amazing experiences of travel become stories you share."],
     "Travel gives you stories.", "You are amazed first, then you tell others."),

    ("What does the quotation 'Fill your life with experiences, not things. Have stories to tell, not stuff to show' suggest?",
     {"A": "experiences matter more than possessions", "B": "you should buy more things", "C": "stories are not important", "D": "you should stay at home"},
     "A", "medium", 21, "Exercise 4: Quotations",
     ["The quotation values experiences and stories over material things."],
     "Experiences are more valuable.", "It encourages travel and new experiences."),

    ("Which phrase can you use to make a final decision after discussion?",
     {"A": "On balance, I'd say ...", "B": "There's a lot to be said for ...", "C": "You have to consider the fact that ...", "D": "Alternatively, ..."},
     "A", "easy", 21, "Speaking box: Giving preferences",
     ["'On balance, I'd say...' gives your final opinion after considering everything."],
     "On balance gives the conclusion.", "The others explore or add points."),

    ("Complete: '______, we could put forward the idea of a trip to the desert.'",
     {"A": "Alternatively", "B": "Definitely", "C": "Clearly", "D": "Surprisingly"},
     "A", "easy", 21, "Speaking box: Considering alternatives",
     ["'Alternatively' introduces another possible option."],
     "Alternatively", "It offers an alternative choice."),

    ("Which phrase means 'there are advantages and disadvantages'?",
     {"A": "There are pros and cons for each.", "B": "No two ways about it.", "C": "It's pretty clear cut to me.", "D": "I'd go for it anytime!"},
     "A", "easy", 21, "Speaking box: Giving preferences",
     ["'Pros and cons' means advantages and disadvantages."],
     "There are pros and cons = both sides.", "It shows the speaker is weighing options."),

    ("In the speaking task, what is one suggested discussion topic?",
     {"A": "holidaying in your own country instead of visiting other countries", "B": "travelling by plane or train only", "C": "the cost of passports", "D": "packing a suitcase"},
     "A", "medium", 21, "Exercise 3: Discussion topics",
     ["One topic is holidaying in your own country instead of abroad."],
     "Holidaying at home is a topic.", "Another topic is large or small groups."),

    ("What should you do before making a decision, according to the speaking lesson?",
     {"A": "consider the pros and cons of each option", "B": "choose the first option you hear", "C": "let someone else decide", "D": "avoid all opinions"},
     "A", "medium", 21, "Speaking box",
     ["Good decision-making involves weighing the pros and cons."],
     "Consider pros and cons.", "The speaking box helps structure this discussion."),

    ("Complete: 'You have to ______ the fact that the trip is very expensive.'",
     {"A": "consider", "B": "ignore", "C": "forget", "D": "invent"},
     "A", "easy", 21, "Speaking box: Considering alternatives",
     ["The phrase is 'You have to consider the fact that...'."],
     "consider", "It asks you to think about an important fact."),

    ("What does 'I'm split between the reef and Antarctica' mean?",
     {"A": "I like both and can't choose easily", "B": "I reject both places", "C": "I have visited both places", "D": "I will visit both next year"},
     "A", "medium", 21, "Speaking box: Giving preferences",
     ["'I'm split between' means I find it hard to choose between the two."],
     "The speaker can't choose easily.", "Both options appeal."),

    ("Which is a suitable phrase to PREPARE a short presentation about the benefits of travelling?",
     {"A": "There are a lot of points in favour of travelling.", "B": "No contest! Antarctica!", "C": "I'm in two minds here.", "D": "Pin me down and I'll say..."},
     "A", "hard", 21, "Exercise 4: Presentation",
     ["A presentation would start by giving points in favour of travelling."],
     "Giving points in favour fits a presentation.", "The others are short replies, not presentation openers."),

    ("What does the speaking lesson help you do?",
     {"A": "compare options and express preferences", "B": "write formal letters", "C": "understand grammar rules", "D": "remember new vocabulary lists"},
     "A", "easy", 21, "Lesson 5A: Speaking",
     ["The lesson focuses on considering options and giving preferences."],
     "It helps you compare and choose.", "The speaking box gives useful phrases."),
]
