ITEMS = [
    (
        "Which sport uses a shuttlecock?",
        {"A": "Badminton", "B": "Tennis", "C": "Football", "D": "Basketball"},
        "A",
        "easy",
        48,
        "L1",
        ["Identify the sport that uses a shuttlecock as its main equipment."],
        "Badminton uses a shuttlecock.",
        "Badminton is played with a shuttlecock, not a ball."
    ),
    (
        "What does 'compete' mean?",
        {"A": "To take part in a contest or game", "B": "To rest after exercise", "C": "To watch a match", "D": "To eat before a game"},
        "A",
        "easy",
        48,
        "L1",
        ["Recall the definition of the verb 'compete'."],
        "Compete means to take part in a contest.",
        "Competing involves actively participating in a contest or game."
    ),
    (
        "Which sport involves gymnastic movements on a mat?",
        {"A": "Gymnastics", "B": "Swimming", "C": "Cycling", "D": "Boxing"},
        "A",
        "easy",
        48,
        "L1",
        ["Match the description to the correct sport."],
        "Gymnastics is performed on a mat.",
        "Gymnastics involves acrobatic movements performed on a mat or apparatus."
    ),
    (
        "What is the opposite of 'win'?",
        {"A": "Lose", "B": "Score", "C": "Train", "D": "Qualify"},
        "A",
        "easy",
        48,
        "L1",
        ["Identify the antonym of 'win'."],
        "The opposite of 'win' is 'lose'.",
        "Winning and losing are opposite outcomes in competition."
    ),
    (
        "Which word describes someone who really wants to succeed?",
        {"A": "Determined", "B": "Exhausted", "C": "Lazy", "D": "Calm"},
        "A",
        "medium",
        48,
        "L1",
        ["Choose the adjective that means strongly motivated to succeed."],
        "Determined means wanting to succeed strongly.",
        "A determined person has strong motivation and willpower to achieve goals."
    ),
    (
        "What does 'to train' mean in sports?",
        {"A": "To practise regularly to improve", "B": "To travel by train", "C": "To eat healthy food", "D": "To sleep early"},
        "A",
        "easy",
        48,
        "L1",
        ["Define the sports meaning of 'train'."],
        "To train means to practise regularly.",
        "Athletes train regularly to improve their performance."
    ),
    (
        "Which is NOT a sport?",
        {"A": "Reading", "B": "Volleyball", "C": "Athletics", "D": "Swimming"},
        "A",
        "easy",
        48,
        "L1",
        ["Identify which option is not classified as a sport."],
        "Reading is not a sport.",
        "Reading is a leisure activity, not a competitive physical sport."
    ),
    (
        "What does 'athletics' refer to?",
        {"A": "Track and field sports like running and jumping", "B": "Playing video games", "C": "Reading books", "D": "Cooking food"},
        "A",
        "medium",
        49,
        "L1",
        ["Recall the meaning of 'athletics' in a sports context."],
        "Athletics refers to track and field sports.",
        "Athletics includes running, jumping, throwing, and walking events."
    ),
    (
        "If someone is 'exhausted', they feel...",
        {"A": "Very tired", "B": "Very happy", "C": "Very hungry", "D": "Very cold"},
        "A",
        "easy",
        49,
        "L1",
        ["Identify the meaning of 'exhausted'."],
        "Exhausted means very tired.",
        "Exhaustion is extreme tiredness, often after physical activity."
    ),
    (
        "Which word means 'to earn a point' in sports?",
        {"A": "Score", "B": "Lose", "C": "Fall", "D": "Rest"},
        "A",
        "easy",
        49,
        "L1",
        ["Identify the verb that means to earn a point."],
        "Score means to earn a point.",
        "Players score points or goals during a game."
    ),
    (
        "What does 'competitive' describe?",
        {"A": "Someone who enjoys winning and trying hard", "B": "Someone who does not care about sports", "C": "Someone who sleeps a lot", "D": "Someone who is very slow"},
        "A",
        "medium",
        49,
        "L1",
        ["Define the adjective 'competitive'."],
        "Competitive describes someone who enjoys winning.",
        "A competitive person tries hard to be the best."
    ),
    (
        "Which sport is played in a swimming pool?",
        {"A": "Water polo", "B": "Cricket", "C": "Baseball", "D": "Rugby"},
        "A",
        "easy",
        49,
        "L1",
        ["Match the sport to its playing location."],
        "Water polo is played in a swimming pool.",
        "Water polo is a team sport played in a pool."
    ),
    (
        "What does 'to qualify' mean in sports?",
        {"A": "To meet the required standard to enter a competition", "B": "To quit a race", "C": "To buy a ticket", "D": "To sleep before a game"},
        "A",
        "medium",
        49,
        "L1",
        ["Define the sports meaning of 'qualify'."],
        "Qualify means to meet requirements for a competition.",
        "Athletes must qualify by achieving certain results before major events."
    ),
    (
        "What is the equipment used in volleyball?",
        {"A": "A large ball and a net", "B": "A bat and a ball", "C": "A racket and a shuttlecock", "D": "A stick and a puck"},
        "A",
        "easy",
        48,
        "L1",
        ["Identify the equipment for volleyball."],
        "Volleyball uses a ball and a net.",
        "Volleyball is played with a large ball over a high net."
    ),
    (
        "Which word best describes someone who never gives up?",
        {"A": "Persistent", "B": "Lazy", "C": "Slow", "D": "Weak"},
        "A",
        "medium",
        49,
        "L1",
        ["Choose the adjective meaning 'never gives up'."],
        "Persistent means never giving up.",
        "A persistent athlete keeps trying even after failures."
    ),
    (
        "What does 'hurdles' refer to in athletics?",
        {"A": "A race over barriers", "B": "A swimming event", "C": "A ball game", "D": "A team sport"},
        "A",
        "medium",
        49,
        "L1",
        ["Identify what 'hurdles' means in athletics."],
        "Hurdles is a race over barriers.",
        "Hurdles is a track event where runners jump over obstacles."
    ),
    (
        "Which sport uses a bat and a ball?",
        {"A": "Cricket", "B": "Swimming", "C": "Running", "D": "Cycling"},
        "A",
        "easy",
        48,
        "L1",
        ["Match the equipment to the correct sport."],
        "Cricket uses a bat and a ball.",
        "In cricket, players hit a ball with a flat bat."
    ),
    (
        "What is a 'tournament'?",
        {"A": "A competition with many matches or games", "B": "A single race", "C": "A practice session", "D": "A rest day"},
        "A",
        "easy",
        49,
        "L1",
        ["Define the noun 'tournament'."],
        "A tournament is a large competition.",
        "A tournament involves many participants playing multiple rounds."
    ),
    (
        "Which word means 'to do physical exercise before an event'?",
        {"A": "Warm up", "B": "Cool down", "C": "Give up", "D": "Break down"},
        "A",
        "easy",
        48,
        "L1",
        ["Identify the correct phrasal verb for pre-exercise activity."],
        "Warm up means to exercise before an event.",
        "Warming up prepares the body for physical activity."
    ),
    (
        "What does 'athletic' mean?",
        {"A": "Good at sports and physically fit", "B": "Bad at sports", "C": "Not interested in exercise", "D": "Very slow"},
        "A",
        "medium",
        49,
        "L1",
        ["Define the adjective 'athletic'."],
        "Athletic means physically fit and good at sports.",
        "An athletic person has strength, speed, and endurance."
    ),
    (
        "Which sport is also known as 'football' in most countries?",
        {"A": "Soccer", "B": "American football", "C": "Rugby", "D": "Cricket"},
        "A",
        "easy",
        48,
        "L1",
        ["Identify the sport called 'football' globally."],
        "Soccer is called football worldwide.",
        "In most countries, 'football' refers to soccer."
    ),
    (
        "What does 'to defeat' someone mean?",
        {"A": "To beat them in a competition", "B": "To help them win", "C": "To train with them", "D": "To share a medal with them"},
        "A",
        "easy",
        49,
        "L1",
        ["Define the verb 'defeat'."],
        "Defeat means to beat someone in competition.",
        "To defeat an opponent means to win against them."
    ),
    (
        "Which is a water sport?",
        {"A": "Surfing", "B": "Cycling", "C": "Boxing", "D": "Tennis"},
        "A",
        "easy",
        48,
        "L1",
        ["Identify which sport is performed in water."],
        "Surfing is a water sport.",
        "Surfing involves riding waves on a board in the ocean."
    ),
    (
        "What does 'spectator' mean?",
        {"A": "A person who watches a sport or event", "B": "A person who plays a sport", "C": "A coach", "D": "A referee"},
        "A",
        "medium",
        49,
        "L1",
        ["Define the noun 'spectator'."],
        "A spectator is a person who watches.",
        "Spectators watch sports events but do not participate."
    ),
    (
        "What is a 'marathon'?",
        {"A": "A long-distance running race of 42 km", "B": "A short sprint", "C": "A swimming race", "D": "A team ball game"},
        "A",
        "medium",
        49,
        "L1",
        ["Define 'marathon' in sports terms."],
        "A marathon is a 42-kilometre running race.",
        "Marathons test endurance and are held in many cities worldwide."
    ),
    (
        "Which word means 'to get ready for a competition'?",
        {"A": "Prepare", "B": "Forget", "C": "Ignore", "D": "Avoid"},
        "A",
        "easy",
        48,
        "L1",
        ["Choose the verb meaning 'get ready'."],
        "Prepare means to get ready.",
        "Athletes prepare physically and mentally for competitions."
    ),
    (
        "What does 'referee' mean?",
        {"A": "The official who enforces the rules in a game", "B": "A player on the team", "C": "A coach", "D": "A fan"},
        "A",
        "medium",
        49,
        "L1",
        ["Define the role of a 'referee'."],
        "A referee enforces the rules in a game.",
        "The referee makes sure all players follow the rules."
    ),
    (
        "Which adjective means 'very fast'?",
        {"A": "Quick", "B": "Heavy", "C": "Tall", "D": "Wide"},
        "A",
        "easy",
        48,
        "L1",
        ["Choose the adjective that means 'very fast'."],
        "Quick means very fast.",
        "Quick athletes have a speed advantage."
    ),
    (
        "What does 'endurance' mean in sports?",
        {"A": "The ability to keep going for a long time", "B": "The ability to run fast for a short time", "C": "The ability to jump high", "D": "The ability to throw far"},
        "A",
        "medium",
        49,
        "L1",
        ["Define 'endurance' in a sports context."],
        "Endurance is the ability to keep going for a long time.",
        "Endurance athletes train to sustain effort over long periods."
    ),
    (
        "Which is NOT a type of exercise?",
        {"A": "Snoring", "B": "Running", "C": "Cycling", "D": "Swimming"},
        "A",
        "easy",
        48,
        "L1",
        ["Identify which option is not a form of exercise."],
        "Snoring is not exercise.",
        "Snoring is an involuntary action during sleep, not physical exercise."
    ),
    (
        "What does 'stamina' mean?",
        {"A": "Physical strength and energy over time", "B": "Speed over a short distance", "C": "Flexibility", "D": "Balance"},
        "A",
        "medium",
        49,
        "L1",
        ["Define 'stamina' in sports."],
        "Stamina is sustained physical energy.",
        "Stamina allows athletes to perform for extended periods."
    ),
    (
        "Which sport is played on ice?",
        {"A": "Ice hockey", "B": "Cricket", "C": "Tennis", "D": "Volleyball"},
        "A",
        "easy",
        48,
        "L1",
        ["Match the sport to its playing surface."],
        "Ice hockey is played on ice.",
        "Ice hockey is a fast-paced sport played on a frozen rink."
    ),
    (
        "What does 'teamwork' mean?",
        {"A": "Working together with others to achieve a goal", "B": "Working alone", "C": "Cheering from the stands", "D": "Wearing a uniform"},
        "A",
        "easy",
        48,
        "L1",
        ["Define 'teamwork' in a sports context."],
        "Teamwork means working together as a group.",
        "Good teamwork helps sports teams succeed."
    ),
    (
        "What is a 'sprint'?",
        {"A": "A short-distance race at maximum speed", "B": "A long-distance jog", "C": "A swimming stroke", "D": "A type of jump"},
        "A",
        "medium",
        49,
        "L1",
        ["Define 'sprint' in athletics."],
        "A sprint is a short fast race.",
        "Sprints are explosive, high-speed races over short distances."
    ),
    (
        "Which word means 'fair play'?",
        {"A": "Sportsmanship", "B": "Cheating", "C": "Laziness", "D": "Sadness"},
        "A",
        "medium",
        49,
        "L1",
        ["Identify the word for fair behaviour in sports."],
        "Sportsmanship means fair play.",
        "Good sportsmanship involves respecting opponents and rules."
    ),
    (
        "What does 'coach' mean?",
        {"A": "A person who trains and guides athletes", "B": "A type of bus", "C": "A type of chair", "D": "A referee"},
        "A",
        "easy",
        48,
        "L1",
        ["Define the role of a 'coach' in sports."],
        "A coach trains and guides athletes.",
        "Coaches help athletes improve their skills and strategy."
    ),
    (
        "Which sport uses a net and rackets?",
        {"A": "Tennis", "B": "Football", "C": "Basketball", "D": "Swimming"},
        "A",
        "easy",
        48,
        "L1",
        ["Match the equipment to the correct sport."],
        "Tennis uses a net and rackets.",
        "Tennis is played with rackets over a net dividing the court."
    ),
    (
        "What does 'to forfeit' mean?",
        {"A": "To give up or withdraw from a competition", "B": "To win a medal", "C": "To score a goal", "D": "To start a race"},
        "A",
        "hard",
        49,
        "L1",
        ["Define the verb 'forfeit'."],
        "Forfeit means to give up a competition.",
        "A team may forfeit if they cannot continue playing."
    ),
    (
        "Which word describes someone who plays sports regularly?",
        {"A": "Active", "B": "Passive", "C": "Dull", "D": "Lazy"},
        "A",
        "easy",
        48,
        "L1",
        ["Choose the adjective for a regularly active person."],
        "Active describes someone who exercises regularly.",
        "Active people engage in physical activities often."
    ),
    (
        "What is a 'bronze medal' awarded for?",
        {"A": "Third place in a competition", "B": "First place", "C": "Last place", "D": "Participation only"},
        "A",
        "medium",
        49,
        "L1",
        ["Recall which place wins a bronze medal."],
        "A bronze medal is for third place.",
        "Gold is first, silver is second, and bronze is third."
    ),
]
