# Unit 4 L5 - Listening and Vocabulary (pages 45-46)
# Kitchen items, cooking verbs, listening scenarios about food
ITEMS = [
    ("Which word means 'a large flat pan used for frying'?",
     {"A": "frying pan", "B": "saucepan", "C": "baking tray", "D": "grater"},
     "A", "easy", 45, "L5",
     ["A frying pan is a flat-bottomed pan used for frying food."],
     "frying pan = flat pan for frying.", "You fry eggs in a frying pan."),

    ("Which word means 'a deep pan with a lid used for boiling'?",
     {"A": "saucepan", "B": "frying pan", "C": "kettle", "D": "blender"},
     "A", "easy", 45, "L5",
     ["A saucepan is a deep cooking pot with a long handle and a lid."],
     "saucepan = deep pot with lid.", "Use a saucepan to boil water or cook soup."),

    ("Which word means 'a sharp tool with small holes used to cut food into thin pieces'?",
     {"A": "grater", "B": "peeler", "C": "whisk", "D": "spatula"},
     "A", "easy", 45, "L5",
     ["A grater is a kitchen tool with sharp-edged holes used for shredding food."],
     "grater = shredding tool.", "Use a grater to shred cheese or carrots."),

    ("Which word means 'a tool with wire loops used to mix ingredients'?",
     {"A": "whisk", "B": "spatula", "C": "ladle", "D": "tongs"},
     "A", "easy", 45, "L5",
     ["A whisk is a cooking tool with wire loops used for beating or mixing."],
     "whisk = mixing tool.", "Use a whisk to beat eggs."),

    ("Which word means 'a flat tool used for lifting and turning food'?",
     {"A": "spatula", "B": "whisk", "C": "ladle", "D": "grater"},
     "A", "easy", 45, "L5",
     ["A spatula is a flat, broad tool used for lifting, turning or spreading food."],
     "spatula = flat lifting tool.", "Use a spatula to flip pancakes."),

    ("Which word means 'a sharp tool used to remove the outer skin of vegetables'?",
     {"A": "peeler", "B": "grater", "C": "knife", "D": "scissors"},
     "A", "easy", 45, "L5",
     ["A peeler is a small tool with a sharp blade used to remove skin from vegetables and fruit."],
     "peeler = skin-removing tool.", "Use a peeler to remove potato skin."),

    ("Which word means 'a large spoon used for serving soup'?",
     {"A": "ladle", "B": "spoon", "C": "fork", "D": "tongs"},
     "A", "easy", 45, "L5",
     ["A ladle is a large, deep spoon used for serving liquid food like soup."],
     "ladle = large soup spoon.", "Use a ladle to serve soup into bowls."),

    ("Which word means 'a tool with two arms used for picking up hot food'?",
     {"A": "tongs", "B": "spatula", "C": "whisk", "D": "ladle"},
     "A", "easy", 45, "L5",
     ["Tongs are a tool with two long arms joined at one end, used for gripping."],
     "tongs = gripping tool.", "Use tongs to pick up hot meat."),

    ("Which word means 'an electrical tool used to mix or liquidise food'?",
     {"A": "blender", "B": "toaster", "C": "kettle", "D": "oven"},
     "A", "easy", 45, "L5",
     ["A blender is an electrical appliance used for mixing, liquidising or puréeing food."],
     "blender = electrical mixer.", "Use a blender to make a fruit smoothie."),

    ("Which word means 'a large box-like appliance used for cooking food with dry heat'?",
     {"A": "oven", "B": "microwave", "C": "fridge", "D": "freezer"},
     "A", "easy", 45, "L5",
     ["An oven is a enclosed appliance used for baking, roasting or heating food."],
     "oven = dry-heat cooker.", "You bake cakes in an oven."),

    ("What does 'to fry' food mean?",
     {"A": "to cook food in hot oil", "B": "to cook food in water", "C": "to freeze food", "D": "to wash food"},
     "A", "easy", 45, "L5",
     ["To fry means to cook food in hot oil or fat in a pan."],
     "fry = cook in oil.", "Fry the onions until they are golden brown."),

    ("What does 'to boil' food mean?",
     {"A": "to cook food in very hot water", "B": "to cook food in oil", "C": "to grill food", "D": "to freeze food"},
     "A", "easy", 45, "L5",
     ["To boil means to heat a liquid until it reaches 100 degrees and bubbles."],
     "boil = cook in hot water.", "Boil the pasta for ten minutes."),

    ("What does 'to bake' food mean?",
     {"A": "to cook food in an oven using dry heat", "B": "to fry food in oil", "C": "to boil food in water", "D": "to grill food"},
     "A", "easy", 45, "L5",
     ["To bake means to cook food in an oven using hot, dry air."],
     "bake = cook in oven.", "Bake the cake at 180 degrees for 30 minutes."),

    ("What does 'to grill' food mean?",
     {"A": "to cook food under direct heat", "B": "to boil food", "C": "to freeze food", "D": "to blend food"},
     "A", "easy", 45, "L5",
     ["To grill means to cook food using direct heat from above or below."],
     "grill = cook under direct heat.", "Grill the chicken for five minutes on each side."),

    ("What does 'to roast' food mean?",
     {"A": "to cook food slowly in an oven with hot air", "B": "to boil food quickly", "C": "to fry food in oil", "D": "to blend food"},
     "A", "medium", 45, "L5",
     ["To roast means to cook food slowly in an oven using hot, dry air."],
     "roast = slow oven cooking.", "Roast the meat for two hours."),

    ("What does 'to steam' food mean?",
     {"A": "to cook food using steam from boiling water", "B": "to fry food in oil", "C": "to grill food", "D": "to freeze food"},
     "A", "medium", 45, "L5",
     ["To steam means to cook food using the steam from boiling water without direct contact."],
     "steamed = cooked by steam.", "Steam the vegetables for five minutes."),

    ("What does 'to simmer' food mean?",
     {"A": "to cook food gently in liquid just below boiling point", "B": "to boil food quickly", "C": "to fry food", "D": "to grill food"},
     "A", "medium", 45, "L5",
     ["To simmer means to cook food gently in liquid at a temperature just below boiling."],
     "simmer = gentle boiling.", "Simmer the soup for twenty minutes."),

    ("What does 'to chop' food mean?",
     {"A": "to cut food into pieces with a knife", "B": "to cook food slowly", "C": "to blend food", "D": "to serve food"},
     "A", "easy", 45, "L5",
     ["To chop means to cut food into rough, irregular pieces."],
     "chop = cut into pieces.", "Chop the onions into small pieces."),

    ("What does 'to dice' food mean?",
     {"A": "to cut food into small equal cubes", "B": "to cut food into thin strips", "C": "to mash food", "D": "to blend food"},
     "A", "medium", 45, "L5",
     ["To dice means to cut food into small, even cubes."],
     "dice = cut into cubes.", "Dice the potatoes into small cubes."),

    ("What does 'to slice' food mean?",
     {"A": "to cut food into thin, flat pieces", "B": "to cut food into cubes", "C": "to mash food", "D": "to cook food"},
     "A", "easy", 45, "L5",
     ["To slice means to cut food into thin, even pieces."],
     "slice = cut thinly.", "Slice the bread into thin pieces."),

    ("What does 'to mash' food mean?",
     {"A": "to crush food into a soft, smooth mass", "B": "to cut food into pieces", "C": "to cook food quickly", "D": "to serve food"},
     "A", "easy", 45, "L5",
     ["To mash means to crush food into a soft, smooth mass."],
     "mash = crush into soft mass.", "Mash the potatoes with butter and milk."),

    ("What does 'to grill' mean in a restaurant context?",
     {"A": "to cook food using direct heat from a grill", "B": "to cook food in water", "C": "to freeze food", "D": "to blend food"},
     "A", "medium", 45, "L5",
     ["In a restaurant, to grill means to cook food on a metal frame over direct heat."],
     "grill = direct heat cooking.", "The chef grilled the fish to perfection."),

    ("What does 'to garnish' food mean?",
     {"A": "to decorate food with small pieces of herbs or vegetables", "B": "to cook food", "C": "to freeze food", "D": "to serve food"},
     "A", "medium", 45, "L5",
     ["To garnish means to add a small amount of decoration to food before serving."],
     "garnish = decorate food.", "Garnish the dish with fresh parsley."),

    ("Which cooking method is best for making crispy chips?",
     {"A": "Deep-frying", "B": "Steaming", "C": "Boiling", "D": "Mashing"},
     "A", "easy", 45, "L5",
     ["Deep-frying in hot oil makes chips crispy and golden."],
     "deep-frying = crispy cooking.", "Chips are deep-fried in hot oil."),

    ("Which cooking method is healthiest for vegetables?",
     {"A": "Steaming", "B": "Deep-frying", "C": "Roasting in lots of oil", "D": "Frying in butter"},
     "A", "medium", 45, "L5",
     ["Steaming preserves the most nutrients in vegetables."],
     "steaming = healthiest method.", "Steaming keeps vitamins in vegetables."),

    ("What does 'a chopping board' mean?",
     {"A": "a flat board used for cutting food on", "B": "a board for playing games", "C": "a board for writing", "D": "a board for sitting on"},
     "A", "easy", 45, "L5",
     ["A chopping board is a flat surface used as a base for cutting food."],
     "chopping board = cutting surface.", "Always use a chopping board when cutting vegetables."),

    ("What does 'kitchen utensils' mean?",
     {"A": "tools and equipment used in cooking", "B": "types of food", "C": "types of kitchen furniture", "D": "recipes"},
     "A", "easy", 45, "L5",
     ["Kitchen utensils are small tools and equipment used for preparing and cooking food."],
     "kitchen utensils = cooking tools.", "Pots, pans and knives are kitchen utensils."),

    ("What does 'preheat the oven' mean?",
     {"A": "to heat the oven before putting food in", "B": "to turn off the oven", "C": "to clean the oven", "D": "to open the oven door"},
     "A", "easy", 45, "L5",
     ["Preheating the oven means heating it to the required temperature before cooking."],
     "preheat = heat before use.", "Preheat the oven to 200 degrees."),

    ("What does 'to drain' food mean?",
     {"A": "to remove water or liquid from food", "B": "to add water to food", "C": "to cook food in water", "D": "to freeze food"},
     "A", "easy", 45, "L5",
     ["To drain means to remove liquid from food, usually using a colander."],
     "drain = remove liquid.", "Drain the pasta after cooking."),

    ("What does 'to defrost' food mean?",
     {"A": "to allow frozen food to return to room temperature", "B": "to freeze food quickly", "C": "to cook frozen food", "D": "to mash frozen food"},
     "A", "easy", 45, "L5",
     ["To defrost means to allow frozen food to thaw and return to its normal temperature."],
     "defrost = thaw frozen food.", "Defrost the chicken in the fridge overnight."),

    ("What does 'to marinate' food mean?",
     {"A": "to soak food in flavoured liquid before cooking", "B": "to cook food quickly", "C": "to freeze food", "D": "to serve food"},
     "A", "medium", 45, "L5",
     ["To marinate means to soak food in a seasoned liquid to add flavour before cooking."],
     "marinate = flavour before cooking.", "Marinate the chicken in lemon juice for two hours."),

    ("What does 'to glaze' food mean?",
     {"A": "to coat food with a shiny layer of sugar or sauce", "B": "to cut food into pieces", "C": "to freeze food", "D": "to boil food"},
     "A", "medium", 45, "L5",
     ["To glaze means to cover food with a thin, shiny coating of sugar or sauce."],
     "glaze = shiny coating.", "Glaze the ham with honey before roasting."),

    ("What does 'a recipe' tell you to do?",
     {"A": "how to prepare and cook a dish step by step", "B": "how to wash dishes", "C": "how to set the table", "D": "how to buy food"},
     "A", "easy", 45, "L5",
     ["A recipe provides step-by-step instructions for preparing and cooking food."],
     "recipe = cooking instructions.", "Follow the recipe carefully for best results."),

    ("What does 'to fold in' ingredients mean?",
     {"A": "to gently mix ingredients together without losing air", "B": "to chop ingredients", "C": "to boil ingredients", "D": "to freeze ingredients"},
     "A", "hard", 45, "L5",
     ["To fold in means to gently combine ingredients using a sweeping motion."],
     "fold in = gently mix.", "Fold the flour into the mixture carefully."),

    ("What does 'to knead' dough mean?",
     {"A": "to press and stretch dough repeatedly with your hands", "B": "to cut dough into pieces", "C": "to boil dough", "D": "to freeze dough"},
     "A", "medium", 45, "L5",
     ["To knead means to work dough by pressing, folding and stretching it."],
     "knead = work dough.", "Knead the dough for ten minutes until smooth."),

    ("What does 'to whisk eggs' mean?",
     {"A": "to beat eggs quickly with a whisk or fork until mixed", "B": "to boil eggs", "C": "to fry eggs", "D": "to freeze eggs"},
     "A", "easy", 45, "L5",
     ["To whisk eggs means to beat them rapidly to mix the yolk and white together."],
     "whisk = beat rapidly.", "Whisk the eggs until they are light and frothy."),

    ("What does 'to stir-fry' mean?",
     {"A": "to cook food quickly in a hot pan with a little oil while stirring", "B": "to boil food slowly", "C": "to grill food", "D": "to freeze food"},
     "A", "medium", 45, "L5",
     ["To stir-fry means to cook food quickly in a very hot pan with oil while stirring."],
     "stir-fry = quick hot-pan cooking.", "Stir-fry the vegetables for three minutes."),

    ("Which kitchen tool is used to measure ingredients precisely?",
     {"A": "measuring scales", "B": "frying pan", "C": "blender", "D": "chopping board"},
     "A", "easy", 45, "L5",
     ["Measuring scales are used to weigh ingredients accurately."],
     "measuring scales = weighing tool.", "Use scales to measure flour precisely."),

    ("Which appliance is used to keep food cold and fresh?",
     {"A": "fridge", "B": "oven", "C": "microwave", "D": "toaster"},
     "A", "easy", 45, "L5",
     ["A fridge is used to keep food and drink cold to preserve freshness."],
     "fridge = cold storage.", "Keep milk in the fridge to keep it fresh."),

    ("What does 'to blanch' vegetables mean?",
     {"A": "to boil briefly then put in cold water to stop cooking", "B": "to fry in oil for a long time", "C": "to freeze raw", "D": "to mash into a paste"},
     "A", "hard", 45, "L5",
     ["Blanching means briefly boiling food then plunging it into cold water."],
     "blanch = brief boil then cold water.", "Blanch the beans for two minutes."),
]
