-- ============================================================
-- قسم «ملفات المعلمين» — مدارك جو
-- الملف مكتفٍ ذاتياً: يعتمد على auth.users فقط.
-- نفّذه كاملاً في SQL Editor الخاص بقاعدة «أنا مجهول».
-- ============================================================

-- ========= 0. الاعتماديات المسبقة (تُتجاهل إن كانت موجودة) =========
do $$
begin
  if not exists (
    select 1 from pg_type t
    join pg_namespace n on n.oid = t.typnamespace
    where n.nspname = 'public' and t.typname = 'app_role'
  ) then
    execute 'create type public.app_role as enum (''admin'')';
  end if;
end $$;

create table if not exists public.user_roles (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  role public.app_role not null default 'admin',
  created_at timestamptz not null default now(),
  unique (user_id, role)
);

alter table public.user_roles enable row level security;

create or replace function public.has_role(_uid uuid, _role public.app_role)
returns boolean
language sql stable security definer set search_path = public
as $$
  select exists (select 1 from public.user_roles where user_id = _uid and role = _role)
$$;

grant execute on function public.has_role(uuid, public.app_role) to anon, authenticated;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'user_roles' and policyname = 'user_roles_select_self'
  ) then
    create policy "user_roles_select_self" on public.user_roles
      for select to authenticated
      using (user_id = auth.uid());
  end if;
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'user_roles' and policyname = 'user_roles_admin_all'
  ) then
    create policy "user_roles_admin_all" on public.user_roles
      for all to authenticated
      using (public.has_role(auth.uid(), 'admin'))
      with check (public.has_role(auth.uid(), 'admin'));
  end if;
end $$;

grant select on public.user_roles to anon, authenticated;
grant all on public.user_roles to service_role;

-- ========= 1. Feature Flag =========
create table if not exists public.teacher_files_settings (
  id integer primary key check (id = 1),
  teacher_files_enabled boolean not null default false,
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);

insert into public.teacher_files_settings (id) values (1) on conflict do nothing;

alter table public.teacher_files_settings enable row level security;

create policy "tf_settings_read" on public.teacher_files_settings
  for select to anon, authenticated using (true);
create policy "tf_settings_admin" on public.teacher_files_settings
  for all to authenticated
  using (public.has_role(auth.uid(), 'admin'))
  with check (public.has_role(auth.uid(), 'admin'));

grant select on public.teacher_files_settings to anon, authenticated;
grant all on public.teacher_files_settings to service_role;

-- الدالة الآمنة للتحقق من تفعيل الميزة
create or replace function public.is_teacher_files_enabled()
returns boolean
language sql stable security definer set search_path = public
as $$
  select coalesce(
    (select teacher_files_enabled from public.teacher_files_settings where id = 1),
    false
  );
$$;

grant execute on function public.is_teacher_files_enabled() to anon, authenticated;

-- ========= 2. القوائم المرجعية =========
create table if not exists public.teacher_subjects (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.teacher_fields (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.teacher_grades (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

-- ========= 3. المعلمون =========
create table if not exists public.teachers (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  bio text not null default '',
  photo_url text,
  website_url text,
  social_links jsonb not null default '[]'::jsonb,
  is_published boolean not null default false,
  featured boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_teachers_slug on public.teachers (slug);
create index if not exists idx_teachers_published on public.teachers (is_published, sort_order);

-- ========= 4. ربط المعلمين بالقوائم =========
create table if not exists public.teacher_subject_links (
  teacher_id uuid not null references public.teachers(id) on delete cascade,
  subject_id uuid not null references public.teacher_subjects(id) on delete cascade,
  primary key (teacher_id, subject_id)
);
create index if not exists idx_tsl_subject on public.teacher_subject_links (subject_id);

create table if not exists public.teacher_field_links (
  teacher_id uuid not null references public.teachers(id) on delete cascade,
  field_id uuid not null references public.teacher_fields(id) on delete cascade,
  primary key (teacher_id, field_id)
);
create index if not exists idx_tfl_field on public.teacher_field_links (field_id);

create table if not exists public.teacher_grade_links (
  teacher_id uuid not null references public.teachers(id) on delete cascade,
  grade_id uuid not null references public.teacher_grades(id) on delete cascade,
  primary key (teacher_id, grade_id)
);
create index if not exists idx_tgl_grade on public.teacher_grade_links (grade_id);

-- ========= 5. أقسام المعلم =========
create table if not exists public.teacher_sections (
  id uuid primary key default gen_random_uuid(),
  teacher_id uuid not null references public.teachers(id) on delete cascade,
  name text not null,
  description text not null default '',
  icon text not null default '📁',
  is_visible boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_ts_teacher_sort on public.teacher_sections (teacher_id, sort_order);

-- ========= 6. محتوى الأقسام =========
create table if not exists public.teacher_contents (
  id uuid primary key default gen_random_uuid(),
  section_id uuid not null references public.teacher_sections(id) on delete cascade,
  title text not null,
  description text not null default '',
  content_type text not null check (content_type in ('file','image','link','video')),
  file_url text,
  file_name text,
  file_mime text,
  link_url text,
  is_published boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_tc_section_sort on public.teacher_contents (section_id, sort_order);

-- ========= 7. RLS + صلاحيات =========
-- helper: RLS policy
do $$
declare
  tbl text;
  tbls text[] := array[
    'teacher_subjects','teacher_fields','teacher_grades',
    'teachers',
    'teacher_subject_links','teacher_field_links','teacher_grade_links',
    'teacher_sections','teacher_contents'
  ];
begin
  foreach tbl in array tbls loop
    execute format('alter table public.%I enable row level security', tbl);

    -- قراءة: مفعلة أم أدمن
    execute format(
      'create policy "%s_read" on public.%s for select to anon, authenticated
       using (public.is_teacher_files_enabled() OR public.has_role(auth.uid(), ''admin''))',
      tbl, tbl
    );

    -- كتابة/تعديل/حذف: أدمن فقط
    execute format(
      'create policy "%s_write" on public.%s for all to authenticated
       using (public.has_role(auth.uid(), ''admin''))
       with check (public.has_role(auth.uid(), ''admin''))',
      tbl, tbl
    );

    -- الصلاحيات
    execute format('grant select on public.%I to anon, authenticated', tbl);
    execute format('grant all on public.%I to authenticated', tbl);
  end loop;
end $$;

-- ========= 8. مخزن ملفات المعلمين =========
insert into storage.buckets (id, name, public)
values ('teacher-files', 'teacher-files', true)
on conflict do nothing;

-- قراءة الملفات (مفعلة أم أدمن)
create policy "tf_storage_read" on storage.objects
  for select to anon, authenticated
  using (
    bucket_id = 'teacher-files'
    AND (public.is_teacher_files_enabled() OR public.has_role(auth.uid(), 'admin'))
  );

-- رفع ملفات: أدمن فقط
create policy "tf_storage_insert" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'teacher-files' AND public.has_role(auth.uid(), 'admin'));

create policy "tf_storage_update" on storage.objects
  for update to authenticated
  using (bucket_id = 'teacher-files' AND public.has_role(auth.uid(), 'admin'))
  with check (bucket_id = 'teacher-files' AND public.has_role(auth.uid(), 'admin'));

create policy "tf_storage_delete" on storage.objects
  for delete to authenticated
  using (bucket_id = 'teacher-files' AND public.has_role(auth.uid(), 'admin'));

-- ========= 9. بيانات أولية =========
insert into public.teacher_fields (name, sort_order) values
  ('هندسة وتكنولوجيا المعلومات', 1),
  ('الطب والعلوم الصحية', 2),
  ('الاقتصاد وإدارة الأعمال', 3),
  ('العلوم الإنسانية واللغات', 4)
on conflict (name) do nothing;

insert into public.teacher_grades (name, sort_order) values
  ('التوجيهي', 1),
  ('الحادي عشر', 2),
  ('العاشر', 3),
  ('التاسع', 4)
on conflict (name) do nothing;

insert into public.teacher_subjects (name, sort_order) values
  ('الرياضيات', 1),
  ('الفيزياء', 2),
  ('الكيمياء', 3),
  ('العلوم الحياتية', 4),
  ('علوم الأرض والبيئة', 5),
  ('اللغة العربية', 6),
  ('اللغة الإنجليزية', 7),
  ('اللغة الفرنسية', 8),
  ('التكنولوجيا وريادة الأعمال', 9),
  ('التربية الإسلامية', 10),
  ('التاريخ', 11),
  ('الجغرافيا', 12),
  ('علوم الحاسوب', 13)
on conflict (name) do nothing;

-- ========= 10. ملاحظة =========
-- بعد تنفيذ هذا الملف:
--   1. افتح لوحة المعلمين (Admin) لإنشاء المعلمين والأقسام والمحتوى.
--   2. للتفعيل النهائي: عدّل teacher_files_enabled إلى true في
--        teacher_files_settings عبر SQL:
--          UPDATE public.teacher_files_settings SET teacher_files_enabled = true WHERE id = 1;
--      أو من واجهة الأدمن إذا أضفت زر toggle في الواجهة.
--   3. عند التفعيل، ستظهر البيانات تلقائياً للطلاب عبر /teacher-files/

-- ========= 10. رمز الدخول السري للأدمن =========
-- الضغط على شعار «مدارك جو» في رأس الموقع → إدخال الرمز → دخول أدمن فوري.
-- الرمز مخزَّن في القاعدة (وليس في أكواد الموقع) ويُغيَّر بأي وقت.
alter table public.teacher_files_settings
  add column if not exists admin_pin text not null default '929292';

update public.teacher_files_settings set admin_pin = '929292' where id = 1 and admin_pin is null;

create or replace function public.login_admin_by_code(p_code text)
returns boolean
language plpgsql security definer set search_path = public
as $$
declare
  _uid uuid := auth.uid();
  _pin text;
begin
  if _uid is null then
    return false;
  end if;
  select admin_pin into _pin from public.teacher_files_settings where id = 1;
  if _pin is null or p_code <> _pin then
    return false;
  end if;
  insert into public.user_roles (user_id, role)
  values (_uid, 'admin'::public.app_role)
  on conflict (user_id, role) do nothing;
  return true;
end;
$$;

grant execute on function public.login_admin_by_code(text) to anon, authenticated;

-- ========= 11. قائمة الإدارة (أسماء من يدخلون بالرمز) =========
-- من يدخل الرمز 929292 يصير أدمن فوراً مهما كان، وعليه تعريف نفسه باسمه
-- ليُعرف في «قائمة الإدارة». التعريف مقيد بجهاز/متصفح (device_id).
create table if not exists public.teacher_files_admin_profiles (
  id uuid primary key default gen_random_uuid(),
  device_id text not null unique,
  name text not null,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz
);

alter table public.teacher_files_admin_profiles enable row level security;

drop policy if exists "tf_admin_profiles_read" on public.teacher_files_admin_profiles;
create policy "tf_admin_profiles_read"
  on public.teacher_files_admin_profiles for select
  to authenticated
  using (public.has_role(auth.uid(), 'admin'));

drop policy if exists "tf_admin_profiles_insert" on public.teacher_files_admin_profiles;
create policy "tf_admin_profiles_insert"
  on public.teacher_files_admin_profiles for insert
  to authenticated
  with check (public.has_role(auth.uid(), 'admin'));

drop policy if exists "tf_admin_profiles_update" on public.teacher_files_admin_profiles;
create policy "tf_admin_profiles_update"
  on public.teacher_files_admin_profiles for update
  to authenticated
  using (public.has_role(auth.uid(), 'admin'))
  with check (public.has_role(auth.uid(), 'admin'));

grant select, insert, update on public.teacher_files_admin_profiles to authenticated;
